/** * Echo Knowledge Ingestion API Routes * Endpoints for ingesting knowledge sources into internal pgvector storage */ import { Router, Request, Response } from"express";
import { ingestionController, type IngestionProgress, type IngestionResult,
} from"../lib/knowledge-ingestion-service"; const router = Router(); /** * POST /api/echo/knowledge/ingest/master-dictionary * Ingest Master Culinary Dictionary into internal storage */
router.post("/knowledge/ingest/master-dictionary", async (req: Request, res: Response) => { try { const progress = ingestionController.getProgress(); if (progress.status ==="in_progress") { return res.status(409).json({ status:"error", message:"Ingestion already in progress", progress: progress, }); } console.log("[API] Starting Master Dictionary ingestion..."); res.json({ status:"started", message:"Master Dictionary ingestion started", progress: ingestionController.getProgress(), }); // Run ingestion in background ingestionController.ingestMasterDictionary().catch((error) => { console.error("[API] Master Dictionary ingestion failed:", error); }); } catch (error) { console.error("[API] Error starting Master Dictionary ingestion:", error); res.status(500).json({ status:"error", message:"Failed to start Master Dictionary ingestion", error: error instanceof Error ? error.message :"Unknown error", }); } },
); /** * POST /api/echo/knowledge/ingest/pinecone * Ingest knowledge from Pinecone into internal storage */
router.post("/knowledge/ingest/pinecone", async (req: Request, res: Response) => { try { const progress = ingestionController.getProgress(); if (progress.status ==="in_progress") { return res.status(409).json({ status:"error", message:"Ingestion already in progress", progress: progress, }); } console.log("[API] Starting Pinecone ingestion..."); res.json({ status:"started", message:"Pinecone ingestion started", progress: ingestionController.getProgress(), }); // Run ingestion in background ingestionController.ingestFromPinecone().catch((error) => { console.error("[API] Pinecone ingestion failed:", error); }); } catch (error) { console.error("[API] Error starting Pinecone ingestion:", error); res.status(500).json({ status:"error", message:"Failed to start Pinecone ingestion", error: error instanceof Error ? error.message :"Unknown error", }); } },
); /** * POST /api/echo/knowledge/ingest/all * Ingest all knowledge sources (Master Dictionary + Pinecone) */
router.post("/knowledge/ingest/all", async (req: Request, res: Response) => { try { const progress = ingestionController.getProgress(); if (progress.status ==="in_progress") { return res.status(409).json({ status:"error", message:"Ingestion already in progress", progress: progress, }); } console.log("[API] Starting bulk knowledge ingestion..."); res.json({ status:"started", message:"Bulk knowledge ingestion started", progress: ingestionController.getProgress(), }); // Run ingestion in background ingestionController.ingestAll().catch((error) => { console.error("[API] Bulk knowledge ingestion failed:", error); }); } catch (error) { console.error("[API] Error starting bulk knowledge ingestion:", error); res.status(500).json({ status:"error", message:"Failed to start bulk knowledge ingestion", error: error instanceof Error ? error.message :"Unknown error", }); }
}); /** * GET /api/echo/knowledge/ingest/progress * Get current ingestion progress */
router.get("/knowledge/ingest/progress", async (req: Request, res: Response) => { try { const progress = ingestionController.getProgress(); const stats = await ingestionController.getStatistics(); res.json({ status:"success", progress: progress, statistics: stats, }); } catch (error) { console.error("[API] Error getting ingestion progress:", error); res.status(500).json({ status:"error", message:"Failed to get ingestion progress", error: error instanceof Error ? error.message :"Unknown error", }); } },
); /** * GET /api/echo/knowledge/ingest/status * Get comprehensive ingestion status */
router.get("/knowledge/ingest/status", async (req: Request, res: Response) => { try { const progress = ingestionController.getProgress(); const stats = await ingestionController.getStatistics(); res.json({ status:"success", ingestion: { progress: progress, statistics: stats, }, }); } catch (error) { console.error("[API] Error getting ingestion status:", error); res.status(500).json({ status:"error", message:"Failed to get ingestion status", error: error instanceof Error ? error.message :"Unknown error", }); }
}); export default router;
