import { Router, Request, Response } from"express";
import { generateEmbedding, storeRecipeVector } from"../lib/vector-engine";
import type { RecipeCodexMetadata } from"../../client/echo/codex";
import { extractDefinitionsFromPdfText, formatDefinitionsForBuilder,
} from"../lib/pdf-definition-extractor"; const router = Router(); interface StoreRecipeRequest { recipe: { id: string; title: string; ingredients: string[]; instructions: string[]; sourceBook: string; sourcePage: number; cuisine?: string; course?: string; difficulty?: string; prepTime?: string; cookTime?: string; yield?: string; tags?: string[]; }; codexMetadata: RecipeCodexMetadata; bookName: string;
} /** * POST /api/echo-training/store-recipe * Store an imported recipe with full codex metadata in vector store * Enriches recipe for EchoChefBrain suggestions */
router.post("/store-recipe", async (req: Request, res: Response) => { try { const { recipe, codexMetadata, bookName } = req.body as StoreRecipeRequest; if (!recipe?.id || !recipe?.title) { return res.status(400).json({ error:"Recipe ID and title required" }); } // Build searchable text for embedding const recipeText = `
Recipe: ${recipe.title}
Ingredients: ${recipe.ingredients.join(",")}
Instructions: ${recipe.instructions.join("")}
${recipe.cuisine ? `Cuisine: ${recipe.cuisine}` :""}
${recipe.course ? `Course: ${recipe.course}` :""}
Complexity: ${codexMetadata.complexity}/5
Techniques: ${codexMetadata.primaryTechniques.join(",")}
Dietary: ${codexMetadata.dietaryTags.join(",")}
Flavor Profile: ${codexMetadata.flavorProfile.join(",")}
Source: ${bookName} (Page ${recipe.sourcePage}) `.trim(); // Generate embedding using existing vector engine const embedding = await generateEmbedding(recipeText); // Enrich tags with source and codex info const enrichedTags = [ ...(recipe.tags || []), `source:${bookName.replace(/\s+/g,"-")}`, `page:${recipe.sourcePage}`,"echo-training","codex-indexed", ...codexMetadata.dietaryTags.map((t) => `dietary:${t}`), ...codexMetadata.allergens.map((a) => `allergen:${a}`), ]; // Store vector with full codex metadata try { await storeRecipeVector( { id: recipe.id, title: recipe.title, description: recipeText, ingredients: recipe.ingredients, cuisine: recipe.cuisine, course: recipe.course, difficulty: recipe.difficulty, tags: enrichedTags, prepTime: recipe.prepTime ? parseInt(recipe.prepTime) : undefined, cookTime: recipe.cookTime ? parseInt(recipe.cookTime) : undefined, },"manufacturing", // Track"echo-system", // Chef"global-knowledge", // Organization (global for all users to benefit) ); } catch (storeError) { console.error("[EchoTraining] Vector storage failed:", storeError); return res.status(500).json({ success: false, error:"Failed to store recipe vector", }); } return res.json({ success: true, recipeId: recipe.id, title: recipe.title, message: `Recipe stored and indexed for EchoChefBrain suggestions`, }); } catch (error: any) { console.error("[EchoTraining] Store recipe failed:", error); return res.status(500).json({ success: false, error: error.message ||"Internal server error", }); }
}); /** * POST /api/echo-training/batch-store-recipes * Store multiple recipes from a textbook in batch * Returns progress and final counts */
router.post("/batch-store-recipes", async (req: Request, res: Response) => { try { const { recipes, bookName } = req.body as { recipes: StoreRecipeRequest["recipe"][]; bookName: string; codexMetadata?: Record<string, RecipeCodexMetadata>; }; if (!recipes || recipes.length === 0) { return res.status(400).json({ error:"Recipes array required" }); } const results = { total: recipes.length, success: 0, failed: 0, recipes: [] as Array<{ id: string; title: string; success: boolean; error?: string; }>, }; for (const recipe of recipes) { try { // Map to codex metadata if not provided const codexMetadata = mapRecipeToCodex(recipe); const recipeText = `
Recipe: ${recipe.title}
Ingredients: ${recipe.ingredients.join(",")}
Instructions: ${recipe.instructions.join("")}
${recipe.cuisine ? `Cuisine: ${recipe.cuisine}` :""}
${recipe.course ? `Course: ${recipe.course}` :""}
Complexity: ${codexMetadata.complexity}/5
Source: ${bookName} (Page ${recipe.sourcePage}) `.trim(); const embedding = await generateEmbedding(recipeText); const enrichedTags = [ ...(recipe.tags || []), `source:${bookName.replace(/\s+/g,"-")}`, `page:${recipe.sourcePage}`,"echo-training", ]; await storeRecipeVector( { id: recipe.id, title: recipe.title, description: recipeText, ingredients: recipe.ingredients, cuisine: recipe.cuisine, tags: enrichedTags, },"manufacturing","echo-system","global-knowledge", ); results.success++; results.recipes.push({ id: recipe.id, title: recipe.title, success: true, }); } catch (error) { results.failed++; results.recipes.push({ id: recipe.id, title: recipe.title, success: false, error: error instanceof Error ? error.message :"Unknown error", }); } } return res.json(results); } catch (error: any) { console.error("[EchoTraining] Batch store failed:", error); return res.status(500).json({ error: error.message ||"Internal server error", }); }
}); // Helper to map recipe to basic codex metadata
function mapRecipeToCodex(recipe: any): RecipeCodexMetadata { return { id: recipe.id, title: recipe.title, category: inferCategory(recipe.course, recipe.title), cuisineRegion: recipe.cuisine, yieldDescription: recipe.yield, complexity: inferComplexity(recipe.difficulty, recipe.cookTime), primaryTechniques: [], mainIngredients: recipe.ingredients.slice(0, 5), dietaryTags: [], allergens: [], flavorProfile: [], };
} function inferCategory(course: string | undefined, title: string) { const text = `${course} ${title}`.toLowerCase(); if (text.includes("appetizer") || text.includes("starter")) return"appetizer"; if (text.includes("salad")) return"salad"; if (text.includes("soup")) return"soup"; if (text.includes("dessert")) return"dessert"; if (text.includes("sauce")) return"sauce"; return"entree";
} function inferComplexity( difficulty: string | undefined, cookTime: string | undefined,
): 1 | 2 | 3 | 4 | 5 { if (difficulty) { const lower = difficulty.toLowerCase(); if (lower.includes("easy")) return 1; if (lower.includes("simple")) return 2; if (lower.includes("intermediate")) return 3; if (lower.includes("advanced")) return 4; if (lower.includes("expert")) return 5; } return 3;
} /** * POST /api/echo-training/extract-definitions-from-pdf * Extract glossary/definitions from PDF text and prepare for Builder.io storage */
router.post("/extract-definitions-from-pdf", async (req: Request, res: Response) => { try { const { pdfText, sourceName } = req.body as { pdfText: string; sourceName: string; }; if (!pdfText || pdfText.trim().length === 0) { return res.status(400).json({ error:"PDF text required" }); } // Extract definitions using the scanner logic const definitions = extractDefinitionsFromPdfText( pdfText, sourceName ||"Imported Cookbook", ); // Format for Builder.io const formatted = formatDefinitionsForBuilder(definitions); return res.json({ success: true, count: definitions.length, definitions: formatted, }); } catch (error: any) { console.error("[EchoTraining] Extract definitions failed:", error); return res.status(500).json({ success: false, error: error.message ||"Internal server error", }); } },
); /** * POST /api/echo-training/store-definitions-batch * Store extracted definitions to Pinecone for Echo knowledge */
router.post("/store-definitions-batch", async (req: Request, res: Response) => { try { const { definitions, sourceName } = req.body as { definitions: Array<{ term: string; definition: string; categories?: string[]; slug?: string; }>; sourceName: string; }; if (!definitions || definitions.length === 0) { return res.status(400).json({ error:"Definitions array required" }); } const results = { success: 0, failed: 0, terms: [] as Array<{ term: string; success: boolean; error?: string; }>, }; // Store each definition in vector store for Echo for (const def of definitions) { try { const definitionText = `
Culinary Term: ${def.term}
Definition: ${def.definition}
${def.categories ? `Categories: ${def.categories.join(",")}` :""}
Source: ${sourceName} `.trim(); // Generate embedding const embedding = await generateEmbedding(definitionText); // Store in vector database for Echo knowledge retrieval const tags = ["culinary-definition","glossary","auto-imported", `source:${sourceName.replace(/\s+/g,"-")}`, ...(def.categories || []).map((c) => `category:${c}`), ].filter(Boolean); // Store using the same vector mechanism as recipes await storeRecipeVector( { id: `def-${def.slug || def.term.replace(/\s+/g,"-")}-${Date.now()}`, title: `Term: ${def.term}`, description: definitionText, ingredients: [], // Not used for definitions tags, },"culinary-knowledge", // recipe type"echo-system", // context"definitions", // source ); results.success++; results.terms.push({ term: def.term, success: true, }); } catch (error) { results.failed++; results.terms.push({ term: def.term, success: false, error: error instanceof Error ? error.message :"Unknown error", }); } } return res.json(results); } catch (error: any) { console.error("[EchoTraining] Store definitions batch failed:", error); return res.status(500).json({ success: false, error: error.message ||"Internal server error", }); }
}); /** * POST /api/echo-training/vision-extract-recipes * Extract recipes from PDF using GPT-4V vision API * Processes PDF as base64 text and sends to OpenAI for analysis */
router.post("/vision-extract-recipes", async (req: Request, res: Response) => { try { const { pdfBase64, pdfName } = req.body as { pdfBase64: string; pdfName: string; }; if (!pdfBase64 || !pdfName) { return res.status(400).json({ error:"PDF base64 and name required" }); } const openaiApiKey = process.env.OPENAI_API_KEY; if (!openaiApiKey) { return res.status(500).json({ error:"OpenAI API key not configured" }); } const recipes: Array<{ title: string; ingredients: string[]; instructions: string[]; cuisine?: string; servings?: string; prepTime?: string; cookTime?: string; }> = []; // Convert base64 PDF to string for text analysis let pdfText =""; try { const buffer = Buffer.from(pdfBase64,"base64"); // For now, we'll treat the base64 as containing PDF data // In production, you'd use a PDF parser library like pdfjs pdfText = buffer.toString("utf8", 0, Math.min(buffer.length, 50000)); // Limit to first 50KB } catch (e) { console.warn("Could not decode PDF base64, using as-is"); pdfText = pdfBase64.substring(0, 50000); } // Send to GPT-4 Turbo for analysis const message = await fetch("https://api.openai.com/v1/chat/completions", { method:"POST", headers: {"Content-Type":"application/json", Authorization: `Bearer ${openaiApiKey}`, }, body: JSON.stringify({ model:"gpt-4-turbo-preview", max_tokens: 4096, messages: [ { role:"user", content: `Analyze this cookbook PDF content and extract ALL recipes. For each recipe found, provide:
- Title (exact name)
- Ingredients (list with exact measurements)
- Instructions/Directions (numbered steps)
- Optional fields if present: Servings, Prep Time, Cook Time, Cuisine Return ONLY a valid JSON array. Example format:
[ {"title":"Recipe Name","ingredients": ["1 cup flour","2 eggs","1/2 tsp salt"],"instructions": ["Step 1 text","Step 2 text"],"servings":"4","prepTime":"15 min","cookTime":"30 min","cuisine":"Italian" }
] If no recipes found, return empty array: [] PDF Content:
${pdfText}`, }, ], }), }); if (!message.ok) { const error = await message.text(); console.error("OpenAI API error:", error); return res.status(500).json({ error:"Failed to process PDF with vision API", details: error, }); } const response = (await message.json()) as any; const content = response.choices?.[0]?.message?.content; if (!content) { return res.status(500).json({ error:"No response from vision API" }); } // Parse the JSON response try { const jsonMatch = content.match(/\[[\s\S]*\]/); if (jsonMatch) { const extractedRecipes = JSON.parse(jsonMatch[0]); if (Array.isArray(extractedRecipes)) { recipes.push(...extractedRecipes); } } } catch (parseError) { console.error("Failed to parse vision response:", content); return res.status(500).json({ error:"Failed to parse recipe data from vision API", }); } return res.json({ success: true, count: recipes.length, recipes, source: pdfName, }); } catch (error: any) { console.error("[EchoTraining] Vision extract failed:", error); return res.status(500).json({ success: false, error: error.message ||"Internal server error", }); }
}); export const echoTrainingRouter = router;
