import { Router, Request, Response } from"express";
import { createClient, SupabaseClient } from"@supabase/supabase-js"; const router = Router(); // Lazy initialization of Supabase client
let supabaseClient: SupabaseClient | null = null; function getSupabaseClient(): SupabaseClient { if (!supabaseClient) { const supabaseUrl = process.env.SUPABASE_URL; const supabaseKey = process.env.SUPABASE_ANON_KEY; if (!supabaseUrl || !supabaseKey) { console.warn("[Inventory Operations] Supabase credentials not configured"); return {} as SupabaseClient; } supabaseClient = createClient(supabaseUrl, supabaseKey); } return supabaseClient;
} // Fuzzy search helper
function fuzzyMatch(searchText: string, item: string): number { const search = searchText.toLowerCase(); const text = item.toLowerCase(); if (text.includes(search)) return 100; let matches = 0; let searchIdx = 0; for (let i = 0; i < text.length && searchIdx < search.length; i++) { if (text[i] === search[searchIdx]) { matches++; searchIdx++; } } return searchIdx === search.length ? (matches / text.length) * 100 : 0;
} // GET /api/inventory/items - Search inventory items with fuzzy match
router.get("/items", async (req: Request, res: Response) => { try { const { q } = req.query; const { data: items, error } = await getSupabaseClient() .from("inventory_items") .select("id, name, category, item_type, unit") .limit(50); if (error) { return res.status(500).json({ error: error.message }); } if (!q) { return res.json(items); } const searchText = String(q); const results = items .map((item) => ({ ...item, score: fuzzyMatch(searchText, item.name), })) .filter((item) => item.score > 0) .sort((a, b) => b.score - a.score) .slice(0, 20); res.json(results.map(({ score, ...item }) => item)); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/inventory/items/:id - Get specific inventory item
router.get("/items/:id", async (req: Request, res: Response) => { try { const { id } = req.params; const { data: item, error } = await getSupabaseClient() .from("inventory_items") .select("*") .eq("id", id) .single(); if (error) { return res.status(404).json({ error:"Item not found" }); } res.json(item); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // POST /api/inventory/transfers - Create inventory transfer
router.post("/transfers", async (req: Request, res: Response) => { try { const { item_id, item_name, quantity, unit, from_department, to_department, requested_by, notes, } = req.body; if (!item_name || !quantity || !to_department || !requested_by) { return res.status(400).json({ error:"Missing required fields" }); } const { data: transfer, error } = await getSupabaseClient() .from("inventory_transfers") .insert({ item_id, item_name, quantity, unit: unit ||"unit", from_department: from_department ||"kitchen", to_department, requested_by, notes, status:"pending", }) .select() .single(); if (error) { return res.status(500).json({ error: error.message }); } res.status(201).json(transfer); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/inventory/transfers - Get transfers with filters
router.get("/transfers", async (req: Request, res: Response) => { try { const { to_department, from_department, status, start_date, end_date, limit ="50", } = req.query; let query = supabase.from("inventory_transfers").select("*"); if (to_department) { query = query.eq("to_department", to_department); } if (from_department) { query = query.eq("from_department", from_department); } if (status) { query = query.eq("status", status); } if (start_date) { query = query.gte("transfer_date", start_date); } if (end_date) { query = query.lte("transfer_date", end_date); } const { data: transfers, error } = await query .order("transfer_date", { ascending: false }) .limit(Number(limit)); if (error) { return res.status(500).json({ error: error.message }); } res.json(transfers); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/inventory/transfers/:id - Get specific transfer
router.get("/transfers/:id", async (req: Request, res: Response) => { try { const { id } = req.params; const { data: transfer, error } = await getSupabaseClient() .from("inventory_transfers") .select("*") .eq("id", id) .single(); if (error) { return res.status(404).json({ error:"Transfer not found" }); } res.json(transfer); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // PUT /api/inventory/transfers/:id - Update transfer status
router.put("/transfers/:id", async (req: Request, res: Response) => { try { const { id } = req.params; const { status, transferred_by, received_date } = req.body; if (!status) { return res.status(400).json({ error:"Status is required" }); } const updateData: any = { status, updated_at: new Date().toISOString() }; if (transferred_by) { updateData.transferred_by = transferred_by; } if (received_date) { updateData.received_date = received_date; } const { data: transfer, error } = await getSupabaseClient() .from("inventory_transfers") .update(updateData) .eq("id", id) .select() .single(); if (error) { return res.status(500).json({ error: error.message }); } res.json(transfer); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // POST /api/inventory/recalls - Create food recall notification
router.post("/recalls", async (req: Request, res: Response) => { try { const { recall_id, item_name, severity, description, action_required } = req.body; if (!recall_id || !item_name || !severity || !description) { return res.status(400).json({ error:"Missing required fields" }); } const { data: recall, error } = await getSupabaseClient() .from("food_recall_notifications") .insert({ recall_id, item_name, severity, description, action_required, }) .select() .single(); if (error) { return res.status(500).json({ error: error.message }); } res.status(201).json(recall); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/inventory/recalls - Get active food recalls
router.get("/recalls", async (req: Request, res: Response) => { try { const { severity, include_resolved ="false" } = req.query; let query = supabase.from("food_recall_notifications").select("*"); if (include_resolved ==="false") { query = query.is("resolved_at", null); } if (severity) { query = query.eq("severity", severity); } const { data: recalls, error } = await query.order("issued_at", { ascending: false, }); if (error) { return res.status(500).json({ error: error.message }); } res.json(recalls); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/inventory/recalls/:id - Get specific recall
router.get("/recalls/:id", async (req: Request, res: Response) => { try { const { id } = req.params; const { data: recall, error } = await getSupabaseClient() .from("food_recall_notifications") .select("*") .eq("id", id) .single(); if (error) { return res.status(404).json({ error:"Recall not found" }); } res.json(recall); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // POST /api/inventory/recalls/:id/device-notification - Notify device about recall
router.post("/recalls/:id/device-notification", async (req: Request, res: Response) => { try { const { id } = req.params; const { device_id, device_name } = req.body; if (!device_id) { return res.status(400).json({ error:"device_id is required" }); } // Check if device already notified const { data: existing } = await getSupabaseClient() .from("food_recall_device_notifications") .select("id") .eq("recall_id", id) .eq("device_id", device_id) .single(); if (existing) { return res.json(existing); } const { data: notification, error } = await getSupabaseClient() .from("food_recall_device_notifications") .insert({ recall_id: id, device_id, device_name, }) .select() .single(); if (error) { return res.status(500).json({ error: error.message }); } res.status(201).json(notification); } catch (error: any) { res.status(500).json({ error: error.message }); } },
); // PUT /api/inventory/recalls/:id/acknowledge - Acknowledge recall on device
router.put("/recalls/:id/acknowledge", async (req: Request, res: Response) => { try { const { id } = req.params; const { device_id, acknowledged_by } = req.body; if (!device_id || !acknowledged_by) { return res .status(400) .json({ error:"device_id and acknowledged_by are required" }); } const { data: notification, error } = await getSupabaseClient() .from("food_recall_device_notifications") .update({ acknowledged_at: new Date().toISOString(), acknowledged_by, }) .eq("recall_id", id) .eq("device_id", device_id) .select() .single(); if (error) { return res.status(500).json({ error: error.message }); } res.json(notification); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/inventory/recalls/device/:device_id - Get recalls for a device
router.get("/recalls/device/:device_id", async (req: Request, res: Response) => { try { const { device_id } = req.params; const { acknowledged ="false" } = req.query; let query = supabase .from("food_recall_device_notifications") .select("*, food_recall_notifications(*)") .eq("device_id", device_id); if (acknowledged ==="false") { query = query.is("acknowledged_at", null); } const { data: notifications, error } = await query.order("first_notified_at", { ascending: false }, ); if (error) { return res.status(500).json({ error: error.message }); } res.json(notifications); } catch (error: any) { res.status(500).json({ error: error.message }); } },
); export default router;
