/** * Load Testing Routes * Endpoints for testing the system's ability to handle large term volumes * * Tests: * - Small load: 1,000 terms * - Medium load: 10,000 terms * - Large load: 180,000 terms */ import { Router, type Request, type Response } from"express";
import { ingestionOrchestrator } from"../lib/ingestion-orchestrator";
import { deduplicationService, type TermForDedup,
} from"../lib/deduplication-service"; export const loadTestingRouter = Router(); /** * Generate synthetic terms for testing */
function generateSyntheticTerms(count: number): TermForDedup[] { const categories = ["technique","ingredient","equipment","method","theory","cuisine","safety", ]; const adjectives = ["classic","modern","traditional","contemporary","french","italian","asian","molecular", ]; const nouns = ["sauce","technique","method","process","equipment","ingredient","preparation","cooking", ]; const terms: TermForDedup[] = []; for (let i = 0; i < count; i++) { const adj = adjectives[Math.floor(Math.random() * adjectives.length)]; const noun = nouns[Math.floor(Math.random() * nouns.length)]; const category = categories[Math.floor(Math.random() * categories.length)]; terms.push({ term: `${adj} ${noun} ${i}`, definition: `A ${adj} culinary ${noun} used in professional kitchens. This is term number ${i} in the test set. Includes related techniques, applications, and industry best practices.`, categories: [category], masteryLevel: ["fundamental","intermediate","advanced","expert"][ Math.floor(Math.random() * 4) ], confidence: 0.75 + Math.random() * 0.25, sourceType:"test-generated", metadata: { testIndex: i, generatedAt: new Date().toISOString(), }, }); } return terms;
} /** * POST /api/load-test/small * Test with 1,000 terms */
loadTestingRouter.post("/load-test/small", async (req: Request, res: Response) => { try { console.log("[LoadTest] Starting small load test (1,000 terms)"); const terms = generateSyntheticTerms(1000); const startTime = Date.now(); const result = await ingestionOrchestrator.ingestTerms( terms, (progress) => { console.log( `[LoadTest] ${progress.phase}: ${progress.progress}% - ${progress.message}`, ); }, ); const duration = (Date.now() - startTime) / 1000; res.json({ success: true, test:"small", duration, result, metricsPerTerm: { averageTimeMs: result.totalTime / result.afterDedup || 0, deduplicationRatePercent: result.deduplicationRate, embeddingSuccessRate: (result.embeddingsGenerated / (result.embeddingsGenerated + result.embeddingsFailed)) * 100, storageSuccessRate: (result.storageSuccessful / (result.storageSuccessful + result.storageFailed)) * 100, }, }); } catch (error) { console.error("[LoadTest] Small test error:", error); res.status(500).json({ success: false, error: error instanceof Error ? error.message :"Unknown error", }); } },
); /** * POST /api/load-test/medium * Test with 10,000 terms */
loadTestingRouter.post("/load-test/medium", async (req: Request, res: Response) => { try { console.log("[LoadTest] Starting medium load test (10,000 terms)"); const terms = generateSyntheticTerms(10000); const startTime = Date.now(); const result = await ingestionOrchestrator.ingestTerms( terms, (progress) => { if (progress.progress % 10 === 0) { console.log( `[LoadTest] ${progress.phase}: ${progress.progress}% - ${progress.message}`, ); } }, ); const duration = (Date.now() - startTime) / 1000; res.json({ success: true, test:"medium", duration, durationMinutes: (duration / 60).toFixed(2), result, metricsPerTerm: { averageTimeMs: result.totalTime / result.afterDedup || 0, deduplicationRatePercent: result.deduplicationRate, embeddingSuccessRate: (result.embeddingsGenerated / (result.embeddingsGenerated + result.embeddingsFailed)) * 100, storageSuccessRate: (result.storageSuccessful / (result.storageSuccessful + result.storageFailed)) * 100, }, projectedTimeFor180K: { estimatedSeconds: (result.totalTime / result.afterDedup) * 180000, estimatedMinutes: ((result.totalTime / result.afterDedup) * 180000) / 60, estimatedHours: ((result.totalTime / result.afterDedup) * 180000) / 60 / 60, }, }); } catch (error) { console.error("[LoadTest] Medium test error:", error); res.status(500).json({ success: false, error: error instanceof Error ? error.message :"Unknown error", }); } },
); /** * POST /api/load-test/deduplication * Test deduplication performance with synthetic duplicates */
loadTestingRouter.post("/load-test/deduplication", async (req: Request, res: Response) => { try { console.log("[LoadTest] Starting deduplication test"); const { termCount = 5000, duplicateRate = 0.2 } = req.body; // Generate terms with intentional duplicates const baseTerms = generateSyntheticTerms( Math.floor(termCount * (1 - duplicateRate)), ); const duplicates: TermForDedup[] = []; // Add duplicates (with slight variations) for (let i = 0; i < Math.floor(termCount * duplicateRate); i++) { const baseTerm = baseTerms[Math.floor(Math.random() * baseTerms.length)]; duplicates.push({ ...baseTerm, term: baseTerm.term + (Math.random() > 0.5 ?" variant" :""), definition: baseTerm.definition + (Math.random() > 0.5 ?" (variation)" :""), }); } const allTerms = [...baseTerms, ...duplicates]; const startTime = Date.now(); const result = deduplicationService.deduplicate(allTerms); const duration = Date.now() - startTime; res.json({ success: true, test:"deduplication", duration, input: allTerms.length, output: result.unique.length, deduplicationRate: result.deduplicationRate, duplicatesFound: result.duplicates.size, metricsPerTerm: { averageTimeMs: duration / allTerms.length, }, }); } catch (error) { console.error("[LoadTest] Deduplication test error:", error); res.status(500).json({ success: false, error: error instanceof Error ? error.message :"Unknown error", }); } },
); /** * GET /api/load-test/estimated-time * Estimate time needed for 180K term ingestion based on current performance */
loadTestingRouter.get("/load-test/estimated-time", async (req: Request, res: Response) => { try { // Run a quick 1000-term test to measure performance const quickTerms = generateSyntheticTerms(1000); const startTime = Date.now(); const result = await ingestionOrchestrator.ingestTerms(quickTerms); const duration = Date.now() - startTime; const timePerTerm = duration / result.afterDedup; const estimatedTotal180K = timePerTerm * 180000; // After dedup, expecting ~180K → ~150K res.json({ success: true, quickTestSize: 1000, quickTestDuration: duration, estimations: { seconds: estimatedTotal180K / 1000, minutes: estimatedTotal180K / 60000, hours: estimatedTotal180K / 3600000, humanReadable: formatDuration(estimatedTotal180K), }, assumptions: { inputTerms: 180000, expectedAfterDedup:"~150000 (15-20% deduplication)", concurrentWorkers: 5, batchSizeEmbeddings: 100, }, }); } catch (error) { console.error("[LoadTest] Estimation error:", error); res.status(500).json({ success: false, error: error instanceof Error ? error.message :"Unknown error", }); } },
); function formatDuration(milliseconds: number): string { const seconds = Math.round(milliseconds / 1000); const minutes = Math.round(seconds / 60); const hours = Math.round(minutes / 60); if (hours > 0) { return `${hours}h ${minutes % 60}m`; } if (minutes > 0) { return `${minutes}m ${seconds % 60}s`; } return `${seconds}s`;
} export default loadTestingRouter;
