import { Router, Request, Response } from"express";
import { generateEmbedding } from"../lib/vector-engine";
import { createClient } from"@supabase/supabase-js"; const supabaseUrl = process.env.SUPABASE_URL ||"";
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY ||""; const isSupabaseConfigured = !!supabaseUrl && !!supabaseServiceKey; function getSupabaseClient() { if (!isSupabaseConfigured) { throw new Error("Supabase credentials not configured"); } return createClient(supabaseUrl, supabaseServiceKey);
} const router = Router(); /** * Middleware to check if Supabase is configured */
const checkSupabaseConfig = (req: Request, res: Response, next: Function) => { if (!isSupabaseConfigured) { return res.status(503).json({ success: false, error:"Supabase is not configured. Culinary procedures feature is unavailable.", message:"Configure SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables to enable this feature.", }); } next();
}; /** * POST /api/procedures/store * Store a culinary procedure with semantic embedding */
router.post("/store", checkSupabaseConfig, async (req: Request, res: Response) => { try { const { title, source_book, category, steps, materials, tools, time_estimate, difficulty, related_keywords, } = req.body; if (!title || !category || !steps) { return res.status(400).json({ success: false, error:"Missing required fields: title, category, steps", }); } // Generate embedding from procedure text const procedureText = `${title} ${steps.map((s: any) => s.instruction).join("")}`; const embedding = await generateEmbedding(procedureText); // Store in Supabase const supabase = getSupabaseClient(); const { data, error } = await supabase .from("culinary_procedures") .insert([ { title, source_book: source_book ||"unknown", category, steps, materials: materials || [], tools: tools || [], time_estimate, difficulty, related_keywords: related_keywords || [], embedding, }, ]) .select(); if (error) { console.error("Error storing procedure:", error); return res.status(500).json({ success: false, error: error.message, }); } return res.json({ success: true, data: data?.[0], }); } catch (error) { console.error("Error in /procedures/store:", error); return res.status(500).json({ success: false, error: error instanceof Error ? error.message :"Unknown error", }); } },
); /** * POST /api/procedures/search * Search procedures semantically */
router.post("/search", checkSupabaseConfig, async (req: Request, res: Response) => { try { const { query, limit = 10, category, min_similarity = 0.3 } = req.body; if (!query) { return res.status(400).json({ success: false, error:"Missing required field: query", }); } // Generate embedding for query const queryEmbedding = await generateEmbedding(query); // Call the search function const supabase = getSupabaseClient(); const { data, error } = await supabase.rpc("search_culinary_procedures", { query_embedding: queryEmbedding, p_limit: limit, p_category: category, p_min_similarity: min_similarity, }); if (error) { console.error("Error searching procedures:", error); return res.status(500).json({ success: false, error: error.message, }); } // Add relevance score to results const results = (data || []).map((proc: any) => ({ procedure: { id: proc.id, title: proc.title, source_book: proc.source_book, category: proc.category, steps: proc.steps, materials: proc.materials, tools: proc.tools, time_estimate: proc.time_estimate, difficulty: proc.difficulty, related_keywords: proc.related_keywords, }, relevance_score: proc.similarity || 0, })); return res.json({ success: true, data: results, }); } catch (error) { console.error("Error in /procedures/search:", error); return res.status(500).json({ success: false, error: error instanceof Error ? error.message :"Unknown error", }); } },
); /** * GET /api/procedures/by-category/:category * Get all procedures for a specific category */
router.get("/by-category/:category", checkSupabaseConfig, async (req: Request, res: Response) => { try { const { category } = req.params; const { limit = 20 } = req.query; const supabase = getSupabaseClient(); const { data, error } = await supabase.rpc("get_procedures_by_category", { p_category: category, p_limit: parseInt(limit as string) || 20, }); if (error) { console.error("Error fetching procedures by category:", error); return res.status(500).json({ success: false, error: error.message, }); } return res.json({ success: true, data, }); } catch (error) { console.error("Error in /procedures/by-category:", error); return res.status(500).json({ success: false, error: error instanceof Error ? error.message :"Unknown error", }); } },
); /** * GET /api/procedures/list * Get all procedures with pagination */
router.get("/list", checkSupabaseConfig, async (req: Request, res: Response) => { try { const { limit = 20, offset = 0, category } = req.query; const supabase = getSupabaseClient(); let query = supabase.from("culinary_procedures").select("*"); if (category) { query = query.eq("category", category); } const { data, error, count } = await query .range( parseInt(offset as string), parseInt(offset as string) + parseInt(limit as string) - 1, ) .order("created_at", { ascending: false }); if (error) { console.error("Error fetching procedures:", error); return res.status(500).json({ success: false, error: error.message, }); } return res.json({ success: true, data, pagination: { limit: parseInt(limit as string), offset: parseInt(offset as string), total: count, }, }); } catch (error) { console.error("Error in /procedures/list:", error); return res.status(500).json({ success: false, error: error instanceof Error ? error.message :"Unknown error", }); } },
); /** * GET /api/procedures/health * Check if procedures feature is configured */
router.get("/health", (req: Request, res: Response) => { return res.json({ success: true, configured: isSupabaseConfigured, message: isSupabaseConfigured ?"Supabase is configured and procedures feature is available" :"Supabase is not configured. Procedures feature is unavailable.", });
}); export default router;
