import { Router, Request, Response } from"express";
import { createClient, SupabaseClient } from"@supabase/supabase-js";
import crypto from"crypto";
import { generateDeviceCredentials, generatePairingQRData, getQRCodeImageUrl,
} from"../lib/tablet-device-pairing"; const router = Router(); const APP_BASE_URL = process.env.APP_BASE_URL ||"http://localhost:5173"; // Lazy initialization of Supabase client
let supabaseClient: SupabaseClient | null = null; function getSupabaseClient(): SupabaseClient { if (!supabaseClient) { const supabaseUrl = process.env.SUPABASE_URL; const supabaseKey = process.env.SUPABASE_ANON_KEY; if (!supabaseUrl || !supabaseKey) { console.warn("[Tablet API] Supabase credentials not configured - tablet features will be limited"); // Return a mock client that doesn't crash return {} as SupabaseClient; } supabaseClient = createClient(supabaseUrl, supabaseKey); } return supabaseClient;
} // ========================================
// DEVICE PAIRING & SETUP ROUTES
// ======================================== // POST /api/tablet/device/create - Admin creates new device pairing (generates QR)
router.post("/device/create", async (req: Request, res: Response) => { try { const { deviceName, credentialMode, includeChefName } = req.body; if (!deviceName || !credentialMode) { return res .status(400) .json({ error:"Missing required fields: deviceName, credentialMode" }); } // Generate device credentials const { deviceId, deviceToken } = generateDeviceCredentials(); // Generate pairing QR data const qrData = generatePairingQRData(deviceId, deviceToken, APP_BASE_URL); // Store device configuration in Supabase const { data: device, error: dbError } = await getSupabaseClient() .from("tablet_configs") .insert({ device_id: deviceId, device_name: deviceName, device_token: deviceToken, credential_mode: credentialMode, include_chef_name: includeChefName || false, enabled: true, }) .select() .single(); if (dbError) { console.error("Database error:", dbError); return res .status(500) .json({ error:"Failed to create device:" + dbError.message }); } // Generate QR code image URL const qrCodeUrl = getQRCodeImageUrl(qrData.pairing_url, 400); res.json({ success: true, device: { id: device.id, device_id: deviceId, device_name: deviceName, created_at: device.created_at, }, pairing: { device_token: deviceToken, pairing_url: qrData.pairing_url, qr_code_url: qrCodeUrl, setup_instructions: `Scan this QR code on the new tablet to automatically configure it for ${deviceName}.`, }, }); } catch (error: any) { console.error("Error creating device:", error); res.status(500).json({ error: error.message }); }
}); // GET /api/tablet/device/list - Get all registered devices (admin only)
router.get("/device/list", async (req: Request, res: Response) => { try { const { data: devices, error } = await getSupabaseClient() .from("tablet_configs") .select("id, device_id, device_name, credential_mode, include_chef_name, enabled, created_at, updated_at", ) .order("created_at", { ascending: false }); if (error) { return res.status(500).json({ error: error.message }); } res.json({ devices: devices || [], total: devices?.length || 0, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // POST /api/tablet/device/register - Tablet scans QR code and registers (automatic setup)
router.post("/device/register", async (req: Request, res: Response) => { try { const { deviceId, deviceToken, tabletInfo } = req.body; if (!deviceId || !deviceToken) { return res.status(400).json({ error:"Missing device credentials" }); } // Verify device exists and token matches const { data: device, error: lookupError } = await getSupabaseClient() .from("tablet_configs") .select("*") .eq("device_id", deviceId) .eq("device_token", deviceToken) .single(); if (lookupError || !device) { return res.status(401).json({ error:"Invalid device credentials" }); } if (!device.enabled) { return res.status(403).json({ error:"Device is disabled" }); } // Create session token for this tablet const sessionToken = crypto.randomBytes(32).toString("hex"); const expiresAt = new Date( Date.now() + 365 * 24 * 60 * 60 * 1000, ).toISOString(); // 1 year // Update device with registration info and session const { error: updateError } = await getSupabaseClient() .from("tablet_configs") .update({ session_token: sessionToken, last_registered_at: new Date().toISOString(), tablet_info: tabletInfo || {}, }) .eq("device_id", deviceId); if (updateError) { return res .status(500) .json({ error:"Failed to register device:" + updateError.message }); } // Store session const { error: sessionError } = await getSupabaseClient() .from("tablet_sessions") .insert({ device_id: deviceId, session_token: sessionToken, expires_at: expiresAt, status:"active", }); if (sessionError) { console.warn("Session storage error (non-critical):", sessionError); } res.json({ success: true, sessionToken, deviceName: device.device_name, credentialMode: device.credential_mode, includeChefName: device.include_chef_name, message: `Tablet registered successfully as"${device.device_name}"`, }); } catch (error: any) { console.error("Error registering device:", error); res.status(500).json({ error: error.message }); }
}); // PUT /api/tablet/device/:deviceId - Update device configuration
router.put("/device/:deviceId", async (req: Request, res: Response) => { try { const { deviceId } = req.params; const { deviceName, credentialMode, includeChefName, enabled } = req.body; const updateData: any = {}; if (deviceName !== undefined) updateData.device_name = deviceName; if (credentialMode !== undefined) updateData.credential_mode = credentialMode; if (includeChefName !== undefined) updateData.include_chef_name = includeChefName; if (enabled !== undefined) updateData.enabled = enabled; updateData.updated_at = new Date().toISOString(); const { error } = await getSupabaseClient() .from("tablet_configs") .update(updateData) .eq("device_id", deviceId); if (error) { return res.status(500).json({ error: error.message }); } res.json({ success: true, message:"Device updated successfully" }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // DELETE /api/tablet/device/:deviceId - Remove device
router.delete("/device/:deviceId", async (req: Request, res: Response) => { try { const { deviceId } = req.params; const { error } = await getSupabaseClient() .from("tablet_configs") .update({ enabled: false }) .eq("device_id", deviceId); if (error) { return res.status(500).json({ error: error.message }); } res.json({ success: true, message:"Device disabled successfully" }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // ========================================
// HELPER FUNCTIONS
// ======================================== // Generate QR code data for label
function generateQRData( recipeName: string, allergens: string[], chefName?: string, timestamp?: number,
): string { const printedAt = timestamp ? new Date(timestamp).toISOString().split("T")[0] : new Date().toISOString().split("T")[0]; const allergenStr = allergens.join(","); const chef = chefName ? `|${chefName}` :""; return `RECIPE:${recipeName}|ALLERGEN:${allergenStr}|DATE:${printedAt}${chef}`;
} // Generate device token
function generateDeviceToken(): string { return crypto.randomBytes(32).toString("hex");
} // Generate session token
function generateSessionToken(): string { return crypto.randomBytes(32).toString("hex");
} // POST /api/tablet/setup - Initial device setup (admin only)
router.post("/setup", async (req: Request, res: Response) => { try { const { adminToken, deviceName, credentialMode, includeChefName, outlet } = req.body; if (!adminToken || !deviceName || !credentialMode) { return res.status(400).json({ error:"Missing required fields" }); } const deviceId = crypto.randomBytes(16).toString("hex"); const deviceToken = generateDeviceToken(); const { data, error } = await getSupabaseClient().from("tablet_configs").insert({ device_id: deviceId, device_name: deviceName, credential_mode: credentialMode, include_chef_name: includeChefName || false, enabled: true, }); if (error) { return res.status(500).json({ error: error.message }); } res.json({ success: true, deviceId, deviceToken, setupUrl: `https://app.example.com/tablet/labels?device=${deviceId}&token=${deviceToken}`, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // POST /api/tablet/validate-token - Validate device token
router.post("/validate-token", async (req: Request, res: Response) => { try { const { deviceToken } = req.body; if (!deviceToken) { return res.status(400).json({ error:"Missing device token" }); } const { data: sessions, error } = await getSupabaseClient() .from("tablet_sessions") .select("*, tablet_configs(*)") .eq("device_token", deviceToken) .single(); if (error || !sessions) { return res.status(401).json({ error:"Invalid device token" }); } if (new Date(sessions.expires_at) < new Date()) { return res.status(401).json({ error:"Session expired" }); } const config = sessions.tablet_configs; if (!config.enabled) { return res.status(403).json({ error:"Device disabled" }); } // Update last activity await getSupabaseClient() .from("tablet_sessions") .update({ last_activity: new Date().toISOString() }) .eq("id", sessions.id); res.json({ valid: true, sessionToken: sessions.session_token, credentialMode: config.credential_mode, includeChefName: config.include_chef_name, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // POST /api/tablet/login - Employee ID login
router.post("/login", async (req: Request, res: Response) => { try { const { deviceToken, employeeId } = req.body; if (!deviceToken || !employeeId) { return res.status(400).json({ error:"Missing required fields" }); } const { data: config, error } = await getSupabaseClient() .from("tablet_configs") .select("*") .eq("device_id", deviceToken) .single(); if (error || !config) { return res.status(401).json({ error:"Invalid device" }); } const sessionToken = generateSessionToken(); const expiresAt = new Date( Date.now() + 30 * 24 * 60 * 60 * 1000, ).toISOString(); const { error: insertError } = await getSupabaseClient() .from("tablet_sessions") .insert({ device_token: deviceToken, session_token: sessionToken, tablet_config_id: config.id, employee_id: employeeId, expires_at: expiresAt, }); if (insertError) { return res.status(500).json({ error: insertError.message }); } res.json({ success: true, sessionToken, expiresAt, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/tablet/recipes - Get recipes for tablet (read-only)
router.get("/recipes", async (req: Request, res: Response) => { try { const { search, limit ="50" } = req.query; let query = getSupabaseClient() .from("user_recipes") .select("id, title, description, imageNames, extra, published"); if (search && typeof search ==="string") { query = query.ilike("title", `%${search}%`); } const { data: recipes, error } = await query .or("published.eq.true,extra->published.eq.true") .limit(Number(limit)) .order("created_at", { ascending: false }); if (error) { console.warn("Recipe fetch error (non-critical):", error); // Try fallback query without OR clause const fallbackQuery = getSupabaseClient() .from("user_recipes") .select("id, title, description, imageNames, extra"); const { data: fallbackRecipes } = await fallbackQuery .limit(Number(limit)) .order("created_at", { ascending: false }); const formattedRecipes = (fallbackRecipes || []).map((r: any) => ({ id: r.id, name: r.title, description: r.description, image: r.imageNames?.[0], extra: r.extra, portionSize: r.extra?.portionSize, })); return res.json(formattedRecipes); } const formattedRecipes = (recipes || []).map((r: any) => ({ id: r.id, name: r.title, description: r.description, image: r.imageNames?.[0], extra: r.extra, portionSize: r.extra?.portionSize, })); res.json(formattedRecipes); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/tablet/recipes/:id - Get single recipe details
router.get("/recipes/:id", async (req: Request, res: Response) => { try { const { id } = req.params; const { data: recipe, error } = await getSupabaseClient() .from("user_recipes") .select("*") .eq("id", id) .single(); if (error || !recipe) { return res.status(404).json({ error:"Recipe not found" }); } res.json({ id: recipe.id, name: recipe.title, description: recipe.description, image: recipe.imageNames?.[0], allergens: recipe.extra?.serverNotes?.allergens || [], ingredients: recipe.ingredients || [], instructions: recipe.instructions?.[0] ||"", cookTime: recipe.extra?.serverNotes?.cookTime, prepTime: recipe.extra?.serverNotes?.prepTime, portionSize: recipe.extra?.portionSize, createdBy: recipe.extra?.serverNotes?.createdBy, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // POST /api/tablet/print-label - Log print action
router.post("/print-label", async (req: Request, res: Response) => { try { const { deviceToken, recipeId, recipeName, allergens, portionSize, portionMultiplier, employeeId, chefName, } = req.body; if (!deviceToken || !recipeId || !recipeName) { return res.status(400).json({ error:"Missing required fields" }); } const { data: config } = await getSupabaseClient() .from("tablet_configs") .select("*") .eq("device_id", deviceToken) .single(); if (!config) { return res.status(401).json({ error:"Invalid device" }); } const bornOn = new Date().toISOString().split("T")[0]; const expiresOn = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000) .toISOString() .split("T")[0]; const qrData = generateQRData(recipeName, allergens || [], chefName); const totalPortions = portionSize && portionMultiplier ? `${portionMultiplier} x ${portionSize}` : undefined; const { error } = await getSupabaseClient().from("tablet_print_history").insert({ device_id: deviceToken, device_name: config.device_name, recipe_id: recipeId, recipe_name: recipeName, born_on: bornOn, expires_on: expiresOn, portion_size: portionSize, portion_multiplier: portionMultiplier || 1, total_portions: totalPortions, allergens: allergens || [], employee_id: employeeId, chef_name: chefName, qr_code_data: qrData, printed_at: new Date().toISOString(), }); if (error) { return res.status(500).json({ error: error.message }); } res.json({ success: true, qrData, bornOn, expiresOn, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/tablet/compliance-report - Get print history for audit
router.get("/compliance-report", async (req: Request, res: Response) => { try { const { deviceId, startDate, endDate, limit ="100" } = req.query; let query = getSupabaseClient().from("tablet_compliance_report").select("*"); if (deviceId) { query = query.eq("device_id", deviceId); } if (startDate) { query = query.gte("print_date", startDate); } if (endDate) { query = query.lte("print_date", endDate); } const { data: report, error } = await query .order("printed_at", { ascending: false }) .limit(Number(limit)); if (error) { return res.status(500).json({ error: error.message }); } res.json(report); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/tablet/settings - Get current tablet settings
router.get("/settings", async (req: Request, res: Response) => { try { const { deviceToken } = req.query; if (!deviceToken) { return res.status(400).json({ error:"Missing device token" }); } const { data: config } = await getSupabaseClient() .from("tablet_configs") .select("*") .eq("device_id", String(deviceToken)) .single(); if (!config) { return res.status(404).json({ error:"Device not found" }); } res.json({ credentialMode: config.credential_mode, includeChefName: config.include_chef_name, enabled: config.enabled, deviceName: config.device_name, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // PUT /api/tablet/settings - Update tablet settings (admin only)
router.put("/settings", async (req: Request, res: Response) => { try { const { deviceToken, credentialMode, includeChefName, enabled } = req.body; if (!deviceToken) { return res.status(400).json({ error:"Missing device token" }); } const { error } = await getSupabaseClient() .from("tablet_configs") .update({ credential_mode: credentialMode, include_chef_name: includeChefName, enabled, updated_at: new Date().toISOString(), }) .eq("device_id", deviceToken); if (error) { return res.status(500).json({ error: error.message }); } res.json({ success: true }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // POST /api/tablet/waste - Record waste entry from tablet
router.post("/waste", async (req: Request, res: Response) => { try { const { category, itemName, quantity, unit, costPerUnit, reason, employeeId, } = req.body; if (!itemName || !quantity || !unit) { return res.status(400).json({ error:"Missing required fields" }); } // Store waste entry (you can save to a database table if needed) // For now, this logs the waste entry const wasteEntry = { id: crypto.randomBytes(16).toString("hex"), category, itemName, quantity, unit, costPerUnit: costPerUnit || 0, totalCost: quantity * (costPerUnit || 0), reason, employeeId, timestamp: new Date().toISOString(), }; // In a full implementation, you would save this to a database console.log("[Tablet Waste Entry]", wasteEntry); res.status(201).json({ success: true, entryId: wasteEntry.id, message:"Waste entry recorded", }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // ========================================
// INVENTORY & LOW STOCK MANAGEMENT
// ======================================== // POST /api/tablet/inventory/shelf-count - Record monthly shelf count
router.post("/inventory/shelf-count", async (req: Request, res: Response) => { try { const { deviceId, items, countDate, employeeId, notes } = req.body; if (!deviceId || !items || !Array.isArray(items)) { return res.status(400).json({ error:"Missing required fields" }); } const countId = crypto.randomBytes(16).toString("hex"); const timestamp = new Date().toISOString(); const inventoryCount = { id: countId, device_id: deviceId, items: items.map((item: any) => ({ id: item.id || crypto.randomBytes(8).toString("hex"), name: item.name, quantity: item.quantity, unit: item.unit, location: item.location, notes: item.notes, })), count_date: countDate || timestamp.split("T")[0], employee_id: employeeId, notes, recorded_at: timestamp, }; const { error } = await getSupabaseClient().from("tablet_inventory_counts").insert({ id: countId, device_id: deviceId, items: inventoryCount.items, count_date: inventoryCount.count_date, employee_id: employeeId, notes, recorded_at: timestamp, }); if (error) { console.warn("Inventory count storage (non-critical):", error); } res.status(201).json({ success: true, countId, itemsRecorded: items.length, message:"Shelf count recorded successfully", }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // POST /api/tablet/inventory/low-stock - Create low stock alert/order suggestion
router.post("/inventory/low-stock", async (req: Request, res: Response) => { try { const { deviceId, itemName, currentQuantity, unit, reorderLevel, suggestedQuantity, employeeId, notes, } = req.body; if (!deviceId || !itemName || currentQuantity === undefined) { return res.status(400).json({ error:"Missing required fields" }); } const alertId = crypto.randomBytes(16).toString("hex"); const timestamp = new Date().toISOString(); const lowStockAlert = { id: alertId, device_id: deviceId, item_name: itemName, current_quantity: currentQuantity, unit, reorder_level: reorderLevel, suggested_quantity: suggestedQuantity, employee_id: employeeId, notes, status:"pending", created_at: timestamp, }; const { error } = await getSupabaseClient().from("tablet_low_stock_alerts").insert({ ...lowStockAlert, }); if (error) { console.warn("Low stock alert storage (non-critical):", error); } res.status(201).json({ success: true, alertId, message: `Low stock alert created for ${itemName}. Purchasing team will be notified.`, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/tablet/inventory/low-stock - Get pending low stock alerts
router.get("/inventory/low-stock", async (req: Request, res: Response) => { try { const { deviceId, status ="pending" } = req.query; let query = getSupabaseClient() .from("tablet_low_stock_alerts") .select("*") .eq("status", status); if (deviceId) { query = query.eq("device_id", deviceId); } const { data: alerts, error } = await query.order("created_at", { ascending: false, }); if (error) { return res.status(500).json({ error: error.message }); } res.json({ alerts: alerts || [], total: alerts?.length || 0, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // PUT /api/tablet/inventory/low-stock/:alertId - Update low stock alert status
router.put("/inventory/low-stock/:alertId", async (req: Request, res: Response) => { try { const { alertId } = req.params; const { status, resolvedNotes } = req.body; if (!status) { return res.status(400).json({ error:"Missing status field" }); } const updateData: any = { status }; if (resolvedNotes) { updateData.resolved_notes = resolvedNotes; updateData.resolved_at = new Date().toISOString(); } const { error } = await getSupabaseClient() .from("tablet_low_stock_alerts") .update(updateData) .eq("id", alertId); if (error) { return res.status(500).json({ error: error.message }); } res.json({ success: true, message:"Alert status updated" }); } catch (error: any) { res.status(500).json({ error: error.message }); } },
); // ========================================
// PRODUCTION & PREP ASSIGNMENT
// ======================================== // POST /api/tablet/production/update - Update production status with screenshot
router.post("/production/update", async (req: Request, res: Response) => { try { const { deviceId, productionTaskId, status, screenshotUrl, notes, employeeId, } = req.body; if (!deviceId || !productionTaskId || !status) { return res.status(400).json({ error:"Missing required fields" }); } const updateId = crypto.randomBytes(16).toString("hex"); const timestamp = new Date().toISOString(); const { error } = await getSupabaseClient().from("tablet_production_updates").insert({ id: updateId, device_id: deviceId, production_task_id: productionTaskId, status, screenshot_url: screenshotUrl, notes, employee_id: employeeId, updated_at: timestamp, }); if (error) { console.warn("Production update storage (non-critical):", error); } res.status(201).json({ success: true, updateId, message:"Production status updated and tablets notified", }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // POST /api/tablet/prep/assign - Assign prep work to staff member
router.post("/prep/assign", async (req: Request, res: Response) => { try { const { deviceId, prepTaskId, assignedToEmployeeId, dueDate, ingredients, instructions, notes, } = req.body; if (!deviceId || !prepTaskId || !assignedToEmployeeId) { return res.status(400).json({ error:"Missing required fields" }); } const assignmentId = crypto.randomBytes(16).toString("hex"); const timestamp = new Date().toISOString(); const { error } = await getSupabaseClient().from("tablet_prep_assignments").insert({ id: assignmentId, device_id: deviceId, prep_task_id: prepTaskId, assigned_to_employee_id: assignedToEmployeeId, due_date: dueDate, ingredients, instructions, notes, status:"assigned", created_at: timestamp, }); if (error) { console.warn("Prep assignment storage (non-critical):", error); } res.status(201).json({ success: true, assignmentId, message:"Prep work assigned successfully", }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/tablet/prep/assigned - Get prep assignments for employee
router.get("/prep/assigned", async (req: Request, res: Response) => { try { const { employeeId, status ="assigned" } = req.query; if (!employeeId) { return res.status(400).json({ error:"Missing employeeId" }); } let query = getSupabaseClient() .from("tablet_prep_assignments") .select("*") .eq("assigned_to_employee_id", employeeId) .eq("status", status); const { data: assignments, error } = await query.order("due_date", { ascending: true, }); if (error) { return res.status(500).json({ error: error.message }); } res.json({ assignments: assignments || [], total: assignments?.length || 0, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // PUT /api/tablet/prep/:assignmentId - Update prep assignment status
router.put("/prep/:assignmentId", async (req: Request, res: Response) => { try { const { assignmentId } = req.params; const { status, completedNotes } = req.body; if (!status) { return res.status(400).json({ error:"Missing status field" }); } const updateData: any = { status }; if (status ==="completed") { updateData.completed_at = new Date().toISOString(); if (completedNotes) { updateData.completed_notes = completedNotes; } } const { error } = await getSupabaseClient() .from("tablet_prep_assignments") .update(updateData) .eq("id", assignmentId); if (error) { return res.status(500).json({ error: error.message }); } res.json({ success: true, message:"Prep assignment updated" }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // ========================================
// RECEIVING & ITEM CHECK-IN
// ======================================== // POST /api/tablet/receiving/check-in - Record item check-in from delivery
router.post("/receiving/check-in", async (req: Request, res: Response) => { try { const { deviceId, orderId, items, employeeId, notes, } = req.body; if (!deviceId || !orderId || !items || !Array.isArray(items)) { return res.status(400).json({ error:"Missing required fields" }); } const checkInId = crypto.randomBytes(16).toString("hex"); const timestamp = new Date().toISOString(); const { error } = await getSupabaseClient().from("tablet_receiving_checkin").insert({ id: checkInId, device_id: deviceId, order_id: orderId, items: items.map((item: any) => ({ id: item.id || crypto.randomBytes(8).toString("hex"), item_name: item.itemName, quantity_expected: item.quantityExpected, quantity_received: item.quantityReceived, unit: item.unit, condition: item.condition ||"good", notes: item.notes, })), employee_id: employeeId, notes, status:"completed", checked_in_at: timestamp, }); if (error) { console.warn("Check-in storage (non-critical):", error); } res.status(201).json({ success: true, checkInId, itemsChecked: items.length, message:"Items checked in successfully", }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // GET /api/tablet/receiving/pending - Get pending receiving orders
router.get("/receiving/pending", async (req: Request, res: Response) => { try { const { deviceId, status ="pending" } = req.query; let query = getSupabaseClient() .from("tablet_receiving_orders") .select("*") .eq("status", status); if (deviceId) { query = query.eq("device_id", deviceId); } const { data: orders, error } = await query.order("expected_delivery_date", { ascending: true, }); if (error) { return res.status(500).json({ error: error.message }); } res.json({ orders: orders || [], total: orders?.length || 0, }); } catch (error: any) { res.status(500).json({ error: error.message }); }
}); // PUT /api/tablet/receiving/:orderId - Update receiving order status
router.put("/receiving/:orderId", async (req: Request, res: Response) => { try { const { orderId } = req.params; const { status, completedNotes } = req.body; if (!status) { return res.status(400).json({ error:"Missing status field" }); } const updateData: any = { status }; if (status ==="completed") { updateData.completed_at = new Date().toISOString(); if (completedNotes) { updateData.completed_notes = completedNotes; } } const { error } = await getSupabaseClient() .from("tablet_receiving_orders") .update(updateData) .eq("id", orderId); if (error) { return res.status(500).json({ error: error.message }); } res.json({ success: true, message:"Receiving order updated" }); } catch (error: any) { res.status(500).json({ error: error.message }); } },
); export default router;
