/** * EchoAurum: Financial Intelligence Core * Real double-entry bookkeeping with GL posting rules, multi-entity consolidation * and Guardian oversight for compliance and audit */ export type AurumEntityType ="hotel" |"restaurant" |"spa" |"entertainment" |"other";
export type AurumAccountType ="asset" |"liability" |"equity" |"revenue" |"expense";
export type TransactionSource ="opera" |"toast" |"vendor" |"manual" |"purchase_order" |"payroll" |"transfer";
export type JournalEntryStatus ="draft" |"pending_approval" |"posted" |"reversed" |"archived";
export type ReconciliationStatus ="pending" |"in_progress" |"matched" |"variance" |"resolved";
export type GuardianCheckStatus ="passed" |"warning" |"failed" |"pending"; export interface AurumEntity { id: string; code: string; name: string; type: AurumEntityType; parentId?: string; baseCurrency: string; fiscalYearStart: number; isConsolidated: boolean; status:"active" |"inactive"; createdAt: string; updatedAt: string;
} export interface GLAccount { id: string; code: string; name: string; description?: string; accountType: AurumAccountType; level: number; parentCode?: string; isControlAccount: boolean; requiresCostCenter: boolean; requiresDepartment: boolean; status:"active" |"archived" |"inactive"; normalBalance:"debit" |"credit"; createdAt: string; updatedAt: string;
} export interface GLPostingRule { id: string; name: string; description: string; triggerEvent: TransactionSource; priority: number; conditions: Array<{ field: string; operator:"equals" |"contains" |"gt" |"lt" |"gte" |"lte" |"in"; value: string | number | string[]; }>; debitAccount: string; creditAccount: string; debitAmount:"full" |"percentage" |"fixed"; debitValue?: number; creditAmount:"full" |"percentage" |"fixed"; creditValue?: number; autoPost: boolean; requiresApproval: boolean; requiresGuardianCheck: boolean; status:"active" |"inactive"; createdAt: string; updatedAt: string;
} export interface JournalLine { id: string; accountCode: string; accountName: string; accountType: AurumAccountType; debitAmount: number; creditAmount: number; costCenter?: string; department?: string; memo?: string;
} export interface JournalEntry { id: string; entryNumber: string; entityId: string; periodDate: string; status: JournalEntryStatus; source: TransactionSource; referenceId?: string; description: string; lines: JournalLine[]; totalDebits: number; totalCredits: number; isBalanced: boolean; createdBy: string; createdAt: string; approvedBy?: string; approvedAt?: string; reversedBy?: string; reversedAt?: string; reversalReason?: string; guardianCheckStatus: GuardianCheckStatus; guardianCheckDetails?: Record<string, unknown>; postedAt?: string;
} export interface GLAccountBalance { accountCode: string; accountName: string; accountType: AurumAccountType; entityId: string; periodDate: string; openingBalance: number; debits: number; credits: number; closingBalance: number; costCenter?: string; lastUpdated: string;
} export interface APInvoice { id: string; invoiceNumber: string; vendorId: string; vendorName: string; entityId: string; invoiceDate: string; dueDate: string; amount: number; currency: string; poNumber?: string; poLineItems?: Array<{ id: string; lineNumber: number; description: string; quantity: number; unitPrice: number; amount: number; glAccount?: string; }>; status:"received" |"matched" |"approved" |"paid" |"archived"; matchStatus:"unmatched" |"po_matched" |"receipt_matched" |"three_way_matched" |"variance"; scannedDocument?: string; OCRConfidence?: number; createdAt: string; updatedAt: string; approvedBy?: string; approvedAt?: string; paidAt?: string; paymentMethod?: string;
} export interface Reconciliation { id: string; type:"bank" |"subledger" |"intercompany" |"balance_sheet"; entityId: string; accountCode: string; periodDate: string; systemBalance: number; externalBalance: number; variance: number; status: ReconciliationStatus; matchedItems: Array<{ journalEntryId: string; externalReference: string; amount: number; }>; unmatchedItems: Array<{ type:"system" |"external"; reference: string; amount: number; ageInDays: number; }>; resolvedAt?: string; resolvedBy?: string; resolutionNotes?: string; createdAt: string; updatedAt: string;
} export interface ConsolidationEntry { id: string; parentEntityId: string; childEntityId: string; periodDate: string; type:"acquisition" |"elimination" |"intercompany_revenue" |"intercompany_expense"; accountCode: string; debitAmount: number; creditAmount: number; source:"automatic" |"manual"; approvedBy?: string; approvedAt?: string; createdAt: string;
} export interface GuardianCheckResult { id: string; checkType:"data_compliance" |"debit_credit_balance" |"account_rules" |"posting_rules" |"duplicate_detection" |"three_way_match"; journalEntryId?: string; invoiceId?: string; reconciliationId?: string; status: GuardianCheckStatus; issues: Array<{ severity:"error" |"warning" |"info"; code: string; message: string; details?: Record<string, unknown>; }>; checkedAt: string; checkedBy: string; resolvedAt?: string; resolvedBy?: string;
} export interface AurumTransaction { id: string; journalEntryId: string; entityId: string; debitAccountCode: string; creditAccountCode: string; amount: number; currency: string; source: TransactionSource; postedAt: string; memo?: string; costCenter?: string; department?: string;
} export interface AurumReport { type:"trial_balance" |"balance_sheet" |"income_statement" |"cash_flow" |"general_ledger"; entityId: string; periodDate: string; generatedAt: string; data: Record<string, unknown>;
} export interface GuardianOverride { id: string; journalEntryId?: string; invoiceId?: string; guardianId:"argus" |"zelda" |"phoenix" |"odin"; overrideReason: string; approvedBy: string; approvedAt: string; expiresAt?: string;
} // ============================================================================
// GUARDIAN SYSTEM TYPES (NEW - from aurumGuardians.ts)
// ============================================================================ export interface ArgusCheckResult { passed: boolean; errors: string[]; warnings: string[]; checksRun: string[]; riskScore: number;
} export interface DuplicateDetected { type:"EXACT_DUPLICATE" |"LIKELY_DUPLICATE" |"TRANSPOSED" |"ROUNDING"; message: string; confidence: number;
} export interface AutoHeal { type:"ROUNDING_CORRECTION" |"DUPLICATE_REMOVAL"; description: string; appliedAutomatically: boolean;
} export interface ZeldaCheckResult { passed: boolean; duplicatesDetected: DuplicateDetected[]; autoHeals: AutoHeal[]; warnings: string[];
} export interface Anomaly { type: string; severity:"INFO" |"WARNING" |"ERROR"; message: string;
} export interface PhoenixCheckResult { passed: boolean; anomalies: Anomaly[]; riskScore: number; // 0-100 warnings: string[];
} export interface OdinCheckResult { passed: boolean; transactionHash: string; auditTrailId: string; warnings: string[];
} export interface GuardianOrchestrationResult { transactionId: string; timestamp: string; argus: ArgusCheckResult; zelda: ZeldaCheckResult; phoenix: PhoenixCheckResult; odin: OdinCheckResult; passedAll: boolean; blockingErrors: string[]; warnings: string[]; riskScore: number; overallStatus:"PASSED" |"WARNINGS" |"BLOCKED";
}
