/** * Shared code between client and server * Useful to share types between client and server * and/or small pure JS functions that can be used on both client and server */ /** * Example response type for /api/demo */
export interface DemoResponse { message: string;
} // Core domain types
export type Tier1Category = |"Protein" |"Produce" |"Dairy" |"Dry Goods" |"Seafood" |"Beverage" |"Non-Food" |"Bakery" |"Frozen";
export type Tier2Category = |"Meat" |"Poultry" |"Seafood" |"Vegetables" |"Fruits" |"Milk" |"Cheese" |"Eggs" |"Spices" |"Canned" |"Grains" |"Oils" |"Cleaning" |"Paper";
export type Tier3Category = |"Chicken" |"Beef" |"Pork" |"Lamb" |"Finfish" |"Shellfish" |"Root Vegetables" |"Leafy Greens" |"Cruciferous" |"Tubers" |"Alliums" |"Squash & Gourds" |"Cucumbers" |"Legumes" |"Mushrooms" |"Hard Cheese" |"Soft Cheese" |"Citrus" |"Berries" |"Pome Fruits" |"Stone Fruits" |"Melons" |"Tropical" |"Grapes" |"Rice" |"Pasta" |"Flour" |"Coffee & Tea" |"Beer" |"Wine" |"Spirits" |"Mixers" |"Juices" |"Concentrates"; export interface ProductStandardization { standardizedName: string; standardUnit:"oz" |"g" |"lb" |"ml" |"l" |"each"; categories: { tier1: Tier1Category; tier2?: Tier2Category; tier3?: Tier3Category; };
} export interface InvoiceLineItemRaw { rawText: string; vendor?: string; productName?: string; quantity?: number; unit?: string; packSize?: string | null; totalCost?: number; unitPrice?: number | null; ord?: string | number | null; ship?: string | number | null; cases?: number | null; lineNumber?: number; glCode?: string | null; category?: string | null; confidence: number; // 0-1 flags?: string[];
} export interface StandardizedLineItem { vendor: string; productName: string; standardized: ProductStandardization; quantityPurchaseUnit: { quantity: number; unit: string; // as read from invoice totalStandardUnits: number; // converted to standardized unit quantity }; totalCost: number; costPerStandardUnit: number; // totalCost / totalStandardUnits date: string; // ISO invoiceNumber?: string; glCode?: string; // GL account code (e.g.,"5050-Seafood") glLabel?: string; // GL account label (e.g.,"Food Cost - Seafood") glConfidence?: number; // Confidence of GL classification (0-1)
} export interface InvoiceDocumentMeta { filename: string; mimeType: string; pages: number; processedAt: string; // ISO
} export interface PartyInfo { name?: string; company?: string; address?: string; email?: string; phone?: string;
}
export interface PaymentInfo { terms?: string; methods?: string; instructions?: string;
}
export interface TaxLine { label?: string; rate?: number; amount?: number;
}
export interface InvoiceHeader { seller: PartyInfo; customer: PartyInfo; invoiceLabelPresent: boolean; invoiceNumber?: string; invoiceDate?: string; // ISO orderDate?: string; // ISO deliveryDate?: string; // ISO dueDate?: string; // ISO supplyDate?: string; // ISO salesPerson?: string | null; customerOutlet?: string | null; poNumber?: string; subtotal?: number; shippingCharge?: number; totalWeight?: number; caseCount?: number; pageNumber?: string | null; discount?: number; taxes?: TaxLine[]; total?: number; payment: PaymentInfo; notes?: string;
} export interface VendorCodeMatch { code: string; outletId?: string | null; outletName?: string | null; confidence: number; source?: string | null;
} export interface InvoiceExtractionResult { meta: InvoiceDocumentMeta; vendor?: string; invoiceNumber?: string; date?: string; // ISO documentType:"invoice" |"credit_memo" |"debit_memo"; // default:"invoice" rawItems: InvoiceLineItemRaw[]; standardized: StandardizedLineItem[]; header?: InvoiceHeader; suggestedOutletId?: string | null; suggestedOutletName?: string | null; vendorCodeMatch?: VendorCodeMatch | null;
} export type ScanStatus ="needs_review" |"hold" |"approved" |"rejected";
export type AnchorRect = { page?: number; x: number; y: number; w: number; h: number;
}; // normalized [0..1] coords on the page
export type FieldAnchorMap = Record<string, AnchorRect>; export interface TrainingFieldBinding { field: string; anchor: AnchorRect; value?: string | number | null; page?: number; label?: string;
} export interface TrainingItemBinding { index: number; field: |"description" |"quantity" |"unit" |"packSize" |"glCode" |"category" |"extension" |"itemsOrdered" |"unitPrice" |"ord" |"ship" |"itemName" |"cases"; anchor: AnchorRect; value?: string | number | null; page?: number; label?: string;
} export interface InvoiceTrainingSession { id: string; createdAt: string; createdBy?: string | null; meta: { pageCount: number; itemCount: number; notes?: string | null; }; headerBindings: TrainingFieldBinding[]; itemBindings: TrainingItemBinding[]; feedbackLog?: { timestamp: string; message: string }[];
} export interface ScannedInvoice { id: string; result: InvoiceExtractionResult; attachments: string[]; vendorName: string; outletId?: string | null; vendorCodeMatch?: VendorCodeMatch | null; createdAt: string; createdBy?: string | null; status: ScanStatus; anchors?: FieldAnchorMap; trainingSessions?: InvoiceTrainingSession[];
} export interface ImageAsset { id: string; name: string; url: string; mimeType?: string | null; outletId?: string | null; vendor?: string | null; createdAt: string;
} export interface YieldProfile { productStandardName: string; yieldPercent: number; // 0-100
} export interface RecipeIngredientInput { productStandardName: string; quantity: number; // in standard unit of the product
} export interface RecipeCostBreakdownRow { productStandardName: string; quantity: number; unit: string; costPerUnit: number; extendedCost: number;
} export interface RecipeCostingResult { recipeName: string; portions: number; rows: RecipeCostBreakdownRow[]; totalRecipeCost: number; costPerPortion: number;
} // Unit normalization and conversion graph helpers
export function normalizeUnit(u: string): string { const s = (u ||"").toLowerCase().trim(); const map: Record<string, string> = { oz:"oz", ounce:"oz", ounces:"oz", lb:"lb", lbs:"lb", pound:"lb", pounds:"lb", g:"g", gram:"g", grams:"g", kg:"kg", kilogram:"kg", kilograms:"kg", ml:"ml", l:"l", liter:"l", litres:"l", litre:"l", each:"each", ea:"each", ct:"each", count:"each", case:"case", cs:"case", }; return map[s] || s;
} function getSettingsConversions(): { from: string; to: string; factor: number;
}[] { try { const raw = localStorage.getItem("echo_settings"); if (!raw) return []; const s = JSON.parse(raw); return (s.conversions || []).map((r: any) => ({ from: normalizeUnit(r.from ||""), to: normalizeUnit(r.to ||""), factor: Number(r.factor || 1), })); } catch { return []; }
} function defaultEdges() { return [ { from:"lb", to:"oz", factor: 16 }, { from:"g", to:"oz", factor: 1 / 28.3495 }, { from:"kg", to:"oz", factor: 35.27396195 }, { from:"ml", to:"oz", factor: 1 / 29.5735 }, { from:"l", to:"oz", factor: 33.8140226 }, ];
} export const toOunces = (qty: number, unit: string): number => { const src = normalizeUnit(unit); if (src ==="oz") return qty; const edges = [...defaultEdges(), ...getSettingsConversions()]; // Build adjacency with reverse edges const graph = new Map<string, { to: string; factor: number }[]>(); const add = (a: string, b: string, f: number) => { const arr = graph.get(a) || []; arr.push({ to: b, factor: f }); graph.set(a, arr); }; for (const e of edges) { add(e.from, e.to, e.factor); add(e.to, e.from, 1 / Number(e.factor || 1)); } // BFS for path to oz const target ="oz"; const q: { u: string; f: number }[] = [{ u: src, f: 1 }]; const seen = new Set<string>([src]); while (q.length) { const cur = q.shift()!; if (cur.u === target) return qty * cur.f; for (const nxt of graph.get(cur.u) || []) { if (seen.has(nxt.to)) continue; seen.add(nxt.to); q.push({ u: nxt.to, f: cur.f * nxt.factor }); } } // Fallback heuristics if no path switch (src) { case"lb": return qty * 16; case"g": return qty / 28.3495; case"kg": return (qty * 1000) / 28.3495; case"ml": return qty / 29.5735; case"l": return (qty * 1000) / 29.5735; default: return qty; }
};
