/** * Hardware device detection and enumeration */ import type { HardwareDevice, ScanDeviceType, DeviceDetectionResult } from './types'; /** * Check if WebUSB is available (for LiDAR devices) */
export async function isWebUSBAvailable(): Promise<boolean> { return 'usb' in navigator;
} /** * Check if WebHID is available (for depth cameras) */
export async function isWebHIDAvailable(): Promise<boolean> { return 'hid' in navigator;
} /** * Check if WebSerial is available */
export async function isWebSerialAvailable(): Promise<boolean> { return 'serial' in navigator;
} /** * Get all mobile cameras available */
export async function detectMobileCameras(): Promise<HardwareDevice[]> { try { const devices = await navigator.mediaDevices.enumerateDevices(); const cameras = devices.filter((device) => device.kind === 'videoinput'); return cameras.map((camera, index) => ({ id: camera.deviceId, name: camera.label || `Camera ${index + 1}`, type: 'mobile' as ScanDeviceType, manufacturer: 'Built-in', connected: true, lastSeen: Date.now(), capabilities: { supportsRGB: true, supportsDepth: false, supportsPointCloud: false, supportsIMU: false, supportsGPS: false, maxFrameRate: 30, maxResolution: { width: 1920, height: 1080 }, }, })); } catch (error) { console.warn('Failed to enumerate cameras:', error); return []; }
} /** * Detect LiDAR devices via WebUSB * Common vendors: Livox, RealSense L515, Sick, Velodyne */
export async function detectLiDARDevices(): Promise<HardwareDevice[]> { if (!await isWebUSBAvailable()) { return []; } try { const devices = await (navigator as any).usb.getDevices(); const lidarDevices: HardwareDevice[] = []; // Common LiDAR vendor/product IDs const knownLiDARs = new Map([ // Livox devices [{ vendorId: 0x3346, productId: 0x1001 }, { name: 'Livox Mid-360', manufacturer: 'Livox' }], [{ vendorId: 0x3346, productId: 0x1002 }, { name: 'Livox Qvga', manufacturer: 'Livox' }], // Intel RealSense L515 (LiDAR) [{ vendorId: 0x8086, productId: 0x0b64 }, { name: 'RealSense L515', manufacturer: 'Intel' }], // Sick LiDAR [{ vendorId: 0x0300, productId: 0x0101 }, { name: 'Sick LiDAR', manufacturer: 'Sick' }], ]); for (const device of devices) { const key = { vendorId: device.vendorId, productId: device.productId }; const lidarInfo = knownLiDARs.get(key); if (lidarInfo) { lidarDevices.push({ id: `lidar_${device.serialNumber || device.vendorId}_${device.productId}`, name: lidarInfo.name, type: 'lidar', manufacturer: lidarInfo.manufacturer, connected: true, lastSeen: Date.now(), vendorId: device.vendorId, productId: device.productId, serialNumber: device.serialNumber, capabilities: { supportsRGB: false, supportsDepth: true, supportsPointCloud: true, supportsIMU: true, supportsGPS: false, maxFrameRate: 20, maxResolution: { width: 320, height: 240 }, depthRange: { min: 0.1, max: 40 }, }, }); } } return lidarDevices; } catch (error) { console.warn('Failed to detect LiDAR devices:', error); return []; }
} /** * Detect depth cameras via WebHID * Includes: Intel RealSense D-series, Azure Kinect, etc. */
export async function detectDepthCameras(): Promise<HardwareDevice[]> { if (!await isWebHIDAvailable()) { return []; } try { const devices = await (navigator as any).hid.getDevices(); const depthCameras: HardwareDevice[] = []; // Common depth camera vendor/product IDs const knownDepthCameras = new Map([ // Intel RealSense D400 series [{ vendorId: 0x8086, productId: 0x0b07 }, { name: 'RealSense D435', manufacturer: 'Intel' }], [{ vendorId: 0x8086, productId: 0x0b3a }, { name: 'RealSense D455', manufacturer: 'Intel' }], // Azure Kinect [{ vendorId: 0x045e, productId: 0x097a }, { name: 'Azure Kinect DK', manufacturer: 'Microsoft' }], // Orbbec [{ vendorId: 0x2bc5, productId: 0x0503 }, { name: 'Femto Bolt', manufacturer: 'Orbbec' }], ]); for (const device of devices) { const key = { vendorId: device.vendorId, productId: device.productId }; const cameraInfo = knownDepthCameras.get(key); if (cameraInfo) { depthCameras.push({ id: `depth_${device.vendorId}_${device.productId}`, name: cameraInfo.name, type: 'depthcam', manufacturer: cameraInfo.manufacturer, connected: true, lastSeen: Date.now(), vendorId: device.vendorId, productId: device.productId, capabilities: { supportsRGB: true, supportsDepth: true, supportsPointCloud: true, supportsIMU: true, supportsGPS: false, maxFrameRate: 30, maxResolution: { width: 1280, height: 720 }, depthRange: { min: 0.1, max: 4 }, }, }); } } return depthCameras; } catch (error) { console.warn('Failed to detect depth cameras:', error); return []; }
} /** * Detect drone/photogrammetry sources * Can be from WebSocket, HTTP stream, or local file drop */
export async function detectDroneDevices(): Promise<HardwareDevice[]> { // Drone detection would come from: // 1. WebSocket connection to drone SDK (DJI, Auterion, etc.) // 2. Network broadcast (mDNS) // 3. Local configuration file // For now, return empty - user needs to manually select or configure return [ // Example: you could check for local DJI SDK or other drone software // This is a placeholder for future expansion ];
} /** * Scan for all available hardware devices */
export async function detectAllDevices(): Promise<DeviceDetectionResult> { const [mobileCameras, lidarDevices, depthCameras, droneDevices] = await Promise.all([ detectMobileCameras(), detectLiDARDevices(), detectDepthCameras(), detectDroneDevices(), ]); const all = [...mobileCameras, ...lidarDevices, ...depthCameras, ...droneDevices]; // Recommend best device in priority order let recommended: HardwareDevice | undefined; if (lidarDevices.length > 0) { recommended = lidarDevices[0]; // LiDAR is preferred for 3D scanning } else if (depthCameras.length > 0) { recommended = depthCameras[0]; // Depth camera is next best } else if (mobileCameras.length > 0) { recommended = mobileCameras[0]; // Mobile camera is fallback } // Auto-detect: if exactly one non-mobile device, use it let autoDetected: HardwareDevice | undefined; const nonMobileDevices = all.filter((d) => d.type !== 'mobile'); if (nonMobileDevices.length === 1) { autoDetected = nonMobileDevices[0]; } return { available: all, autoDetected, recommended, };
} /** * Request permission to use a device (for WebUSB, WebHID) */
export async function requestDeviceAccess(device: HardwareDevice): Promise<boolean> { try { if (device.type === 'lidar' && device.vendorId) { const filter = { vendorId: device.vendorId, productId: device.productId, }; const selectedDevices = await (navigator as any).usb.requestDevice({ filters: [filter] }); return !!selectedDevices; } else if (device.type === 'depthcam') { const filter = { vendorId: device.vendorId, productId: device.productId, }; const selectedDevices = await (navigator as any).hid.requestDevice({ filters: [filter] }); return !!selectedDevices; } else if (device.type === 'mobile') { // Mobile camera access is requested by the driver when streaming return true; } return false; } catch (error) { console.warn('Failed to request device access:', error); return false; }
} /** * Watch for device connections/disconnections */
export function watchDeviceConnections( onConnected: (device: HardwareDevice) => void, onDisconnected: (device: HardwareDevice) => void
): () => void { const handlers: { [key: string]: (event: any) => void } = {}; // WebUSB device connection if ('usb' in navigator) { handlers.usbConnect = async (event: any) => { const devices = await detectLiDARDevices(); devices.forEach(onConnected); }; handlers.usbDisconnect = async (event: any) => { // Handle USB disconnect onDisconnected({ id: 'usb_device', name: 'USB Device', type: 'lidar', connected: false, lastSeen: Date.now(), capabilities: { supportsRGB: false, supportsDepth: false, supportsPointCloud: false, supportsIMU: false, supportsGPS: false, maxFrameRate: 0, maxResolution: { width: 0, height: 0 }, }, }); }; (navigator as any).usb.addEventListener('connect', handlers.usbConnect); (navigator as any).usb.addEventListener('disconnect', handlers.usbDisconnect); } // Cleanup function return () => { if ('usb' in navigator) { (navigator as any).usb.removeEventListener('connect', handlers.usbConnect); (navigator as any).usb.removeEventListener('disconnect', handlers.usbDisconnect); } };
}
