import * as THREE from 'three'; export interface LayoutObject { id: string; type: string; position: [number, number, number]; rotation?: [number, number, number]; dimensions?: { width?: number; length?: number }; seats?: number;
} export interface RoomDimensions { width: number; length: number;
} export interface LayoutValidation { isValid: boolean; issues: string[]; warnings: string[]; accessibility: { compliant: boolean; aisleWidth: number; minAisleRequired: number; };
} /** * Calculate optimal table arrangement for dining layout */
export function optimizeTableArrangement( room: RoomDimensions, covers: number, layout: LayoutObject[]
): LayoutObject[] { const optimized = [...layout]; const tableSpacing = 1.5; // Minimum spacing between tables const aisleWidth = 1.5; // ADA minimum // Group tables by type const roundTables = optimized.filter((o) => o.type === 'table_round'); const rectTables = optimized.filter((o) => o.type === 'table_rect'); // Calculate grid positions const gridWidth = Math.floor(room.width / (3.5 + tableSpacing)); // ~3.5ft table + spacing const gridLength = Math.floor(room.length / (3.5 + tableSpacing)); let position = 0; // Position round tables in grid pattern roundTables.forEach((table) => { const row = Math.floor(position / gridWidth); const col = position % gridWidth; const x = -room.width / 2 + 2 + col * (3.5 + tableSpacing); const z = -room.length / 2 + 2 + row * (3.5 + tableSpacing); const idx = optimized.findIndex((t) => t.id === table.id); if (idx !== -1) { optimized[idx].position = [x, 0, z]; } position++; }); return optimized;
} /** * Validate layout for ADA compliance and spacing */
export function validateLayout( layout: LayoutObject[], room: RoomDimensions
): LayoutValidation { const issues: string[] = []; const warnings: string[] = []; const minAisleWidth = 1.524; // 5 feet in meters // Check object spacing for (let i = 0; i < layout.length; i++) { for (let j = i + 1; j < layout.length; j++) { const obj1 = layout[i]; const obj2 = layout[j]; const distance = Math.sqrt( Math.pow(obj2.position[0] - obj1.position[0], 2) + Math.pow(obj2.position[2] - obj1.position[2], 2) ); if (distance < 1.0) { issues.push( `Objects"${obj1.id}" and"${obj2.id}" are too close (${distance.toFixed(2)}m)` ); } } } // Check room boundaries layout.forEach((obj) => { if (Math.abs(obj.position[0]) > room.width / 2 - 0.5) { warnings.push(`Object"${obj.id}" is near the left/right boundary`); } if (Math.abs(obj.position[2]) > room.length / 2 - 0.5) { warnings.push(`Object"${obj.id}" is near the front/back boundary`); } }); // Calculate seating and capacity const totalSeats = layout.reduce((sum, obj) => sum + (obj.seats || 0), 0); if (totalSeats === 0) { warnings.push('No seating configured in layout'); } return { isValid: issues.length === 0, issues, warnings, accessibility: { compliant: issues.length === 0, aisleWidth: minAisleWidth, minAisleRequired: minAisleWidth, }, };
} /** * Calculate floor space utilization */
export function calculateUtilization( layout: LayoutObject[], room: RoomDimensions
): { totalArea: number; occupiedArea: number; utilizationPercent: number; availableSpace: number;
} { const totalArea = room.width * room.length; let occupiedArea = 0; layout.forEach((obj) => { if (obj.type === 'table_round') { occupiedArea += Math.PI * Math.pow(1.6, 2); // ~8 sqm for round table } else if (obj.type === 'table_rect') { occupiedArea += 1.5 * 0.8; // ~1.2 sqm for rect table } else if (obj.type === 'buffet') { const dims = obj.dimensions || { width: 3, length: 0.6 }; occupiedArea += (dims.width || 3) * (dims.length || 0.6); } else if (obj.type === 'dance_floor') { const dims = obj.dimensions || { width: 4, length: 4 }; occupiedArea += (dims.width || 4) * (dims.length || 4); } else { occupiedArea += 0.5; // Default small footprint } }); const utilizationPercent = (occupiedArea / totalArea) * 100; const availableSpace = totalArea - occupiedArea; return { totalArea, occupiedArea, utilizationPercent, availableSpace, };
} /** * Generate layout statistics */
export function generateLayoutStats(layout: LayoutObject[]) { const stats = { totalObjects: layout.length, tables: layout.filter((o) => o.type.startsWith('table')).length, roundTables: layout.filter((o) => o.type === 'table_round').length, rectTables: layout.filter((o) => o.type === 'table_rect').length, chairs: layout.filter((o) => o.type === 'chair').length, buffets: layout.filter((o) => o.type === 'buffet').length, totalSeats: layout.reduce((sum, o) => sum + (o.seats || 0), 0), danceFloors: layout.filter((o) => o.type === 'dance_floor').length, decorativeItems: layout.filter((o) => o.type === 'equipment' || o.type === 'station').length, }; return stats;
} /** * Export layout to JSON */
export function exportLayoutJSON( layout: LayoutObject[], metadata: { name: string; date: string; room: RoomDimensions }
): string { const data = { metadata, layout, stats: generateLayoutStats(layout), timestamp: new Date().toISOString(), }; return JSON.stringify(data, null, 2);
} /** * Import layout from JSON */
export function importLayoutJSON(jsonString: string): { layout: LayoutObject[]; metadata: any; stats: any;
} { try { const data = JSON.parse(jsonString); return { layout: data.layout || [], metadata: data.metadata || {}, stats: data.stats || {}, }; } catch (error) { throw new Error(`Failed to parse layout JSON: ${error}`); }
} /** * Suggest layout improvements */
export function suggestImprovements( layout: LayoutObject[], room: RoomDimensions
): string[] { const suggestions: string[] = []; const validation = validateLayout(layout, room); const utilization = calculateUtilization(layout, room); const stats = generateLayoutStats(layout); if (validation.issues.length > 0) { suggestions.push('Fix compliance issues before finalizing layout'); } if (stats.totalSeats === 0) { suggestions.push('Add seating to accommodate guests'); } if (utilization.utilizationPercent < 40) { suggestions.push('Add more elements to better utilize available space'); } if (utilization.utilizationPercent > 80) { suggestions.push('Layout may feel crowded; consider removing some elements'); } if (stats.buffets === 0 && stats.totalSeats > 20) { suggestions.push('Consider adding buffet stations for large guest count'); } if (stats.danceFloors === 0 && stats.totalSeats > 50) { suggestions.push('Add a dance floor for interactive entertainment'); } return suggestions;
} /** * Calculate scene bounds for camera positioning */
export function calculateSceneBounds( layout: LayoutObject[]
): { min: THREE.Vector3; max: THREE.Vector3; center: THREE.Vector3; radius: number;
} { const positions = layout.map((o) => new THREE.Vector3(...o.position)); if (positions.length === 0) { return { min: new THREE.Vector3(-5, 0, -5), max: new THREE.Vector3(5, 2, 5), center: new THREE.Vector3(0, 1, 0), radius: 10, }; } const min = new THREE.Vector3( Math.min(...positions.map((p) => p.x)), Math.min(...positions.map((p) => p.y)), Math.min(...positions.map((p) => p.z)) ); const max = new THREE.Vector3( Math.max(...positions.map((p) => p.x)), Math.max(...positions.map((p) => p.y)), Math.max(...positions.map((p) => p.z)) ); const center = new THREE.Vector3( (min.x + max.x) / 2, (min.y + max.y) / 2, (min.z + max.z) / 2 ); const radius = Math.max( max.x - min.x, max.z - min.z ) / 2 + 2; return { min, max, center, radius };
}
