import { LayoutObject, RoomDimensions } from './layoutUtils'; export interface ExportOptions { format: 'png' | 'jpg' | 'pdf' | 'json' | 'svg'; quality?: number; // 0-1 for image formats includeMetadata?: boolean; includeDimensions?: boolean; filename?: string;
} export interface RenderSettings { width: number; height: number; dpi?: number; backgroundColor?: string; showGrid?: boolean; showWalls?: boolean; showLabels?: boolean;
} /** * Export canvas as PNG image */
export async function exportCanvasPNG( canvas: HTMLCanvasElement, options: Partial<ExportOptions> = {}
): Promise<Blob | null> { return new Promise((resolve) => { canvas.toBlob( (blob) => resolve(blob), 'image/png', options.quality || 1.0 ); });
} /** * Export canvas as JPEG image */
export async function exportCanvasJPEG( canvas: HTMLCanvasElement, options: Partial<ExportOptions> = {}
): Promise<Blob | null> { return new Promise((resolve) => { canvas.toBlob( (blob) => resolve(blob), 'image/jpeg', options.quality || 0.9 ); });
} /** * Generate SVG floorplan from layout */
export function generateSVGFloorplan( layout: LayoutObject[], room: RoomDimensions, options: Partial<RenderSettings> = {}
): string { const width = options.width || 800; const height = options.height || 600; const scale = Math.min(width / room.width, height / room.length) * 0.8; const offsetX = width / 2; const offsetY = height / 2; let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg"> <defs> <style> .room-bg { fill: #f5f5f0; stroke: #333; stroke-width: 2; } .table-round { fill: #d4af87; stroke: #8b7355; stroke-width: 1; } .table-rect { fill: #d4af87; stroke: #8b7355; stroke-width: 1; } .chair { fill: #5a5a5a; stroke: #333; stroke-width: 0.5; } .buffet { fill: #8e9aa9; stroke: #667; stroke-width: 1; } .text { font-family: Arial; font-size: 10px; } </style> </defs> <!-- Room background --> <rect class="room-bg" x="${offsetX - (room.width / 2) * scale}" y="${offsetY - (room.length / 2) * scale}" width="${room.width * scale}" height="${room.length * scale}"/> <!-- Grid lines --> ${options.showGrid ? generateGridLines(room, scale, offsetX, offsetY) : ''} <!-- Layout elements --> ${layout.map((obj) => generateSVGElement(obj, scale, offsetX, offsetY)).join('\n')} <!-- Dimensions --> ${options.includeDimensions ? generateDimensionLabels(room, scale, offsetX, offsetY) : ''}
</svg>`; return svg;
} /** * Generate PDF floorplan */
export function generatePDFFloorplan( layout: LayoutObject[], room: RoomDimensions, options: Partial<RenderSettings> = {}
): string { // This creates a basic PDF structure // For a complete solution, use a library like jsPDF + html2pdf const title = options.filename || 'Event Layout Floorplan'; const timestamp = new Date().toLocaleString(); const svg = generateSVGFloorplan(layout, room, options); // Return as data URL that can be used with a PDF library return `data:image/svg+xml;base64,${btoa(svg)}`;
} /** * Export layout metadata as JSON */
export function exportLayoutMetadata( layout: LayoutObject[], room: RoomDimensions, metadata: Record<string, any> = {}
): string { const totalSeats = layout.reduce((sum, obj) => sum + (obj.seats || 0), 0); const tables = layout.filter((o) => o.type.startsWith('table')).length; const buffets = layout.filter((o) => o.type === 'buffet').length; const exportData = { metadata: { ...metadata, exportedAt: new Date().toISOString(), roomDimensions: room, }, summary: { totalObjects: layout.length, totalTables: tables, totalSeats, totalBuffets: buffets, roomArea: room.width * room.length, }, objects: layout.map((obj) => ({ id: obj.id, type: obj.type, position: obj.position, rotation: obj.rotation, seats: obj.seats, dimensions: obj.dimensions, })), }; return JSON.stringify(exportData, null, 2);
} /** * Download file to user's computer */
export function downloadFile( content: string | Blob, filename: string, mimeType: string = 'text/plain'
): void { let blob: Blob; if (content instanceof Blob) { blob = content; } else { blob = new Blob([content], { type: mimeType }); } const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); document.body.removeChild(link); URL.revokeObjectURL(url);
} /** * Export layout in multiple formats */
export async function exportLayout( layout: LayoutObject[], room: RoomDimensions, canvas: HTMLCanvasElement | null, options: ExportOptions
): Promise<void> { const baseFilename = options.filename || `layout_${Date.now()}`; try { switch (options.format) { case 'png': { if (!canvas) throw new Error('Canvas required for PNG export'); const blob = await exportCanvasPNG(canvas, options); if (blob) downloadFile(blob, `${baseFilename}.png`, 'image/png'); break; } case 'jpg': { if (!canvas) throw new Error('Canvas required for JPEG export'); const blob = await exportCanvasJPEG(canvas, options); if (blob) downloadFile(blob, `${baseFilename}.jpg`, 'image/jpeg'); break; } case 'svg': { const svg = generateSVGFloorplan(layout, room, { width: 1200, height: 900, showGrid: true, includeDimensions: true, }); downloadFile(svg, `${baseFilename}.svg`, 'image/svg+xml'); break; } case 'pdf': { const pdfUrl = generatePDFFloorplan(layout, room); // In a real implementation, use jsPDF to create actual PDF window.open(pdfUrl, '_blank'); break; } case 'json': { const json = exportLayoutMetadata(layout, room, { exportFormat: 'complete', }); downloadFile(json, `${baseFilename}.json`, 'application/json'); break; } default: throw new Error(`Unsupported export format: ${options.format}`); } } catch (error) { console.error('Export failed:', error); throw error; }
} /** * Generate grid lines for SVG */
function generateGridLines( room: RoomDimensions, scale: number, offsetX: number, offsetY: number
): string { const gridSize = 1; // 1 meter grid const lines: string[] = []; // Vertical lines for (let x = -room.width / 2; x <= room.width / 2; x += gridSize) { const x1 = offsetX + x * scale; const y1 = offsetY - (room.length / 2) * scale; const y2 = offsetY + (room.length / 2) * scale; lines.push( `<line x1="${x1}" y1="${y1}" x2="${x1}" y2="${y2}" stroke="#ddd" stroke-width="0.5"/>` ); } // Horizontal lines for (let z = -room.length / 2; z <= room.length / 2; z += gridSize) { const x1 = offsetX - (room.width / 2) * scale; const x2 = offsetX + (room.width / 2) * scale; const y = offsetY + z * scale; lines.push( `<line x1="${x1}" y1="${y}" x2="${x2}" y2="${y}" stroke="#ddd" stroke-width="0.5"/>` ); } return lines.join('\n');
} /** * Generate SVG element for layout object */
function generateSVGElement( obj: LayoutObject, scale: number, offsetX: number, offsetY: number
): string { const x = offsetX + obj.position[0] * scale; const y = offsetY + obj.position[2] * scale; switch (obj.type) { case 'table_round': { const radius = 1.6 * scale; return `<circle class="table-round" cx="${x}" cy="${y}" r="${radius}"/> <text class="text" x="${x}" y="${y + 5}" text-anchor="middle">Round</text>`; } case 'table_rect': { const width = 1.5 * scale; const height = 0.8 * scale; return `<rect class="table-rect" x="${x - width / 2}" y="${y - height / 2}" width="${width}" height="${height}"/> <text class="text" x="${x}" y="${y + 5}" text-anchor="middle">Rect</text>`; } case 'buffet': { const length = (obj.dimensions?.length || 3) * scale; const width = 0.6 * scale; return `<rect class="buffet" x="${x - length / 2}" y="${y - width / 2}" width="${length}" height="${width}"/>`; } case 'dance_floor': { const width = (obj.dimensions?.width || 4) * scale; const length = (obj.dimensions?.length || 4) * scale; return `<rect class="buffet" x="${x - width / 2}" y="${y - length / 2}" width="${width}" height="${length}" fill="#1a1a2e" opacity="0.7"/>`; } default: return `<circle cx="${x}" cy="${y}" r="5" fill="#999"/>`; }
} /** * Generate dimension labels */
function generateDimensionLabels( room: RoomDimensions, scale: number, offsetX: number, offsetY: number
): string { const labels: string[] = []; // Width label labels.push(` <text class="text" x="${offsetX}" y="${offsetY - (room.length / 2) * scale - 20}" text-anchor="middle" font-weight="bold"> ${room.width.toFixed(1)}m </text> `); // Length label labels.push(` <text class="text" x="${offsetX - (room.width / 2) * scale - 20}" y="${offsetY}" text-anchor="middle" font-weight="bold" transform="rotate(-90 ${offsetX - (room.width / 2) * scale - 20} ${offsetY})"> ${room.length.toFixed(1)}m </text> `); return labels.join('\n');
}
