/** * React Hooks for ML Forecasting * Provides easy access to demand forecasts with caching and real-time updates */ import { useEffect, useState, useCallback } from 'react';
import { supabase } from '@/lib/supabaseClient';
import { logger } from '@/lib/logger'; interface ForecastData { product_id: string; outlet_id: string; forecast_date: string; point_forecast: number[]; p10: number[]; p50: number[]; p90: number[]; confidence: number; explanation: { trend: 'increasing' | 'decreasing' | 'stable'; change_percent: number; recent_average: number; forecast_average: number; factors: string[]; }; components: { xgboost: number[] | null; lstm: number[] | null; arima: number[] | null; };
} /** * Fetch forecast for a product at an outlet */
export function useForecast( organizationId: string, productId: string, outletId: string, forecastDays: number = 14
) { const [forecast, setForecast] = useState<ForecastData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [lastUpdated, setLastUpdated] = useState<string | null>(null); const refetch = useCallback(async () => { try { setLoading(true); setError(null); // Call Edge Function const response = await fetch('/functions/forecast/predict', { method: 'POST', headers: { 'Content-Type': 'application/json', }, body: JSON.stringify({ organization_id: organizationId, product_id: productId, outlet_id: outletId, forecast_days: forecastDays, }), }); if (!response.ok) { throw new Error(`Forecast error: ${response.statusText}`); } const data = (await response.json()) as ForecastData; setForecast(data); setLastUpdated(new Date().toISOString()); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to fetch forecast'); } finally { setLoading(false); } }, [organizationId, productId, outletId, forecastDays]); useEffect(() => { refetch(); // Refresh every 12 hours const interval = setInterval(refetch, 12 * 60 * 60 * 1000); return () => clearInterval(interval); }, [refetch]); return { forecast, loading, error, lastUpdated, refetch, };
} /** * Fetch forecasts for multiple products at an outlet */
export function useOutletForecasts( organizationId: string, outletId: string, productIds: string[]
) { const [forecasts, setForecasts] = useState<Record<string, ForecastData>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { if (productIds.length === 0) { setLoading(false); return; } const fetchAll = async () => { try { setLoading(true); setError(null); const results: Record<string, ForecastData> = {}; // Fetch in parallel (max 5 concurrent) for (let i = 0; i < productIds.length; i += 5) { const batch = productIds.slice(i, i + 5); const promises = batch.map((productId) => fetch('/functions/forecast/predict', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ organization_id: organizationId, product_id: productId, outlet_id: outletId, forecast_days: 14, }), }) .then((res) => res.json()) .then((data) => { results[productId] = data; }) .catch((err) => logger.error(`Failed to fetch forecast for ${productId}:`, err)) ); await Promise.all(promises); } setForecasts(results); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to fetch forecasts'); } finally { setLoading(false); } }; fetchAll(); }, [organizationId, outletId, productIds.join(',')]); return { forecasts, loading, error, };
} /** * Get forecast status (fresh vs stale) */
export function useForecastStatus( organizationId: string, productId?: string, outletId?: string
) { const [status, setStatus] = useState<{ status: 'fresh' | 'stale' | 'no_forecast'; last_forecast?: string; confidence?: number; ttl?: string; } | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { const fetch = async () => { try { const params = new URLSearchParams({ organization_id: organizationId, ...(productId && { product_id: productId }), ...(outletId && { outlet_id: outletId }), }); const response = await fetch(`/functions/forecast/status?${params}`); const data = await response.json(); setStatus(data); } catch (err) { logger.error('Failed to fetch forecast status:', err); } finally { setLoading(false); } }; fetch(); }, [organizationId, productId, outletId]); return { status, loading };
} /** * Trigger model retraining */
export function useForecastRetraining() { const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const retrain = useCallback(async (organizationId: string) => { try { setLoading(true); setError(null); const response = await fetch('/functions/forecast/retrain', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ organization_id: organizationId }), }); if (!response.ok) { throw new Error(`Retrain error: ${response.statusText}`); } return await response.json(); } catch (err) { const message = err instanceof Error ? err.message : 'Failed to trigger retraining'; setError(message); throw err; } finally { setLoading(false); } }, []); return { retrain, loading, error };
} /** * Subscribe to real-time forecast updates */
export function useForecastSubscription(organizationId: string) { const [lastUpdate, setLastUpdate] = useState<{ product_id: string; outlet_id: string; timestamp: string; } | null>(null); useEffect(() => { const subscription = supabase .channel(`forecasts:${organizationId}`) .on( 'postgres_changes', { event: 'INSERT', schema: 'public', table: 'forecast_cache', filter: `organization_id=eq.${organizationId}`, }, (payload) => { setLastUpdate({ product_id: payload.new.product_id, outlet_id: payload.new.outlet_id, timestamp: new Date().toISOString(), }); } ) .subscribe(); return () => { supabase.removeChannel(subscription); }; }, [organizationId]); return lastUpdate;
} /** * Calculate suggested reorder quantity based on forecast */
export function calculateReorderQty( forecast: ForecastData, safetyStockDays: number = 3, currentStock: number = 0
): { suggested_qty: number; reorder_point: number; safety_stock: number; recommendation: 'order_now' | 'order_soon' | 'ok' | 'overstock';
} { const avgForecast = forecast.point_forecast.slice(0, 7).reduce((a, b) => a + b, 0) / 7; const safetyStock = avgForecast * safetyStockDays; const reorderPoint = avgForecast * 2; // Reorder when stock < 2 days of avg demand const suggestedQty = Math.max(0, reorderPoint + safetyStock - currentStock); let recommendation: 'order_now' | 'order_soon' | 'ok' | 'overstock' = 'ok'; if (currentStock < reorderPoint) { recommendation = 'order_now'; } else if (currentStock < reorderPoint + avgForecast) { recommendation = 'order_soon'; } else if (currentStock > reorderPoint + safetyStock * 2) { recommendation = 'overstock'; } return { suggested_qty: Math.round(suggestedQty), reorder_point: Math.round(reorderPoint), safety_stock: Math.round(safetyStock), recommendation, };
} export default { useForecast, useOutletForecasts, useForecastStatus, useForecastRetraining, useForecastSubscription, calculateReorderQty,
};
