/** * React Hooks for Purchasing Domain * Provides convenient data access patterns for React components * Handles loading, error, and caching states */ import { useEffect, useState, useCallback } from 'react';
import suppliersAPI from '@/api/suppliers';
import aslAPI from '@/api/approved-suppliers';
import productsAPI from '@/api/products';
import poAPI from '@/api/purchase-orders';
import { logger } from '@/lib/logger'; // ============================================================================
// SUPPLIERS HOOKS
// ============================================================================ export function useSuppliers(filters?: Parameters<typeof suppliersAPI.getSuppliers>[0]) { const [data, setData] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { const fetchSuppliers = async () => { try { setLoading(true); setError(null); const suppliers = await suppliersAPI.getSuppliers(filters); setData(suppliers || []); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to fetch suppliers'); } finally { setLoading(false); } }; fetchSuppliers(); }, [filters?.search, filters?.supplier_type, filters?.compliance_status]); return { data, loading, error };
} export function useSupplier(supplierId: string) { const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { if (!supplierId) return; const fetchSupplier = async () => { try { setLoading(true); const supplier = await suppliersAPI.getSupplier(supplierId); setData(supplier); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to fetch supplier'); } finally { setLoading(false); } }; fetchSupplier(); }, [supplierId]); return { data, loading, error };
} export function useSupplierSearch(query: string) { const [results, setResults] = useState<any[]>([]); const [loading, setLoading] = useState(false); const search = useCallback(async (q: string) => { if (!q || q.length < 2) { setResults([]); return; } try { setLoading(true); const data = await suppliersAPI.searchSuppliers(q); setResults(data || []); } catch (err) { logger.error('Search error:', err); setResults([]); } finally { setLoading(false); } }, []); useEffect(() => { const timer = setTimeout(() => search(query), 300); // Debounce return () => clearTimeout(timer); }, [query, search]); return { results, loading };
} // ============================================================================
// ASL (APPROVED SUPPLIER LIST) HOOKS
// ============================================================================ export function useApprovedSuppliers(outletId?: string, categoryTier1Id?: string) { const [data, setData] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { if (!outletId) return; const fetchASL = async () => { try { setLoading(true); const suppliers = await aslAPI.getOutletSuppliers(outletId, categoryTier1Id); setData(suppliers || []); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to fetch suppliers'); } finally { setLoading(false); } }; fetchASL(); }, [outletId, categoryTier1Id]); return { data, loading, error };
} export function useIsSupplierApproved(supplierId: string, outletId: string) { const [isApproved, setIsApproved] = useState(false); const [loading, setLoading] = useState(true); useEffect(() => { if (!supplierId || !outletId) return; const check = async () => { try { const approved = await aslAPI.isSupplierApproved(supplierId, outletId); setIsApproved(approved); } catch (err) { logger.error('Error checking supplier approval:', err); } finally { setLoading(false); } }; check(); }, [supplierId, outletId]); return { isApproved, loading };
} // ============================================================================
// PRODUCTS HOOKS
// ============================================================================ export function useProducts( tier1Id?: string, tier2Id?: string, search?: string
) { const [data, setData] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { const fetchProducts = async () => { try { setLoading(true); const products = await productsAPI.getProductsByCategory(tier1Id, tier2Id, undefined, { search, limit: 100, }); setData(products || []); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to fetch products'); } finally { setLoading(false); } }; fetchProducts(); }, [tier1Id, tier2Id, search]); return { data, loading, error };
} export function useProductCategories() { const [categories, setCategories] = useState<any[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { const fetch = async () => { try { const data = await productsAPI.getProductCategories(); setCategories(data || []); } catch (err) { logger.error('Error fetching categories:', err); } finally { setLoading(false); } }; fetch(); }, []); return { categories, loading };
} export function useProductSearch(query: string) { const [results, setResults] = useState<any[]>([]); const [loading, setLoading] = useState(false); useEffect(() => { if (!query || query.length < 2) { setResults([]); return; } const timer = setTimeout(async () => { try { setLoading(true); const products = await productsAPI.searchProducts(query, 20); setResults(products || []); } catch (err) { logger.error('Search error:', err); } finally { setLoading(false); } }, 300); // Debounce return () => clearTimeout(timer); }, [query]); return { results, loading };
} export function useOutletFavorites(outletId: string) { const [favorites, setFavorites] = useState<any[]>([]); const [loading, setLoading] = useState(true); const addFavorite = useCallback(async (productId: string, supplierId?: string, defaultQty?: number) => { try { await productsAPI.addToFavorites(outletId, productId, supplierId, defaultQty); // Refetch favorites const updated = await productsAPI.getOutletFavorites(outletId); setFavorites(updated || []); } catch (err) { logger.error('Error adding favorite:', err); } }, [outletId]); const removeFavorite = useCallback(async (productId: string, supplierId?: string) => { try { await productsAPI.removeFromFavorites(outletId, productId, supplierId); const updated = await productsAPI.getOutletFavorites(outletId); setFavorites(updated || []); } catch (err) { logger.error('Error removing favorite:', err); } }, [outletId]); useEffect(() => { if (!outletId) return; const fetch = async () => { try { setLoading(true); const data = await productsAPI.getOutletFavorites(outletId); setFavorites(data || []); } catch (err) { logger.error('Error fetching favorites:', err); } finally { setLoading(false); } }; fetch(); }, [outletId]); return { favorites, loading, addFavorite, removeFavorite };
} // ============================================================================
// PURCHASE ORDERS HOOKS
// ============================================================================ export function usePurchaseOrders(filters?: Parameters<typeof poAPI.getPurchaseOrders>[0]) { const [data, setData] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { const fetch = async () => { try { setLoading(true); const pos = await poAPI.getPurchaseOrders(filters); setData(pos || []); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to fetch POs'); } finally { setLoading(false); } }; fetch(); }, [filters?.outlet_id, filters?.vendor_id, filters?.status]); return { data, loading, error };
} export function usePurchaseOrder(poId: string) { const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { if (!poId) return; const fetch = async () => { try { setLoading(true); const po = await poAPI.getPurchaseOrder(poId); setData(po); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to fetch PO'); } finally { setLoading(false); } }; fetch(); }, [poId]); return { data, loading, error };
} export function usePendingApprovals() { const [approvals, setApprovals] = useState<any[]>([]); const [loading, setLoading] = useState(true); const approvePO = useCallback(async (poId: string) => { try { await poAPI.approvePO(poId); // Refetch const updated = await poAPI.getPendingApprovals(); setApprovals(updated || []); } catch (err) { logger.error('Error approving PO:', err); } }, []); useEffect(() => { const fetch = async () => { try { setLoading(true); const pending = await poAPI.getPendingApprovals(); setApprovals(pending || []); } catch (err) { logger.error('Error fetching approvals:', err); } finally { setLoading(false); } }; fetch(); }, []); return { approvals, loading, approvePO };
} export default { useSuppliers, useSupplier, useSupplierSearch, useApprovedSuppliers, useIsSupplierApproved, useProducts, useProductCategories, useProductSearch, useOutletFavorites, usePurchaseOrders, usePurchaseOrder, usePendingApprovals,
};
