import { useState, useEffect, useCallback } from "react";
import { useAuth } from "@/context/AuthContext";
import { logger } from "@/lib/logger"; // Types
export interface DeliverySchedule { id: string; organization_id: string; vendor_id: string; scheduled_date: string; scheduled_time_start?: string; scheduled_time_end?: string; delivery_type:"standing_order" |"po_based" |"emergency" |"scheduled"; expected_items_count: number; expected_value?: number; po_numbers?: string[]; status:"scheduled" |"in_transit" |"arrived" |"unloading" |"completed" |"cancelled"; notes?: string; vendors?: { name: string };
} export interface Shipment { id: string; organization_id: string; delivery_schedule_id: string; vendor_id: string; truck_number?: string; driver_name?: string; driver_phone?: string; estimated_arrival?: string; actual_arrival?: string; actual_departure?: string; temperature_current?: number; status:"scheduled" |"in_transit" |"arrived" |"unloading" |"completed" |"left";
} export interface TruckInspection { id: string; shipment_id: string; truck_cleanliness_score: number; temperature_acceptable: boolean; seal_intact: boolean; inspection_status:"pass" |"conditional" |"fail"; can_proceed_to_unload: boolean;
} export interface HACCPCheck { id: string; shipment_id: string; frozen_acceptable: boolean; chilled_acceptable: boolean; ambient_acceptable: boolean; haccp_status:"pass" |"conditional" |"fail";
} export interface ReceivingCheckin { id: string; shipment_id: string; outlet_id: string; product_id?: string; sku?: string; product_name: string; category?: string; po_quantity: number; received_quantity: number; short_quantity: number; received_condition:"good" |"damaged" |"expired" |"partial" |"missing"; checkin_status:"received" |"verified" |"flagged" |"short" |"damaged" |"disputed"; checkin_date: string;
} export interface ReceivingDiscrepancy { id: string; shipment_id: string; outlet_id: string; vendor_id: string; discrepancy_type:"short" |"damaged" |"expired" |"wrong_item" |"quality_issue"; quantity_affected: number; vendor_notified: boolean; resolution_status:"open" |"pending_vendor_response" |"pending_credit" |"received_credit" |"resolved" |"disputed"; vendors?: { name: string };
} export interface ReceivingSummary { id: string; shipment_id: string; outlet_id: string; total_expected_items: number; total_received_items: number; total_short_items: number; total_damaged_items: number; checkin_completed: boolean; checkin_completed_at?: string;
} // Hook: Delivery Schedules
export function useDeliverySchedules(organizationId: string, filters?: any) { const [schedules, setSchedules] = useState<DeliverySchedule[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error | null>(null); const fetchSchedules = useCallback(async () => { try { setLoading(true); const params = new URLSearchParams({ organization_id: organizationId, ...filters }); const res = await fetch(`/api/receiving/delivery-schedules?${params}`); if (!res.ok) throw new Error("Failed to fetch schedules"); const json = await res.json(); setSchedules(json.data || []); setError(null); } catch (err) { const error = err instanceof Error ? err : new Error(String(err)); setError(error); logger.error("Failed to fetch delivery schedules:", error); } finally { setLoading(false); } }, [organizationId, filters]); useEffect(() => { fetchSchedules(); }, [fetchSchedules]); return { schedules, loading, error, refetch: fetchSchedules };
} // Hook: Shipments
export function useShipments(organizationId: string, status?: string) { const [shipments, setShipments] = useState<Shipment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error | null>(null); useEffect(() => { const fetchShipments = async () => { try { setLoading(true); const params = new URLSearchParams({ organization_id: organizationId }); if (status) params.append("status", status); const res = await fetch(`/api/receiving/shipments?${params}`); if (!res.ok) throw new Error("Failed to fetch shipments"); const json = await res.json(); setShipments(json.data || []); setError(null); } catch (err) { const error = err instanceof Error ? err : new Error(String(err)); setError(error); logger.error("Failed to fetch shipments:", error); } finally { setLoading(false); } }; fetchShipments(); }, [organizationId, status]); return { shipments, loading, error };
} // Hook: Check-ins for Outlet
export function useReceivingCheckins(outletId: string, shipmentId?: string) { const [checkins, setCheckins] = useState<ReceivingCheckin[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error | null>(null); const addCheckin = useCallback(async (checkinData: Partial<ReceivingCheckin>) => { try { const res = await fetch("/api/receiving/receiving-checkins", { method:"POST", headers: {"Content-Type":"application/json" }, body: JSON.stringify(checkinData), }); if (!res.ok) throw new Error("Failed to add check-in"); const newCheckin = await res.json(); setCheckins((prev) => [newCheckin, ...prev]); return newCheckin; } catch (err) { const error = err instanceof Error ? err : new Error(String(err)); logger.error("Failed to add check-in:", error); throw error; } }, []); useEffect(() => { const fetchCheckins = async () => { try { setLoading(true); const params = new URLSearchParams({ page:"1", limit:"100" }); if (shipmentId) params.append("shipment_id", shipmentId); const res = await fetch(`/api/receiving/receiving-checkins/${outletId}?${params}`); if (!res.ok) throw new Error("Failed to fetch check-ins"); const json = await res.json(); setCheckins(json.data || []); setError(null); } catch (err) { const error = err instanceof Error ? err : new Error(String(err)); setError(error); logger.error("Failed to fetch check-ins:", error); } finally { setLoading(false); } }; fetchCheckins(); }, [outletId, shipmentId]); return { checkins, loading, error, addCheckin };
} // Hook: Discrepancies
export function useReceivingDiscrepancies(organizationId: string, filters?: any) { const [discrepancies, setDiscrepancies] = useState<ReceivingDiscrepancy[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error | null>(null); const notifyVendor = useCallback( async ( discrepancyId: string, notificationMethod:"phone" |"email" |"sms" |"in_app", vendorNotifiedByUserId: string ) => { try { const res = await fetch( `/api/receiving/receiving-discrepancies/${discrepancyId}/notify-vendor`, { method:"POST", headers: {"Content-Type":"application/json" }, body: JSON.stringify({ notification_method: notificationMethod, vendor_notified_by_user_id: vendorNotifiedByUserId, }), } ); if (!res.ok) throw new Error("Failed to notify vendor"); const updated = await res.json(); setDiscrepancies((prev) => prev.map((d) => (d.id === discrepancyId ? updated : d)) ); return updated; } catch (err) { const error = err instanceof Error ? err : new Error(String(err)); logger.error("Failed to notify vendor:", error); throw error; } }, [] ); useEffect(() => { const fetchDiscrepancies = async () => { try { setLoading(true); const params = new URLSearchParams({ organization_id: organizationId, resolution_status:"open", page:"1", limit:"100", }); const res = await fetch(`/api/receiving/receiving-discrepancies?${params}`); if (!res.ok) throw new Error("Failed to fetch discrepancies"); const json = await res.json(); setDiscrepancies(json.data || []); setError(null); } catch (err) { const error = err instanceof Error ? err : new Error(String(err)); setError(error); logger.error("Failed to fetch discrepancies:", error); } finally { setLoading(false); } }; fetchDiscrepancies(); }, [organizationId]); return { discrepancies, loading, error, notifyVendor };
} // Hook: Receiving Summary
export function useReceivingSummary(shipmentId: string, outletId: string) { const [summary, setSummary] = useState<ReceivingSummary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<Error | null>(null); const completeSummary = useCallback(async (completedByUserId: string) => { try { const res = await fetch( `/api/receiving/receiving-summaries/${shipmentId}/${outletId}/complete`, { method:"POST", headers: {"Content-Type":"application/json" }, body: JSON.stringify({ checkin_completed_by_user_id: completedByUserId }), } ); if (!res.ok) throw new Error("Failed to complete summary"); const updated = await res.json(); setSummary(updated); return updated; } catch (err) { const error = err instanceof Error ? err : new Error(String(err)); logger.error("Failed to complete summary:", error); throw error; } }, [shipmentId, outletId]); useEffect(() => { const fetchSummary = async () => { try { setLoading(true); const res = await fetch(`/api/receiving/receiving-summaries/${shipmentId}/${outletId}`); if (!res.ok) { // Summary doesn't exist yet - that's OK setSummary(null); setError(null); return; } const data = await res.json(); setSummary(data); setError(null); } catch (err) { const error = err instanceof Error ? err : new Error(String(err)); logger.error("Failed to fetch summary:", error); // Don't set error - summary might not exist yet setError(null); } finally { setLoading(false); } }; fetchSummary(); }, [shipmentId, outletId]); return { summary, loading, error, completeSummary };
}
