/** * Slide Deck Generator * Automatically generates presentation slides from whiteboard canvas */ import {
  CanvasState,
  PresentationDeck,
  PresentationSlide,
  ShapeElement,
  TextElement,
  StickyNote,
} from "./types";
import { v4 as uuidv4 } from "uuid";
interface SectionBounds {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
  elements: Array<{ kind: string; id: string }>;
}
class SlideDeckGenerator {
  private static SECTION_SPACING = 500;
  private static MIN_SECTION_ELEMENTS = 1;
  private static ANIMATION_STAGGER = 100;
  static generateDeckFromCanvas(
    canvasState: CanvasState,
    sessionId: string,
    userId: string,
    title: string = "Whiteboard Presentation",
  ): PresentationDeck {
    const sections = this.identifySections(canvasState);
    const slides = this.createSlidesFromSections(sections, canvasState);
    return {
      id: uuidv4(),
      title,
      sessionId,
      slides,
      createdAt: Date.now(),
      updatedAt: Date.now(),
      createdBy: userId,
      isAutoGenerated: true,
      settings: {
        autoAdvance: false,
        transitionDuration: 300,
        showSpeakerNotes: true,
      },
    };
  }
  private static identifySections(canvasState: CanvasState): SectionBounds[] {
    const allElements: Array<{
      kind: string;
      id: string;
      x: number;
      y: number;
      width: number;
      height: number;
    }> = [];
    canvasState.shapes.forEach((s) =>
      allElements.push({
        kind: "shape",
        id: s.id,
        x: s.x,
        y: s.y,
        width: s.width,
        height: s.height,
      }),
    );
    canvasState.texts.forEach((t) =>
      allElements.push({
        kind: "text",
        id: t.id,
        x: t.x,
        y: t.y,
        width: 200,
        height: 50,
      }),
    );
    canvasState.stickyNotes.forEach((s) =>
      allElements.push({
        kind: "sticky",
        id: s.id,
        x: s.x,
        y: s.y,
        width: s.width,
        height: s.height,
      }),
    );
    canvasState.images.forEach((i) =>
      allElements.push({
        kind: "image",
        id: i.id,
        x: i.x,
        y: i.y,
        width: i.width,
        height: i.height,
      }),
    );
    canvasState.pdfs.forEach((p) =>
      allElements.push({
        kind: "pdf",
        id: p.id,
        x: p.x,
        y: p.y,
        width: p.width,
        height: p.height,
      }),
    );
    if (allElements.length === 0) {
      return [];
    }
    allElements.sort((a, b) => a.y - b.y);
    const sections: SectionBounds[] = [];
    let currentSection: SectionBounds | null = null;
    for (const element of allElements) {
      if (!currentSection) {
        currentSection = {
          minX: element.x,
          minY: element.y,
          maxX: element.x + element.width,
          maxY: element.y + element.height,
          elements: [{ kind: element.kind, id: element.id }],
        };
      } else {
        const yGap = element.y - currentSection.maxY;
        if (yGap > this.SECTION_SPACING) {
          if (currentSection.elements.length >= this.MIN_SECTION_ELEMENTS) {
            sections.push(currentSection);
          }
          currentSection = {
            minX: element.x,
            minY: element.y,
            maxX: element.x + element.width,
            maxY: element.y + element.height,
            elements: [{ kind: element.kind, id: element.id }],
          };
        } else {
          currentSection.minX = Math.min(currentSection.minX, element.x);
          currentSection.maxX = Math.max(
            currentSection.maxX,
            element.x + element.width,
          );
          currentSection.maxY = Math.max(
            currentSection.maxY,
            element.y + element.height,
          );
          currentSection.elements.push({ kind: element.kind, id: element.id });
        }
      }
    }
    if (
      currentSection &&
      currentSection.elements.length >= this.MIN_SECTION_ELEMENTS
    ) {
      sections.push(currentSection);
    }
    return sections;
  }
  private static createSlidesFromSections(
    sections: SectionBounds[],
    canvasState: CanvasState,
  ): PresentationSlide[] {
    return sections.map((section, index) => {
      const slideTitle = this.generateSlideTitle(section, canvasState);
      const slideElements = section.elements.map((el, idx) => ({
        kind: el.kind as any,
        id: el.id,
        animationType: "fade-in" as const,
        animationDelay: idx * this.ANIMATION_STAGGER,
      }));
      return {
        id: uuidv4(),
        title: slideTitle,
        description: `Slide ${index + 1}`,
        elements: slideElements,
        speakerNotes: this.generateSpeakerNotes(section, canvasState),
        duration: 30,
        backgroundColor: canvasState.backgroundColor,
      };
    });
  }
  private static generateSlideTitle(
    section: SectionBounds,
    canvasState: CanvasState,
  ): string {
    const textElements = section.elements
      .filter((e) => e.kind === "text")
      .map((e) => canvasState.texts.find((t) => t.id === e.id)?.text)
      .filter(Boolean);
    if (textElements.length > 0) {
      return textElements[0]!.substring(0, 50);
    }
    const stickyElements = section.elements
      .filter((e) => e.kind === "sticky")
      .map((e) => canvasState.stickyNotes.find((s) => s.id === e.id)?.text)
      .filter(Boolean);
    if (stickyElements.length > 0) {
      return stickyElements[0]!.substring(0, 50);
    }
    return `Slide ${section.elements.length} Elements`;
  }
  private static generateSpeakerNotes(
    section: SectionBounds,
    canvasState: CanvasState,
  ): string {
    const notes: string[] = [];
    const elementCount = section.elements.length;
    notes.push(
      `This slide contains ${elementCount} element${elementCount !== 1 ? "s" : ""}.`,
    );
    const texts = section.elements
      .filter((e) => e.kind === "text")
      .map((e) => canvasState.texts.find((t) => t.id === e.id)?.text)
      .filter(Boolean);
    if (texts.length > 0) {
      notes.push(`Key points: ${texts.join(",")}`);
    }
    const stickies = section.elements
      .filter((e) => e.kind === "sticky")
      .map((e) => canvasState.stickyNotes.find((s) => s.id === e.id)?.text)
      .filter(Boolean);
    if (stickies.length > 0) {
      notes.push(`Notes: ${stickies.join("")}`);
    }
    return notes.join("\n");
  }
  static createBlankDeck(
    sessionId: string,
    userId: string,
    title: string = "New Presentation",
  ): PresentationDeck {
    return {
      id: uuidv4(),
      title,
      sessionId,
      slides: [
        {
          id: uuidv4(),
          title: "Title Slide",
          description: "Start your presentation",
          elements: [],
          speakerNotes: "Introduce yourself and the topic",
          duration: 30,
        },
      ],
      createdAt: Date.now(),
      updatedAt: Date.now(),
      createdBy: userId,
      isAutoGenerated: false,
      settings: {
        autoAdvance: false,
        transitionDuration: 300,
        showSpeakerNotes: true,
      },
    };
  }
  static validateDeck(deck: PresentationDeck): {
    valid: boolean;
    errors: string[];
  } {
    const errors: string[] = [];
    if (!deck.title) {
      errors.push("Deck must have a title");
    }
    if (deck.slides.length === 0) {
      errors.push("Deck must have at least one slide");
    }
    deck.slides.forEach((slide, idx) => {
      if (!slide.title) {
        errors.push(`Slide ${idx + 1} must have a title`);
      }
    });
    return { valid: errors.length === 0, errors };
  }
}
export default SlideDeckGenerator;
