import "dotenv/config";
import express from "express";
import cors from "cors";
import { handleDemo } from "./routes/demo";
import { weeklyTotalsRouter } from "./routes/payroll/weekly_totals";
import { notifyRouter } from "./routes/notify";
import { filesRouter } from "./routes/files";
import scheduleRouter from "./api/routes/schedule";
import tipPoolsRouter from "./api/routes/tipPools";
import eventsRouter from "./api/routes/events";
import echoRouter from "./api/routes/echo";
import forecastRouter from "./api/routes/forecast";
import complianceRoutes from "./api/routes/compliance";
import selfServiceRoutes from "./api/routes/selfService";
import importsRoutes from "./api/routes/imports";
import reportsRoutes from "./api/routes/reports";
import adminRoutes from "./api/routes/admin";
import auditRoutes from "./api/routes/audit";
import healthRoutes from "./api/routes/health";
import analyticsRoutes from "./api/routes/analytics";
import acksRoutes from "./api/routes/acks";
import kpiRoutes from "./api/routes/kpi";
import staffRoutes from "./api/routes/staff";
import schedulerRoutes from "./api/routes/scheduler";
import analyticsInfinityRoutes from "./api/routes/analytics_infinity";
import posWebhookRoutes from "./api/routes/pos_webhook";
import publishRoutes from "./api/routes/publish";
import lmsRoutes from "./api/routes/lms";
import glExportRoutes from "./api/routes/glExport";
import orgSummaryRoutes from "./api/routes/orgSummary";
import echoWhisperRoutes from "./api/routes/echoWhisper";
import echoOptimizeRoutes from "./api/routes/echoOptimize";
import autoRepairRoutes from "./api/routes/autoRepair";
import sseRoutes from "./api/routes/sse";
import predictiveOpsRoutes from "./api/routes/predictiveOps";
import echoMultilingualRoutes from "./api/routes/echoMultilingual";
import dataPipelineRoutes from "./api/routes/dataPipeline";
import advancedAIRoutes from "./api/routes/advancedAI";
import performanceRoutes from "./api/routes/performance";
import autoHealingRoutes from "./api/routes/autoHealing";
import securityRoutes from "./api/routes/security";
import employeesRoutes from "./api/routes/employees";
import { cacheGetMiddleware } from "./middleware/cache";
import { authenticateUser, requireRole } from "./middleware/auth";
import { errorHandler } from "./middleware/errorHandler";
import { regionRouter } from "./middleware/regionRouter";
import { performanceMonitor } from "./middleware/performanceMonitor";
import helmet from "helmet";
import compression from "compression";
export function createServer() {
  const app = express(); // Security & Performance middleware app.use(helmet()); app.use(compression()); // Core middleware app.use(cors()); app.use(express.json({ limit:"10mb" })); app.use(express.urlencoded({ extended: true, limit:"10mb" })); // Request tracking & region routing app.use((req, res, next) => { (req as any).requestId = crypto.randomUUID(); res.setHeader("X-Request-ID", (req as any).requestId); next(); }); app.use(regionRouter); // Performance monitoring app.use(performanceMonitor); // Authentication middleware app.use(authenticateUser); // Optional auth middleware (for testing) // Example API routes app.get("/api/ping", (_req, res) => { const ping = process.env.PING_MESSAGE ??"ping"; res.json({ message: ping }); }); app.get("/api/demo", handleDemo); // Static audit vault (read-only) app.use("/vault", express.static("vault")); // Multi-tenant scheduling system app.use("/api/schedule", scheduleRouter); app.use("/api/tip-pools", tipPoolsRouter); app.use("/api/events", eventsRouter); app.use("/api/echo", echoRouter); // Forecasting & scenario planning app.use("/api/forecast", forecastRouter); // Compliance engine app.use("/api/compliance", complianceRoutes); // Employee self-service app.use("/api/self", selfServiceRoutes); // CSV imports app.use("/api/imports", importsRoutes); // Reports & exports app.use("/api/reports", cacheGetMiddleware(), reportsRoutes); // Admin management app.use("/api/admin", adminRoutes); // Audit logging app.use("/api/audit", auditRoutes); // Health checks app.use("/api/health", healthRoutes); // Analytics & charts app.use("/api/analytics", analyticsRoutes); // Acknowledgements & realtime app.use("/api/acks", acksRoutes); // KPI Header stats app.use("/api/kpi", requireRole("DEPT_MGR","GM","ADMIN"), kpiRoutes); // Staff management (skills, ratings, dev plans, training) app.use("/api/staff", staffRoutes); // Scheduler (auto-generate, validate, publish) app.use("/api/scheduler", schedulerRoutes); // Analytics (Infinity: interval coverage, drilldown, performance, insights, KPI) app.use("/api/analytics", analyticsInfinityRoutes); // POS webhooks (Toast, Square, Lightspeed) app.use("/api/pos/webhook", posWebhookRoutes); // Publish workflow (schedules + acknowledgements) app.use("/api/publish", publishRoutes); // Learning Management System (skills, certifications) app.use("/api/lms", lmsRoutes); // Financial exports (GL codes, P&L reports) app.use("/api/gl", glExportRoutes); // Organization summary (multi-property dashboard) app.use("/api/org-summary", orgSummaryRoutes); // Echo AI enhancements app.use("/api/echo/whisper", echoWhisperRoutes); app.use("/api/echo", echoOptimizeRoutes); app.use("/api/echo-multilingual", echoMultilingualRoutes); // Predictive Operations Intelligence app.use("/api/predictive-ops", predictiveOpsRoutes); // Auto-repair engine app.use("/api/auto-repair", autoRepairRoutes); // Real-time updates (Server-Sent Events) app.use("/api/sse", sseRoutes); // Data Pipeline & Ingestion app.use("/api/data-pipeline", dataPipelineRoutes); // Advanced AI & Anomaly Detection app.use("/api/advanced-ai", advancedAIRoutes); // Performance Monitoring & Optimization app.use("/api/performance", performanceRoutes); // Auto-Healing & System Health app.use("/api/auto-healing", autoHealingRoutes); // Security & Compliance app.use("/api/security", securityRoutes); // Employee Management & Onboarding app.use("/api/employees", employeesRoutes); // Legacy payroll and exports app.use("/api/payroll", weeklyTotalsRouter); // Notifications / audit app.use("/api/notify", notifyRouter); app.use("/api/files", filesRouter); // Error handling (must be last) app.use(errorHandler); return app;
}
