import React from 'react';
import {
  BEOBuilderPanel,
  BEOREOEditorPanel,
  MenuRecipePanel,
  TimelinePanel,
  MaestroDashboardPanel,
  EnhancedMaestroDashboard,
  BEOEditor,
  GlobalCalendar,
  EchoIntegrationPanel,
  ChatPanel,
  BEOMessaging,
  SeatingPlannerPanel,
  ExecutionConsolePanel,
  FinancePnlPanel,
  BeveragePlannerPanel,
  NutritionAllergenPanel,
  HACCPPanel,
  PreHealthInspectorChecklistPanel,
  SectionPlannerPanel,
  FiringOrderPanel,
  CaptainConsolePanel,
  ChefLaunchBoardPanel,
  ButcherPanel,
  ProductionOrderingPanel,
  DemographicTracker,
  CartTrackerPanel,
  ChefForecastPanel,
  ChefKitchenView,
  KitchenOperationsPanel,
  PrepSheetsPanel,
  ProductionListManager,
  RequisitionPanel,
} from './index';

export type PanelComponent = React.ComponentType<any>;

export const PanelRegistry: Record<string, PanelComponent> = {
  BEOBuilderPanel,
  BEOREOEditorPanel,
  MenuRecipePanel,
  TimelinePanel,
  MaestroDashboardPanel,
  EnhancedMaestroDashboard,
  BEOEditor,
  GlobalCalendar,
  EchoIntegrationPanel,
  ChatPanel,
  BEOMessaging,
  SeatingPlannerPanel,
  ExecutionConsolePanel,
  FinancePnlPanel,
  BeveragePlannerPanel,
  NutritionAllergenPanel,
  HACCPPanel,
  PreHealthInspectorChecklistPanel,
  SectionPlannerPanel,
  FiringOrderPanel,
  CaptainConsolePanel,
  ChefLaunchBoardPanel,
  ButcherPanel,
  ProductionOrderingPanel,
  DemographicTracker,
  CartTrackerPanel,
  ChefForecastPanel,
  ChefKitchenView,
  KitchenOperationsPanel,
  PrepSheetsPanel,
  ProductionListManager,
  RequisitionPanel,
};

export const panelIds = Object.keys(PanelRegistry);
