/** * EchoAurum Approval Workflow Engine * Multi-level approval chains, delegation, escalation, audit trails * Supports journal entries, invoices, payments, GL postings */ import type { RequestHandler } from"express";
import { AurumDatabaseService } from "../services/aurumDatabase"; // ============================================================================
// APPROVAL WORKFLOW TYPES
// ============================================================================ interface ApprovalWorkflow { id: string; name: string; type: 'journal_entry' | 'invoice' | 'payment' | 'gl_posting'; entityId: string; triggers: { type: 'amount' | 'account' | 'role' | 'default'; value?: string | number; }[]; approverChain: Array<{ level: number; approverRole: string; approvers: string[]; }>; escalationDays: number; status: 'active' | 'inactive';
} interface ApprovalRequest { id: string; workflowId: string; transactionType: string; transactionId: string; transactionDetails: Record<string, any>; currentApprovalLevel: number; status: 'pending' | 'approved' | 'rejected' | 'escalated'; createdAt: string; createdBy: string;
} interface ApprovalAction { id: string; approvalRequestId: string; approvedBy: string; approverRole: string; status: 'approved' | 'rejected' | 'escalated'; comments?: string; timestamp: string;
} // ============================================================================
// CREATE APPROVAL WORKFLOW TEMPLATE
// ============================================================================ export const handleCreateApprovalWorkflow: RequestHandler = async (req, res) => { const { name, type, entityId, approverChain, triggers, escalationDays } = req.body; if (!name || !type || !approverChain) { return res.status(400).json({ error:"Missing required fields" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; const workflow: ApprovalWorkflow = { id: `wf_${Date.now()}`, name, type, entityId: entityId ||"ent_default", triggers: triggers || [{ type: 'default' }], approverChain, escalationDays: escalationDays || 2, status: 'active', }; // Store in database await db.pool.query( `INSERT INTO approval_workflows (id, name, type, entityId, triggers, approverChain, escalationDays, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`, [ workflow.id, workflow.name, workflow.type, workflow.entityId, JSON.stringify(workflow.triggers), JSON.stringify(workflow.approverChain), workflow.escalationDays, workflow.status, ] ); return res.status(201).json({ workflow, message: `Approval workflow '${name}' created successfully`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to create approval workflow"; res.status(500).json({ error: message }); }
}; // ============================================================================
// SUBMIT FOR APPROVAL
// ============================================================================ export const handleSubmitForApproval: RequestHandler = async (req, res) => { const { transactionType, transactionId, transactionDetails, entityId, createdBy } = req.body; if (!transactionType || !transactionId) { return res.status(400).json({ error:"Missing transactionType or transactionId" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; // Find matching workflow const workflowResult = await db.pool.query<ApprovalWorkflow>( `SELECT * FROM approval_workflows WHERE type = $1 AND entityId = $2 AND status = 'active' LIMIT 1`, [transactionType, entityId ||"ent_default"] ); if (!workflowResult.rows || workflowResult.rows.length === 0) { // Use default no-approval workflow return res.json({ approvalRequest: { id: `appreq_${Date.now()}`, status: 'approved', message: 'No approval workflow configured - transaction approved automatically', }, }); } const workflow = workflowResult.rows[0]; // Create approval request const approvalRequest: ApprovalRequest = { id: `appreq_${Date.now()}`, workflowId: workflow.id, transactionType, transactionId, transactionDetails, currentApprovalLevel: 1, status: 'pending', createdAt: new Date().toISOString(), createdBy, }; // Store approval request await db.pool.query( `INSERT INTO approval_requests (id, workflowId, transactionType, transactionId, transactionDetails, currentApprovalLevel, status, createdAt, createdBy) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`, [ approvalRequest.id, approvalRequest.workflowId, approvalRequest.transactionType, approvalRequest.transactionId, JSON.stringify(approvalRequest.transactionDetails), approvalRequest.currentApprovalLevel, approvalRequest.status, approvalRequest.createdAt, approvalRequest.createdBy, ] ); // Get next approvers const currentLevel = workflow.approverChain.find((c: any) => c.level === approvalRequest.currentApprovalLevel); return res.status(201).json({ approvalRequest, nextApprovers: currentLevel?.approvers || [], message: `Submitted for approval. Waiting for ${currentLevel?.approverRole} approval.`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to submit for approval"; res.status(500).json({ error: message }); }
}; // ============================================================================
// APPROVE REQUEST
// ============================================================================ export const handleApproveRequest: RequestHandler = async (req, res) => { const { approvalRequestId, approverRole, comments } = req.body; const approvedBy = req.body.approvedBy ||"current-user"; if (!approvalRequestId) { return res.status(400).json({ error:"Missing approvalRequestId" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; // Get approval request const reqResult = await db.pool.queryOne<ApprovalRequest>("SELECT * FROM approval_requests WHERE id = $1", [approvalRequestId] ); if (!reqResult) { return res.status(404).json({ error:"Approval request not found" }); } // Get workflow const wfResult = await db.pool.queryOne<ApprovalWorkflow>("SELECT * FROM approval_workflows WHERE id = $1", [reqResult.workflowId] ); if (!wfResult) { return res.status(404).json({ error:"Workflow not found" }); } // Record approval action const approvalAction: ApprovalAction = { id: `appr_${Date.now()}`, approvalRequestId, approvedBy, approverRole: approverRole ||"manager", status: 'approved', comments, timestamp: new Date().toISOString(), }; await db.pool.query( `INSERT INTO approval_actions (id, approvalRequestId, approvedBy, approverRole, status, comments, timestamp) VALUES ($1, $2, $3, $4, $5, $6, $7)`, [ approvalAction.id, approvalAction.approvalRequestId, approvalAction.approvedBy, approvalAction.approverRole, approvalAction.status, approvalAction.comments, approvalAction.timestamp, ] ); // Check if more approvals needed const nextLevel = reqResult.currentApprovalLevel + 1; const hasMoreLevels = wfResult.approverChain.some((c: any) => c.level === nextLevel); let newStatus = 'approved'; let nextApprovers: string[] = []; if (hasMoreLevels) { newStatus = 'pending'; const nextLevelApprovers = wfResult.approverChain.find((c: any) => c.level === nextLevel); nextApprovers = nextLevelApprovers?.approvers || []; // Update approval request with new level await db.pool.query( `UPDATE approval_requests SET currentApprovalLevel = $1, status = $2, updatedAt = $3 WHERE id = $4`, [nextLevel, newStatus, new Date().toISOString(), approvalRequestId] ); } else { // All approvals complete await db.pool.query( `UPDATE approval_requests SET status = 'approved', approvedAt = $1 WHERE id = $2`, [new Date().toISOString(), approvalRequestId] ); } return res.json({ approvalAction, approvalRequest: { id: reqResult.id, status: newStatus, currentApprovalLevel: hasMoreLevels ? nextLevel : reqResult.currentApprovalLevel, }, nextApprovers, message: hasMoreLevels ? `Approved by ${approverRole}. Awaiting final approval...` : 'Fully approved. Transaction can now proceed.', }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to approve request"; res.status(500).json({ error: message }); }
}; // ============================================================================
// REJECT REQUEST
// ============================================================================ export const handleRejectRequest: RequestHandler = async (req, res) => { const { approvalRequestId, approverRole, rejectReason } = req.body; const rejectedBy = req.body.rejectedBy ||"current-user"; if (!approvalRequestId || !rejectReason) { return res.status(400).json({ error:"Missing approvalRequestId or rejectReason" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; // Record rejection const rejectionAction: ApprovalAction = { id: `appr_${Date.now()}`, approvalRequestId, approvedBy: rejectedBy, approverRole: approverRole ||"manager", status: 'rejected', comments: rejectReason, timestamp: new Date().toISOString(), }; await db.pool.query( `INSERT INTO approval_actions (id, approvalRequestId, approvedBy, approverRole, status, comments, timestamp) VALUES ($1, $2, $3, $4, $5, $6, $7)`, [ rejectionAction.id, rejectionAction.approvalRequestId, rejectionAction.approvedBy, rejectionAction.approverRole, rejectionAction.status, rejectionAction.comments, rejectionAction.timestamp, ] ); // Mark request as rejected await db.pool.query( `UPDATE approval_requests SET status = 'rejected', rejectedAt = $1 WHERE id = $2`, [new Date().toISOString(), approvalRequestId] ); return res.json({ approvalAction: rejectionAction, approvalRequest: { id: approvalRequestId, status: 'rejected', }, message: `Request rejected by ${approverRole}: ${rejectReason}`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to reject request"; res.status(500).json({ error: message }); }
}; // ============================================================================
// DELEGATE APPROVAL
// ============================================================================ export const handleDelegateApproval: RequestHandler = async (req, res) => { const { approvalRequestId, delegateToUser, delegationReason } = req.body; const delegatedBy = req.body.delegatedBy ||"current-user"; if (!approvalRequestId || !delegateToUser) { return res.status(400).json({ error:"Missing required fields" }); } try { // Record delegation const delegationRecord = { id: `deleg_${Date.now()}`, approvalRequestId, delegatedBy, delegatedTo: delegateToUser, reason: delegationReason, timestamp: new Date().toISOString(), }; // Store delegation const db = req.app.get("aurumDb") as AurumDatabaseService; await db.pool.query( `INSERT INTO approval_delegations (id, approvalRequestId, delegatedBy, delegatedTo, reason, timestamp) VALUES ($1, $2, $3, $4, $5, $6)`, [ delegationRecord.id, delegationRecord.approvalRequestId, delegationRecord.delegatedBy, delegationRecord.delegatedTo, delegationRecord.reason, delegationRecord.timestamp, ] ); return res.status(201).json({ delegation: delegationRecord, message: `Approval delegated to ${delegateToUser}`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to delegate approval"; res.status(500).json({ error: message }); }
}; // ============================================================================
// GET APPROVAL QUEUE
// ============================================================================ export const handleGetApprovalQueue: RequestHandler = async (req, res) => { const { approverRole, status, type } = req.query; try { const db = req.app.get("aurumDb") as AurumDatabaseService; let query = ` SELECT ar.*, aa.approverRole, aa.status as lastAction FROM approval_requests ar LEFT JOIN approval_actions aa ON ar.id = aa.approvalRequestId WHERE 1=1 `; const params: any[] = []; if (status) { query += ` AND ar.status = $${params.length + 1}`; params.push(status); } if (type) { query += ` AND ar.transactionType = $${params.length + 1}`; params.push(type); } query += ` ORDER BY ar.createdAt DESC`; const result = await db.pool.query<ApprovalRequest>(query, params); return res.json({ approvals: result.rows || [], total: result.rows?.length || 0, summary: { pending: result.rows?.filter((a: any) => a.status === 'pending').length || 0, approved: result.rows?.filter((a: any) => a.status === 'approved').length || 0, rejected: result.rows?.filter((a: any) => a.status === 'rejected').length || 0, }, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to get approval queue"; res.status(500).json({ error: message }); }
}; // ============================================================================
// GET APPROVAL DETAIL
// ============================================================================ export const handleGetApprovalDetail: RequestHandler = async (req, res) => { const { id } = req.params; if (!id) { return res.status(400).json({ error:"Missing approval request id" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; const request = await db.pool.queryOne<ApprovalRequest>("SELECT * FROM approval_requests WHERE id = $1", [id] ); if (!request) { return res.status(404).json({ error:"Approval request not found" }); } // Get all actions for this request const actionsResult = await db.pool.query<ApprovalAction>("SELECT * FROM approval_actions WHERE approvalRequestId = $1 ORDER BY timestamp DESC", [id] ); // Get workflow for context const workflow = await db.pool.queryOne<ApprovalWorkflow>("SELECT * FROM approval_workflows WHERE id = $1", [request.workflowId] ); return res.json({ approvalRequest: request, actions: actionsResult.rows || [], workflow, approvalHistory: (actionsResult.rows || []).map((action: ApprovalAction) => ({ action: action.status === 'approved' ? '✓ Approved' : action.status === 'rejected' ? '✗ Rejected' : '→ Escalated', by: action.approvedBy, role: action.approverRole, at: action.timestamp, comments: action.comments, })), }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to get approval detail"; res.status(500).json({ error: message }); }
};
