/** * EchoAurum Bank Reconciliation Engine * Import bank statements, match with GL, investigate variances, auto-reconcile * Supports CSV, OFX, MT940 formats */ import type { RequestHandler } from"express";
import type { Reconciliation } from "@shared/aurum";
import { AurumDatabaseService } from "../services/aurumDatabase"; // ============================================================================
// BANK STATEMENT PARSING
// ============================================================================ interface BankTransaction { date: string; amount: number; description: string; reference?: string; type: 'debit' | 'credit';
} interface ParsedBankStatement { accountNumber: string; statementDate: string; openingBalance: number; closingBalance: number; transactions: BankTransaction[];
} function parseCSVStatement(content: string): ParsedBankStatement { // Simple CSV parser - production would use csv library const lines = content.trim().split('\n'); const header = lines[0].split(','); const transactions: BankTransaction[] = []; for (let i = 1; i < lines.length; i++) { if (!lines[i].trim()) continue; const values = lines[i].split(','); const row = Object.fromEntries( header.map((h, idx) => [h.trim().toLowerCase(), values[idx]?.trim()]) ); transactions.push({ date: row.date || new Date().toISOString().split('T')[0], amount: parseFloat(row.amount || '0'), description: row.description || row.memo || 'Bank transaction', reference: row.reference || row.checknumber, type: (parseFloat(row.amount || '0') < 0) ? 'debit' : 'credit', }); } return { accountNumber: 'PARSED', statementDate: new Date().toISOString().split('T')[0], openingBalance: 0, closingBalance: transactions.reduce((sum, t) => sum + (t.type === 'credit' ? t.amount : -t.amount), 0), transactions, };
} export const handleUploadBankStatement: RequestHandler = async (req, res) => { const { accountCode, statementContent, format = 'csv', entityId, periodDate } = req.body; if (!accountCode || !statementContent) { return res.status(400).json({ error:"Missing accountCode or statementContent" }); } try { let statement: ParsedBankStatement; if (format === 'csv') { statement = parseCSVStatement(statementContent); } else { return res.status(400).json({ error: `Format ${format} not yet supported` }); } const db = req.app.get("aurumDb") as AurumDatabaseService; // Create reconciliation record const reconciliation = await db.createReconciliation({ type:"bank", entityId: entityId ||"ent_default", accountCode, periodDate: periodDate || new Date().toISOString().split('T')[0], systemBalance: 0, // Would be fetched from GL externalBalance: statement.closingBalance, variance: 0, status:"pending", matchedItems: [], unmatchedItems: statement.transactions.map((t) => ({ type:"external", reference: t.reference || t.description, amount: t.amount, ageInDays: 0, })), }); return res.status(201).json({ reconciliation, statement, nextStep:"match", message: `Bank statement imported with ${statement.transactions.length} transactions`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to upload statement"; res.status(500).json({ error: message }); }
}; // ============================================================================
// TRANSACTION MATCHING
// ============================================================================ export const handleMatchBankTransaction: RequestHandler = async (req, res) => { const { reconciliationId, journalLineIds, bankTransactionReferences } = req.body; if (!reconciliationId || !journalLineIds || !bankTransactionReferences) { return res.status(400).json({ error:"Missing required fields" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; const recon = await db.pool.queryOne<Reconciliation>("SELECT * FROM reconciliations WHERE id = $1", [reconciliationId] ); if (!recon) { return res.status(404).json({ error:"Reconciliation not found" }); } // Match transactions const matches = journalLineIds.map((jlId: string, idx: number) => ({ journalLineId: jlId, bankTransactionReference: bankTransactionReferences[idx], matchedAt: new Date().toISOString(), })); const updated = await db.pool.queryOne<Reconciliation>( `UPDATE reconciliations SET matchedItems = matchedItems || $1::jsonb, updatedAt = $2 WHERE id = $3 RETURNING *`, [JSON.stringify(matches), new Date().toISOString(), reconciliationId] ); return res.json({ reconciliation: updated, matchCount: matches.length, nextStep:"investigate", message: `${matches.length} transactions matched. Investigating remaining variance...`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to match transactions"; res.status(500).json({ error: message }); }
}; // ============================================================================
// AUTO-RECONCILIATION
// ============================================================================ export const handleAutoReconcile: RequestHandler = async (req, res) => { const { reconciliationId, varianceThreshold = 0.01 } = req.body; if (!reconciliationId) { return res.status(400).json({ error:"Missing reconciliationId" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; const recon = await db.pool.queryOne<Reconciliation>("SELECT * FROM reconciliations WHERE id = $1", [reconciliationId] ); if (!recon) { return res.status(404).json({ error:"Reconciliation not found" }); } // Calculate variance const variance = Math.abs(recon.variance); // Auto-reconcile if variance is within threshold let status = recon.status; let message ="Manual review required"; if (variance < varianceThreshold) { status ="matched"; message = `Auto-reconciled: variance of ${variance.toFixed(2)} is within ${(varianceThreshold * 100).toFixed(2)}% threshold`; } else if (variance === 0) { status ="matched"; message ="Perfect match - reconciliation complete"; } const updated = await db.pool.queryOne<Reconciliation>( `UPDATE reconciliations SET status = $1, updatedAt = $2 WHERE id = $3 RETURNING *`, [status, new Date().toISOString(), reconciliationId] ); return res.json({ reconciliation: updated, autoReconciled: status ==="matched", variance: variance.toFixed(2), message, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to auto-reconcile"; res.status(500).json({ error: message }); }
}; // ============================================================================
// VARIANCE INVESTIGATION
// ============================================================================ export const handleInvestigateVariance: RequestHandler = async (req, res) => { const { reconciliationId, varianceType, investigationNotes } = req.body; if (!reconciliationId) { return res.status(400).json({ error:"Missing reconciliationId" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; const recon = await db.pool.queryOne<Reconciliation>("SELECT * FROM reconciliations WHERE id = $1", [reconciliationId] ); if (!recon) { return res.status(404).json({ error:"Reconciliation not found" }); } // Categorize variance const analysis = { totalVariance: recon.variance, varianceType: varianceType ||"outstanding_items", // timing, outstanding, error potentialCauses: [] as string[], recommendations: [] as string[], investigationNotes, }; // Analyze common variance causes if (recon.variance > 0) { analysis.potentialCauses.push("Outstanding deposits not yet cleared"); analysis.potentialCauses.push("In-transit transactions"); analysis.recommendations.push("Check for deposits made near period end"); } else { analysis.potentialCauses.push("Outstanding checks or transfers"); analysis.potentialCauses.push("Bank fees not recorded"); analysis.recommendations.push("Check for outstanding checks"); analysis.recommendations.push("Review bank statement for fees or charges"); } return res.json({ reconciliation: recon, analysis, nextStep:"resolve", message: `Variance of ${Math.abs(recon.variance).toFixed(2)} analyzed. ${analysis.recommendations.length} recommendations provided.`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to investigate variance"; res.status(500).json({ error: message }); }
}; // ============================================================================
// RECONCILIATION RESOLUTION
// ============================================================================ export const handleResolveReconciliation: RequestHandler = async (req, res) => { const { reconciliationId, adjustmentEntries, resolutionNotes, resolvedBy } = req.body; if (!reconciliationId || !resolvedBy) { return res.status(400).json({ error:"Missing reconciliationId or resolvedBy" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; // Create adjustment GL entries if provided const adjustmentSummary = []; if (adjustmentEntries && Array.isArray(adjustmentEntries)) { for (const adj of adjustmentEntries) { const entry = await db.createJournalEntry({ entityId: adj.entityId ||"ent_default", periodDate: new Date().toISOString().split("T")[0], status:"draft", source:"bank_reconciliation", referenceId: reconciliationId, description: adj.description ||"Reconciliation adjustment", lines: [ { id:"", accountCode: adj.debitAccount, accountName: adj.debitAccountName, accountType:"asset", debitAmount: adj.amount, creditAmount: 0, memo: `Bank reconciliation adjustment: ${adj.description}`, }, { id:"", accountCode: adj.creditAccount, accountName: adj.creditAccountName, accountType:"expense", debitAmount: 0, creditAmount: adj.amount, memo: `Bank reconciliation adjustment: ${adj.description}`, }, ], createdBy: resolvedBy, guardianCheckStatus:"pending", }); adjustmentSummary.push({ description: adj.description, amount: adj.amount, journalEntryId: entry.id, }); } } // Mark reconciliation as resolved const now = new Date().toISOString(); const updated = await db.pool.queryOne<Reconciliation>( `UPDATE reconciliations SET status = 'resolved', resolvedAt = $1, resolvedBy = $2, resolutionNotes = $3, updatedAt = $1 WHERE id = $4 RETURNING *`, [now, resolvedBy, resolutionNotes, reconciliationId] ); return res.json({ reconciliation: updated, adjustments: adjustmentSummary, nextStep:"complete", message: `Reconciliation resolved. ${adjustmentSummary.length} adjustment entries created.`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to resolve reconciliation"; res.status(500).json({ error: message }); }
}; // ============================================================================
// GET RECONCILIATION DETAIL
// ============================================================================ export const handleGetReconciliationDetail: RequestHandler = async (req, res) => { const { id } = req.params; if (!id) { return res.status(400).json({ error:"Missing reconciliation id" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; const recon = await db.pool.queryOne<Reconciliation>("SELECT * FROM reconciliations WHERE id = $1", [id] ); if (!recon) { return res.status(404).json({ error:"Reconciliation not found" }); } // Calculate aging of unmatched items const now = new Date(); const unmatchedWithAge = (recon.unmatchedItems || []).map((item: any) => ({ ...item, ageInDays: Math.floor((now.getTime() - new Date(item.createdAt).getTime()) / (1000 * 60 * 60 * 24)), })); return res.json({ id: recon.id, type: recon.type, entityId: recon.entityId, accountCode: recon.accountCode, periodDate: recon.periodDate, systemBalance: recon.systemBalance, bankBalance: recon.externalBalance, variance: recon.variance, status: recon.status, matchedCount: (recon.matchedItems || []).length, unmatchedCount: unmatchedWithAge.length, unmatched: unmatchedWithAge, matched: recon.matchedItems || [], resolutionNotes: recon.resolutionNotes, resolvedBy: recon.resolvedBy, resolvedAt: recon.resolvedAt, createdAt: recon.createdAt, updatedAt: recon.updatedAt, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to get reconciliation detail"; res.status(500).json({ error: message }); }
}; // ============================================================================
// LIST RECONCILIATIONS
// ============================================================================ export const handleListReconciliations: RequestHandler = async (req, res) => { const { entityId, status, accountCode } = req.query; try { const db = req.app.get("aurumDb") as AurumDatabaseService; let query ="SELECT * FROM reconciliations WHERE 1=1"; const params: any[] = []; if (entityId) { query += ` AND entityId = $${params.length + 1}`; params.push(entityId); } if (status) { query += ` AND status = $${params.length + 1}`; params.push(status); } if (accountCode) { query += ` AND accountCode = $${params.length + 1}`; params.push(accountCode); } query +=" ORDER BY periodDate DESC"; const result = await db.pool.query<Reconciliation>(query, params); return res.json({ reconciliations: result.rows, total: result.rows.length, summary: { pending: result.rows.filter((r: any) => r.status ==="pending").length, matched: result.rows.filter((r: any) => r.status ==="matched").length, resolved: result.rows.filter((r: any) => r.status ==="resolved").length, }, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to list reconciliations"; res.status(500).json({ error: message }); }
};
