/** * NPV & IRR Engine * Foundation for all financial valuations in EchoAurum */ import type { CashFlow } from '../types/aurum-types'; /** * Calculate Net Present Value * NPV = Σ(CF_t / (1 + r)^t) where CF_t is cash flow at period t * @param discountRate Annual discount rate (WACC, hurdle rate) * @param cashFlows Array of cash flows with periods * @returns NPV in the given currency */
export function npv(discountRate: number, cashFlows: CashFlow[]): number { if (cashFlows.length === 0) return 0; const r = discountRate; return cashFlows.reduce((acc, cf) => { const t = cf.period; const discounted = cf.amount / Math.pow(1 + r, t); return acc + discounted; }, 0);
} /** * Calculate Internal Rate of Return (IRR) * Solves for r where NPV = 0 * Uses Newton-Raphson method for efficiency * @param cashFlows Array of cash flows * @param initialGuess Starting guess (default 10%) * @returns IRR as decimal (e.g. 0.15 = 15%) or null if not found */
export function irr( cashFlows: CashFlow[], initialGuess = 0.1
): number | null { if (cashFlows.length < 2) return null; const maxIterations = 100; const tolerance = 1e-8; let rate = initialGuess; // NPV function const f = (r: number) => cashFlows.reduce((acc, cf) => acc + cf.amount / Math.pow(1 + r, cf.period), 0); // Derivative of NPV with respect to r const fPrime = (r: number) => cashFlows.reduce( (acc, cf) => acc + (-cf.period * cf.amount) / Math.pow(1 + r, cf.period + 1), 0 ); // Newton-Raphson iteration for (let i = 0; i < maxIterations; i++) { const value = f(rate); const derivative = fPrime(rate); // Avoid division by very small numbers if (Math.abs(derivative) < 1e-12) return null; const nextRate = rate - value / derivative; // Convergence check if (Math.abs(nextRate - rate) < tolerance) { return nextRate; } rate = nextRate; // Bound check: IRR shouldn't be wildly outside [-100%, +500%] if (rate < -0.99 || rate > 5) { return null; // Likely no valid IRR } } return null; // Failed to converge
} /** * Calculate Payback Period * Time required to recover initial investment * @param cashFlows Array of cash flows * @returns Number of periods to break even, or null if never breaks even */
export function paybackPeriod(cashFlows: CashFlow[]): number | null { if (cashFlows.length === 0) return null; let cumulative = 0; const sorted = [...cashFlows].sort((a, b) => a.period - b.period); for (const cf of sorted) { cumulative += cf.amount; if (cumulative >= 0) { // Linear interpolation for fractional period const prev = cumulative - cf.amount; const fraction = Math.abs(prev) / cf.amount; return cf.period - 1 + fraction; } } return null; // Never breaks even
} /** * Calculate Profitability Index (PI) * PI = PV of future cash flows / Initial investment * Higher PI = better investment per dollar of initial investment * @param discountRate Discount rate * @param cashFlows Cash flows (first should be negative/investment) * @returns PI ratio */
export function profitabilityIndex(discountRate: number, cashFlows: CashFlow[]): number { if (cashFlows.length === 0) return 0; const initialInvestment = Math.abs(cashFlows[0].amount); if (initialInvestment === 0) return 0; const futureFlows = cashFlows.slice(1); const pvFuture = npv(discountRate, futureFlows); return pvFuture / initialInvestment;
} /** * Economic Value Added (EVA) * EVA = NOPAT - (Invested Capital × WACC) * Shows if capital is earning above its cost * @param nopat Net Operating Profit After Tax * @param investedCapital Total capital employed * @param wacc Weighted Average Cost of Capital * @returns EVA */
export function eva(nopat: number, investedCapital: number, wacc: number): number { return nopat - investedCapital * wacc;
} /** * ROIC - Return on Invested Capital * ROIC = NOPAT / Invested Capital * Should exceed WACC for value creation * @param nopat Net Operating Profit After Tax * @param investedCapital Total capital employed * @returns ROIC */
export function roic(nopat: number, investedCapital: number): number { if (investedCapital === 0) return 0; return nopat / investedCapital;
} /** * Terminal Value (Gordon Growth Model) * TV = CF_final × (1 + g) / (r - g) * where g = perpetual growth rate, r = discount rate * @param finalCashFlow Last modeled cash flow * @param growthRate Long-term perpetual growth rate * @param discountRate Discount rate * @returns Terminal value */
export function terminalValue( finalCashFlow: number, growthRate: number, discountRate: number
): number { const denominator = discountRate - growthRate; if (Math.abs(denominator) < 1e-8) { return 0; // Invalid: discount rate = growth rate } return (finalCashFlow * (1 + growthRate)) / denominator;
} /** * Present Value of Growing Annuity * PV = PMT × [1 - ((1 + g) / (1 + r))^n] / (r - g) * @param payment First payment * @param growthRate Annual growth rate * @param discountRate Discount rate * @param periods Number of periods * @returns Present value */
export function pvGrowingAnnuity( payment: number, growthRate: number, discountRate: number, periods: number
): number { if (discountRate === growthRate) { return payment * periods; } const ratio = (1 + growthRate) / (1 + discountRate); return (payment * (1 - Math.pow(ratio, periods))) / (discountRate - growthRate);
} /** * Breakeven Analysis * Find the discount rate at which NPV = 0 (same as IRR, but for reference) * Returns both the rate and the sensitivity */
export interface BreakevenAnalysis { breakevenRate: number | null; margin: number; // how much rate can change before NPV goes negative riskAssessment: 'low' | 'medium' | 'high'; // based on margin
} export function breakeven( cashFlows: CashFlow[], discountRate: number
): BreakevenAnalysis { const currentNpv = npv(discountRate, cashFlows); const irrVal = irr(cashFlows); let riskAssessment: 'low' | 'medium' | 'high' = 'medium'; let margin = 0; if (irrVal) { margin = Math.abs(irrVal - discountRate); if (margin > 0.1) { riskAssessment = 'low'; } else if (margin < 0.02) { riskAssessment = 'high'; } } return { breakevenRate: irrVal, margin, riskAssessment };
}
