/** * Portfolio Optimization Engine * Simplified Markowitz, Efficient Frontier, Risk-Return Analysis */ import type { PortfolioAsset, PortfolioOptimizationResult } from '../types/aurum-types';
import { sharpeRatio } from './risk_metrics'; /** * Calculate portfolio expected return */
export function portfolioExpectedReturn(assets: PortfolioAsset[]): number { return assets.reduce((acc, asset) => { const weight = asset.weight ?? 0; return acc + weight * asset.expectedReturn; }, 0);
} /** * Calculate portfolio volatility (simplified - no full covariance matrix) * Assumes correlations are not provided; approximation only */
export function portfolioVolatility(assets: PortfolioAsset[]): number { if (assets.length === 0) return 0; // Simplified: sqrt(sum of squared weighted volatilities) // Full Markowitz would use covariance matrix const varianceSum = assets.reduce((acc, asset) => { const weight = asset.weight ?? 0; return acc + Math.pow(weight * asset.volatility, 2); }, 0); return Math.sqrt(varianceSum);
} /** * Simple optimizer: brute force grid search for 2-4 assets * Maximizes Sharpe Ratio * Builder.io can later integrate quadratic programming */
export function optimizePortfolioSimple( assets: PortfolioAsset[], riskFreeRate = 0.02
): PortfolioOptimizationResult { if (assets.length < 2 || assets.length > 4) { throw new Error('Current optimizer supports between 2 and 4 assets.'); } let bestResult: PortfolioOptimizationResult | null = null; const step = 0.05; // 5% weight increments const n = assets.length; // Grid search over weights function searchWeights(weights: number[], remaining: number, index: number) { if (index === n - 1) { // Last asset gets remaining weight const finalWeights = [...weights, Math.max(0, remaining)]; evaluatePortfolio(finalWeights); return; } // Try different weights for current asset for (let w = 0; w <= remaining; w += step) { const roundedW = Math.round(w * 100) / 100; const newRemaining = Math.round((remaining - roundedW) * 100) / 100; if (newRemaining >= 0) { searchWeights([...weights, roundedW], newRemaining, index + 1); } } } function evaluatePortfolio(weights: number[]) { // Normalize weights to sum to 1 const sum = weights.reduce((a, w) => a + w, 0); if (sum === 0) return; const normalizedWeights = weights.map(w => w / sum); // Set weights temporarily const assetsWithWeights = assets.map((a, i) => ({ ...a, weight: normalizedWeights[i] })); const expReturn = portfolioExpectedReturn(assetsWithWeights); const vol = portfolioVolatility(assetsWithWeights); const sharpe = sharpeRatio(expReturn, riskFreeRate, vol); if (!bestResult || sharpe > bestResult.sharpeRatio) { bestResult = { assets: assetsWithWeights, expectedReturn: expReturn, volatility: vol, sharpeRatio: sharpe }; } } searchWeights([], 1.0, 0); if (!bestResult) { throw new Error('Failed to compute optimal portfolio.'); } return bestResult;
} /** * Generate Efficient Frontier (simplified) * Returns multiple portfolios at different risk levels */
export interface EfficientFrontierPoint { volatility: number; expectedReturn: number; sharpeRatio: number; weights: number[];
} export function efficientFrontier( assets: PortfolioAsset[], riskFreeRate = 0.02, points = 10
): EfficientFrontierPoint[] { const frontier: EfficientFrontierPoint[] = []; // Generate random portfolios to approximate frontier for (let i = 0; i < points * 5; i++) { const weights = generateRandomWeights(assets.length); const assetsWithWeights = assets.map((a, idx) => ({ ...a, weight: weights[idx] })); const expectedReturn = portfolioExpectedReturn(assetsWithWeights); const volatility = portfolioVolatility(assetsWithWeights); const sharpe = sharpeRatio(expectedReturn, riskFreeRate, volatility); frontier.push({ volatility, expectedReturn, sharpeRatio: sharpe, weights }); } // Sort by volatility return frontier.sort((a, b) => a.volatility - b.volatility);
} /** * Generate random portfolio weights (for frontier generation) */
function generateRandomWeights(n: number): number[] { const weights = Array(n) .fill(0) .map(() => Math.random()); const sum = weights.reduce((a, w) => a + w, 0); return weights.map(w => w / sum);
} /** * Risk Parity Portfolio * Allocates weight inversely proportional to volatility * Each asset contributes equally to portfolio risk */
export function riskParityPortfolio( assets: PortfolioAsset[]
): PortfolioOptimizationResult { if (assets.length === 0) { throw new Error('Need at least one asset'); } // Inverse volatility weighting const invVols = assets.map(a => 1 / a.volatility); const sumInvVol = invVols.reduce((a, v) => a + v, 0); const weights = invVols.map(iv => iv / sumInvVol); const assetsWithWeights = assets.map((a, i) => ({ ...a, weight: weights[i] })); const expectedReturn = portfolioExpectedReturn(assetsWithWeights); const volatility = portfolioVolatility(assetsWithWeights); const sharpeRatio = sharpeRatio(expectedReturn, 0.02, volatility); return { assets: assetsWithWeights, expectedReturn, volatility, sharpeRatio };
} /** * Minimum Variance Portfolio * Lowest possible volatility * Implemented as subset of efficient frontier search */
export function minimumVariancePortfolio( assets: PortfolioAsset[]
): PortfolioOptimizationResult { const frontier = efficientFrontier(assets, 0.02, 5); // Find portfolio with minimum volatility let minVarPortfolio = frontier[0]; for (const point of frontier) { if (point.volatility < minVarPortfolio.volatility) { minVarPortfolio = point; } } const assetsWithWeights = assets.map((a, i) => ({ ...a, weight: minVarPortfolio.weights[i] })); return { assets: assetsWithWeights, expectedReturn: minVarPortfolio.expectedReturn, volatility: minVarPortfolio.volatility, sharpeRatio: minVarPortfolio.sharpeRatio };
} /** * Black-Litterman Model (simplified) * Blends market equilibrium with investor views */
export interface InvestorView { assetId: string; expectedReturn: number; confidence: number; // 0-1
} export function blackLittermanBlend( assets: PortfolioAsset[], marketWeights: number[], views: InvestorView[], confidenceScaling = 0.5
): PortfolioAsset[] { return assets.map((asset, i) => { let blendedReturn = asset.expectedReturn * (1 - confidenceScaling); blendedReturn += marketWeights[i] * asset.expectedReturn * confidenceScaling; // Apply investor views const view = views.find(v => v.assetId === asset.id); if (view) { blendedReturn = blendedReturn * (1 - view.confidence) + view.expectedReturn * view.confidence; } return { ...asset, expectedReturn: blendedReturn }; });
} /** * Asset Allocation for Target Return * Find minimum-risk portfolio that achieves target return */
export function targetReturnPortfolio( assets: PortfolioAsset[], targetReturn: number
): PortfolioOptimizationResult | null { const frontier = efficientFrontier(assets, 0.02, 20); // Find portfolio closest to target return with lowest volatility let bestPortfolio: EfficientFrontierPoint | null = null; let bestDistance = Infinity; for (const point of frontier) { const distance = Math.abs(point.expectedReturn - targetReturn); if (distance < bestDistance) { bestDistance = distance; bestPortfolio = point; } } if (!bestPortfolio) return null; const assetsWithWeights = assets.map((a, i) => ({ ...a, weight: bestPortfolio.weights[i] })); return { assets: assetsWithWeights, expectedReturn: bestPortfolio.expectedReturn, volatility: bestPortfolio.volatility, sharpeRatio: bestPortfolio.sharpeRatio };
} /** * Asset Allocation for Target Risk * Find maximum-return portfolio at target volatility */
export function targetRiskPortfolio( assets: PortfolioAsset[], targetRisk: number
): PortfolioOptimizationResult | null { const frontier = efficientFrontier(assets, 0.02, 20); // Find portfolio closest to target risk let bestPortfolio: EfficientFrontierPoint | null = null; let bestDistance = Infinity; for (const point of frontier) { const distance = Math.abs(point.volatility - targetRisk); if (distance < bestDistance) { bestDistance = distance; bestPortfolio = point; } } if (!bestPortfolio) return null; const assetsWithWeights = assets.map((a, i) => ({ ...a, weight: bestPortfolio.weights[i] })); return { assets: assetsWithWeights, expectedReturn: bestPortfolio.expectedReturn, volatility: bestPortfolio.volatility, sharpeRatio: bestPortfolio.sharpeRatio };
}
