/** * Monte Carlo Simulation Engine * Estimates probability distributions of outcomes under uncertainty */ import type { CashFlow, DistributionStats, ScenarioInput } from '../types/aurum-types';
import { npv, irr } from './npv_irr'; /** * Generate random number from standard normal distribution * Using Box-Muller transform */
function randomNormal(): number { const u1 = Math.random(); const u2 = Math.random(); return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
} /** * Generate random number from log-normal distribution * Useful for positive cash flows */
function randomLogNormal(mean: number, volatility: number): number { const normal = randomNormal(); const logReturn = mean + volatility * normal; return Math.exp(logReturn);
} /** * Simulate NPV distribution via Monte Carlo * Shocks each cash flow by volatility and recalculates NPV * @param scenario Base scenario with baseline cash flows * @param iterations Number of simulations (default 5000) * @returns Distribution statistics of NPV outcomes */
export function simulateScenarioNPV( scenario: ScenarioInput, iterations = 5000
): DistributionStats { const npvResults: number[] = []; const baseFlows = scenario.cashFlows; const volatility = scenario.volatility ?? 0.15; // 15% default // Run Monte Carlo for (let i = 0; i < iterations; i++) { const shockedFlows = baseFlows.map(cf => { // Log-normal shock: each CF can vary up/down, but stays positive const shock = randomNormal(); const factor = Math.exp(volatility * shock); return { ...cf, amount: cf.amount * factor }; }); const val = npv(scenario.discountRate, shockedFlows); npvResults.push(val); } // Calculate statistics const sorted = npvResults.sort((a, b) => a - b); const n = npvResults.length; const mean = npvResults.reduce((a, v) => a + v, 0) / n; const variance = npvResults.reduce((a, v) => a + Math.pow(v - mean, 2), 0) / n; const stdDev = Math.sqrt(variance); // Calculate percentiles const percentile5 = sorted[Math.floor(n * 0.05)]; const percentile95 = sorted[Math.floor(n * 0.95)]; // Skewness: (m3) / (sigma^3) const m3 = npvResults.reduce((a, v) => a + Math.pow(v - mean, 3), 0) / n; const skewness = m3 / Math.pow(stdDev, 3); // Kurtosis: (m4) / (sigma^4) - 3 const m4 = npvResults.reduce((a, v) => a + Math.pow(v - mean, 4), 0) / n; const kurtosis = m4 / Math.pow(stdDev, 4) - 3; return { mean, stdDev, min: sorted[0], max: sorted[n - 1], percentile5, percentile95, skewness, kurtosis };
} /** * Simulate multiple scenarios and compare their distributions * Useful for decision-making under uncertainty */
export function compareScenarios( scenarios: ScenarioInput[], iterations = 5000
): Record<string, DistributionStats> { const results: Record<string, DistributionStats> = {}; for (const scenario of scenarios) { results[scenario.name] = simulateScenarioNPV(scenario, iterations); } return results;
} /** * Value at Risk (VaR) at specified confidence level * E.g. 95% VaR = the amount below which we're 95% confident the outcome won't go * @param npvResults Array of simulated NPV results * @param confidenceLevel E.g. 0.05 for 5% VaR (worst 5%) * @returns Value at risk */
export function valueAtRisk(npvResults: number[], confidenceLevel = 0.05): number { const sorted = npvResults.sort((a, b) => a - b); const idx = Math.floor(sorted.length * confidenceLevel); return sorted[idx];
} /** * Conditional Value at Risk (CVaR) / Expected Shortfall * Average loss given that loss is worse than VaR * More conservative than VaR * @param npvResults Array of simulated NPV results * @param confidenceLevel E.g. 0.05 for expected shortfall in worst 5% * @returns CVaR */
export function conditionalValueAtRisk(npvResults: number[], confidenceLevel = 0.05): number { const sorted = npvResults.sort((a, b) => a - b); const idx = Math.floor(sorted.length * confidenceLevel); const tailValues = sorted.slice(0, idx + 1); return tailValues.reduce((a, v) => a + v, 0) / tailValues.length;
} /** * Probability of achieving a target return * @param npvResults Simulated NPV outcomes * @param targetNpv Target NPV to achieve * @returns Probability (0-1) */
export function probabilityOfTarget(npvResults: number[], targetNpv: number): number { const achieves = npvResults.filter(v => v >= targetNpv).length; return achieves / npvResults.length;
} /** * Tornado Analysis (simplified) * Show sensitivity of NPV to key variables * @param scenario Base scenario * @param variables Variables to test * @param percentageChange How much to vary (e.g. 0.1 = ±10%) * @returns Sensitivity results */
export function tornadoAnalysis( scenario: ScenarioInput, variables: (keyof ScashFlow)[] = ['amount'], percentageChange = 0.1
): { variable: string; upside: number; downside: number; impact: number;
}[] { const baseNpv = npv(scenario.discountRate, scenario.cashFlows); const results = variables.map(varName => { // Up case: increase variable const upFlows = scenario.cashFlows.map(cf => { const modifiedCf = { ...cf }; if (varName in modifiedCf) { const currentVal = (modifiedCf as any)[varName]; if (typeof currentVal === 'number') { (modifiedCf as any)[varName] = currentVal * (1 + percentageChange); } } return modifiedCf; }); const upNpv = npv(scenario.discountRate, upFlows); // Down case: decrease variable const downFlows = scenario.cashFlows.map(cf => { const modifiedCf = { ...cf }; if (varName in modifiedCf) { const currentVal = (modifiedCf as any)[varName]; if (typeof currentVal === 'number') { (modifiedCf as any)[varName] = currentVal * (1 - percentageChange); } } return modifiedCf; }); const downNpv = npv(scenario.discountRate, downFlows); return { variable: String(varName), upside: upNpv - baseNpv, downside: downNpv - baseNpv, impact: Math.abs(upNpv - downNpv) }; }); // Sort by impact (most sensitive first) return results.sort((a, b) => b.impact - a.impact);
} /** * Scenario Analysis * Compare outcomes under different assumptions */
export interface ScenarioComparison { bestCase: { npv: number; probability: number }; baseCase: { npv: number; probability: number }; worstCase: { npv: number; probability: number }; expectedValue: number;
} export function scenarioAnalysis(scenarios: { best: ScenarioInput; base: ScenarioInput; worst: ScenarioInput;
}): ScenarioComparison { const bestNpv = npv(scenarios.best.discountRate, scenarios.best.cashFlows); const baseNpv = npv(scenarios.base.discountRate, scenarios.base.cashFlows); const worstNpv = npv(scenarios.worst.discountRate, scenarios.worst.cashFlows); // Assume simple probabilities (can be overridden) const expectedValue = bestNpv * 0.25 + baseNpv * 0.5 + worstNpv * 0.25; return { bestCase: { npv: bestNpv, probability: 0.25 }, baseCase: { npv: baseNpv, probability: 0.5 }, worstCase: { npv: worstNpv, probability: 0.25 }, expectedValue };
}
