import { promises as fs } from"fs";
import path from"path";
import crypto from"crypto";
import { type HistorianChecks, type HistorianEvent, type HistorianFileChange, type HistorianListResponse, type HistorianSpecReview,
} from"../../shared/historian"; const ROOT = process.cwd();
const HISTORIAN_DIR = path.join(ROOT,"server",".historian"); export type HistorianEventInput = { actor: string; message: string; backupId?: string; files: HistorianFileChange[]; checks?: HistorianChecks; specReview?: HistorianSpecReview | null; projectSlug?: string | null;
}; async function ensureDir() { await fs.mkdir(HISTORIAN_DIR, { recursive: true });
} function truncate(value: string | null | undefined, max = 20000): string | null { if (value == null) return null; if (value.length <= max) return value; const omitted = value.length - max; return value.slice(0, max) + `\n… truncated (${omitted} chars omitted)`;
} function normalizeChange(change: HistorianFileChange): HistorianFileChange { return { ...change, before: truncate(change.before ?? null), after: truncate(change.after ?? null), beforeHash: change.beforeHash ?? null, afterHash: change.afterHash ?? null, };
} export function summarizeDiff(before: string, after: string): { added: number; removed: number;
} { if (before === after) { return { added: 0, removed: 0 }; } const a = before.split(/\r?\n/); const b = after.split(/\r?\n/); const m = a.length; const n = b.length; const dp = Array.from({ length: m + 1 }, () => new Array<number>(n + 1).fill(0)); for (let i = m - 1; i >= 0; i--) { for (let j = n - 1; j >= 0; j--) { dp[i][j] = a[i] === b[j] ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1]); } } let i = 0; let j = 0; let added = 0; let removed = 0; while (i < m && j < n) { if (a[i] === b[j]) { i++; j++; continue; } if (dp[i + 1][j] >= dp[i][j + 1]) { removed++; i++; } else { added++; j++; } } removed += m - i; added += n - j; return { added, removed };
} function parseEventId(id: string): string { return id.endsWith(".json") ? id.slice(0, -5) : id;
} export async function recordHistorianEvent( input: HistorianEventInput,
): Promise<HistorianEvent> { await ensureDir(); const createdAt = Date.now(); const id = `${createdAt}-${crypto.randomBytes(4).toString("hex")}`; const event: HistorianEvent = { id, createdAt, actor: input.actor, message: input.message, backupId: input.backupId, files: input.files.map(normalizeChange), checks: input.checks, specReview: input.specReview ?? null, projectSlug: input.projectSlug ?? null, }; await fs.writeFile( path.join(HISTORIAN_DIR, `${id}.json`), JSON.stringify(event, null, 2),"utf8", ); return event;
} export async function getHistorianEvent(id: string): Promise<HistorianEvent | null> { try { const raw = await fs.readFile(path.join(HISTORIAN_DIR, `${id}.json`),"utf8"); return JSON.parse(raw) as HistorianEvent; } catch { return null; }
} export async function listHistorianEvents(params: { limit?: number; cursor?: string | null;
}): Promise<HistorianListResponse> { const { limit = 50, cursor = null } = params; await ensureDir(); const entries = (await fs.readdir(HISTORIAN_DIR).catch(() => [])) .filter((name) => name.endsWith(".json")) .sort((a, b) => (a < b ? 1 : a > b ? -1 : 0)); let startIndex = 0; if (cursor) { const idx = entries.findIndex((name) => parseEventId(name) === cursor); if (idx >= 0) { startIndex = idx + 1; } } const slice = entries.slice(startIndex, startIndex + limit); const events: HistorianEvent[] = []; for (const file of slice) { try { const raw = await fs.readFile(path.join(HISTORIAN_DIR, file),"utf8"); events.push(JSON.parse(raw) as HistorianEvent); } catch { // ignore parse errors } } const nextFile = entries[startIndex + limit] ?? null; return { events, nextCursor: nextFile ? parseEventId(nextFile) : null, };
}
