/** * EXIF utility for embedding cake design metadata in images * Stores prompt, cake config, client ID, timestamp, consent status */ import { DesignData } from"../modules/cake-builder/types"; export interface CakeMetadata { prompt: string; // Original AI prompt cakeConfig: { type?: string; flavor?: string; icing?: string; filling?: string; shape: string; tiers: number; servings: number; theme?: string; }; clientId?: string; clientName?: string; timestamp: string; // ISO date consentStatus:"adult" |"standard"; estimatedPrice?: number; designName?: string;
} /** * Embed metadata into image as EXIF data (via canvas manipulation) * Note: True EXIF embedding requires server-side processing (piexifjs won't work in browser) * Alternative: Embed as base64 JSON in image comment or use Canvas to encode in pixels */
export function embedMetadataInImage( imageUrl: string, metadata: CakeMetadata,
): Promise<Blob> { return new Promise((resolve, reject) => { const img = new Image(); img.crossOrigin ="anonymous"; img.onload = () => { const canvas = document.createElement("canvas"); canvas.width = img.width; canvas.height = img.height; const ctx = canvas.getContext("2d"); if (!ctx) { reject(new Error("Could not get canvas context")); return; } // Draw the image ctx.drawImage(img, 0, 0); // Add metadata as base64-encoded JSON in bottom-right corner (invisible) const metadataJson = JSON.stringify(metadata); const metadataBase64 = btoa(metadataJson); // Store metadata length in pixels (encode in alpha channel of bottom-right pixel) const imageData = ctx.getImageData(canvas.width - 1, canvas.height - 1, 1, 1); imageData.data[3] = Math.min(metadataBase64.length, 255); // Alpha channel = length ctx.putImageData(imageData, canvas.width - 1, canvas.height - 1); // Add metadata text overlay (faint, bottom-left corner) ctx.font ="10px monospace"; ctx.fillStyle ="rgba(0,0,0,0.01)"; // Nearly invisible ctx.fillText(`META:${metadataBase64.substring(0, 50)}...`, 5, canvas.height - 5); // Convert to blob and resolve canvas.toBlob( (blob) => { if (blob) { resolve(blob); } else { reject(new Error("Failed to create blob from canvas")); } },"image/png", ); }; img.onerror = () => { reject(new Error(`Failed to load image: ${imageUrl}`)); }; img.src = imageUrl; });
} /** * Store metadata in Supabase as JSON alongside image * This is the more reliable method for compliance tracking */
export async function storeMetadataInDatabase( imageId: string, metadata: CakeMetadata,
): Promise<void> { try { const response = await fetch("/api/store-cake-metadata", { method:"POST", headers: {"Content-Type":"application/json" }, body: JSON.stringify({ imageId, metadata, }), }); if (!response.ok) { throw new Error(`Failed to store metadata: ${response.statusText}`); } } catch (error) { console.error("Error storing metadata:", error); throw error; }
} /** * Extract metadata from image (if embedded) */
export function extractMetadataFromImage(imageUrl: string): Promise<CakeMetadata | null> { return new Promise((resolve) => { const img = new Image(); img.crossOrigin ="anonymous"; img.onload = () => { try { const canvas = document.createElement("canvas"); canvas.width = img.width; canvas.height = img.height; const ctx = canvas.getContext("2d"); if (!ctx) { resolve(null); return; } ctx.drawImage(img, 0, 0); // Read length from alpha channel const imageData = ctx.getImageData(img.width - 1, img.height - 1, 1, 1); const metadataLength = imageData.data[3]; if (metadataLength === 0 || metadataLength === 255) { resolve(null); return; } // Try to extract from text (simplified - actual implementation would need full parsing) resolve(null); } catch (error) { console.error("Error extracting metadata:", error); resolve(null); } }; img.onerror = () => { resolve(null); }; img.src = imageUrl; });
} /** * Create a downloadable JSON file with cake design metadata (as recipe card) */
export function downloadCakeRecipeCard(metadata: CakeMetadata): void { const recipeCard = { title: `Cake Design: ${metadata.designName ||"Untitled"}`, generatedAt: metadata.timestamp, client: metadata.clientName ||"Anonymous", prompt: metadata.prompt, cake: metadata.cakeConfig, consent: metadata.consentStatus, estimatedPrice: metadata.estimatedPrice, instructions: ["This recipe card contains the design specifications for recreating this cake design.","Use the prompt and configuration to regenerate the cake visualization.","All measurements are in standard baking units.", ], }; const json = JSON.stringify(recipeCard, null, 2); const blob = new Blob([json], { type:"application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `cake-recipe-${Date.now()}.json`; document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url);
}
