/** * Analytics endpoints (interval coverage, drilldown, performance, insights, KPI) */
import { Router } from"express";
import { getSupabase } from"../../lib/supabase";
import { computeWeeklyKPI } from"../../services/metricsEngine";
import { computePerformanceForDept } from"../../services/performanceModel"; const router = Router(); /** GET /api/analytics/interval-coverage?dept_id&date&interval=15 */
router.get("/interval-coverage", async (req, res) => { try { const { dept_id, date, interval ="15" } = req.query as any; const supabase = getSupabase(); if (!supabase) return res.json({ rows: [] }); // Try to get from materialized table, fallback to empty const { data: reqs } = await supabase .from("interval_coverage") .select("ts, required, provided") .eq("dept_id", dept_id) .gte("ts", `${date}T00:00:00`) .lt("ts", `${date}T23:59:59`); const rows = (reqs || []).map((r: any) => ({ ts: r.ts, required: r.required || 0, provided: r.provided || 0, })); res.json({ rows }); } catch (err) { console.error("GET /interval-coverage error:", err); res.json({ rows: [] }); }
}); /** GET /api/analytics/drilldown?org_id&outlet_id&dept_id&start&end */
router.get("/drilldown", async (req, res) => { try { const { org_id, outlet_id, dept_id, start, end } = req.query as any; const supabase = getSupabase(); if (!supabase) return res.json({ rows: [] }); const { data: shifts } = await supabase .from("shifts") .select("id, employee_id, starts_at, ends_at, break_min, dept_id, notes" ) .eq("dept_id", dept_id) .gte("starts_at", start) .lt("starts_at", end); const empIds = Array.from( new Set((shifts || []).map((s: any) => s.employee_id)) ); const { data: emps } = await supabase .from("employees") .select("id, first_name, last_name, role_title, hourly_rate") .in("id", empIds); const empMap: Record<string, any> = {}; (emps || []).forEach((e: any) => (empMap[e.id] = e)); // Simple drilldown: shift-level breakdown const rows = (shifts || []).map((s: any) => { const emp = empMap[s.employee_id]; const startMs = new Date(s.starts_at).getTime(); const endMs = new Date(s.ends_at).getTime(); const durationMs = endMs - startMs; const hours = (durationMs - (s.break_min || 0) * 60 * 1000) / 3600000; const cost = (emp?.hourly_rate || 0) * hours; return { ts: s.starts_at, employee_name: emp ? `${emp.first_name} ${emp.last_name}` : s.employee_id, position: emp?.role_title ||"Unknown", hours: Math.max(0, hours), cost: Math.max(0, cost), revenue: 0, tips: 0, notes: s.notes ||"", }; }); res.json({ rows }); } catch (err) { console.error("GET /drilldown error:", err); res.status(500).json({ error: String(err) }); }
}); /** GET /api/analytics/drilldown-csv?... → CSV export */
router.get("/drilldown-csv", async (req, res) => { try { const { org_id, outlet_id, dept_id, start, end } = req.query as any; // Reuse drilldown endpoint const response = await fetch( `http://localhost/api/analytics/drilldown?org_id=${org_id}&outlet_id=${outlet_id}&dept_id=${dept_id}&start=${start}&end=${end}`, { headers: { Host:"localhost" } } ).catch(() => null); let rows: any[] = []; if (response && response.ok) { const data = await response.json(); rows = data.rows || []; } const header = ["ts","employee_name","position","hours","cost","revenue","tips","notes", ]; const lines = [header.join(",")].concat( rows.map((x: any) => header.map((h) => JSON.stringify(x[h] ??"")).join(",")) ); res.setHeader("Content-Type","text/csv"); res.send(lines.join("\n")); } catch (err) { console.error("GET /drilldown-csv error:", err); res.status(500).json({ error: String(err) }); }
}); /** GET /api/analytics/performance?dept_id&start&end&includeTips=0/1 */
router.get("/performance", async (req, res) => { try { const { dept_id, start, end, includeTips } = req.query as any; const rows = await computePerformanceForDept( dept_id, start, end, includeTips ==="1" ); const supabase = getSupabase(); let employees: any[] = []; if (supabase) { const { data } = await supabase .from("employees") .select("id, first_name, last_name, role_title") .eq("dept_id", dept_id); employees = data || []; } res.json({ rows, employees }); } catch (err) { console.error("GET /performance error:", err); res.status(500).json({ error: String(err) }); }
}); /** GET /api/analytics/echo-insights?org_id&outlet_id&dept_id&start&end */
router.get("/echo-insights", async (req, res) => { try { const { dept_id, start, end } = req.query as any; const supabase = getSupabase(); if (!supabase) return res.json({ rows: [] }); // Simple heuristics: check shift counts const { data: shifts } = await supabase .from("shifts") .select("id, starts_at") .eq("dept_id", dept_id) .gte("starts_at", start) .lt("starts_at", end); const rows: any[] = []; if ((shifts || []).length === 0) { rows.push({ ts: new Date().toISOString(), message: `No shifts scheduled for this period. Review demand forecast and staffing plan.`, severity:"warn", }); } else { rows.push({ ts: new Date().toISOString(), message: `${(shifts || []).length} shifts scheduled. Monitor coverage quality and staff utilization.`, severity:"info", }); } res.json({ rows }); } catch (err) { console.error("GET /echo-insights error:", err); res.status(500).json({ error: String(err) }); }
}); /** GET /api/analytics/kpi/weekly?org_id&outlet_id&dept_id&week_start → KPI bundle */
router.get("/kpi/weekly", async (req, res) => { try { const { org_id, outlet_id, dept_id, week_start } = req.query as any; const kpi = await computeWeeklyKPI({ org_id, outlet_id, dept_id, week_start, }); res.json(kpi); } catch (err) { console.error("GET /kpi/weekly error:", err); res.status(500).json({ error: String(err) }); }
}); export default router;
