import { Router } from"express";
import { z } from"zod";
import { validateBody } from"../../middleware/validate";
import { authenticateUser } from"../../middleware/auth";
import { supabase } from"../../lib/db"; const router = Router(); const onboardingSchema = z.object({ firstName: z.string().min(1), lastName: z.string().min(1), email: z.string().email(), phone: z.string().min(10), address: z.string().min(5), ssn: z.string().regex(/^\d{3}-\d{2}-\d{4}$/), dateOfBirth: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), emergencyName: z.string().min(1), emergencyPhone: z.string().min(10), emergencyRelationship: z.string().min(1), bankRoutingNumber: z.string().regex(/^\d{9}$/), bankAccountNumber: z.string().min(8), accountType: z.enum(["checking","savings"]), position: z.string().min(1), department: z.string().min(1), startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), resumeParsed: z.object({ name: z.string().optional(), email: z.string().optional(), phone: z.string().optional(), experience: z.array(z.string()).optional(), skills: z.array(z.string()).optional(), education: z.array(z.string()).optional(), }).optional(), allComplete: z.boolean(),
}); /** * POST /api/employees/onboard * Complete employee onboarding process */
router.post("/onboard", authenticateUser, validateBody(onboardingSchema), async (req, res, next) => { try { const data = req.body; // Create employee record const { data: employee, error: insertError } = await supabase .from("employees") .insert({ first_name: data.firstName, last_name: data.lastName, email: data.email, phone: data.phone, hourly_rate: 15.0, active: true, }) .select() .single(); if (insertError) { return res.status(400).json({ success: false, error: `Failed to create employee: ${insertError.message}`, }); } // Store onboarding data in documents table const { error: docError } = await supabase .from("employee_documents") .insert({ employee_id: employee.id, document_type:"onboarding", data: { address: data.address, ssn_encrypted: data.ssn, dateOfBirth: data.dateOfBirth, emergency: { name: data.emergencyName, phone: data.emergencyPhone, relationship: data.emergencyRelationship, }, directDeposit: { routingNumber: data.bankRoutingNumber, accountNumber: data.bankAccountNumber, accountType: data.accountType, }, position: data.position, department: data.department, startDate: data.startDate, resumeParsed: data.resumeParsed, }, uploaded_at: new Date(), }); if (docError) { console.error("Document storage error:", docError); } res.status(201).json({ success: true, employee: { id: employee.id, name: `${data.firstName} ${data.lastName}`, email: data.email, position: data.position, startDate: data.startDate, }, message:"Employee onboarding completed successfully", }); } catch (error) { console.error("Onboarding error:", error); next(error); }
}); /** * GET /api/employees/{id}/onboarding-status * Get onboarding status for an employee */
router.get("/:id/onboarding-status", authenticateUser, async (req, res, next) => { try { const { id } = req.params; const { data: employee, error } = await supabase .from("employees") .select("*") .eq("id", id) .single(); if (error) { return res.status(404).json({ error:"Employee not found" }); } const { data: docs } = await supabase .from("employee_documents") .select("document_type, uploaded_at") .eq("employee_id", id); const requiredDocs = ["w4","i9","direct_deposit"]; const uploadedDocs = docs?.map((d: any) => d.document_type) || []; res.json({ success: true, employee: { id: employee.id, name: `${employee.first_name} ${employee.last_name}`, email: employee.email, }, onboarding: { completionPercentage: (uploadedDocs.length / requiredDocs.length) * 100, requiredDocuments: requiredDocs, uploadedDocuments: uploadedDocs, missingDocuments: requiredDocs.filter( (d) => !uploadedDocs.includes(d) ), }, }); } catch (error) { console.error("Error fetching onboarding status:", error); next(error); }
}); /** * POST /api/employees/{id}/documents * Upload employee document */
router.post("/:id/documents", authenticateUser, async (req, res, next) => { try { const { id } = req.params; const { documentType, content } = req.body; if (!documentType || !content) { return res.status(400).json({ error:"documentType and content required", }); } const { error } = await supabase .from("employee_documents") .insert({ employee_id: id, document_type: documentType, data: { content }, uploaded_at: new Date(), }); if (error) { return res.status(400).json({ error: error.message }); } res.json({ success: true, message: `${documentType} document uploaded successfully`, }); } catch (error) { console.error("Document upload error:", error); next(error); }
}); /** * GET /api/employees * List all employees */
router.get("/", authenticateUser, async (req, res, next) => { try { const { data, error } = await supabase .from("employees") .select("*") .eq("active", true) .order("created_at", { ascending: false }); if (error) { return res.status(400).json({ error: error.message }); } res.json({ success: true, count: data?.length || 0, employees: data || [], }); } catch (error) { console.error("List employees error:", error); next(error); }
}); export default router;
