/** * Organization Summary API * Provides aggregated data across all outlets in organization * GET /api/org-summary?org_id=... */ import { Router } from"express";
import { z } from"zod";
import { getSupabase } from"../../lib/supabase";
import { requireRole, validateTenant } from"../../middleware/auth";
import { validateQuery } from"../../middleware/validate"; const router = Router(); const summarySchema = z.object({ org_id: z.string().uuid("Invalid org ID"),
}); /** * GET /api/org-summary?org_id=... * Returns aggregated metrics by outlet */
router.get("/", requireRole("GM","ADMIN"), validateTenant, validateQuery(summarySchema), async (req, res, next) => { try { const { org_id } = req.query as any; const supabase = getSupabase(); if (!supabase) return res.json([]); // Fetch aggregated data by outlet const { data, error } = await supabase .from("property_summary") .select( ` outlet_id, outlets(name), labor_cost, revenue, tips ` ) .eq("org_id", org_id); if (error) throw error; // Group and aggregate by outlet const summaryMap = new Map<string, any>(); (data || []).forEach((row: any) => { const outletId = row.outlet_id; const outletName = row.outlets?.name || outletId; if (!summaryMap.has(outletId)) { summaryMap.set(outletId, { outlet: outletName, revenue: 0, labor_cost: 0, tips: 0, periods: 0, }); } const entry = summaryMap.get(outletId); entry.revenue += row.revenue || 0; entry.labor_cost += row.labor_cost || 0; entry.tips += row.tips || 0; entry.periods += 1; }); // Calculate percentages const result = Array.from(summaryMap.values()).map((entry) => ({ outlet: entry.outlet, revenue: Math.round(entry.revenue * 100) / 100, labor_cost: Math.round(entry.labor_cost * 100) / 100, tips: Math.round(entry.tips * 100) / 100, labor_pct: entry.revenue > 0 ? Math.round((entry.labor_cost / entry.revenue) * 1000) / 10 : 0, })); res.json(result); } catch (err) { next(err); } }
); /** * GET /api/org-summary/trend?org_id=...&weeks=13 * Returns trend data over time */
router.get("/trend", requireRole("GM","ADMIN"), validateTenant, validateQuery(z.object({ org_id: z.string().uuid(), weeks: z.string().default("13") })), async (req, res, next) => { try { const { org_id, weeks } = req.query as any; const supabase = getSupabase(); if (!supabase) return res.json([]); const daysBack = parseInt(weeks) * 7; const startDate = new Date(Date.now() - daysBack * 86400000) .toISOString() .split("T")[0]; const { data, error } = await supabase .from("property_summary") .select("report_date, revenue, labor_cost") .eq("org_id", org_id) .gte("report_date", startDate) .order("report_date"); if (error) throw error; // Aggregate by week const weeklyMap = new Map<string, any>(); (data || []).forEach((row: any) => { const date = new Date(row.report_date); const weekStart = new Date( date.getTime() - (date.getDay() || 7) * 86400000 ) .toISOString() .split("T")[0]; if (!weeklyMap.has(weekStart)) { weeklyMap.set(weekStart, { week: weekStart, revenue: 0, labor_cost: 0, }); } const entry = weeklyMap.get(weekStart); entry.revenue += row.revenue || 0; entry.labor_cost += row.labor_cost || 0; }); const result = Array.from(weeklyMap.values()) .sort((a, b) => a.week.localeCompare(b.week)) .map((entry) => ({ week: entry.week, revenue: Math.round(entry.revenue * 100) / 100, labor_cost: Math.round(entry.labor_cost * 100) / 100, labor_pct: entry.revenue > 0 ? Math.round((entry.labor_cost / entry.revenue) * 1000) / 10 : 0, })); res.json(result); } catch (err) { next(err); } }
); export default router;
