/** * Server-Sent Events (SSE) Route * Provides real-time updates for acknowledgements, notifications, KPI changes * GET /api/sse/acks */ import { Router } from"express";
import { z } from"zod";
import { getSupabase } from"../../lib/supabase";
import { validateQuery } from"../../middleware/validate"; const router = Router(); const sseSchema = z.object({ schedule_id: z.string().uuid("Invalid schedule ID"),
}); /** * GET /api/sse/acks?schedule_id=... * Stream acknowledgement updates via SSE */
router.get("/acks", validateQuery(sseSchema), async (req, res, next) => { try { const { schedule_id } = req.query as any; // Set SSE headers res.setHeader("Content-Type","text/event-stream"); res.setHeader("Cache-Control","no-cache"); res.setHeader("Connection","keep-alive"); res.setHeader("X-Accel-Buffering","no"); // Send initial connection message res.write("data:" + JSON.stringify({ type:"connected", time: new Date().toISOString() }) +"\n\n"); const supabase = getSupabase(); // Poll for acknowledgement updates every 2 seconds let lastAckCount = 0; const pollInterval = setInterval(async () => { try { if (!supabase) return; const { data: acks, error } = await supabase .from("publish_acknowledgements") .select("*") .eq("schedule_id", schedule_id); if (error) throw error; const ackCount = (acks || []).length; // Only send if changed if (ackCount !== lastAckCount) { lastAckCount = ackCount; const { data: shifts } = await supabase .from("shifts") .select("employee_id") .eq("schedule_id", schedule_id); const totalEmps = new Set((shifts || []).map((s: any) => s.employee_id)) .size; res.write("data:" + JSON.stringify({ type:"ack_update", acknowledged: ackCount, total: totalEmps, pending: totalEmps - ackCount, percentage: totalEmps > 0 ? Math.round((ackCount / totalEmps) * 100) : 0, timestamp: new Date().toISOString(), }) +"\n\n" ); } } catch (error) { console.error("SSE poll error:", error); } }, 2000); // Clean up on client disconnect req.on("close", () => { clearInterval(pollInterval); res.end(); }); } catch (err) { next(err); } }
); /** * GET /api/sse/kpi?dept_id=... * Stream KPI updates via SSE */
router.get("/kpi", validateQuery(z.object({ dept_id: z.string().uuid() })), async (req, res, next) => { try { const { dept_id } = req.query as any; // Set SSE headers res.setHeader("Content-Type","text/event-stream"); res.setHeader("Cache-Control","no-cache"); res.setHeader("Connection","keep-alive"); res.write("data:" + JSON.stringify({ type:"kpi_connected", dept_id, time: new Date().toISOString(), }) +"\n\n" ); const supabase = getSupabase(); // Update every 5 seconds const pollInterval = setInterval(async () => { try { if (!supabase) return; const { data: summary } = await supabase .from("property_summary") .select("*") .gte("report_date", new Date().toISOString().split("T")[0]) .limit(1); if (summary && summary.length > 0) { const s = summary[0]; const labor_pct = s.revenue > 0 ? Math.round((s.labor_cost / s.revenue) * 1000) / 10 : 0; res.write("data:" + JSON.stringify({ type:"kpi_update", revenue: s.revenue, labor_cost: s.labor_cost, labor_pct, tips: s.tips, timestamp: new Date().toISOString(), }) +"\n\n" ); } } catch (error) { console.error("SSE KPI poll error:", error); } }, 5000); req.on("close", () => { clearInterval(pollInterval); res.end(); }); } catch (err) { next(err); } }
); export default router;
