/** * Staff management endpoints (skills, ratings, dev plans, training) */
import { Router } from"express";
import { getSupabase } from"../../lib/supabase"; const router = Router(); /** GET /api/staff/skills?dept_id=... → Skill matrix rows + skill catalog */
router.get("/skills", async (req, res) => { try { const { dept_id } = req.query as any; const supabase = getSupabase(); if (!supabase) return res.json({ rows: [], skills: [] }); // Get skills for this org const { data: skillsData } = await supabase .from("skills") .select("*"); // Get employees and their skills const { data: empsData } = await supabase .from("employees") .select("id, first_name, last_name") .eq("dept_id", dept_id); const { data: empSkillsData } = await supabase .from("employee_skills") .select("employee_id, skill_slug, level"); const skillMap: Record<string, Record<string, number>> = {}; (empSkillsData || []).forEach((es: any) => { if (!skillMap[es.employee_id]) skillMap[es.employee_id] = {}; skillMap[es.employee_id][es.skill_slug] = es.level; }); const rows = (empsData || []).map((e: any) => ({ employee_id: e.id, name: `${e.first_name} ${e.last_name}`, skills: skillMap[e.id] || {}, })); res.json({ rows, skills: skillsData || [] }); } catch (err) { console.error("GET /skills error:", err); res.status(500).json({ error: String(err) }); }
}); /** POST /api/staff/skills/level { employee_id, slug, level } */
router.post("/skills/level", async (req, res) => { try { const { employee_id, slug, level } = req.body; const supabase = getSupabase(); if (!supabase) return res.json({ ok: true }); const { error } = await supabase.from("employee_skills").upsert({ employee_id, skill_slug: slug, level, }); if (error) throw error; res.json({ ok: true }); } catch (err) { console.error("POST /skills/level error:", err); res.status(500).json({ error: String(err) }); }
}); /** POST /api/staff/rate — used by RatingEntryForm */
router.post("/rate", async (req, res) => { try { const { employee_id, outlet_id, shift_date, punctuality, quality, teamwork, guest_feedback, notes, } = req.body; const total = avg([punctuality, quality, teamwork, guest_feedback]); const supabase = getSupabase(); if (!supabase) return res.json({ ok: true }); const { error } = await supabase.from("ratings").insert({ employee_id, outlet_id, shift_date, punctuality, quality, teamwork, guest_feedback: guest_feedback || null, total_score: total, notes: notes || null, }); if (error) throw error; // Refresh cached avg const { data: ratings } = await supabase .from("ratings") .select("total_score") .eq("employee_id", employee_id); const newAvg = (ratings || []).reduce((s: number, r: any) => s + Number(r.total_score || 0), 0) / Math.max(1, ratings?.length || 1); await supabase .from("employees") .update({ rating_avg: newAvg }) .eq("id", employee_id); res.json({ ok: true }); } catch (err) { console.error("POST /rate error:", err); res.status(500).json({ error: String(err) }); }
}); /** GET /api/staff/devplan/:employee_id */
router.get("/devplan/:employee_id", async (req, res) => { try { const { employee_id } = req.params; const supabase = getSupabase(); if (!supabase) return res.json({ plan: null }); const { data } = await supabase .from("development_plans") .select("*") .eq("employee_id", employee_id) .order("created_at", { ascending: false }) .limit(1) .single(); res.json({ plan: data || null }); } catch (err) { res.json({ plan: null }); }
}); /** POST /api/staff/devplan/:employee_id (create/update latest) */
router.post("/devplan/:employee_id", async (req, res) => { try { const { employee_id } = req.params; const p = req.body; const supabase = getSupabase(); if (!supabase) return res.json({ ok: true }); const { error } = await supabase.from("development_plans").upsert({ employee_id, goal_title: p.goal_title, description: p.description, target_date: p.target_date || null, status: p.status, milestones: p.milestones || [], ai_recommendation: p.ai_recommendation || null, }); if (error) throw error; res.json({ ok: true }); } catch (err) { console.error("POST /devplan/:employee_id error:", err); res.status(500).json({ error: String(err) }); }
}); /** POST /api/staff/devplan/:employee_id/ai — Echo AI suggestion */
router.post("/devplan/:employee_id/ai", async (req, res) => { try { const { employee_id } = req.params; const supabase = getSupabase(); if (!supabase) return res.json({ text:"No database configured" }); const { data: emp } = await supabase .from("employees") .select("first_name, last_name, role_title") .eq("id", employee_id) .single(); const { data: ratings } = await supabase .from("ratings") .select("total_score") .eq("employee_id", employee_id); const name = emp ? `${emp.first_name} ${emp.last_name}` :"Employee"; const avgScore = (ratings || []).reduce((s: number, r: any) => s + Number(r.total_score || 0), 0) / Math.max(1, ratings?.length || 1); const text = `Recommended focus for ${name} (avg score ${avgScore.toFixed(2)}): strengthen guest engagement and cross-train for Banquet Support. Milestones: (1) Complete banquet setup module; (2) 2 shadow shifts next month; (3) Service quality target ≥4.5.`; res.json({ text }); } catch (err) { console.error("POST /devplan/:employee_id/ai error:", err); res.status(500).json({ error: String(err) }); }
}); /** GET /api/staff/trainings/:employee_id */
router.get("/trainings/:employee_id", async (req, res) => { try { const { employee_id } = req.params; const supabase = getSupabase(); if (!supabase) return res.json({ rows: [] }); const { data } = await supabase .from("training_records") .select("*") .eq("employee_id", employee_id) .order("start_date", { ascending: false }); res.json({ rows: data || [] }); } catch (err) { console.error("GET /trainings/:employee_id error:", err); res.status(500).json({ error: String(err) }); }
}); function avg(nums: Array<number | undefined>) { const xs = nums.filter((n): n is number => typeof n ==="number"); return xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0;
} export default router;
