import { Request, Response, NextFunction } from"express"; interface PerformanceMetric { path: string; method: string; duration: number; statusCode: number; timestamp: Date; userAgent?: string;
} interface QueryMetric { query: string; duration: number; rowCount: number; timestamp: Date;
} const metrics: PerformanceMetric[] = [];
const queryMetrics: QueryMetric[] = [];
const maxMetricsSize = 10000; export function performanceMonitor( req: Request, res: Response, next: NextFunction
): void { const startTime = Date.now(); const startCpuUsage = process.cpuUsage(); res.on("finish", () => { const duration = Date.now() - startTime; const cpuUsage = process.cpuUsage(startCpuUsage); const metric: PerformanceMetric = { path: req.path, method: req.method, duration, statusCode: res.statusCode, timestamp: new Date(), userAgent: req.get("user-agent"), }; metrics.push(metric); // Keep metrics array size manageable if (metrics.length > maxMetricsSize) { metrics.shift(); } // Log slow requests (>1000ms) if (duration > 1000) { console.warn( `[SLOW REQUEST] ${req.method} ${req.path} took ${duration}ms` ); } // Log high CPU usage if (cpuUsage.user > 100000 || cpuUsage.system > 100000) { console.warn(`[HIGH CPU] ${req.method} ${req.path} - CPU spike detected`); } }); next();
} export function recordQueryMetric( query: string, duration: number, rowCount: number = 0
): void { const metric: QueryMetric = { query, duration, rowCount, timestamp: new Date(), }; queryMetrics.push(metric); if (queryMetrics.length > maxMetricsSize) { queryMetrics.shift(); } // Log slow queries (>500ms) if (duration > 500) { console.warn(`[SLOW QUERY] ${duration}ms - ${query.substring(0, 100)}`); }
} export interface PerformanceStats { requests: { total: number; avgDuration: number; slowRequests: number; errorRate: number; percentiles: { p50: number; p75: number; p95: number; p99: number; }; }; queries: { total: number; avgDuration: number; slowQueries: number; percentiles: { p50: number; p75: number; p95: number; p99: number; }; }; endpoints: Array<{ path: string; method: string; count: number; avgDuration: number; maxDuration: number; errorCount: number; }>;
} export function getPerformanceStats(): PerformanceStats { const durations = metrics.map((m) => m.duration).sort((a, b) => a - b); const slowRequests = metrics.filter((m) => m.duration > 1000).length; const errorCount = metrics.filter((m) => m.statusCode >= 400).length; const queryDurations = queryMetrics .map((q) => q.duration) .sort((a, b) => a - b); const slowQueries = queryMetrics.filter((q) => q.duration > 500).length; // Group metrics by endpoint const endpointMap = new Map< string, { count: number; durations: number[]; errors: number; } >(); metrics.forEach((m) => { const key = `${m.method} ${m.path}`; const existing = endpointMap.get(key) || { count: 0, durations: [], errors: 0, }; existing.count++; existing.durations.push(m.duration); if (m.statusCode >= 400) existing.errors++; endpointMap.set(key, existing); }); const endpoints = Array.from(endpointMap.entries()).map(([key, data]) => { const [method, path] = key.split(""); return { path, method, count: data.count, avgDuration: Math.round( data.durations.reduce((a, b) => a + b, 0) / data.durations.length ), maxDuration: Math.max(...data.durations), errorCount: data.errors, }; }); const getPercentile = (arr: number[], p: number): number => { if (arr.length === 0) return 0; const index = Math.ceil((p / 100) * arr.length) - 1; return arr[Math.max(0, index)]; }; return { requests: { total: metrics.length, avgDuration: metrics.length > 0 ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length) : 0, slowRequests, errorRate: metrics.length > 0 ? (errorCount / metrics.length) * 100 : 0, percentiles: { p50: getPercentile(durations, 50), p75: getPercentile(durations, 75), p95: getPercentile(durations, 95), p99: getPercentile(durations, 99), }, }, queries: { total: queryMetrics.length, avgDuration: queryMetrics.length > 0 ? Math.round( queryDurations.reduce((a, b) => a + b, 0) / queryDurations.length ) : 0, slowQueries, percentiles: { p50: getPercentile(queryDurations, 50), p75: getPercentile(queryDurations, 75), p95: getPercentile(queryDurations, 95), p99: getPercentile(queryDurations, 99), }, }, endpoints: endpoints .sort((a, b) => b.count - a.count) .slice(0, 20), };
} export function resetMetrics(): void { metrics.length = 0; queryMetrics.length = 0;
} export function getMetrics(): PerformanceMetric[] { return [...metrics];
} export function getQueryMetrics(): QueryMetric[] { return [...queryMetrics];
}
