/** * Stripe Payment Gateway Integration * Secure PCI-compliant payment processing */ import Stripe from "stripe";
import { supabase } from "./supabase";
import { logger, logPaymentTransaction, sanitizeError } from "./logger"; const stripeKey = process.env.STRIPE_SECRET_KEY ||""; // Lazy initialization of Stripe - only create when actually needed
let stripeInstance: Stripe | null = null; /** * Get Stripe instance (lazy initialization) */
function getStripe(): Stripe { if (stripeInstance) { return stripeInstance; } if (!stripeKey) { throw new Error("Stripe API key not configured. Set STRIPE_SECRET_KEY environment variable.", ); } stripeInstance = new Stripe(stripeKey, { apiVersion:"2024-06-20", }); return stripeInstance;
} export function isStripeConfigured(): boolean { return !!stripeKey;
} export function getStripeInstance(): Stripe | null { if (!stripeKey) { return null; } return getStripe();
} /** * Process a payment using Stripe */
export async function processPayment( amount: number, currency: string, paymentMethodId: string, organizationId: string, invoicePaymentId: string, description?: string,
): Promise<Stripe.PaymentIntent> { try { const stripe = getStripe(); const paymentIntent = await stripe.paymentIntents.create({ amount: Math.round(amount * 100), // Convert to cents currency: currency.toLowerCase(), payment_method: paymentMethodId, confirm: true, automatic_payment_methods: { enabled: true, allow_redirects:"never", }, metadata: { invoicePaymentId, organizationId, }, description: description || `Invoice Payment - ${invoicePaymentId}`, }); return paymentIntent; } catch (error) { logPaymentTransaction( invoicePaymentId,"failed", amount, currency, organizationId,"failure", error, ); throw new Error( `Payment processing failed: ${ error instanceof Error ? error.message :"Unknown error" }`, ); }
} /** * Refund a payment */
export async function refundPayment( paymentIntentId: string, amount?: number,
): Promise<Stripe.Refund> { try { const stripe = getStripe(); const refund = await stripe.refunds.create({ payment_intent: paymentIntentId, ...(amount && { amount: Math.round(amount * 100) }), }); return refund; } catch (error) { logger.error("Stripe refund error", sanitizeError(error)); throw error; }
} /** * Create a setup intent for saving payment methods */
export async function createSetupIntent( customerId: string,
): Promise<Stripe.SetupIntent> { try { const stripe = getStripe(); const setupIntent = await stripe.setupIntents.create({ customer: customerId, payment_method_types: ["card"], }); return setupIntent; } catch (error) { logger.error("Stripe setup intent error", sanitizeError(error)); throw error; }
} /** * Create or retrieve customer */
export async function getOrCreateCustomer( customerId: string, email: string, name: string,
): Promise<Stripe.Customer> { try { // Try to retrieve existing customer const stripe = getStripe(); if (customerId) { const customer = await stripe.customers.retrieve(customerId); if (!customer.deleted) { return customer; } } // Create new customer const customer = await stripe.customers.create({ email, name, }); return customer; } catch (error) { logger.error("Stripe customer error", sanitizeError(error)); throw error; }
} /** * Handle Stripe webhook events */
export async function handleStripeWebhook( event: Stripe.Event,
): Promise<boolean> { try { switch (event.type) { case"payment_intent.succeeded": { const paymentIntent = event.data.object as Stripe.PaymentIntent; const invoicePaymentId = paymentIntent.metadata.invoicePaymentId; // Update payment status await supabase .from("invoice_payments") .update({ status:"completed", transaction_id: paymentIntent.id, payment_date: new Date().toISOString().split("T")[0], updated_at: new Date().toISOString(), }) .eq("id", invoicePaymentId); logPaymentTransaction( invoicePaymentId,"succeeded", paymentIntent.amount / 100, paymentIntent.currency, paymentIntent.metadata.organizationId,"success", ); } break; case"payment_intent.payment_failed": { const paymentIntent = event.data.object as Stripe.PaymentIntent; const invoicePaymentId = paymentIntent.metadata.invoicePaymentId; // Update payment status await supabase .from("invoice_payments") .update({ status:"failed", transaction_id: paymentIntent.id, updated_at: new Date().toISOString(), }) .eq("id", invoicePaymentId); logPaymentTransaction( invoicePaymentId,"failed", paymentIntent.amount / 100, paymentIntent.currency, paymentIntent.metadata.organizationId,"failure", paymentIntent.last_payment_error, ); } break; case"charge.refunded": { const charge = event.data.object as Stripe.Charge; logger.info(`Charge ${charge.id} refunded`); } break; default: logger.debug(`Unhandled Stripe event type: ${event.type}`); } return true; } catch (error) { logger.error("Webhook processing error", sanitizeError(error)); return false; }
}
