/** * PDF Extractor Test and Debugging Tool * Used to test and validate PDF definition extraction logic */ import { extractDefinitionsFromPdfText } from './pdf-definition-extractor';
import { extractTextFromPDFBuffer } from './pdf-upload-handler';
import { convertPDFToMasterTerms } from './pdf-knowledge-extractor';
import type { PDFMetadata } from './pdf-knowledge-extractor'; /** * Test glossary extraction with sample text */
export function testGlossaryExtraction(text: string, sourceName: string ="Test Source") { console.log("\n=== PDF GLOSSARY EXTRACTION TEST ==="); console.log(`Source: ${sourceName}`); console.log(`Text length: ${text.length} characters`); console.log("---"); const definitions = extractDefinitionsFromPdfText(text, sourceName); console.log(`\n✓ Extracted ${definitions.length} definitions`); if (definitions.length === 0) { console.log("⚠️ No definitions extracted! Debugging information:"); // Debug: Show first 1000 chars console.log("\nFirst 500 characters of text:"); console.log(text.substring(0, 500)); console.log("---"); // Debug: Look for patterns console.log("\nLooking for potential term patterns:"); const lines = text.split('\n').slice(0, 20); lines.forEach((line, i) => { if (line.trim().length > 0) { console.log(`Line ${i}:"${line.substring(0, 100)}"`); } }); } else { console.log("\nFirst 10 extracted definitions:"); definitions.slice(0, 10).forEach((def, i) => { console.log(`${i + 1}."${def.term}" - ${def.definition.substring(0, 60)}...`); console.log(` Categories: ${def.categories.join(', ')}`); }); } return definitions;
} /** * Test PDF text extraction from buffer */
export async function testPDFTextExtraction(buffer: Buffer, filename: string) { console.log("\n=== PDF TEXT EXTRACTION TEST ==="); console.log(`Filename: ${filename}`); console.log(`Buffer size: ${buffer.length} bytes`); console.log("---"); try { const text = await extractTextFromPDFBuffer(buffer, filename); console.log(`✓ Extracted ${text.length} characters`); console.log("\nFirst 500 characters:"); console.log(text.substring(0, 500)); console.log("---"); // Count lines const lines = text.split('\n'); console.log(`Total lines: ${lines.length}`); console.log(`Average line length: ${Math.round(text.length / lines.length)} chars`); return text; } catch (error) { console.error("✗ Text extraction failed:"); console.error(error instanceof Error ? error.message : String(error)); return null; }
} /** * Full pipeline test: PDF buffer -> text -> definitions */
export async function testFullPDFPipeline( buffer: Buffer, filename: string, metadata: PDFMetadata
) { console.log("\n=== FULL PDF PIPELINE TEST ==="); console.log(`File: ${filename}`); console.log("---"); // Step 1: Extract text console.log("\nStep 1: Text Extraction..."); const text = await testPDFTextExtraction(buffer, filename); if (!text) { console.error("Pipeline failed at text extraction"); return null; } // Step 2: Extract definitions console.log("\n\nStep 2: Definition Extraction..."); const definitions = testGlossaryExtraction(text, metadata.title); // Step 3: Convert to master terms console.log("\n\nStep 3: Master Term Conversion..."); const masterTerms = convertPDFToMasterTerms(text, metadata); console.log(`✓ Converted to ${masterTerms.terms.length} master culinary terms`); console.log(`Average confidence: ${masterTerms.metadata.confidence.toFixed(2)}`); if (masterTerms.terms.length > 0) { console.log("\nFirst 5 master terms:"); masterTerms.terms.slice(0, 5).forEach((term, i) => { console.log(`${i + 1}."${term.term}"`); console.log(` Definition: ${term.definition.substring(0, 60)}...`); console.log(` Categories: ${term.categories.join(', ')}`); console.log(` Mastery Level: ${term.masteryLevel}`); console.log(` Confidence: ${term.confidence.toFixed(2)}`); }); } return masterTerms;
} /** * Test specific glossary patterns */
export function testGlossaryPatterns() { console.log("\n=== GLOSSARY PATTERN TEST ==="); const testCases = [ // Format 1:"Term Definition" (multiple spaces)"Brunoise A small, fine dice of vegetable, approximately 1/8 inch cubes", // Format 2:"Term: Definition""Julienne: A thin, matchstick-like cut of vegetables, about 1/8 inch on each side", // Format 3:"TERM Definition""CHIFFONADE A thin ribbon cut of leafy vegetables or herbs", // Format 4: Term on one line, definition on next"Mirepoix\nA classic vegetable base of onions, carrots, and celery", // Format 5: Term - Definition"Ganache - A mixture of chocolate and cream used for icing or filling", // Format 6: Term — Definition (em dash)"Roux — A mixture of equal parts fat and flour used to thicken sauces", // Format 7: Multi-word definition"Mise en Place The practice of preparing and organizing all ingredients and equipment before cooking", ]; const results = testCases.map(testCase => { const defs = extractDefinitionsFromPdfText(testCase,"Pattern Test"); return { input: testCase.replace(/\n/g, ' | '), matches: defs.length, terms: defs.map(d => d.term), }; }); console.log("Test Results:"); results.forEach((result, i) => { const status = result.matches > 0 ?"✓" :"✗"; console.log(`${status} ${i + 1}. Matches: ${result.matches}`); if (result.matches > 0) { console.log(` Terms: ${result.terms.join(', ')}`); } console.log(` Input: ${result.input.substring(0, 80)}...`); });
} // Export for use in other modules
export default { testGlossaryExtraction, testPDFTextExtraction, testFullPDFPipeline, testGlossaryPatterns,
};
