/** * Pinecone Extraction Service * Extracts all knowledge data from Pinecone for migration to internal PostgreSQL/pgvector storage * Enables cost-effective transition from Pinecone to internal knowledge management */ let PineconeClass: any = null;
let pineconeClientInstance: any = null; async function getPineconeModule() { if (!PineconeClass) { const module = await import("@pinecone-database/pinecone"); PineconeClass = module.Pinecone; } return PineconeClass;
} const PINECONE_API_KEY = process.env.PINECONE_API_KEY ||"";
const KNOWLEDGE_INDEX ="echo-knowledge"; async function getPineconeClient() { if (!pineconeClientInstance && PINECONE_API_KEY) { const Pinecone = await getPineconeModule(); pineconeClientInstance = new Pinecone({ apiKey: PINECONE_API_KEY, }); } return pineconeClientInstance;
} export interface ExtractedPineconeItem { id: string; values: number[]; metadata: Record<string, any>;
} export interface ExtractionResult { items: ExtractedPineconeItem[]; totalItems: number; index: string; extractedAt: string;
} /** * Extract all vectors from Pinecone knowledge index * Fetches data in paginated batches to handle large datasets */
export async function extractAllPineconeKnowledge(): Promise<ExtractionResult> { if (!PINECONE_API_KEY) { throw new Error("Pinecone API key not configured"); } try { console.log("[Pinecone Extract] Starting extraction of all knowledge from Pinecone...", ); const client = await getPineconeClient(); const index = client.Index(KNOWLEDGE_INDEX); const allItems: ExtractedPineconeItem[] = []; let cursor: string | undefined; let batchCount = 0; // List all vectors using pagination do { console.log(`[Pinecone Extract] Fetching batch ${batchCount + 1}...`); const listResponse = await index.listPaginated({ limit: 100, paginationToken: cursor, }); if (!listResponse || !listResponse.vectors) { console.log("[Pinecone Extract] No more vectors to fetch"); break; } // Fetch vectors with their metadata const vectorIds = listResponse.vectors.map((v: any) => v.id); if (vectorIds.length > 0) { const fetchResponse = await index.fetch(vectorIds); if (fetchResponse && fetchResponse.records) { for (const [id, vectorData] of Object.entries( fetchResponse.records, )) { const record = vectorData as any; allItems.push({ id, values: record.values || [], metadata: record.metadata || {}, }); } } } cursor = listResponse.pagination?.next; batchCount++; console.log( `[Pinecone Extract] Batch ${batchCount} extracted: ${allItems.length} total items`, ); } while (cursor); console.log( `[Pinecone Extract] Extraction complete: ${allItems.length} total items`, ); return { items: allItems, totalItems: allItems.length, index: KNOWLEDGE_INDEX, extractedAt: new Date().toISOString(), }; } catch (error) { const errorMsg = error instanceof Error ? error.message : String(error); console.error("[Pinecone Extract] Error extracting knowledge:", errorMsg); throw error; }
} /** * Extract Pinecone vectors by filter criteria * Useful for extracting specific types of knowledge (e.g., all PDF data) */
export async function extractPineconeKnowledgeByFilter( filterCriteria: Record<string, any>,
): Promise<ExtractionResult> { if (!PINECONE_API_KEY) { throw new Error("Pinecone API key not configured"); } try { console.log("[Pinecone Extract] Extracting Pinecone knowledge with filters...", filterCriteria, ); const client = await getPineconeClient(); const index = client.Index(KNOWLEDGE_INDEX); const allItems: ExtractedPineconeItem[] = []; let pageCount = 0; // Query with the specified filters to get matching vectors const queryVector = new Array(1536).fill(0.001); // Dummy vector to get all results with filter let cursor: string | undefined; do { const queryResponse = await (index as any).query({ vector: queryVector, topK: 100, includeMetadata: true, filter: filterCriteria, paginationToken: cursor, }); if (!queryResponse || !queryResponse.matches) { break; } for (const match of queryResponse.matches) { allItems.push({ id: match.id, values: match.values || [], metadata: match.metadata || {}, }); } cursor = queryResponse.pagination?.next; pageCount++; console.log( `[Pinecone Extract] Page ${pageCount} extracted: ${allItems.length} total items`, ); } while (cursor); console.log( `[Pinecone Extract] Filtered extraction complete: ${allItems.length} items`, ); return { items: allItems, totalItems: allItems.length, index: KNOWLEDGE_INDEX, extractedAt: new Date().toISOString(), }; } catch (error) { const errorMsg = error instanceof Error ? error.message : String(error); console.error("[Pinecone Extract] Error extracting with filters:", errorMsg, ); throw error; }
} /** * Extract Pinecone vectors by source type (e.g., all PDFs) */
export async function extractPineconeKnowledgeBySourceType( sourceType: string,
): Promise<ExtractionResult> { return extractPineconeKnowledgeByFilter({ sourceType: { $eq: sourceType }, });
} /** * Extract Pinecone vectors by domain (e.g., all 'culinary' domain knowledge) */
export async function extractPineconeKnowledgeByDomain( domain: string,
): Promise<ExtractionResult> { return extractPineconeKnowledgeByFilter({ domain: { $eq: domain }, });
} /** * Get Pinecone index statistics without extracting all data */
export async function getPineconeIndexStats(): Promise<{ indexReady: boolean; dimension: number; indexSize?: number; totalVectors?: number; indexName: string;
}> { if (!PINECONE_API_KEY) { return { indexReady: false, dimension: 1536, indexName: KNOWLEDGE_INDEX, }; } try { const client = await getPineconeClient(); const index = client.Index(KNOWLEDGE_INDEX); // Describe index to get statistics const indexDescription = await (index as any).describeIndexStats(); return { indexReady: true, dimension: indexDescription.dimension || 1536, indexSize: indexDescription.indexSize, totalVectors: indexDescription.totalCount, indexName: KNOWLEDGE_INDEX, }; } catch (error) { const errorMsg = error instanceof Error ? error.message : String(error); console.error("[Pinecone Extract] Error getting index stats:", errorMsg); return { indexReady: false, dimension: 1536, indexName: KNOWLEDGE_INDEX, }; }
} /** * Count vectors in Pinecone by running a query */
export async function countPineconeVectors(): Promise<number> { if (!PINECONE_API_KEY) { return 0; } try { const client = await getPineconeClient(); const index = client.Index(KNOWLEDGE_INDEX); // Try to get all vectors count let totalCount = 0; let cursor: string | undefined; do { const listResponse = await index.listPaginated({ limit: 100, paginationToken: cursor, }); if (!listResponse || !listResponse.vectors) { break; } totalCount += listResponse.vectors.length; cursor = listResponse.pagination?.next; } while (cursor); console.log(`[Pinecone Extract] Total vectors in Pinecone: ${totalCount}`); return totalCount; } catch (error) { console.error("[Pinecone Extract] Error counting vectors:", error); return 0; }
} /** * Transform extracted Pinecone data to internal knowledge vector format */
export function transformPineconeToInternalFormat( pineconeItem: ExtractedPineconeItem,
): { title: string; content: string; description?: string; sourceType: string; categories: string[]; source: string; domain: string; metadata: { author?: string; publicationYear?: number; cuisine?: string; confidence: number; tags: string[]; relatedTerms: string[]; createdAt: string; updatedAt: string; };
} { const metadata = pineconeItem.metadata || {}; // Handle tags - could be array or comma-separated string const tagsArray = Array.isArray(metadata.tags) ? metadata.tags : typeof metadata.tags ==="string" ? metadata.tags.split(",").map((t: string) => t.trim()) : []; // Map Pinecone sourceType to valid internal types const mapSourceType = (sourceType: string | undefined): string => { if (!sourceType) return"user-imported"; const validTypes: Record<string, string> = { pdf:"pdf","master-dictionary":"master-dictionary","external-llm":"external-llm", openai:"external-llm", // Map openai to external-llm recipe:"recipe","user-imported":"user-imported","user_imported":"user-imported", pinecone:"user-imported", }; return validTypes[sourceType.toLowerCase()] ||"user-imported"; }; return { title: metadata.title ||"Untitled", content: metadata.content || metadata.description ||"", description: metadata.description, sourceType: mapSourceType(metadata.sourceType), categories: tagsArray, source: metadata.source ||"Pinecone Migration", domain: metadata.domain ||"culinary", metadata: { author: metadata.author, publicationYear: metadata.publicationYear, cuisine: metadata.cuisine, confidence: metadata.confidence || 0.85, tags: tagsArray, relatedTerms: Array.isArray(metadata.relatedTerms) ? metadata.relatedTerms : [], createdAt: metadata.createdAt || new Date().toISOString(), updatedAt: metadata.updatedAt || new Date().toISOString(), }, };
} /** * Verify Pinecone connectivity */
export async function verifyPineconeConnection(): Promise<{ connected: boolean; error?: string;
}> { if (!PINECONE_API_KEY) { return { connected: false, error:"Pinecone API key not configured", }; } try { const client = await getPineconeClient(); const index = client.Index(KNOWLEDGE_INDEX); // Try a simple query to verify connection await (index as any).query({ vector: new Array(1536).fill(0), topK: 1, includeMetadata: true, }); console.log("[Pinecone Extract] Connection verified successfully"); return { connected: true }; } catch (error) { const errorMsg = error instanceof Error ? error.message : String(error); console.error("[Pinecone Extract] Connection failed:", errorMsg); return { connected: false, error: errorMsg, }; }
}
