/** * Toast PMS Integration Connector * Syncs sales, inventory, labor, and guest data from Toast PMS * Toast is a cloud-based POS and management system for restaurants and hospitality */ import type { RequestHandler } from"express";
import { AurumDatabaseService } from "../services/aurumDatabase"; interface ToastConfig { apiUrl: string; clientId: string; clientSecret: string; entityId: string;
} interface ToastSalesData { date: string; revenue: number; covers: number; averageCheck: number; categories: Record<string, number>;
} interface ToastInventoryItem { id: string; name: string; sku: string; quantity: number; costPerUnit: number; lastUpdated: string;
} interface ToastLaborData { date: string; totalHours: number; regularHours: number; overtimeHours: number; laborCost: number; headCount: number;
} // ============================================================================
// TOAST OAUTH AUTHENTICATION
// ============================================================================ export async function authenticateToast( config: ToastConfig,
): Promise<string | null> { try { const response = await fetch(`${config.apiUrl}/oauth/token`, { method:"POST", headers: {"Content-Type":"application/json" }, body: JSON.stringify({ grant_type:"client_credentials", client_id: config.clientId, client_secret: config.clientSecret, }), }); if (!response.ok) { console.error("Toast authentication failed:", response.statusText); return null; } const data = await response.json(); return data.access_token; } catch (error) { console.error("Toast authentication error:", error); return null; }
} // ============================================================================
// FETCH SALES DATA FROM TOAST
// ============================================================================ export async function fetchToastSalesData( token: string, config: ToastConfig, startDate: string, endDate: string,
): Promise<ToastSalesData[]> { try { const response = await fetch( `${config.apiUrl}/v1/restaurants/${config.entityId}/sales?startDate=${startDate}&endDate=${endDate}`, { headers: { Authorization: `Bearer ${token}` }, }, ); if (!response.ok) { throw new Error(`Failed to fetch sales data: ${response.statusText}`); } const data = await response.json(); return data.sales || []; } catch (error) { console.error("Error fetching Toast sales data:", error); return []; }
} // ============================================================================
// FETCH INVENTORY DATA FROM TOAST
// ============================================================================ export async function fetchToastInventory( token: string, config: ToastConfig,
): Promise<ToastInventoryItem[]> { try { const response = await fetch( `${config.apiUrl}/v1/restaurants/${config.entityId}/inventory`, { headers: { Authorization: `Bearer ${token}` }, }, ); if (!response.ok) { throw new Error(`Failed to fetch inventory: ${response.statusText}`); } const data = await response.json(); return data.inventory || []; } catch (error) { console.error("Error fetching Toast inventory:", error); return []; }
} // ============================================================================
// FETCH LABOR DATA FROM TOAST
// ============================================================================ export async function fetchToastLaborData( token: string, config: ToastConfig, startDate: string, endDate: string,
): Promise<ToastLaborData[]> { try { const response = await fetch( `${config.apiUrl}/v1/restaurants/${config.entityId}/labor?startDate=${startDate}&endDate=${endDate}`, { headers: { Authorization: `Bearer ${token}` }, }, ); if (!response.ok) { throw new Error(`Failed to fetch labor data: ${response.statusText}`); } const data = await response.json(); return data.labor || []; } catch (error) { console.error("Error fetching Toast labor data:", error); return []; }
} // ============================================================================
// SYNC TOAST SALES TO AURUM
// ============================================================================ export const handleSyncToastSales: RequestHandler = async (req, res) => { const { startDate, endDate, entityId } = req.body; if (!startDate || !endDate) { return res.status(400).json({ error:"Missing startDate or endDate" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; const toastConfig: ToastConfig = { apiUrl: process.env.TOAST_API_URL ||"https://api.toasttab.com", clientId: process.env.TOAST_CLIENT_ID ||"", clientSecret: process.env.TOAST_CLIENT_SECRET ||"", entityId: entityId || process.env.TOAST_ENTITY_ID ||"", }; // Authenticate with Toast const token = await authenticateToast(toastConfig); if (!token) { return res .status(401) .json({ error:"Failed to authenticate with Toast" }); } // Fetch sales data const salesData = await fetchToastSalesData( token, toastConfig, startDate, endDate, ); // Store in database for (const sale of salesData) { await db.pool.query( `INSERT INTO toast_sales (date, revenue, covers, averageCheck, categories, entityId, createdAt) VALUES ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT (date, entityId) DO UPDATE SET revenue = EXCLUDED.revenue, covers = EXCLUDED.covers, averageCheck = EXCLUDED.averageCheck, categories = EXCLUDED.categories`, [ sale.date, sale.revenue, sale.covers, sale.averageCheck, JSON.stringify(sale.categories), entityId ||"default", new Date().toISOString(), ], ); } return res.json({ synced: salesData.length, period: { startDate, endDate }, message: `Successfully synced ${salesData.length} sales records from Toast`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to sync Toast sales"; res.status(500).json({ error: message }); }
}; // ============================================================================
// SYNC TOAST INVENTORY TO AURUM
// ============================================================================ export const handleSyncToastInventory: RequestHandler = async (req, res) => { const { entityId } = req.body; try { const db = req.app.get("aurumDb") as AurumDatabaseService; const toastConfig: ToastConfig = { apiUrl: process.env.TOAST_API_URL ||"https://api.toasttab.com", clientId: process.env.TOAST_CLIENT_ID ||"", clientSecret: process.env.TOAST_CLIENT_SECRET ||"", entityId: entityId || process.env.TOAST_ENTITY_ID ||"", }; // Authenticate with Toast const token = await authenticateToast(toastConfig); if (!token) { return res .status(401) .json({ error:"Failed to authenticate with Toast" }); } // Fetch inventory const inventory = await fetchToastInventory(token, toastConfig); // Store in database for (const item of inventory) { await db.pool.query( `INSERT INTO toast_inventory (toastId, name, sku, quantity, costPerUnit, entityId, lastUpdated) VALUES ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT (toastId, entityId) DO UPDATE SET quantity = EXCLUDED.quantity, costPerUnit = EXCLUDED.costPerUnit, lastUpdated = EXCLUDED.lastUpdated`, [ item.id, item.name, item.sku, item.quantity, item.costPerUnit, entityId ||"default", new Date().toISOString(), ], ); } return res.json({ synced: inventory.length, message: `Successfully synced ${inventory.length} inventory items from Toast`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to sync Toast inventory"; res.status(500).json({ error: message }); }
}; // ============================================================================
// SYNC TOAST LABOR TO AURUM
// ============================================================================ export const handleSyncToastLabor: RequestHandler = async (req, res) => { const { startDate, endDate, entityId } = req.body; if (!startDate || !endDate) { return res.status(400).json({ error:"Missing startDate or endDate" }); } try { const db = req.app.get("aurumDb") as AurumDatabaseService; const toastConfig: ToastConfig = { apiUrl: process.env.TOAST_API_URL ||"https://api.toasttab.com", clientId: process.env.TOAST_CLIENT_ID ||"", clientSecret: process.env.TOAST_CLIENT_SECRET ||"", entityId: entityId || process.env.TOAST_ENTITY_ID ||"", }; // Authenticate with Toast const token = await authenticateToast(toastConfig); if (!token) { return res .status(401) .json({ error:"Failed to authenticate with Toast" }); } // Fetch labor data const laborData = await fetchToastLaborData( token, toastConfig, startDate, endDate, ); // Store in database for (const labor of laborData) { await db.pool.query( `INSERT INTO toast_labor (date, totalHours, regularHours, overtimeHours, laborCost, headCount, entityId, createdAt) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT (date, entityId) DO UPDATE SET totalHours = EXCLUDED.totalHours, regularHours = EXCLUDED.regularHours, overtimeHours = EXCLUDED.overtimeHours, laborCost = EXCLUDED.laborCost, headCount = EXCLUDED.headCount`, [ labor.date, labor.totalHours, labor.regularHours, labor.overtimeHours, labor.laborCost, labor.headCount, entityId ||"default", new Date().toISOString(), ], ); } return res.json({ synced: laborData.length, period: { startDate, endDate }, message: `Successfully synced ${laborData.length} labor records from Toast`, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to sync Toast labor"; res.status(500).json({ error: message }); }
}; // ============================================================================
// GET TOAST SYNC STATUS
// ============================================================================ export const handleGetToastSyncStatus: RequestHandler = async (req, res) => { const { entityId } = req.query; try { const db = req.app.get("aurumDb") as AurumDatabaseService; const salesResult = await db.pool.query("SELECT COUNT(*) as count, MAX(date) as lastSync FROM toast_sales WHERE entityId = $1", [entityId ||"default"], ); const inventoryResult = await db.pool.query( 'SELECT COUNT(*) as count, MAX("lastUpdated") as lastSync FROM toast_inventory WHERE entityId = $1', [entityId ||"default"], ); const laborResult = await db.pool.query("SELECT COUNT(*) as count, MAX(date) as lastSync FROM toast_labor WHERE entityId = $1", [entityId ||"default"], ); return res.json({ sales: { records: salesResult.rows[0]?.count || 0, lastSync: salesResult.rows[0]?.lastSync || null, }, inventory: { records: inventoryResult.rows[0]?.count || 0, lastSync: inventoryResult.rows[0]?.lastSync || null, }, labor: { records: laborResult.rows[0]?.count || 0, lastSync: laborResult.rows[0]?.lastSync || null, }, }); } catch (error) { const message = error instanceof Error ? error.message :"Failed to get sync status"; res.status(500).json({ error: message }); }
};
