/** * EchoAurum Decision Engine * Core financial AI that evaluates options and explains reasoning * Integrates all math engines (NPV, Monte Carlo, Portfolio, Risk metrics) */ import type { DecisionRequest, DecisionResponse, ScenarioResult, ScenarioInput, RiskLevel, AurumObjective
} from '../types/aurum-types';
import { npv, irr, profitabilityIndex, eva } from '../math/npv_irr';
import { simulateScenarioNPV } from '../math/simulation';
import { sharpeRatio, valueAtRisk, downsideDeviation, maxDrawdown } from '../math/risk_metrics'; /** * Classify risk level based on volatility */
function classifyRiskLevel(stdDev: number): RiskLevel { if (stdDev < 0.05) return 'low'; if (stdDev < 0.10) return 'medium'; if (stdDev < 0.20) return 'high'; return 'severe';
} /** * Evaluate a single scenario * Calculates NPV, IRR, risk metrics, and confidence */
export function evaluateScenario(scenario: ScenarioInput): ScenarioResult { try { // Base valuation const baseNPV = npv(scenario.discountRate, scenario.cashFlows); const irrVal = irr(scenario.cashFlows); const profIndex = profitabilityIndex(scenario.discountRate, scenario.cashFlows); // Monte Carlo simulation for risk analysis const stats = simulateScenarioNPV(scenario, 2000); const riskLevel = classifyRiskLevel(stats.stdDev); // Calculate risk metrics const sharpe = sharpeRatio(stats.mean, 0.02, stats.stdDev); const var5 = valueAtRisk([stats.mean], 0.05); const downsideRisk = stats.percentile5 ?? stats.mean - stats.stdDev; // Upside potential const upsideCapture = stats.percentile95 ? (stats.percentile95 - stats.mean) / stats.mean : 0; // Confidence: higher if low volatility, higher if positive NPV let confidence = 0.7; if (baseNPV > 0) confidence += 0.1; if (stats.stdDev < 0.1) confidence += 0.1; if (confidence > 1) confidence = 1; return { scenarioName: scenario.name, npv: baseNPV, irr: irrVal, profitabilityIndex: profIndex, riskLevel, downsideRisk, upsideCapture, monteCarlo: stats, confidence, notes: [] }; } catch (error) { console.error(`Error evaluating scenario ${scenario.name}:`, error); return { scenarioName: scenario.name, npv: 0, riskLevel: 'severe', monteCarlo: { mean: 0, stdDev: 0 }, confidence: 0, notes: [`Error evaluating scenario: ${error instanceof Error ? error.message : 'Unknown error'}`] }; }
} /** * Score an option based on decision objective */
function scoreOption( result: ScenarioResult, objective: AurumObjective, riskTolerance: RiskLevel
): number { let score = 0; switch (objective) { case 'maximize_npv': score = result.npv; break; case 'maximize_risk_adjusted_return': // Return per unit of risk if (result.monteCarlo && result.monteCarlo.stdDev > 0) { score = result.monteCarlo.mean / result.monteCarlo.stdDev; } else { score = result.npv; } break; case 'minimize_volatility': // Lower volatility = higher score (negative because we minimize) if (result.monteCarlo) { score = -result.monteCarlo.stdDev; } break; case 'maximize_long_term_value': // Blend of NPV and stability (lower volatility is better) const npvComponent = result.npv * 0.6; const stabilityBonus = result.monteCarlo ? (1 / (1 + result.monteCarlo.stdDev)) * 0.4 : 0.4; score = npvComponent + stabilityBonus; break; case 'balance_growth_stability': // Sharpe-like: return per volatility if (result.monteCarlo && result.monteCarlo.stdDev > 0) { score = result.monteCarlo.mean / (1 + result.monteCarlo.stdDev); } else { score = result.npv * 0.5; } break; } // Risk tolerance penalty // If option's risk is too high for tolerance, penalize heavily const riskPenalty = getRiskPenalty(result.riskLevel, riskTolerance); score *= 1 - riskPenalty; return score;
} /** * Calculate penalty for mismatched risk tolerance */
function getRiskPenalty(actualRisk: RiskLevel, tolerance: RiskLevel): number { const riskLevels = { low: 0, medium: 1, high: 2, severe: 3 }; const actualIdx = riskLevels[actualRisk]; const toleranceIdx = riskLevels[tolerance]; const diff = actualIdx - toleranceIdx; if (diff <= 0) return 0; // Risk is acceptable if (diff === 1) return 0.2; // Slightly risky if (diff === 2) return 0.5; // Moderately risky return 0.8; // Much too risky
} /** * Main decision evaluation function * Evaluates all options and ranks them */
export function evaluateDecision(request: DecisionRequest): DecisionResponse { const scenarioSummaries: Record<string, ScenarioResult> = {}; const scores: { optionId: string; score: number; reason?: string }[] = []; // Evaluate each option for (const option of request.options) { const result = evaluateScenario(option.scenario); scenarioSummaries[option.id] = result; const score = scoreOption(result, request.objective, request.riskTolerance); scores.push({ optionId: option.id, score, reason: buildScoreReason(result, request.objective) }); } // Rank by score scores.sort((a, b) => b.score - a.score); const best = scores[0]; // Build explanation const explanation = buildExplanation( request, scenarioSummaries, scores, request.options ); // Calculate average confidence across all scenarios const avgConfidence = Object.values(scenarioSummaries).reduce((sum, s) => sum + s.confidence, 0) / Object.keys(scenarioSummaries).length; return { requestId: request.id, bestOptionId: best.optionId, ranking: scores, scenarioSummaries, explanation, assumptions: buildAssumptions(request), confidence: Math.min(avgConfidence, 0.95), timestamp: new Date().toISOString() };
} /** * Build human-readable explanation for score */
function buildScoreReason(result: ScenarioResult, objective: AurumObjective): string { switch (objective) { case 'maximize_npv': return `NPV of $${result.npv?.toFixed(0) ?? '0'} with ${result.riskLevel} risk`; case 'maximize_risk_adjusted_return': return `Strong risk-adjusted return with ${result.riskLevel} risk`; case 'minimize_volatility': return `Volatility of ${result.monteCarlo?.stdDev.toFixed(1) ?? 'unknown'}% offers stability`; case 'maximize_long_term_value': return `Balanced approach: $${result.npv?.toFixed(0) ?? '0'} with manageable risk`; case 'balance_growth_stability': return `Good growth-risk balance`; default: return 'Evaluated objectively'; }
} /** * Build structured explanation of the decision */
function buildExplanation( request: DecisionRequest, scenarioSummaries: Record<string, ScenarioResult>, scores: { optionId: string; score: number; reason?: string }[], options: any[]
): any[] { const steps = []; // Step 1: Objective statement steps.push({ label: 'Decision Objective', details: `Analyzed ${request.options.length} options optimizing for"${request.objective .replace(/_/g, ' ') .toLowerCase()}" with ${request.riskTolerance} risk tolerance.` }); // Step 2: Best option rationale const best = scores[0]; const bestScenario = scenarioSummaries[best.optionId]; const bestOption = options.find(o => o.id === best.optionId); steps.push({ label: 'Recommended Option', details: `"${bestOption?.label || best.optionId}" is the optimal choice because it offers the best balance of ${request.objective .replace(/_/g, ' ') .toLowerCase()}.`, supportingData: { npv: bestScenario.npv, riskLevel: bestScenario.riskLevel, confidence: bestScenario.confidence } }); // Step 3: Risk analysis steps.push({ label: 'Risk Assessment', details: `The recommended option carries ${bestScenario.riskLevel} risk. Monte Carlo simulations show ${bestScenario.monteCarlo?.percentile5 ? `a 95% chance of returns above $${bestScenario.monteCarlo.percentile5.toFixed(0)}` : 'variable outcomes'}.` }); // Step 4: Comparative analysis if (scores.length > 1) { const second = scores[1]; const secondScenario = scenarioSummaries[second.optionId]; const improvement = ((best.score - second.score) / Math.abs(second.score)) * 100; steps.push({ label: 'Why Not The Alternative?', details: `The second-ranked option offers similar characteristics but scores ${improvement.toFixed( 0 )}% lower on your objective function.` }); } // Step 5: Key assumptions steps.push({ label: 'Critical Assumptions', details: 'This analysis assumes the provided cash flows, volatility, and discount rates are accurate. Market conditions or unexpected events could materially affect outcomes.' }); return steps;
} /** * Build assumption statements */
function buildAssumptions(request: DecisionRequest): string[] { const assumptions = [ 'Cash flows and discount rates are estimated accurately.', 'Market conditions remain stable during the investment period.', 'No major regulatory or tax law changes occur.', 'Historical volatility is representative of future volatility.' ]; if (request.assumptions) { assumptions.push(...request.assumptions); } if (request.timeHorizon) { assumptions.push( `Analysis covers a ${request.timeHorizon}-year time horizon.` ); } return assumptions;
} /** * Sensitivity Analysis * Shows how outcome changes with different assumptions */
export function sensitivityAnalysis( scenario: ScenarioInput, variableField: keyof ScenarioInput, variations = [0.8, 0.9, 1, 1.1, 1.2]
) { const results = []; for (const factor of variations) { const modified = { ...scenario }; const baseValue = scenario[variableField]; if (typeof baseValue === 'number') { (modified as any)[variableField] = baseValue * factor; } const result = evaluateScenario(modified); results.push({ parameterValue: baseValue, multiplier: factor, npv: result.npv, irr: result.irr }); } return results;
}
