import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { getSupabaseServiceClient } from '../lib/supabase';
import { logger, sanitizeError } from '../lib/logger';
import { validateRequest, UUIDSchema } from '../middleware/validation';
import { paginationMiddleware, applyPaginationRange, buildPaginatedResponse, countTotal } from '../middleware/pagination';
import { dynamicPricingEngine } from '../lib/dynamic-pricing-engine'; const router = Router(); const getClient = () => getSupabaseServiceClient(); // ============================================================================
// PRICE RECOMMENDATIONS
// ============================================================================ /** * GET /price-recommendations * Get AI-powered menu price recommendations for an outlet */
router.get( '/price-recommendations', validateRequest({ query: z.object({ organization_id: UUIDSchema, outlet_id: UUIDSchema, }), }), async (req: Request, res: Response) => { try { const { organization_id, outlet_id } = req.query as { organization_id: string; outlet_id: string; }; const recommendations = await dynamicPricingEngine.recommendMenuPrices( organization_id, outlet_id, ); // Calculate summary stats const highImpact = recommendations.filter(r => Math.abs(r.priceChangePercent) > 5); const avgConfidence = recommendations.length > 0 ? recommendations.reduce((sum, r) => sum + r.confidence, 0) / recommendations.length : 0; const totalPotentialRevenue = recommendations.reduce((sum, r) => sum + r.potentialRevenueLift, 0); res.json({ organization_id, outlet_id, timestamp: new Date().toISOString(), summary: { total_items: recommendations.length, high_impact_count: highImpact.length, avg_confidence: Number(avgConfidence.toFixed(2)), total_potential_revenue_lift: Number(totalPotentialRevenue.toFixed(2)), }, recommendations: recommendations.slice(0, 20), // Top 20 }); } catch (error) { logger.error('GET /price-recommendations failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); /** * GET /price-recommendations/:itemId * Get specific price recommendation for menu item */
router.get( '/price-recommendations/:itemId', validateRequest({ params: z.object({ itemId: UUIDSchema }), query: z.object({ organization_id: UUIDSchema, outlet_id: UUIDSchema, }), }), async (req: Request, res: Response) => { try { const { itemId } = req.params; const { organization_id, outlet_id } = req.query as { organization_id: string; outlet_id: string; }; const recommendations = await dynamicPricingEngine.recommendMenuPrices( organization_id, outlet_id, ); const recommendation = recommendations.find(r => r.menuItemId === itemId); if (!recommendation) { return res.status(404).json({ error: 'Price recommendation not found' }); } res.json(recommendation); } catch (error) { logger.error('GET /price-recommendations/:itemId failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// COST SPIKE DETECTION
// ============================================================================ /** * GET /cost-spikes * Detect ingredient cost spikes and margin threats */
router.get( '/cost-spikes', validateRequest({ query: z.object({ organization_id: UUIDSchema, outlet_id: UUIDSchema, threshold: z.string().default('5').transform(v => parseInt(v)), }), }), async (req: Request, res: Response) => { try { const { organization_id, outlet_id, threshold } = req.query as { organization_id: string; outlet_id: string; threshold: number; }; const spikes = await dynamicPricingEngine.detectCostSpikes( organization_id, outlet_id, threshold, ); const critical = spikes.filter(s => s.marginThresholdBreached); const avgPriceChange = spikes.length > 0 ? spikes.reduce((sum, s) => sum + Math.abs(s.priceChangePercent), 0) / spikes.length : 0; res.json({ organization_id, outlet_id, timestamp: new Date().toISOString(), summary: { total_spikes: spikes.length, critical_alerts: critical.length, avg_price_change_percent: Number(avgPriceChange.toFixed(2)), }, spikes: spikes.sort((a, b) => Math.abs(b.priceChangePercent) - Math.abs(a.priceChangePercent)), }); } catch (error) { logger.error('GET /cost-spikes failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// A/B TESTING
// ============================================================================ /** * POST /ab-tests * Create a new price A/B test */
router.post( '/ab-tests', validateRequest({ body: z.object({ organization_id: UUIDSchema, outlet_id: UUIDSchema, menu_item_id: UUIDSchema, control_price: z.number().positive(), test_price: z.number().positive(), duration_days: z.number().int().positive().default(7), }), }), async (req: Request, res: Response) => { try { const { organization_id, outlet_id, menu_item_id, control_price, test_price, duration_days, } = req.body; const abTest = await dynamicPricingEngine.runABTest( organization_id, outlet_id, menu_item_id, control_price, test_price, duration_days, ); logger.info('A/B test created', { testId: abTest.id, menuItemId: menu_item_id, controlPrice: control_price, testPrice: test_price, }); res.status(201).json(abTest); } catch (error) { logger.error('POST /ab-tests failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); /** * GET /ab-tests * Get active and completed A/B tests */
router.get( '/ab-tests', paginationMiddleware, validateRequest({ query: z.object({ organization_id: UUIDSchema, outlet_id: UUIDSchema, status: z.enum(['active', 'completed', 'all']).default('active'), }), }), async (req: Request, res: Response) => { try { const supabase = getClient(); const pagination = res.locals.pagination; const { organization_id, outlet_id, status } = req.query as { organization_id: string; outlet_id: string; status: string; }; let query = supabase .from('ab_tests') .select('*') .eq('organization_id', organization_id) .eq('outlet_id', outlet_id); if (status !== 'all') { query = query.eq('status', status); } const { data, error } = await applyPaginationRange( query.order('start_date', { ascending: false }), pagination, ); if (error) throw error; // Get total count let countQuery = supabase .from('ab_tests') .select('id', { count: 'exact', head: true }) .eq('organization_id', organization_id) .eq('outlet_id', outlet_id); if (status !== 'all') { countQuery = countQuery.eq('status', status); } const total = await countTotal(countQuery); res.json( buildPaginatedResponse(data || [], total, pagination.limit, pagination.offset), ); } catch (error) { logger.error('GET /ab-tests failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); /** * PATCH /ab-tests/:testId * Update A/B test results */
router.patch( '/ab-tests/:testId', validateRequest({ params: z.object({ testId: UUIDSchema }), body: z.object({ control_sales: z.number().optional(), test_sales: z.number().optional(), control_revenue: z.number().optional(), test_revenue: z.number().optional(), status: z.enum(['active', 'completed', 'cancelled']).optional(), }), }), async (req: Request, res: Response) => { try { const supabase = getClient(); const { testId } = req.params; const { data, error } = await supabase .from('ab_tests') .update(req.body) .eq('id', testId) .select() .single(); if (error) throw error; logger.info('A/B test updated', { testId }); res.json(data); } catch (error) { logger.error('PATCH /ab-tests/:testId failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// PROFITABILITY TRACKING
// ============================================================================ /** * GET /profitability * Get profitability metrics for all menu items */
router.get( '/profitability', validateRequest({ query: z.object({ organization_id: UUIDSchema, outlet_id: UUIDSchema, }), }), async (req: Request, res: Response) => { try { const { organization_id, outlet_id } = req.query as { organization_id: string; outlet_id: string; }; const metrics = await dynamicPricingEngine.trackProfitability( organization_id, outlet_id, ); // Calculate summary stats const totalWeeklyProfit = metrics.reduce((sum, m) => sum + m.weeklyProfit, 0); const avgMarginPercent = metrics.length > 0 ? metrics.reduce((sum, m) => sum + m.marginPercent, 0) / metrics.length : 0; const increasingTrend = metrics.filter(m => m.trend === 'increasing').length; const decreasingTrend = metrics.filter(m => m.trend === 'decreasing').length; res.json({ organization_id, outlet_id, timestamp: new Date().toISOString(), summary: { total_items: metrics.length, total_weekly_profit: Number(totalWeeklyProfit.toFixed(2)), avg_margin_percent: Number(avgMarginPercent.toFixed(1)), items_with_increasing_trend: increasingTrend, items_with_decreasing_trend: decreasingTrend, }, metrics: metrics.slice(0, 30), // Top 30 by profit }); } catch (error) { logger.error('GET /profitability failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); /** * GET /profitability/:itemId * Get profitability metrics for specific menu item */
router.get( '/profitability/:itemId', validateRequest({ params: z.object({ itemId: UUIDSchema }), query: z.object({ organization_id: UUIDSchema, outlet_id: UUIDSchema, }), }), async (req: Request, res: Response) => { try { const { itemId } = req.params; const { organization_id, outlet_id } = req.query as { organization_id: string; outlet_id: string; }; const metrics = await dynamicPricingEngine.trackProfitability( organization_id, outlet_id, ); const itemMetrics = metrics.find(m => m.menuItemId === itemId); if (!itemMetrics) { return res.status(404).json({ error: 'Menu item profitability not found' }); } res.json(itemMetrics); } catch (error) { logger.error('GET /profitability/:itemId failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// POS INTEGRATION (Toast/Square)
// ============================================================================ /** * POST /sync-prices-to-pos * Sync recommended prices to POS system (Toast/Square) */
router.post( '/sync-prices-to-pos', validateRequest({ body: z.object({ organization_id: UUIDSchema, outlet_id: UUIDSchema, menu_item_ids: z.array(UUIDSchema), pos_system: z.enum(['toast', 'square', 'other']), }), }), async (req: Request, res: Response) => { try { const { organization_id, outlet_id, menu_item_ids, pos_system } = req.body; logger.info('Price sync to POS initiated', { organization_id, outlet_id, pos_system, itemCount: menu_item_ids.length, }); // In production, would call Toast/Square API here // For now, just log and return success res.json({ organization_id, outlet_id, pos_system, timestamp: new Date().toISOString(), status: 'sync_initiated', items_count: menu_item_ids.length, message: `Price sync to ${pos_system} initiated. Check status in POS system.`, }); } catch (error) { logger.error('POST /sync-prices-to-pos failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); export default router;
