import { Router, Request, Response } from 'express';
import { exceptionResolver } from '../lib/exception-resolver';
import { logger } from '../lib/logger';
import { z } from 'zod'; const router = Router(); // Validation schemas
const ResolveExceptionSchema = z.object({ exceptionId: z.string().uuid(), resolutionMethod: z.string(), notes: z.string().optional(),
}); const CreateRuleSchema = z.object({ organizationId: z.string().uuid(), exceptionType: z.string(), condition: z.string(), autoResolveThreshold: z.number().optional(), resolutionAction: z.string(),
}); const SetThresholdsSchema = z.object({ organizationId: z.string().uuid(), outletId: z.string().uuid().optional(), priceVariancePercent: z.number().positive().optional(), quantityVariancePercent: z.number().positive().optional(), deadlineDaysBuffer: z.number().int().positive().optional(),
}); // Detect exceptions
router.post('/detect/:organizationId/:outletId', async (req: Request, res: Response) => { try { const { organizationId, outletId } = req.params; const exceptions = await exceptionResolver.detectExceptions( organizationId, outletId, ); logger.info('Exceptions detected', { outletId, count: exceptions.length, }); res.json(exceptions); } catch (error) { logger.error('Failed to detect exceptions', error); res.status(500).json({ error: 'Failed to detect exceptions' }); }
}); // Auto-resolve exceptions
router.post('/auto-resolve/:organizationId/:outletId', async (req: Request, res: Response) => { try { const { organizationId, outletId } = req.params; const result = await exceptionResolver.autoResolveExceptions( organizationId, outletId, ); logger.info('Auto-resolution executed', result); res.json(result); } catch (error) { logger.error('Failed to auto-resolve exceptions', error); res.status(500).json({ error: 'Failed to auto-resolve exceptions' }); }
}); // Get open exceptions
router.get('/open/:organizationId', async (req: Request, res: Response) => { try { const { organizationId } = req.params; const { outletId } = req.query; const exceptions = await exceptionResolver.getOpenExceptions( organizationId, outletId as string, ); res.json(exceptions); } catch (error) { logger.error('Failed to fetch open exceptions', error); res.status(500).json({ error: 'Failed to fetch exceptions' }); }
}); // Manually resolve exception
router.post('/resolve', async (req: Request, res: Response) => { try { const { exceptionId, resolutionMethod, notes } = ResolveExceptionSchema.parse(req.body); const userId = req.user?.id; if (!userId) { return res.status(401).json({ error: 'Unauthorized' }); } // Update exception in database const { error } = await (req as any).supabase .from('exceptions') .update({ status: 'manual_resolved', resolution_notes: notes, resolved_by: userId, resolved_at: new Date().toISOString(), updated_at: new Date().toISOString(), }) .eq('id', exceptionId); if (error) { logger.error('Failed to resolve exception', error); throw error; } // Log resolution await (req as any).supabase.from('exception_resolutions').insert({ id: crypto.randomUUID(), exception_id: exceptionId, organization_id: req.user?.organization_id, resolution_method: resolutionMethod, resolved_by: userId, notes, manual_override: true, created_at: new Date().toISOString(), }); logger.info('Exception resolved manually', { exceptionId }); res.json({ success: true }); } catch (error) { logger.error('Failed to resolve exception', error); if (error instanceof z.ZodError) { return res.status(400).json({ error: error.errors }); } res.status(500).json({ error: 'Failed to resolve exception' }); }
}); // Create auto-resolution rule
router.post('/rules', async (req: Request, res: Response) => { try { const { organizationId, exceptionType, condition, autoResolveThreshold, resolutionAction, } = CreateRuleSchema.parse(req.body); const userId = req.user?.id; const { data, error } = await (req as any).supabase .from('exception_rules') .insert({ id: crypto.randomUUID(), organization_id: organizationId, exception_type: exceptionType, condition, auto_resolve_threshold: autoResolveThreshold, resolution_action: resolutionAction, enabled: true, created_by: userId, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), }) .select() .single(); if (error) { logger.error('Failed to create rule', error); throw error; } logger.info('Exception rule created', { exceptionType }); res.json(data); } catch (error) { logger.error('Failed to create rule', error); if (error instanceof z.ZodError) { return res.status(400).json({ error: error.errors }); } res.status(500).json({ error: 'Failed to create rule' }); }
}); // Set variance thresholds
router.post('/thresholds', async (req: Request, res: Response) => { try { const { organizationId, outletId, priceVariancePercent, quantityVariancePercent, deadlineDaysBuffer, } = SetThresholdsSchema.parse(req.body); const userId = req.user?.id; const { error } = await (req as any).supabase .from('variance_thresholds') .upsert({ id: crypto.randomUUID(), organization_id: organizationId, outlet_id: outletId, price_variance_percent: priceVariancePercent, quantity_variance_percent: quantityVariancePercent, deadline_days_buffer: deadlineDaysBuffer, created_by: userId, updated_at: new Date().toISOString(), }); if (error) { logger.error('Failed to set thresholds', error); throw error; } logger.info('Variance thresholds updated', { organizationId, outletId }); res.json({ success: true }); } catch (error) { logger.error('Failed to set thresholds', error); if (error instanceof z.ZodError) { return res.status(400).json({ error: error.errors }); } res.status(500).json({ error: 'Failed to set thresholds' }); }
}); export const exceptionResolutionRouter = router;
