import { Router, Request, Response } from "express";
import { z } from "zod";
import { getSupabaseServiceClient } from "../lib/supabase";
import { applyPaginationRange, buildPaginatedResponse } from "../middleware/pagination";
import { getGLSuggestionEngine } from "../lib/gl-suggestion-engine";
import { getChartOfAccounts } from "../lib/chart-of-accounts"; const router = Router();
const supabase = getSupabaseServiceClient(); // ============================================================================
// INVOICE EXTRACTION & PROCESSING ENDPOINTS
// ============================================================================ const extractionResultSchema = z.object({ organizationId: z.string().uuid(), invoiceId: z.string().uuid(), extractionMethod: z.enum(["ocr","api","manual","edi"]), ocrConfidenceOverall: z.number().optional(), extractedNumber: z.string().optional(), extractedDate: z.string().optional(), extractedVendorName: z.string().optional(), extractedSubtotal: z.number().optional(), extractedTax: z.number().optional(), extractedTotal: z.number().optional(), extractedLineCount: z.number().optional(),
}); router.post("/extractions", async (req: Request, res: Response) => { try { const validated = extractionResultSchema.parse(req.body); const userId = req.headers["x-user-id"] as string; const { data, error } = await supabase .from("invoice_extraction_results") .insert({ organization_id: validated.organizationId, invoice_id: validated.invoiceId, extraction_method: validated.extractionMethod, ocr_confidence_overall: validated.ocrConfidenceOverall, extracted_number: validated.extractedNumber, extracted_date: validated.extractedDate, extracted_vendor_name: validated.extractedVendorName, extracted_subtotal: validated.extractedSubtotal, extracted_tax: validated.extractedTax, extracted_total: validated.extractedTotal, extracted_line_count: validated.extractedLineCount, line_extraction_status:"pending", }) .select() .single(); if (error) throw error; res.status(201).json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.get("/extractions", async (req: Request, res: Response) => { try { const { limit ="50", offset ="0", invoiceId, status } = req.query; let query = supabase .from("invoice_extraction_results") .select( ` id, invoice_id, extraction_timestamp, extraction_method, ocr_confidence_overall, extracted_number, extracted_date, extracted_total, extracted_line_count, line_extraction_status, variance_detected, created_at, invoices (number, vendor_id, vendors(name)) `, { count:"exact" } ) .order("created_at", { ascending: false }); if (invoiceId) query = query.eq("invoice_id", invoiceId); if (status) query = query.eq("line_extraction_status", status); const { from, to } = applyPaginationRange(Number(limit), Number(offset)); const { data, count, error } = await query.range(from, to); if (error) throw error; res.json( buildPaginatedResponse(data || [], Number(limit), Number(offset), count || 0) ); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); // ============================================================================
// GL ALLOCATION ENDPOINTS
// ============================================================================ const glAllocationSchema = z.object({ organizationId: z.string().uuid(), invoiceId: z.string().uuid(), invoiceLineId: z.string().uuid().optional(), outletId: z.string().uuid(), glCodeId: z.string().uuid(), allocationType: z.enum(["invoice_line","proportional","manual","auto_mapped"]), allocatedAmount: z.number().finite(), allocationPercentage: z.number().optional(), itemId: z.string().uuid().optional(), quantity: z.number().optional(), notes: z.string().optional(),
}); router.post("/allocations", async (req: Request, res: Response) => { try { const validated = glAllocationSchema.parse(req.body); const userId = req.headers["x-user-id"] as string; // Get GL code details const { data: glCode } = await supabase .from("gl_codes") .select("code") .eq("id", validated.glCodeId) .single(); const { data, error } = await supabase .from("invoice_gl_allocations") .insert({ organization_id: validated.organizationId, invoice_id: validated.invoiceId, invoice_line_id: validated.invoiceLineId || null, outlet_id: validated.outletId, gl_code_id: validated.glCodeId, gl_code: glCode?.code ||"", allocation_type: validated.allocationType, allocated_amount: validated.allocatedAmount, allocation_percentage: validated.allocationPercentage, item_id: validated.itemId || null, quantity: validated.quantity, posting_status:"pending", notes: validated.notes, }) .select() .single(); if (error) throw error; // Queue for GL posting await supabase.from("invoice_gl_posting_queue").insert({ organization_id: validated.organizationId, invoice_id: validated.invoiceId, allocation_id: data.id, post_period: new Date().toISOString().slice(0, 7), status:"pending", }); res.status(201).json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.get("/allocations", async (req: Request, res: Response) => { try { const { limit ="50", offset ="0", invoiceId, outletId, status } = req.query; let query = supabase .from("invoice_gl_allocations") .select( ` id, invoice_id, outlet_id, gl_code_id, gl_code, allocation_type, allocated_amount, posting_status, created_at, invoices (number), outlets (name), gl_codes (code, description) `, { count:"exact" } ) .order("created_at", { ascending: false }); if (invoiceId) query = query.eq("invoice_id", invoiceId); if (outletId) query = query.eq("outlet_id", outletId); if (status) query = query.eq("posting_status", status); const { from, to } = applyPaginationRange(Number(limit), Number(offset)); const { data, count, error } = await query.range(from, to); if (error) throw error; res.json( buildPaginatedResponse(data || [], Number(limit), Number(offset), count || 0) ); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); // ============================================================================
// VARIANCE TRACKING ENDPOINTS
// ============================================================================ const varianceSchema = z.object({ organizationId: z.string().uuid(), invoiceId: z.string().uuid(), varianceType: z.enum(["line_count","total_amount","tax_calculation","sku_mismatch","quantity_variance","price_variance","duplicate","missing_item", ]), severity: z.enum(["low","medium","high","critical"]), expectedValue: z.number().optional(), actualValue: z.number().optional(), varianceAmount: z.number().optional(), description: z.string(),
}); router.post("/variances", async (req: Request, res: Response) => { try { const validated = varianceSchema.parse(req.body); const { data, error } = await supabase .from("invoice_variance_tracking") .insert({ organization_id: validated.organizationId, invoice_id: validated.invoiceId, variance_type: validated.varianceType, severity: validated.severity, expected_value: validated.expectedValue, actual_value: validated.actualValue, variance_amount: validated.varianceAmount, variance_percentage: validated.expectedValue && validated.varianceAmount ? (validated.varianceAmount / validated.expectedValue) * 100 : null, description: validated.description, requires_manual_review: validated.severity ==="high" || validated.severity ==="critical", }) .select() .single(); if (error) throw error; res.status(201).json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.get("/variances", async (req: Request, res: Response) => { try { const { limit ="50", offset ="0", invoiceId, severity, reviewed } = req.query; let query = supabase .from("invoice_variance_tracking") .select( ` id, invoice_id, variance_type, severity, expected_value, actual_value, variance_amount, variance_percentage, description, requires_manual_review, reviewed_at, created_at, invoices (number, vendor_id, vendors(name)) `, { count:"exact" } ) .order("created_at", { ascending: false }); if (invoiceId) query = query.eq("invoice_id", invoiceId); if (severity) query = query.eq("severity", severity); if (reviewed ==="false") { query = query.is("reviewed_at", null); } else if (reviewed ==="true") { query = query.not("reviewed_at","is", null); } const { from, to } = applyPaginationRange(Number(limit), Number(offset)); const { data, count, error } = await query.range(from, to); if (error) throw error; res.json( buildPaginatedResponse(data || [], Number(limit), Number(offset), count || 0) ); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.patch("/variances/:id/review", async (req: Request, res: Response) => { try { const { id } = req.params; const { notes } = req.body; const userId = req.headers["x-user-id"] as string; const { data, error } = await supabase .from("invoice_variance_tracking") .update({ reviewed_at: new Date().toISOString(), reviewed_by: userId, resolution_notes: notes, }) .eq("id", id) .select() .single(); if (error) throw error; res.json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); // ============================================================================
// APPROVAL WORKFLOW ENDPOINTS
// ============================================================================ const workflowSchema = z.object({ organizationId: z.string().uuid(), invoiceId: z.string().uuid(), workflowType: z.enum(["standard","high_value","variance_detected","variance_critical"]), totalAmount: z.number().optional(),
}); router.post("/workflows", async (req: Request, res: Response) => { try { const validated = workflowSchema.parse(req.body); const userId = req.headers["x-user-id"] as string; const { data, error } = await supabase .from("invoice_approval_workflows") .insert({ organization_id: validated.organizationId, invoice_id: validated.invoiceId, workflow_type: validated.workflowType, total_amount: validated.totalAmount, status:"pending", current_reviewer_id: userId, }) .select() .single(); if (error) throw error; res.status(201).json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.get("/workflows", async (req: Request, res: Response) => { try { const { limit ="50", offset ="0", status, invoiceId } = req.query; let query = supabase .from("invoice_approval_workflows") .select( ` id, invoice_id, workflow_type, total_amount, status, required_approvers, approvals_received, submitted_at, created_at, invoices (number, vendor_id, vendors(name)) `, { count:"exact" } ) .order("submitted_at", { ascending: false }); if (status) query = query.eq("status", status); if (invoiceId) query = query.eq("invoice_id", invoiceId); const { from, to } = applyPaginationRange(Number(limit), Number(offset)); const { data, count, error } = await query.range(from, to); if (error) throw error; res.json( buildPaginatedResponse(data || [], Number(limit), Number(offset), count || 0) ); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.patch("/workflows/:id/approve", async (req: Request, res: Response) => { try { const { id } = req.params; const { notes } = req.body; const userId = req.headers["x-user-id"] as string; // Get current workflow const { data: workflow, error: fetchError } = await supabase .from("invoice_approval_workflows") .select("approvals_received, required_approvers") .eq("id", id) .single(); if (fetchError) throw fetchError; const newApprovalsReceived = (workflow.approvals_received || 0) + 1; const newStatus = newApprovalsReceived >= workflow.required_approvers ?"approved" :"in_review"; const { data, error } = await supabase .from("invoice_approval_workflows") .update({ approvals_received: newApprovalsReceived, status: newStatus, approved_at: newStatus ==="approved" ? new Date().toISOString() : null, approval_notes: notes, }) .eq("id", id) .select() .single(); if (error) throw error; res.json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.patch("/workflows/:id/reject", async (req: Request, res: Response) => { try { const { id } = req.params; const { notes } = req.body; const { data, error } = await supabase .from("invoice_approval_workflows") .update({ status:"rejected", approval_notes: notes, }) .eq("id", id) .select() .single(); if (error) throw error; res.json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); // ============================================================================
// GL POSTING QUEUE ENDPOINTS
// ============================================================================ router.get("/posting-queue", async (req: Request, res: Response) => { try { const { limit ="50", offset ="0", status, period } = req.query; let query = supabase .from("invoice_gl_posting_queue") .select( ` id, invoice_id, allocation_id, post_period, status, posting_attempt, scheduled_post_date, actual_post_date, created_at, invoices (number), invoice_gl_allocations (allocated_amount, gl_code) `, { count:"exact" } ) .order("scheduled_post_date", { ascending: true }); if (status) query = query.eq("status", status); if (period) query = query.eq("post_period", period); const { from, to } = applyPaginationRange(Number(limit), Number(offset)); const { data, count, error } = await query.range(from, to); if (error) throw error; res.json( buildPaginatedResponse(data || [], Number(limit), Number(offset), count || 0) ); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.patch("/posting-queue/:id/post", async (req: Request, res: Response) => { try { const { id } = req.params; const userId = req.headers["x-user-id"] as string; // Get allocation details const { data: queueItem, error: queueError } = await supabase .from("invoice_gl_posting_queue") .select("allocation_id") .eq("id", id) .single(); if (queueError) throw queueError; // Update queue status const { error: updateError } = await supabase .from("invoice_gl_posting_queue") .update({ status:"posted", actual_post_date: new Date(), }) .eq("id", id); if (updateError) throw updateError; // Update allocation status const { data, error } = await supabase .from("invoice_gl_allocations") .update({ posting_status:"posted", posting_date: new Date().toISOString().slice(0, 10), posted_by: userId, }) .eq("id", queueItem.allocation_id) .select() .single(); if (error) throw error; res.json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); // ============================================================================
// INVOICE PROCESSING SUMMARY
// ============================================================================ router.get("/summary/invoice/:invoiceId", async (req: Request, res: Response) => { try { const { invoiceId } = req.params; // Get invoice summary with all related data const { data: invoice } = await supabase .from("invoices") .select( ` id, number, vendor_id, total, status, created_at, vendors (name) ` ) .eq("id", invoiceId) .single(); const { data: extractions } = await supabase .from("invoice_extraction_results") .select("*") .eq("invoice_id", invoiceId); const { data: allocations } = await supabase .from("invoice_gl_allocations") .select("allocated_amount, posting_status") .eq("invoice_id", invoiceId); const { data: variances } = await supabase .from("invoice_variance_tracking") .select("variance_type, severity") .eq("invoice_id", invoiceId); const { data: workflows } = await supabase .from("invoice_approval_workflows") .select("status") .eq("invoice_id", invoiceId); const totalAllocated = allocations?.reduce((sum, a) => sum + (a.allocated_amount || 0), 0) || 0; const pendingAllocations = allocations?.filter((a) => a.posting_status ==="pending").length || 0; const criticalVariances = variances?.filter((v) => v.severity ==="critical").length || 0; res.json({ invoice, summary: { totalAmount: invoice?.total || 0, totalAllocated, remainingToAllocate: (invoice?.total || 0) - totalAllocated, allocationCount: allocations?.length || 0, pendingAllocations, varianceCount: variances?.length || 0, criticalVariances, workflowStatus: workflows?.[0]?.status ||"none", extractionStatus: extractions?.[0]?.line_extraction_status ||"pending", }, }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); // ============================================================================
// GL CODE SUGGESTION ENDPOINTS
// ============================================================================ /** * POST /api/invoice-gl-integration/suggest-gl * Get GL code suggestions for an invoice or line item */
router.post("/suggest-gl", async (req: Request, res: Response) => { try { const { vendorName, invoiceAmount, lineItemDescription, organizationId } = z .object({ vendorName: z.string().optional(), invoiceAmount: z.number().optional(), lineItemDescription: z.string().optional(), organizationId: z.string().uuid().optional(), }) .parse(req.body); const orgId = organizationId || (req.headers["x-org-id"] as string); const engine = getGLSuggestionEngine(); // Fetch historical patterns from database const { data: historicalData } = await supabase .from("gl_suggestions") .select("gl_code, frequency, confidence") .eq("organization_id", orgId) .eq("vendor_name", vendorName ||"") .order("frequency", { ascending: false }) .limit(10); const suggestion = await engine.suggestGLCode({ vendorName: vendorName ||"", invoiceAmount: invoiceAmount || 0, lineItemDescription: lineItemDescription ||"", organizationId: orgId, historicalData: historicalData?.map((d: any) => ({ vendorName: vendorName ||"", glCode: d.gl_code, frequency: d.frequency, confidence: d.confidence, })) || [], }); res.json({ suggestedGL: suggestion.glCode, glAccountName: suggestion.glAccountName, confidence: suggestion.confidence, reasoning: suggestion.reasoning, alternativeGLCodes: suggestion.alternativeGLCodes, }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); /** * GET /api/invoice-gl-integration/chart-of-accounts * Get full chart of accounts for the organization */
router.get("/chart-of-accounts", async (req: Request, res: Response) => { try { const coa = getChartOfAccounts(); const allAccounts = coa.getFullChart(); res.json(allAccounts); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); /** * POST /api/invoice-gl-integration/accept-suggestion * Record accepted GL suggestion for feedback loop */
router.post("/accept-suggestion", async (req: Request, res: Response) => { try { const { glCode, vendorName, invoiceId, confidence } = z .object({ glCode: z.string(), vendorName: z.string(), invoiceId: z.string().uuid(), confidence: z.number().optional(), }) .parse(req.body); const organizationId = req.headers["x-org-id"] as string; const userId = req.headers["x-user-id"] as string; // Record the GL suggestion acceptance for learning const { data, error } = await supabase .from("gl_suggestions") .insert({ organization_id: organizationId, vendor_name: vendorName, gl_code: glCode, frequency: 1, confidence: confidence || 0.8, accepted_by: userId, invoice_id: invoiceId, }) .select() .single(); if (error) throw error; res.status(201).json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); export default router;
