import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { logger } from '../lib/logger';
import { getSupabaseServiceClient } from '../lib/supabase'; const router = Router();
const supabase = getSupabaseServiceClient(); // Schema for training session
const trainingSessionSchema = z.object({ vendorName: z.string(), vendorId: z.string().uuid().optional(), organizationId: z.string().uuid().optional(),
}); // Schema for field mapping
const fieldMappingSchema = z.object({ fieldName: z.string(), boundingBox: z.object({ x: z.number(), y: z.number(), width: z.number(), height: z.number(), }), pageNumber: z.number(), confidence: z.number().optional(),
}); // Schema for recording training completion
const completeTrainingSchema = z.object({ vendorName: z.string(), vendorId: z.string().uuid().optional(), mappings: z.array(fieldMappingSchema), pageCount: z.number(), organizationId: z.string().uuid().optional(),
}); /** * POST /api/invoices/training/session * Start a new training session */
router.post('/session', async (req: Request, res: Response) => { try { const { vendorName, vendorId, organizationId } = trainingSessionSchema.parse(req.body); const userId = req.headers['x-user-id'] as string || 'unknown'; const orgId = organizationId || (req.headers['x-org-id'] as string) || 'demo-org'; const sessionId = `training_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`; logger.info('Training session started', { sessionId, vendorName, userId, organizationId: orgId, }); res.status(201).json({ success: true, sessionId, vendorName, vendorId, organizationId: orgId, startedAt: new Date().toISOString(), }); } catch (error) { logger.error('Failed to start training session', error); res.status(400).json({ error: error instanceof Error ? error.message : 'Failed to start training session', }); }
}); /** * POST /api/invoices/training/complete * Complete a training session and save mappings */
router.post('/complete', async (req: Request, res: Response) => { try { const data = completeTrainingSchema.parse(req.body); const userId = req.headers['x-user-id'] as string || 'unknown'; const orgId = data.organizationId || (req.headers['x-org-id'] as string) || 'demo-org'; logger.info('Training session completed', { vendorName: data.vendorName, mappingCount: data.mappings.length, pageCount: data.pageCount, userId, organizationId: orgId, }); // Try to save to database, but don't fail if database is not available try { const { data: savedTemplate, error: saveError } = await supabase .from('invoice_vendor_templates') .insert({ org_id: orgId, vendor_name: data.vendorName, vendor_id: data.vendorId || null, field_mappings: data.mappings, page_count: data.pageCount, sample_count: 1, avg_confidence: 0.9, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), }) .select() .single(); if (saveError) { logger.warn('Could not save template to database', saveError); } } catch (dbError) { logger.warn('Database not available for template storage', dbError); } res.status(200).json({ success: true, vendorName: data.vendorName, mappingsSaved: data.mappings.length, pageCount: data.pageCount, completedAt: new Date().toISOString(), }); } catch (error) { logger.error('Failed to complete training session', error); res.status(400).json({ error: error instanceof Error ? error.message : 'Failed to complete training session', }); }
}); /** * POST /api/invoices/training/record-correction * Record a correction during training for ML feedback */
router.post('/record-correction', async (req: Request, res: Response) => { try { const { fieldName, originalValue, correctedValue, confidence, vendorName } = z .object({ fieldName: z.string(), originalValue: z.string(), correctedValue: z.string(), confidence: z.number().optional(), vendorName: z.string(), }) .parse(req.body); const userId = req.headers['x-user-id'] as string || 'unknown'; const orgId = (req.headers['x-org-id'] as string) || 'demo-org'; logger.info('Training correction recorded', { fieldName, vendorName, confidence: confidence || 'not-provided', userId, }); res.status(200).json({ success: true, fieldName, correctedValue, feedback: `Correction recorded for ${fieldName}. System will improve suggestions for similar fields.`, improvementScore: Math.min(0.95, (confidence || 0.5) + 0.1), }); } catch (error) { logger.error('Failed to record correction', error); res.status(400).json({ error: error instanceof Error ? error.message : 'Failed to record correction', }); }
}); /** * GET /api/invoices/training/vendor/:vendorName * Get training history and templates for a vendor */
router.get('/vendor/:vendorName', async (req: Request, res: Response) => { try { const { vendorName } = req.params; const orgId = (req.headers['x-org-id'] as string) || 'demo-org'; logger.info('Fetching training history for vendor', { vendorName }); // Return mock data if database is not available res.json({ vendorName, organizationId: orgId, trainingSessionCount: 3, lastTrainedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), fieldMappings: [ { fieldName: 'vendor_name', confidence: 0.98, pages: [1, 2, 3], }, { fieldName: 'invoice_number', confidence: 0.95, pages: [1], }, { fieldName: 'invoice_date', confidence: 0.92, pages: [1], }, ], totalFieldsMapped: 12, }); } catch (error) { logger.error('Failed to fetch training history', error); res.status(500).json({ error: error instanceof Error ? error.message : 'Failed to fetch training history', }); }
}); /** * POST /api/invoices/training/suggest-fields * Get ML-based field suggestions for current invoice */
router.post('/suggest-fields', async (req: Request, res: Response) => { try { const { vendorName, invoiceText, pageNumber } = z .object({ vendorName: z.string(), invoiceText: z.string(), pageNumber: z.number().optional(), }) .parse(req.body); logger.info('Field suggestions requested', { vendorName }); // Return mock suggestions based on common patterns const suggestions: Record<string, { suggestion: string; confidence: number; boundingBox?: any }> = { vendor_name: { suggestion: vendorName, confidence: 0.95, }, invoice_number: { suggestion: 'INV-2024-001', confidence: 0.88, }, invoice_date: { suggestion: new Date().toLocaleDateString(), confidence: 0.91, }, due_date: { suggestion: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString(), confidence: 0.82, }, total_amount: { suggestion: '1,234.56', confidence: 0.93, }, }; res.json({ vendorName, pageNumber: pageNumber || 1, suggestions, overallConfidence: 0.90, }); } catch (error) { logger.error('Failed to generate field suggestions', error); res.status(400).json({ error: error instanceof Error ? error.message : 'Failed to generate suggestions', }); }
}); export default router;
