import { Router, Request, Response } from "express";
import { z } from "zod";
import { getSupabaseServiceClient } from "../lib/supabase";
import { applyPaginationRange, buildPaginatedResponse } from "../middleware/pagination"; const router = Router();
const supabase = getSupabaseServiceClient(); // ============================================================================
// ALERT ENDPOINTS
// ============================================================================ const createAlertSchema = z.object({ organizationId: z.string().uuid(), alertDefinitionId: z.string().uuid(), alertType: z.string(), severity: z.enum(["low","medium","high","critical"]), title: z.string(), description: z.string().optional(), outletId: z.string().uuid().optional(), referenceType: z.enum(["shipment","invoice","inventory","vendor","payment","receiving"]).optional(), referenceId: z.string().uuid().optional(), metadata: z.record(z.any()).optional(),
}); router.post("/alerts", async (req: Request, res: Response) => { try { const validated = createAlertSchema.parse(req.body); const { data, error } = await supabase .from("manager_alerts") .insert({ organization_id: validated.organizationId, alert_definition_id: validated.alertDefinitionId, alert_type: validated.alertType, severity: validated.severity, title: validated.title, description: validated.description, outlet_id: validated.outletId || null, reference_type: validated.referenceType || null, reference_id: validated.referenceId || null, metadata: validated.metadata, status:"active", action_required: validated.severity ==="critical" || validated.severity ==="high", }) .select() .single(); if (error) throw error; // Create notifications for subscribed users const { data: subscriptions } = await supabase .from("alert_subscriptions") .select("user_id, delivery_methods") .eq("organization_id", validated.organizationId) .eq("alert_type", validated.alertType) .eq("enabled", true); if (subscriptions && subscriptions.length > 0) { const notifications = subscriptions.flatMap((sub) => (sub.delivery_methods || ["dashboard"]).map((method) => ({ organization_id: validated.organizationId, alert_id: data.id, user_id: sub.user_id, delivery_method: method, delivery_status:"pending", })) ); await supabase.from("alert_notifications").insert(notifications); } res.status(201).json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.get("/alerts", async (req: Request, res: Response) => { try { const { limit ="50", offset ="0", status, severity, outletId, type } = req.query; const userId = req.headers["x-user-id"] as string; let query = supabase .from("manager_alerts") .select( ` id, alert_type, severity, title, description, status, action_required, outlet_id, reference_type, reference_id, created_at, acknowledged_at, resolved_at, outlets (name), alert_definitions (alert_name) `, { count:"exact" } ) .order("created_at", { ascending: false }); if (status) query = query.eq("status", status); if (severity) query = query.eq("severity", severity); if (outletId) query = query.eq("outlet_id", outletId); if (type) query = query.eq("alert_type", type); const { from, to } = applyPaginationRange(Number(limit), Number(offset)); const { data, count, error } = await query.range(from, to); if (error) throw error; res.json( buildPaginatedResponse(data || [], Number(limit), Number(offset), count || 0) ); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.patch("/alerts/:id/acknowledge", async (req: Request, res: Response) => { try { const { id } = req.params; const userId = req.headers["x-user-id"] as string; const { data, error } = await supabase .from("manager_alerts") .update({ status:"acknowledged", acknowledged_by: userId, acknowledged_at: new Date().toISOString(), }) .eq("id", id) .select() .single(); if (error) throw error; // Log to audit trail await supabase.from("alert_audit_log").insert({ organization_id: data.organization_id, alert_id: id, action:"acknowledged", action_by: userId, previous_status:"active", new_status:"acknowledged", }); res.json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.patch("/alerts/:id/resolve", async (req: Request, res: Response) => { try { const { id } = req.params; const { notes } = req.body; const userId = req.headers["x-user-id"] as string; const { data, error } = await supabase .from("manager_alerts") .update({ status:"resolved", resolved_by: userId, resolved_at: new Date().toISOString(), resolution_notes: notes, }) .eq("id", id) .select() .single(); if (error) throw error; // Log to audit trail await supabase.from("alert_audit_log").insert({ organization_id: data.organization_id, alert_id: id, action:"resolved", action_by: userId, action_notes: notes, previous_status:"acknowledged", new_status:"resolved", }); res.json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); // ============================================================================
// SUBSCRIPTION ENDPOINTS
// ============================================================================ const subscriptionSchema = z.object({ organizationId: z.string().uuid(), alertType: z.string(), minSeverity: z.enum(["low","medium","high","critical"]).optional(), deliveryMethods: z.array(z.enum(["dashboard","email","sms","push"])).optional(), outletIds: z.array(z.string().uuid()).optional(),
}); router.post("/subscriptions", async (req: Request, res: Response) => { try { const validated = subscriptionSchema.parse(req.body); const userId = req.headers["x-user-id"] as string; const { data, error } = await supabase .from("alert_subscriptions") .upsert({ organization_id: validated.organizationId, user_id: userId, alert_type: validated.alertType, min_severity: validated.minSeverity ||"medium", delivery_methods: validated.deliveryMethods || ["dashboard"], outlet_ids: validated.outletIds || [], enabled: true, }) .select() .single(); if (error) throw error; res.status(201).json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.get("/subscriptions", async (req: Request, res: Response) => { try { const userId = req.headers["x-user-id"] as string; const { data, error } = await supabase .from("alert_subscriptions") .select("*") .eq("user_id", userId); if (error) throw error; res.json(data || []); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.delete("/subscriptions/:id", async (req: Request, res: Response) => { try { const { id } = req.params; const { error } = await supabase .from("alert_subscriptions") .delete() .eq("id", id); if (error) throw error; res.json({ success: true }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); // ============================================================================
// NOTIFICATION ENDPOINTS
// ============================================================================ router.get("/notifications", async (req: Request, res: Response) => { try { const userId = req.headers["x-user-id"] as string; const { limit ="50", offset ="0", status } = req.query; let query = supabase .from("alert_notifications") .select( ` id, alert_id, delivery_method, delivery_status, delivered_at, read_at, created_at, manager_alerts (id, title, severity, alert_type) `, { count:"exact" } ) .eq("user_id", userId) .order("created_at", { ascending: false }); if (status) query = query.eq("delivery_status", status); const { from, to } = applyPaginationRange(Number(limit), Number(offset)); const { data, count, error } = await query.range(from, to); if (error) throw error; res.json( buildPaginatedResponse(data || [], Number(limit), Number(offset), count || 0) ); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.patch("/notifications/:id/read", async (req: Request, res: Response) => { try { const { id } = req.params; const { data, error } = await supabase .from("alert_notifications") .update({ read_at: new Date().toISOString(), delivery_status:"read", }) .eq("id", id) .select() .single(); if (error) throw error; res.json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); // ============================================================================
// DASHBOARD SUMMARY ENDPOINTS
// ============================================================================ router.get("/summary", async (req: Request, res: Response) => { try { const organizationId = req.headers["x-org-id"] as string; const { data: bySeverity } = await supabase .from("alert_summary_by_severity") .select("*") .eq("organization_id", organizationId); const { data: byType } = await supabase .from("alert_summary_by_type") .select("*") .eq("organization_id", organizationId); const { data: byOutlet } = await supabase .from("alert_summary_by_outlet") .select("*") .eq("organization_id", organizationId); const { data: activeAlerts, error } = await supabase .from("manager_alerts") .select("severity") .eq("organization_id", organizationId) .eq("status","active"); if (error) throw error; const criticalCount = activeAlerts?.filter((a) => a.severity ==="critical").length || 0; const highCount = activeAlerts?.filter((a) => a.severity ==="high").length || 0; const totalActive = activeAlerts?.length || 0; res.json({ summary: { totalAlerts: totalActive, criticalAlerts: criticalCount, highAlerts: highCount, mediumAlerts: totalActive - criticalCount - highCount, }, bySeverity: bySeverity || [], byType: byType || [], byOutlet: byOutlet || [], }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); // ============================================================================
// PREFERENCES ENDPOINTS
// ============================================================================ router.get("/preferences", async (req: Request, res: Response) => { try { const userId = req.headers["x-user-id"] as string; const { data, error } = await supabase .from("alert_dashboard_preferences") .select("*") .eq("user_id", userId) .single(); if (error) throw error; res.json(data || {}); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); router.patch("/preferences", async (req: Request, res: Response) => { try { const userId = req.headers["x-user-id"] as string; const organizationId = req.headers["x-org-id"] as string; const { data, error } = await supabase .from("alert_dashboard_preferences") .upsert({ organization_id: organizationId, user_id: userId, ...req.body, }) .select() .single(); if (error) throw error; res.json(data); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message :"Unknown error" }); }
}); export default router;
