import { Router, Request, Response } from 'express';
import { mobileInventorySyncService } from '../lib/mobile-inventory-sync';
import { barcodeService } from '../lib/barcode-service';
import { inventoryTransferService } from '../lib/inventory-transfer-service';
import { logger } from '../lib/logger';
import { z } from 'zod'; const router = Router(); // Validation schemas
const CountSessionSchema = z.object({ outletId: z.string().uuid(), organizationId: z.string().uuid(),
}); const CountRecordSchema = z.object({ sessionId: z.string().uuid(), itemId: z.string().uuid(), quantity: z.number().positive(), unit: z.string(), location: z.string().optional(), bin: z.string().optional(), barcodeScanned: z.boolean().default(false), notes: z.string().optional(),
}); const BarcodeScanSchema = z.object({ barcode: z.string(), organizationId: z.string().uuid(), outletId: z.string().uuid(), sessionId: z.string().uuid(),
}); const TransferSchema = z.object({ organizationId: z.string().uuid(), fromOutletId: z.string().uuid(), toOutletId: z.string().uuid(), items: z.array( z.object({ itemId: z.string().uuid(), quantity: z.number().positive(), unit: z.string(), }), ), notes: z.string().optional(),
}); // Mobile count sessions
router.post('/sessions', async (req: Request, res: Response) => { try { const { outletId, organizationId } = CountSessionSchema.parse(req.body); const userId = req.user?.id; if (!userId) { return res.status(401).json({ error: 'Unauthorized' }); } const session = await mobileInventorySyncService.createCountSession( outletId, organizationId, userId, ); logger.info('Count session created', { sessionId: session.id, outletId }); res.json(session); } catch (error) { logger.error('Failed to create count session', error); if (error instanceof z.ZodError) { return res.status(400).json({ error: error.errors }); } res.status(500).json({ error: 'Failed to create count session' }); }
}); router.get('/sessions/:sessionId', async (req: Request, res: Response) => { try { const { sessionId } = req.params; const details = await mobileInventorySyncService.getSessionDetails( sessionId, ); res.json(details); } catch (error) { logger.error('Failed to fetch session details', error); res.status(500).json({ error: 'Failed to fetch session details' }); }
}); // Count records
router.post('/records', async (req: Request, res: Response) => { try { const { sessionId, itemId, quantity, unit, location, bin, barcodeScanned, notes, } = CountRecordSchema.parse(req.body); const userId = req.user?.id; if (!userId) { return res.status(401).json({ error: 'Unauthorized' }); } // Need to get organization and outlet from session const sessionDetails = await mobileInventorySyncService.getSessionDetails( sessionId, ); const record = await mobileInventorySyncService.recordCountLine( sessionId, sessionDetails.session.organizationId, sessionDetails.session.outletId, itemId, quantity, unit, userId, location, bin, barcodeScanned, notes, ); logger.info('Count record created', { recordId: record.id, itemId }); res.json(record); } catch (error) { logger.error('Failed to record count line', error); if (error instanceof z.ZodError) { return res.status(400).json({ error: error.errors }); } res.status(500).json({ error: 'Failed to record count line' }); }
}); // Barcode scanning
router.post('/scan', async (req: Request, res: Response) => { try { const { barcode, organizationId, outletId, sessionId } = BarcodeScanSchema.parse(req.body); const userId = req.user?.id; if (!userId) { return res.status(401).json({ error: 'Unauthorized' }); } const result = await barcodeService.scanBarcode( barcode, organizationId, outletId, userId, sessionId, ); res.json(result); } catch (error) { logger.error('Failed to scan barcode', error); if (error instanceof z.ZodError) { return res.status(400).json({ error: error.errors }); } res.status(500).json({ error: 'Failed to scan barcode' }); }
}); router.get('/scan-history/:organizationId', async (req: Request, res: Response) => { try { const { organizationId } = req.params; const { limit } = req.query; const history = barcodeService.getScanHistory( organizationId, parseInt(limit as string) || 50, ); res.json(history); } catch (error) { logger.error('Failed to fetch scan history', error); res.status(500).json({ error: 'Failed to fetch scan history' }); }
}); // Sync operations
router.post('/sync/:sessionId', async (req: Request, res: Response) => { try { const { sessionId } = req.params; const userId = req.user?.id; if (!userId) { return res.status(401).json({ error: 'Unauthorized' }); } // Get session details to get organization ID const sessionDetails = await mobileInventorySyncService.getSessionDetails( sessionId, ); const result = await mobileInventorySyncService.syncSessionRecords( sessionId, sessionDetails.session.organizationId, userId, ); logger.info('Session synced', { sessionId, synced: result.synced, conflicts: result.conflicts.length, }); res.json(result); } catch (error) { logger.error('Failed to sync session records', error); res.status(500).json({ error: 'Failed to sync session records' }); }
}); // Conflicts
router.get('/conflicts/:organizationId', async (req: Request, res: Response) => { try { const { organizationId } = req.params; const conflicts = await mobileInventorySyncService.getConflicts( organizationId, ); res.json(conflicts); } catch (error) { logger.error('Failed to fetch conflicts', error); res.status(500).json({ error: 'Failed to fetch conflicts' }); }
}); router.post('/resolve-conflict/:conflictId', async (req: Request, res: Response) => { try { const { conflictId } = req.params; const { method, manualQuantity } = req.body; await mobileInventorySyncService.resolveConflict( conflictId, method, manualQuantity, ); logger.info('Conflict resolved', { conflictId, method }); res.json({ success: true }); } catch (error) { logger.error('Failed to resolve conflict', error); res.status(500).json({ error: 'Failed to resolve conflict' }); }
}); // Transfers
router.post('/transfers', async (req: Request, res: Response) => { try { const { organizationId, fromOutletId, toOutletId, items, notes, } = TransferSchema.parse(req.body); const userId = req.user?.id; if (!userId) { return res.status(401).json({ error: 'Unauthorized' }); } const transfer = await inventoryTransferService.createTransfer( organizationId, fromOutletId, toOutletId, items, userId, notes, ); logger.info('Transfer created', { transferId: transfer.id }); res.json(transfer); } catch (error) { logger.error('Failed to create transfer', error); if (error instanceof z.ZodError) { return res.status(400).json({ error: error.errors }); } res.status(500).json({ error: 'Failed to create transfer' }); }
}); router.post('/transfers/:transferId/approve', async (req: Request, res: Response) => { try { const { transferId } = req.params; const userId = req.user?.id; if (!userId) { return res.status(401).json({ error: 'Unauthorized' }); } const transfer = await inventoryTransferService.approveTransfer( transferId, userId, ); logger.info('Transfer approved', { transferId }); res.json(transfer); } catch (error) { logger.error('Failed to approve transfer', error); res.status(500).json({ error: 'Failed to approve transfer' }); }
}); router.post('/transfers/:transferId/receive', async (req: Request, res: Response) => { try { const { transferId } = req.params; const userId = req.user?.id; if (!userId) { return res.status(401).json({ error: 'Unauthorized' }); } const transfer = await inventoryTransferService.receiveTransfer( transferId, userId, ); logger.info('Transfer received', { transferId }); res.json(transfer); } catch (error) { logger.error('Failed to receive transfer', error); res.status(500).json({ error: 'Failed to receive transfer' }); }
}); router.get('/transfers/:organizationId', async (req: Request, res: Response) => { try { const { organizationId } = req.params; const { outletId, limit } = req.query; const transfers = await inventoryTransferService.getTransferHistory( organizationId, outletId as string, parseInt(limit as string) || 50, ); res.json(transfers); } catch (error) { logger.error('Failed to fetch transfers', error); res.status(500).json({ error: 'Failed to fetch transfers' }); }
}); // Par levels
router.get('/par-levels/:outletId', async (req: Request, res: Response) => { try { const { outletId } = req.params; const alerts = await inventoryTransferService.checkParLevels( req.user?.organization_id || '', outletId, ); res.json(alerts); } catch (error) { logger.error('Failed to check par levels', error); res.status(500).json({ error: 'Failed to check par levels' }); }
}); router.post('/par-levels/:outletId/:itemId', async (req: Request, res: Response) => { try { const { outletId, itemId } = req.params; const { quantity } = req.body; await inventoryTransferService.setParLevel( req.user?.organization_id || '', outletId, itemId, quantity, ); logger.info('Par level updated', { outletId, itemId, quantity }); res.json({ success: true }); } catch (error) { logger.error('Failed to set par level', error); res.status(500).json({ error: 'Failed to set par level' }); }
}); export const mobileInventoryRouter = router;
