import { Router } from "express";
import { randomUUID } from"node:crypto";
import { PurchaseOrder, POItem, POStatus } from "@shared/purchasing";
import { logger } from "../lib/logger"; interface OrderLineInput { itemId?: string; name?: string | null; qty: number; uom: string; unitPrice?: number;
} interface CreateOrderInput { vendorId: string; outletId: string; eta?: string | null; lines: OrderLineInput[];
} interface StatusUpdateInput { status: POStatus; eta?: string | null;
} const orders = new Map<string, PurchaseOrder>(); const router = Router(); function emitEchoEvent(po: PurchaseOrder) { const payload = { poNumber: po.number, vendorId: po.vendorId, status: po.status, eta: po.eta ?? null, }; logger.info("[echo:event] po.status", { payload });
} function normalizeCreateInput(body: any): CreateOrderInput { if (!body || typeof body !=="object") throw new Error("Invalid payload"); const { vendorId, outletId, lines, eta } = body as CreateOrderInput; if (!vendorId || !outletId) throw new Error("vendorId and outletId required"); if (!Array.isArray(lines) || !lines.length) throw new Error("lines required"); const normalizedLines = lines.map((l) => { if (!l || typeof l !=="object") throw new Error("Invalid line"); if (typeof l.qty !=="number" || l.qty <= 0) throw new Error("qty must be > 0"); if (!l.uom) throw new Error("uom required"); return { itemId: l.itemId ?? null, name: l.name ?? null, qty: l.qty, uom: l.uom, unitPrice: typeof l.unitPrice ==="number" ? l.unitPrice : undefined, } satisfies OrderLineInput; }); return { vendorId, outletId, eta: eta ?? null, lines: normalizedLines, };
} router.post("/create", (req, res, next) => { try { const input = normalizeCreateInput(req.body); const now = new Date().toISOString(); const id = randomUUID(); const number = `PO-${Number(Date.now()).toString(36).toUpperCase()}`; const items: POItem[] = input.lines.map((line) => ({ id: randomUUID(), itemId: line.itemId ?? null, productName: line.name ?? line.itemId ??"Unmatched Item", qty: line.qty, unit: line.uom, expectedDate: input.eta ?? now, unitPrice: line.unitPrice ?? null, receivedQty: 0, })); const po: PurchaseOrder = { id, number, vendorId: input.vendorId, outletId: input.outletId, status:"created", createdAt: now, eta: input.eta ?? null, expectedDate: input.eta ?? null, items, }; orders.set(id, po); emitEchoEvent(po); // Emit Stratus event for decision intelligence try { const { emitPurchaseOrderCreated } = await import("../../../../../server/lib/module-event-emitters.js"); const totalAmount = items.reduce((sum, item) => sum + ((item.unitPrice || 0) * item.qty), 0); await emitPurchaseOrderCreated({ tenant_id: input.vendorId, // Would need org_id org_id: input.vendorId, // Would need actual org_id outlet_id: input.outletId, po_id: id, po_number: number, vendor_id: input.vendorId, vendor_name: undefined, // Would fetch vendor name total_amount: totalAmount, items: items.map(item => ({ id: item.itemId || item.id, name: item.productName, quantity: item.qty, unit_price: item.unitPrice || 0, total: (item.unitPrice || 0) * item.qty, })), created_at: now, created_by: undefined, // Would get from request }); } catch (stratusError) { logger.warn("[Orders] Failed to emit Stratus PO event:", stratusError); // Don't fail if Stratus event emission fails } res.json({ order: po }); } catch (err) { next(err); }
}); router.post("/:id/status", (req, res, next) => { try { const { id } = req.params; const { status, eta } = req.body as StatusUpdateInput; if (!orders.has(id)) { res.status(404).json({ error:"PO not found" }); return; } if (!status) { res.status(400).json({ error:"status required" }); return; } const allowed: POStatus[] = ["created","sent","confirmed","shipped","delivered","closed","void"]; if (!allowed.includes(status)) { res.status(400).json({ error:"Invalid status" }); return; } const current = orders.get(id)!; const updated: PurchaseOrder = { ...current, status, eta: eta ?? current.eta ?? null, }; orders.set(id, updated); emitEchoEvent(updated); res.json({ order: updated }); } catch (err) { next(err); }
}); export { router as ordersRouter, orders };
