import { Router, Request, Response } from "express";
import { getSupabaseServiceClient } from "../lib/supabase";
import { logger } from "../lib/logger"; export const receivingApiRouter = Router(); // ============================================================================
// RECEIVING SESSION MANAGEMENT
// ============================================================================ // START receiving session
receivingApiRouter.post("/sessions", async (req: Request, res: Response) => { try { const { organization_id, outlet_id, po_id } = req.body; if (!organization_id || !po_id) { res.status(400).json({ error:"Missing required fields" }); return; } const supabase = getSupabaseServiceClient(); const { data, error } = await supabase .from("receiving_sessions") .insert({ organization_id, outlet_id, po_id, status:"in_progress", started_at: new Date().toISOString(), }) .select() .single(); if (error) throw error; res.status(201).json(data); } catch (error) { logger.error("POST /sessions", error); res.status(500).json({ error:"Failed to create receiving session" }); }
}); // GET receiving session
receivingApiRouter.get("/sessions/:sessionId", async (req: Request, res: Response) => { try { const { sessionId } = req.params; const supabase = getSupabaseServiceClient(); const { data: session, error: sessionError } = await supabase .from("receiving_sessions") .select("*, purchase_orders(po_number, vendor_id), receiving_items(*)") .eq("id", sessionId) .maybeSingle(); if (sessionError) throw sessionError; if (!session) { res.status(404).json({ error:"Session not found" }); return; } res.json(session); } catch (error) { logger.error("GET /sessions/:sessionId", error); res.status(500).json({ error:"Failed to fetch session" }); } },
); // ============================================================================
// BARCODE SCANNING
// ============================================================================ // SCAN barcode and add item
receivingApiRouter.post("/sessions/:sessionId/scan", async (req: Request, res: Response) => { try { const { sessionId } = req.params; const { barcode, quantity, temperature, notes, product_id } = req.body; if (!barcode || !quantity) { res.status(400).json({ error:"barcode and quantity required" }); return; } const supabase = getSupabaseServiceClient(); // Get session and PO const { data: session, error: sessionError } = await supabase .from("receiving_sessions") .select("po_id") .eq("id", sessionId) .maybeSingle(); if (sessionError) throw sessionError; if (!session) { res.status(404).json({ error:"Session not found" }); return; } // Add scanned item const { data: item, error: itemError } = await supabase .from("receiving_items") .insert({ receiving_session_id: sessionId, po_id: session.po_id, product_id, barcode, quantity_scanned: quantity, temperature: temperature || null, notes: notes || null, scanned_at: new Date().toISOString(), }) .select() .single(); if (itemError) throw itemError; res.json({ item, message:"Item scanned successfully", }); } catch (error) { logger.error("POST /sessions/:sessionId/scan", error); res.status(500).json({ error:"Failed to scan item" }); } },
); // ============================================================================
// SHORTAGE DETECTION
// ============================================================================ // GET shortages for session
receivingApiRouter.get("/sessions/:sessionId/shortages", async (req: Request, res: Response) => { try { const { sessionId } = req.params; const supabase = getSupabaseServiceClient(); // Get session const { data: session, error: sessionError } = await supabase .from("receiving_sessions") .select("po_id") .eq("id", sessionId) .maybeSingle(); if (sessionError) throw sessionError; if (!session) { res.status(404).json({ error:"Session not found" }); return; } // Get PO lines const { data: poLines, error: poError } = await supabase .from("purchase_order_lines") .select("*") .eq("po_id", session.po_id); if (poError) throw poError; // Get scanned items for this session const { data: scannedItems, error: scannedError } = await supabase .from("receiving_items") .select("*") .eq("receiving_session_id", sessionId); if (scannedError) throw scannedError; // Calculate shortages const shortages = poLines ?.map((line) => { const scanned = scannedItems?.reduce((sum, item) => { if ( item.po_id === line.po_id && item.product_id === line.product_id ) { return sum + item.quantity_scanned; } return sum; }, 0) || 0; const shortage = line.qty - scanned; return { line_id: line.id, product_id: line.product_id, product_name: line.product_name, ordered: line.qty, received: scanned, shortage, unit: line.unit, is_short: shortage > 0, }; }) .filter((s) => s.is_short) || []; res.json(shortages); } catch (error) { logger.error("GET /sessions/:sessionId/shortages", error); res.status(500).json({ error:"Failed to fetch shortages" }); } },
); // ============================================================================
// DELIVERY CONFIRMATION
// ============================================================================ // COMPLETE receiving session with signature
receivingApiRouter.post("/sessions/:sessionId/complete", async (req: Request, res: Response) => { try { const { sessionId } = req.params; const { signed_by, signature_image, notes } = req.body; if (!signed_by) { res.status(400).json({ error:"signed_by required" }); return; } const supabase = getSupabaseServiceClient(); // Update session const { data: session, error: sessionError } = await supabase .from("receiving_sessions") .update({ status:"completed", completed_at: new Date().toISOString(), signed_by, signature_image: signature_image || null, notes: notes || null, }) .eq("id", sessionId) .select() .single(); if (sessionError) throw sessionError; // Get all items for this session const { data: items, error: itemsError } = await supabase .from("receiving_items") .select("*") .eq("receiving_session_id", sessionId); if (itemsError) throw itemsError; // Update PO status to received await supabase .from("purchase_orders") .update({ status:"received" }) .eq("id", session.po_id); res.json({ session, items_received: items?.length || 0, message:"Receiving session completed", }); } catch (error) { logger.error("POST /sessions/:sessionId/complete", error); res.status(500).json({ error:"Failed to complete session" }); } },
); // ============================================================================
// QUALITY CHECKS & TEMPERATURE MONITORING
// ============================================================================ // RECORD temperature issue
receivingApiRouter.post("/sessions/:sessionId/temperature-issue", async (req: Request, res: Response) => { try { const { sessionId } = req.params; const { receiving_item_id, temperature, required_temp, notes } = req.body; const supabase = getSupabaseServiceClient(); // Record quality issue const { data, error } = await supabase .from("receiving_quality_issues") .insert({ receiving_session_id: sessionId, receiving_item_id, issue_type:"temperature", description: `Temperature: ${temperature}°F (required: ${required_temp}°F). ${notes ||""}`, severity: temperature < required_temp ?"critical" :"warning", detected_at: new Date().toISOString(), }) .select() .single(); if (error) throw error; res.status(201).json(data); } catch (error) { logger.error("POST /sessions/:sessionId/temperature-issue", error); res.status(500).json({ error:"Failed to record issue" }); } },
); // RECORD damage/shortage issue
receivingApiRouter.post("/sessions/:sessionId/damage-issue", async (req: Request, res: Response) => { try { const { sessionId } = req.params; const { receiving_item_id, issue_type, description, severity } = req.body; const supabase = getSupabaseServiceClient(); const { data, error } = await supabase .from("receiving_quality_issues") .insert({ receiving_session_id: sessionId, receiving_item_id, issue_type: issue_type ||"damage", description, severity: severity ||"warning", detected_at: new Date().toISOString(), }) .select() .single(); if (error) throw error; res.status(201).json(data); } catch (error) { logger.error("POST /sessions/:sessionId/damage-issue", error); res.status(500).json({ error:"Failed to record issue" }); } },
); // GET quality issues for session
receivingApiRouter.get("/sessions/:sessionId/quality-issues", async (req: Request, res: Response) => { try { const { sessionId } = req.params; const supabase = getSupabaseServiceClient(); const { data, error } = await supabase .from("receiving_quality_issues") .select("*") .eq("receiving_session_id", sessionId); if (error) throw error; res.json(data || []); } catch (error) { logger.error("GET /sessions/:sessionId/quality-issues", error); res.status(500).json({ error:"Failed to fetch issues" }); } },
); // ============================================================================
// CASE WEIGHT CONVERSION
// ============================================================================ // CALCULATE inventory quantity from case weight
receivingApiRouter.post("/calculate-inventory", async (req: Request, res: Response) => { try { const { product_id, case_weight_lbs, weight_per_unit, unit_of_measure } = req.body; if (!case_weight_lbs || !weight_per_unit) { res .status(400) .json({ error:"case_weight_lbs and weight_per_unit required" }); return; } const inventory_quantity = case_weight_lbs / weight_per_unit; res.json({ case_weight_lbs, weight_per_unit, unit_of_measure: unit_of_measure ||"units", calculated_inventory_quantity: Math.round(inventory_quantity * 100) / 100, message:"Conversion calculated", }); } catch (error) { logger.error("POST /calculate-inventory", error); res.status(500).json({ error:"Failed to calculate inventory" }); } },
);
