import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { logger, sanitizeError } from '../lib/logger';
import { validateRequest, UUIDSchema } from '../middleware/validation';
import { rfqMarketplaceEngine } from '../lib/rfq-marketplace-engine'; const router = Router(); // ============================================================================
// RFQ MANAGEMENT
// ============================================================================ /** * POST /rfqs * Create a new RFQ */
router.post( '/rfqs', validateRequest({ body: z.object({ organization_id: UUIDSchema, group_admin_id: UUIDSchema, title: z.string().min(5), description: z.string(), items: z.array(z.object({ sku_code: z.string(), description: z.string(), quantity: z.number().positive(), unit_of_measure: z.string(), target_price: z.number().optional(), })), distributed_to: z.array(UUIDSchema), requested_by: z.string(), expires_at: z.string(), delivery_date: z.string(), delivery_location: z.string(), }), }), async (req: Request, res: Response) => { try { const { organization_id, group_admin_id, title, description, items, distributed_to, requested_by, expires_at, delivery_date, delivery_location, } = req.body; const rfq = await rfqMarketplaceEngine.createRFQ( organization_id, group_admin_id, { title, description, items: items.map(i => ({ skuCode: i.sku_code, description: i.description, quantity: i.quantity, unitOfMeasure: i.unit_of_measure, targetPrice: i.target_price, })), distributedTo: distributed_to, requestedBy: requested_by, expiresAt: expires_at, deliveryDate: delivery_date, deliveryLocation: delivery_location, }, ); res.status(201).json(rfq); } catch (error) { logger.error('POST /rfqs failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); /** * POST /rfqs/:rfqId/publish * Publish RFQ to suppliers */
router.post( '/rfqs/:rfqId/publish', validateRequest({ params: z.object({ rfqId: UUIDSchema }), }), async (req: Request, res: Response) => { try { const { rfqId } = req.params; await rfqMarketplaceEngine.publishRFQ(rfqId); res.json({ rfq_id: rfqId, status: 'published', message: 'RFQ published and distributed to suppliers', }); } catch (error) { logger.error('POST /rfqs/:rfqId/publish failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// SUPPLIER BIDDING
// ============================================================================ /** * POST /rfqs/:rfqId/bids * Submit supplier bid */
router.post( '/rfqs/:rfqId/bids', validateRequest({ params: z.object({ rfqId: UUIDSchema }), body: z.object({ supplier_id: UUIDSchema, supplier_name: z.string(), bid_items: z.array(z.object({ sku_code: z.string(), bid_price: z.number().positive(), lead_time: z.number().int().positive(), notes: z.string().optional(), })), total_bid_amount: z.number().positive(), delivery_terms: z.string(), payment_terms: z.string(), quality_metrics: z.object({ on_time_delivery_percent: z.number(), quality_score: z.number(), responsiveness: z.number(), }).optional(), }), }), async (req: Request, res: Response) => { try { const { rfqId } = req.params; const { supplier_id, supplier_name, bid_items, total_bid_amount, delivery_terms, payment_terms, quality_metrics, } = req.body; const bid = await rfqMarketplaceEngine.submitBid({ rfqId, supplierId: supplier_id, supplierName: supplier_name, bidItems: bid_items.map(item => ({ skuCode: item.sku_code, bidPrice: item.bid_price, leadTime: item.lead_time, notes: item.notes, })), totalBidAmount: total_bid_amount, deliveryTerms: delivery_terms, paymentTerms: payment_terms, qualityMetrics: quality_metrics ? { onTimeDeliveryPercent: quality_metrics.on_time_delivery_percent, qualityScore: quality_metrics.quality_score, responsiveness: quality_metrics.responsiveness, } : undefined, }); res.status(201).json(bid); } catch (error) { logger.error('POST /rfqs/:rfqId/bids failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); /** * GET /rfqs/:rfqId/bids * Get all bids for an RFQ */
router.get( '/rfqs/:rfqId/bids', validateRequest({ params: z.object({ rfqId: UUIDSchema }), }), async (req: Request, res: Response) => { try { const { rfqId } = req.params; const bids = await rfqMarketplaceEngine.getBidsForRFQ(rfqId); res.json({ rfq_id: rfqId, bid_count: bids.length, bids, }); } catch (error) { logger.error('GET /rfqs/:rfqId/bids failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// RFQ EVALUATION
// ============================================================================ /** * POST /rfqs/:rfqId/evaluate * Evaluate bids for an RFQ */
router.post( '/rfqs/:rfqId/evaluate', validateRequest({ params: z.object({ rfqId: UUIDSchema }), body: z.object({ weights: z.object({ price: z.number().default(0.4), quality: z.number().default(0.3), delivery: z.number().default(0.2), responsiveness: z.number().default(0.1), }).optional(), }), }), async (req: Request, res: Response) => { try { const { rfqId } = req.params; const { weights } = req.body; const evaluation = await rfqMarketplaceEngine.evaluateBids( rfqId, weights, ); res.json(evaluation); } catch (error) { logger.error('POST /rfqs/:rfqId/evaluate failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// RFQ AWARD
// ============================================================================ /** * POST /rfqs/:rfqId/award * Award RFQ to supplier */
router.post( '/rfqs/:rfqId/award', validateRequest({ params: z.object({ rfqId: UUIDSchema }), body: z.object({ supplier_id: UUIDSchema, }), }), async (req: Request, res: Response) => { try { const { rfqId } = req.params; const { supplier_id } = req.body; await rfqMarketplaceEngine.awardRFQ(rfqId, supplier_id); // Create contract from RFQ const contractId = await rfqMarketplaceEngine.createContractFromRFQ(rfqId); res.json({ rfq_id: rfqId, awarded_to: supplier_id, contract_id: contractId, status: 'awarded', message: 'RFQ awarded and contract created', }); } catch (error) { logger.error('POST /rfqs/:rfqId/award failed', { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); export default router;
