/** * Waste Tracking Server Routes * Handles all waste, disposal, and prevention endpoints */ import { Router, Request, Response } from "express";
import { z } from "zod";
import { getSupabaseServiceClient } from "../lib/supabase";
import { logger, sanitizeError } from "../lib/logger";
import { validateRequest, UUIDSchema, WasteLogSchema, PaginationSchema,
} from "../middleware/validation";
import { paginationMiddleware, applyPaginationRange, buildPaginatedResponse, countTotal,
} from "../middleware/pagination"; const router = Router(); // Lazy initialization helper to defer Supabase client creation
const getClient = () => getSupabaseServiceClient(); // ============================================================================
// WASTE LOGS
// ============================================================================ router.get("/waste-logs", paginationMiddleware, async (req: Request, res: Response) => { try { const supabase = getClient(); const pagination = res.locals.pagination; const { organization_id, outlet_id, waste_category } = req.query; let query = supabase .from("waste_logs") .select("*") .eq("organization_id", organization_id as string); if (outlet_id) query = query.eq("outlet_id", outlet_id); if (waste_category) query = query.eq("waste_category", waste_category); const { data, error } = await applyPaginationRange( query.order("created_at", { ascending: false }), pagination, ); if (error) throw error; // Get total count let countQuery = supabase .from("waste_logs") .select("id", { count:"exact", head: true }) .eq("organization_id", organization_id as string); if (outlet_id) countQuery = countQuery.eq("outlet_id", outlet_id); if (waste_category) countQuery = countQuery.eq("waste_category", waste_category); const total = await countTotal(countQuery); res.json( buildPaginatedResponse( data || [], total, pagination.limit, pagination.offset, ), ); } catch (error) { res.status(500).json({ error: (error as Error).message }); } },
); router.post("/waste-logs", validateRequest({ body: WasteLogSchema }), async (req: Request, res: Response) => { try { const supabase = getClient(); const { data, error } = await supabase .from("waste_logs") .insert([req.body]) .select() .single(); if (error) { logger.error("Failed to create waste log", { error: sanitizeError(error), }); throw error; } logger.info("Waste log created", { logId: data?.id, category: req.body.category, }); res.status(201).json(data); } catch (error) { logger.error("POST /waste-logs failed", { error: sanitizeError(error) }); res.status(500).json({ error: (error as Error).message }); } },
); router.patch("/waste-logs/:logId", validateRequest({ params: z.object({ logId: UUIDSchema }), body: WasteLogSchema.partial(), }), async (req: Request, res: Response) => { try { const supabase = getClient(); const { data, error } = await supabase .from("waste_logs") .update(req.body) .eq("id", req.params.logId) .select() .single(); if (error) { logger.error("Failed to update waste log", { logId: req.params.logId, error: sanitizeError(error), }); throw error; } logger.info("Waste log updated", { logId: req.params.logId }); res.json(data); } catch (error) { logger.error("PATCH /waste-logs/:logId failed", { error: sanitizeError(error), }); res.status(500).json({ error: (error as Error).message }); } },
); router.delete("/waste-logs/:logId", validateRequest({ params: z.object({ logId: UUIDSchema }) }), async (req: Request, res: Response) => { try { const supabase = getClient(); const { error } = await supabase .from("waste_logs") .delete() .eq("id", req.params.logId); if (error) { logger.error("Failed to delete waste log", { logId: req.params.logId, error: sanitizeError(error), }); throw error; } logger.info("Waste log deleted", { logId: req.params.logId }); res.status(204).send(); } catch (error) { logger.error("DELETE /waste-logs/:logId failed", { error: sanitizeError(error), }); res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// WASTE DAILY SUMMARY
// ============================================================================ router.get("/waste-daily-summary", paginationMiddleware, async (req: Request, res: Response) => { try { const supabase = getClient(); const pagination = res.locals.pagination; const { organization_id, outlet_id } = req.query; let query = supabase .from("waste_daily_summary") .select("*") .eq("organization_id", organization_id as string); if (outlet_id) query = query.eq("outlet_id", outlet_id); const { data, error } = await applyPaginationRange( query.order("day_date", { ascending: false }), pagination, ); if (error) throw error; // Get total count let countQuery = supabase .from("waste_daily_summary") .select("id", { count:"exact", head: true }) .eq("organization_id", organization_id as string); if (outlet_id) countQuery = countQuery.eq("outlet_id", outlet_id); const total = await countTotal(countQuery); res.json( buildPaginatedResponse( data || [], total, pagination.limit, pagination.offset, ), ); } catch (error) { res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// WASTE MONTHLY METRICS
// ============================================================================ router.get("/waste-monthly-metrics", paginationMiddleware, async (req: Request, res: Response) => { try { const supabase = getClient(); const pagination = res.locals.pagination; const { organization_id, outlet_id } = req.query; let query = supabase .from("waste_monthly_metrics") .select("*") .eq("organization_id", organization_id as string); if (outlet_id) query = query.eq("outlet_id", outlet_id); const { data, error } = await applyPaginationRange( query.order("year_month", { ascending: false }), pagination, ); if (error) throw error; // Get total count let countQuery = supabase .from("waste_monthly_metrics") .select("id", { count:"exact", head: true }) .eq("organization_id", organization_id as string); if (outlet_id) countQuery = countQuery.eq("outlet_id", outlet_id); const total = await countTotal(countQuery); res.json( buildPaginatedResponse( data || [], total, pagination.limit, pagination.offset, ), ); } catch (error) { res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// WASTE CATEGORY BREAKDOWN
// ============================================================================ router.get("/waste-category-breakdown", async (req: Request, res: Response) => { try { const supabase = getClient(); const { organization_id, outlet_id } = req.query; let query = supabase .from("waste_logs") .select("waste_category, total_waste_cost") .eq("organization_id", organization_id as string); if (outlet_id) query = query.eq("outlet_id", outlet_id); const { data, error } = await query; if (error) throw error; const breakdown = (data || []).reduce( (acc: any, log: any) => { acc[log.waste_category] = (acc[log.waste_category] || 0) + log.total_waste_cost; return acc; }, {} as Record<string, number>, ); res.json(breakdown); } catch (error) { res.status(500).json({ error: (error as Error).message }); }
}); // ============================================================================
// WASTE METRICS SUMMARY
// ============================================================================ router.get("/waste-metrics", async (req: Request, res: Response) => { try { const supabase = getClient(); const { organization_id, outlet_id } = req.query; let query = supabase .from("waste_logs") .select("total_waste_cost, waste_category") .eq("organization_id", organization_id as string); if (outlet_id) query = query.eq("outlet_id", outlet_id); const { data, error } = await query; if (error) throw error; const logs = data || []; const total = logs.length; const totalCost = logs.reduce( (sum: number, l: any) => sum + (l.total_waste_cost || 0), 0, ); const spoilageCount = logs.filter( (l: any) => l.waste_category ==="spoilage", ).length; res.json({ total_waste_cost: totalCost, avg_daily_waste: totalCost / Math.max(1, total), waste_percentage: total > 0 ? (totalCost / (totalCost * 2)) * 100 : 0, spoilage_percentage: (spoilageCount / Math.max(1, total)) * 100, trend:"stable", }); } catch (error) { res.status(500).json({ error: (error as Error).message }); }
}); // ============================================================================
// TOP WASTED PRODUCTS
// ============================================================================ router.get("/waste-top-products", paginationMiddleware, async (req: Request, res: Response) => { try { const supabase = getClient(); const pagination = res.locals.pagination; const { organization_id, outlet_id } = req.query; let query = supabase .from("waste_logs") .select("product_id, product_name, total_waste_cost") .eq("organization_id", organization_id as string); if (outlet_id) query = query.eq("outlet_id", outlet_id); const { data, error } = await applyPaginationRange( query.order("total_waste_cost", { ascending: false }), pagination, ); if (error) throw error; // Get total count let countQuery = supabase .from("waste_logs") .select("id", { count:"exact", head: true }) .eq("organization_id", organization_id as string); if (outlet_id) countQuery = countQuery.eq("outlet_id", outlet_id); const total = await countTotal(countQuery); res.json( buildPaginatedResponse( (data || []).map((l: any) => ({ product_id: l.product_id, product_name: l.product_name, total_waste_cost: l.total_waste_cost, waste_count: 1, })), total, pagination.limit, pagination.offset, ), ); } catch (error) { res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// WASTE DISPOSALS
// ============================================================================ router.get("/waste-disposals", paginationMiddleware, async (req: Request, res: Response) => { try { const supabase = getClient(); const pagination = res.locals.pagination; const { organization_id, outlet_id } = req.query; let query = supabase .from("waste_disposals") .select("*") .eq("organization_id", organization_id as string); if (outlet_id) query = query.eq("outlet_id", outlet_id); const { data, error } = await applyPaginationRange( query.order("created_at", { ascending: false }), pagination, ); if (error) throw error; // Get total count let countQuery = supabase .from("waste_disposals") .select("id", { count:"exact", head: true }) .eq("organization_id", organization_id as string); if (outlet_id) countQuery = countQuery.eq("outlet_id", outlet_id); const total = await countTotal(countQuery); res.json( buildPaginatedResponse( data || [], total, pagination.limit, pagination.offset, ), ); } catch (error) { res.status(500).json({ error: (error as Error).message }); } },
); router.post("/waste-disposals", async (req: Request, res: Response) => { try { const supabase = getClient(); const { data, error } = await supabase .from("waste_disposals") .insert([req.body]) .select() .single(); if (error) throw error; res.status(201).json(data); } catch (error) { res.status(500).json({ error: (error as Error).message }); }
}); // ============================================================================
// DISPOSAL METHODS
// ============================================================================ router.get("/disposal-methods", paginationMiddleware, async (req: Request, res: Response) => { try { const supabase = getClient(); const pagination = res.locals.pagination; const { data, error } = await applyPaginationRange( supabase .from("disposal_methods") .select("*") .eq("is_active", true) .order("name", { ascending: true }), pagination, ); if (error) throw error; // Get total count const total = await countTotal( supabase .from("disposal_methods") .select("id", { count:"exact", head: true }) .eq("is_active", true), ); res.json( buildPaginatedResponse( data || [], total, pagination.limit, pagination.offset, ), ); } catch (error) { res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// WASTE ALERTS
// ============================================================================ router.get("/waste-alerts", paginationMiddleware, async (req: Request, res: Response) => { try { const supabase = getClient(); const pagination = res.locals.pagination; const { organization_id, outlet_id, status } = req.query; let query = supabase .from("waste_alerts") .select("*") .eq("organization_id", organization_id as string); if (outlet_id) query = query.eq("outlet_id", outlet_id); if (status) query = query.eq("status", status); const { data, error } = await applyPaginationRange( query.order("created_at", { ascending: false }), pagination, ); if (error) throw error; // Get total count let countQuery = supabase .from("waste_alerts") .select("id", { count:"exact", head: true }) .eq("organization_id", organization_id as string); if (outlet_id) countQuery = countQuery.eq("outlet_id", outlet_id); if (status) countQuery = countQuery.eq("status", status); const total = await countTotal(countQuery); res.json( buildPaginatedResponse( data || [], total, pagination.limit, pagination.offset, ), ); } catch (error) { res.status(500).json({ error: (error as Error).message }); } },
); router.post("/waste-alerts/:alertId/acknowledge", async (req: Request, res: Response) => { try { const supabase = getClient(); const { acknowledged_by } = req.body; const { data, error } = await supabase .from("waste_alerts") .update({ status:"acknowledged", acknowledged_by, acknowledged_at: new Date().toISOString(), }) .eq("id", req.params.alertId) .select() .single(); if (error) throw error; res.json(data); } catch (error) { res.status(500).json({ error: (error as Error).message }); } },
); // ============================================================================
// PREVENTION ACTIONS
// ============================================================================ router.get("/prevention-actions", paginationMiddleware, async (req: Request, res: Response) => { try { const supabase = getClient(); const pagination = res.locals.pagination; const { organization_id, outlet_id, status } = req.query; let query = supabase .from("waste_prevention_actions") .select("*") .eq("organization_id", organization_id as string); if (outlet_id) query = query.eq("outlet_id", outlet_id); if (status) query = query.eq("status", status); const { data, error } = await applyPaginationRange( query.order("created_at", { ascending: false }), pagination, ); if (error) throw error; // Get total count let countQuery = supabase .from("waste_prevention_actions") .select("id", { count:"exact", head: true }) .eq("organization_id", organization_id as string); if (outlet_id) countQuery = countQuery.eq("outlet_id", outlet_id); if (status) countQuery = countQuery.eq("status", status); const total = await countTotal(countQuery); res.json( buildPaginatedResponse( data || [], total, pagination.limit, pagination.offset, ), ); } catch (error) { res.status(500).json({ error: (error as Error).message }); } },
); router.post("/prevention-actions", async (req: Request, res: Response) => { try { const supabase = getClient(); const { data, error } = await supabase .from("waste_prevention_actions") .insert([req.body]) .select() .single(); if (error) throw error; res.status(201).json(data); } catch (error) { res.status(500).json({ error: (error as Error).message }); }
}); // ============================================================================
// PREVENTION ROI
// ============================================================================ router.get("/prevention-roi", paginationMiddleware, async (req: Request, res: Response) => { try { const supabase = getClient(); const pagination = res.locals.pagination; const { organization_id, outlet_id } = req.query; let query = supabase .from("waste_prevention_roi") .select("*") .eq("organization_id", organization_id as string); if (outlet_id) query = query.eq("outlet_id", outlet_id); const { data, error } = await applyPaginationRange( query.order("total_savings", { ascending: false }), pagination, ); if (error) throw error; // Get total count let countQuery = supabase .from("waste_prevention_roi") .select("id", { count:"exact", head: true }) .eq("organization_id", organization_id as string); if (outlet_id) countQuery = countQuery.eq("outlet_id", outlet_id); const total = await countTotal(countQuery); res.json( buildPaginatedResponse( data || [], total, pagination.limit, pagination.offset, ), ); } catch (error) { res.status(500).json({ error: (error as Error).message }); } },
); export default router;
