/**
 * Genesis Configuration Types
 * Complete property + outlet + commissary + rules setup
 * Generated by onboarding wizard, used by all Genesis E-H panels
 */

export type InventoryCadenceOption =
  | "DAILY"
  | "AM_PM"
  | "WEEKLY"
  | "MONTH_END"
  | "AS_NEEDED";

export type OutletType =
  | "OUTLET"
  | "PRODUCTION_KITCHEN"
  | "COMMISSARY"
  | "BANQUETS"
  | "PASTRY";

export type CommissaryType =
  | "STOREROOM"
  | "PASTRY_COMMISSARY"
  | "BANQUETS_PRODUCTION";

export type FulfillmentCategory =
  | "FINISHED_GOODS"
  | "SUB_RECIPES"
  | "RAW_ITEMS";

export type TransferPricing = "AT_COST" | "STANDARD_COST" | "MARKUP";

export type CostAttributionMode =
  | "SOURCE_PAYS"
  | "REQUESTING_OUTLET_PAYS"
  | "SPLIT"
  | "EVENT_BASED";

export type FiscalWeekStart = "MONDAY" | "SUNDAY";

/**
 * Individual outlet/kitchen configuration
 */
export interface OutletConfig {
  id: string;
  name: string;
  type: OutletType;
  timezone?: string;
  stocksIngredients: boolean; // false = "assemble-only"
  defaultInventoryCadence: InventoryCadenceOption;
  notes?: string;
}

/**
 * Commissary configuration (storeroom, pastry, banquets production)
 */
export interface CommissaryConfig {
  id: string;
  name: string;
  type: CommissaryType;
  canFulfill: FulfillmentCategory[];
  transferPricing: TransferPricing;
  orderedBy: string[]; // outlet IDs that can order from this
  notes?: string;
}

/**
 * Receiving location setup
 */
export interface ReceivingConfig {
  locations: string[]; // outlet/commissary IDs that can receive
  allowedTransfers: Array<{
    from: string; // outlet/commissary ID
    to: string; // outlet/commissary ID
    allowIfNonStock: boolean; // Allow transfer even if 'to' doesn't stock
    trackAsFinishedGood: boolean; // Track in inventory or as expense
  }>;
}

/**
 * Cost attribution override (specific conditions)
 */
export interface CostAttributionOverride {
  id: string;
  condition: string; // "is_beo" | "outlet_id == X" | "category == pastry"
  rule: CostAttributionMode;
  note: string;
  createdAt: string; // ISO
}

/**
 * Cost attribution policy
 */
export interface CostAttributionPolicy {
  default: CostAttributionMode;
  overrides: CostAttributionOverride[];
  allowChangingPayerLater: boolean;
}

/**
 * Role definition
 */
export interface RoleConfig {
  id: string;
  name: string;
  description?: string;
  permissions: Array<
    | "view_config"
    | "edit_config"
    | "view_queue"
    | "claim_queue"
    | "fulfill_queue"
    | "view_procurement"
    | "edit_procurement"
    | "view_costs"
    | "edit_costs"
    | "view_audit"
    | "manage_roles"
  >;
}

/**
 * Default role assignments (outlet-specific)
 */
export interface RoleAssignments {
  [outletId: string]: string; // role ID
}

/**
 * Audit policy configuration
 */
export interface AuditPolicy {
  captureCostChanges: boolean;
  captureRuleChanges: boolean;
  captureOutletChanges: boolean;
  requireComments: boolean;
  archiveAfterDays: number; // 90 = archive after 90 days
}

/**
 * Individual policy revision record
 */
export interface PolicyRevision {
  revisionId: string;
  effectiveDate: string; // ISO date
  changes: Array<{
    field: string; // "costAttributionRule" | "commissaryStructure" | "outletCadence"
    oldValue: any;
    newValue: any;
    reason: string;
    impactedOutlets: string[];
    impactedCommissaries: string[];
  }>;
  aurumAnnotationsRequired: boolean; // Should we auto-journal this?
  createdBy: string; // userId
  createdAt: string; // ISO
}

/**
 * Complete Genesis Configuration
 * Union of A + B + E/F/G/H/D policies
 * Single source of truth for all Genesis operations
 */
export interface GenesisConfig {
  version: 2;

  // ===== SECTION 1: PROPERTY & ORG =====
  propertyId: string;
  propertyName: string;
  timezone: string; // IANA timezone
  fiscalCalendarStartDay: FiscalWeekStart;
  currency: string; // "USD" | "EUR" | etc.
  isMultiProperty: boolean;

  // ===== SECTION 2: OUTLETS & KITCHENS =====
  outlets: OutletConfig[];

  // ===== SECTION 3: COMMISSARIES =====
  commissaries: CommissaryConfig[];

  // ===== SECTION 4: RECEIVING & TRANSFERS =====
  receiving: ReceivingConfig;

  // ===== SECTION 5: COST ATTRIBUTION RULES =====
  costAttribution: CostAttributionPolicy;

  // ===== SECTION 6: ROLES & PERMISSIONS =====
  roles: RoleConfig[];
  roleAssignments: RoleAssignments;

  // ===== SECTION 7: AUDIT POLICY =====
  auditPolicy: AuditPolicy;

  // ===== METADATA =====
  createdAt: string; // ISO
  updatedAt: string; // ISO
  generatedBy?: string; // userId
  generatedAt?: string; // ISO
  version1MigrationNote?: string; // If migrating from genesis A/B

  // ===== POLICY REVISION HISTORY =====
  policyRevisions: PolicyRevision[];
}

/**
 * Default/empty GenesisConfig for new properties
 */
export function createDefaultGenesisConfig(
  propertyId: string,
  propertyName: string,
): GenesisConfig {
  const now = new Date().toISOString();

  return {
    version: 2,
    propertyId,
    propertyName,
    timezone: "UTC",
    fiscalCalendarStartDay: "MONDAY",
    currency: "USD",
    isMultiProperty: false,

    outlets: [],
    commissaries: [],

    receiving: {
      locations: [],
      allowedTransfers: [],
    },

    costAttribution: {
      default: "SOURCE_PAYS",
      overrides: [],
      allowChangingPayerLater: true,
    },

    roles: [
      {
        id: "super_admin",
        name: "Super Admin",
        permissions: [
          "view_config",
          "edit_config",
          "view_queue",
          "claim_queue",
          "fulfill_queue",
          "view_procurement",
          "edit_procurement",
          "view_costs",
          "edit_costs",
          "view_audit",
          "manage_roles",
        ],
      },
      {
        id: "finance_admin",
        name: "Finance Admin",
        permissions: [
          "view_config",
          "edit_config",
          "view_costs",
          "edit_costs",
          "view_audit",
        ],
      },
      {
        id: "chef",
        name: "Chef",
        permissions: [
          "view_queue",
          "claim_queue",
          "fulfill_queue",
          "view_procurement",
        ],
      },
      {
        id: "manager_readonly",
        name: "Manager (Read-Only)",
        permissions: [
          "view_config",
          "view_queue",
          "view_procurement",
          "view_costs",
        ],
      },
    ],

    roleAssignments: {},

    auditPolicy: {
      captureCostChanges: true,
      captureRuleChanges: true,
      captureOutletChanges: true,
      requireComments: false,
      archiveAfterDays: 90,
    },

    createdAt: now,
    updatedAt: now,
    policyRevisions: [],
  };
}
