import express from"express";
import db from"../db/client.js"; const router = express.Router(); /** * POST /api/transfers * Create a new transfer request */
router.post("/", async (req, res) => { try { const { fromVenueId, toVenueId, items, notes, requestedByUserId } = req.body; // Generate transfer ID const transferId = `T-${new Date().getFullYear()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`; const { rows: transferRows } = await db.query( `INSERT INTO inventory_transfers ( transfer_id, from_venue_id, to_venue_id, requested_by_user_id, status, notes ) VALUES ($1, $2, $3, $4, 'pending', $5) RETURNING id`, [transferId, fromVenueId, toVenueId, requestedByUserId, notes] ); const transferDbId = transferRows[0].id; // Add line items for (const item of items) { await db.query( `INSERT INTO transfer_line_items ( transfer_id, liquor_id, beer_id, wine_id, quantity, unit_price ) VALUES ($1, $2, $3, $4, $5, $6)`, [ transferDbId, item.liquorId || null, item.beerId || null, item.wineId || null, item.quantity, item.unitPrice, ] ); } res.json({ id: transferDbId, transferId, status:"created", }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Failed to create transfer", }); }
}); /** * GET /api/transfers * Get all transfers with optional filters */
router.get("/", async (req, res) => { try { const { venueId, status, limit = 50, offset = 0 } = req.query; let query = ` SELECT t.*, v1.name as from_venue_name, v2.name as to_venue_name, u.email as requested_by_email, COUNT(tli.id) as item_count FROM inventory_transfers t LEFT JOIN venues v1 ON t.from_venue_id = v1.id LEFT JOIN venues v2 ON t.to_venue_id = v2.id LEFT JOIN users u ON t.requested_by_user_id = u.id LEFT JOIN transfer_line_items tli ON t.id = tli.transfer_id `; const params: any[] = []; const conditions: string[] = []; if (venueId) { conditions.push(`(t.from_venue_id = $${params.length + 1} OR t.to_venue_id = $${params.length + 1})`); params.push(venueId, venueId); } if (status) { conditions.push(`t.status = $${params.length + 1}`); params.push(status); } if (conditions.length > 0) { query +=" WHERE" + conditions.join(" AND"); } query += ` GROUP BY t.id ORDER BY t.created_at DESC LIMIT $${params.length + 1} OFFSET $${params.length + 2}`; params.push(limit, offset); const { rows } = await db.query(query, params); res.json(rows); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Database error", }); }
}); /** * GET /api/transfers/:transferId * Get transfer details with line items */
router.get("/:transferId", async (req, res) => { try { const { transferId } = req.params; const { rows: transferRows } = await db.query( ` SELECT t.*, v1.name as from_venue_name, v2.name as to_venue_name, u.email as requested_by_email FROM inventory_transfers t LEFT JOIN venues v1 ON t.from_venue_id = v1.id LEFT JOIN venues v2 ON t.to_venue_id = v2.id LEFT JOIN users u ON t.requested_by_user_id = u.id WHERE t.id = $1 `, [transferId] ); if (transferRows.length === 0) { return res.status(404).json({ error:"Transfer not found" }); } const { rows: itemRows } = await db.query( ` SELECT tli.*, l.name as liquor_name, l.spirit_type, b.name as beer_name, b.beer_style, w.name as wine_name, w.vintage FROM transfer_line_items tli LEFT JOIN liquor_spirits l ON tli.liquor_id = l.id LEFT JOIN beer_catalog b ON tli.beer_id = b.id LEFT JOIN wines w ON tli.wine_id = w.id WHERE tli.transfer_id = $1 `, [transferRows[0].id] ); res.json({ transfer: transferRows[0], items: itemRows, }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Database error", }); }
}); /** * PATCH /api/transfers/:transferId/approve * Approve a transfer request */
router.patch("/:transferId/approve", async (req, res) => { try { const { transferId } = req.params; const { approvedByUserId } = req.body; await db.query( `UPDATE inventory_transfers SET status = 'approved', approved_at = NOW(), approved_by_user_id = $1 WHERE id = $2`, [approvedByUserId, transferId] ); res.json({ status:"approved" }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Failed to approve transfer", }); }
}); /** * PATCH /api/transfers/:transferId/reject * Reject a transfer request */
router.patch("/:transferId/reject", async (req, res) => { try { const { transferId } = req.params; await db.query( `UPDATE inventory_transfers SET status = 'rejected' WHERE id = $1`, [transferId] ); res.json({ status:"rejected" }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Failed to reject transfer", }); }
}); /** * PATCH /api/transfers/:transferId/receive * Mark transfer as received by destination venue */
router.patch("/:transferId/receive", async (req, res) => { try { const { transferId } = req.params; const { receivedByUserId, verifiedCount, discrepancyNotes, signatureData } = req.body; // Update transfer status await db.query( `UPDATE inventory_transfers SET status = 'received', received_at = NOW(), received_by_user_id = $1 WHERE id = $2`, [receivedByUserId, transferId] ); // Create approval record with signature const { rows: transferRows } = await db.query( `SELECT id FROM inventory_transfers WHERE id = $1`, [transferId] ); await db.query( `INSERT INTO transfer_approvals ( transfer_id, approved_by_user_id, verified_count, discrepancy_notes, signature_data, signature_timestamp ) VALUES ($1, $2, $3, $4, $5, NOW())`, [transferId, receivedByUserId, verifiedCount, discrepancyNotes, signatureData || null] ); res.json({ status:"received" }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Failed to receive transfer", }); }
}); /** * POST /api/transfers/:transferId/generate-invoice * Generate transfer invoice */
router.post("/:transferId/generate-invoice", async (req, res) => { try { const { transferId } = req.params; const { generatedByUserId, signatureData } = req.body; const invoiceNumber = `INV-${new Date().getFullYear()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`; const { rows } = await db.query( `INSERT INTO transfer_invoices ( transfer_id, invoice_number, generated_by_user_id, signature_data, signature_timestamp ) VALUES ($1, $2, $3, $4, NOW()) RETURNING id, invoice_number`, [transferId, invoiceNumber, generatedByUserId, signatureData || null] ); res.json({ invoiceId: rows[0].id, invoiceNumber: rows[0].invoice_number, status:"generated", }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Failed to generate invoice", }); }
}); /** * GET /api/transfers/pending/:venueId * Get pending transfers for a venue (for approval) */
router.get("/pending/:venueId", async (req, res) => { try { const { venueId } = req.params; const { rows } = await db.query( ` SELECT t.*, v1.name as from_venue_name, COUNT(tli.id) as item_count FROM inventory_transfers t LEFT JOIN venues v1 ON t.from_venue_id = v1.id LEFT JOIN transfer_line_items tli ON t.id = tli.transfer_id WHERE t.to_venue_id = $1 AND t.status = 'pending' GROUP BY t.id ORDER BY t.created_at ASC `, [venueId] ); res.json(rows); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Database error", }); }
}); export default router;
