import express from"express";
import db from"../db/client.js"; const router = express.Router(); /** * POST /api/variance-audit/start-audit * Start a new physical inventory audit */
router.post("/start-audit", async (req, res) => { try { const { venueId, auditedByUserId, notes } = req.body; const auditId = `A-${new Date().getFullYear()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`; const { rows } = await db.query( `INSERT INTO inventory_audit ( venue_id, audit_id, audit_date, audited_by_user_id, status, notes ) VALUES ($1, $2, CURRENT_DATE, $3, 'in_progress', $4) RETURNING id, audit_id`, [venueId, auditId, auditedByUserId, notes] ); res.json({ id: rows[0].id, auditId: rows[0].audit_id, status:"started", }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Failed to start audit", }); }
}); /** * POST /api/variance-audit/:auditId/add-count * Add physical count for an item during audit */
router.post("/:auditId/add-count", async (req, res) => { try { const { auditId } = req.params; const { liquorId, beerId, wineId, expectedCount, actualCount, volumePercentage, photoUrl, notes, } = req.body; const { rows } = await db.query( `INSERT INTO audit_line_items ( audit_id, wine_id, liquor_id, beer_id, expected_count, actual_count, volume_percentage, photo_url, photo_timestamp, notes ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), $9) RETURNING id`, [ auditId, wineId || null, liquorId || null, beerId || null, expectedCount, actualCount, volumePercentage || 100, photoUrl || null, notes, ] ); res.json({ id: rows[0].id, status:"count_recorded", }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Failed to record count", }); }
}); /** * PATCH /api/variance-audit/:auditId/complete * Complete audit and detect variances */
router.patch("/:auditId/complete", async (req, res) => { try { const { auditId } = req.params; // Get variance tolerance for the venue const { rows: auditRows } = await db.query( `SELECT a.id, a.venue_id FROM inventory_audit a WHERE a.id = $1`, [auditId] ); if (auditRows.length === 0) { return res.status(404).json({ error:"Audit not found" }); } const venueId = auditRows[0].venue_id; const { rows: configRows } = await db.query( `SELECT variance_tolerance_percentage FROM system_configuration LIMIT 1` ); const varianceTolerance = configRows[0]?.variance_tolerance_percentage || 1.0; // Get all audit items and detect variances const { rows: auditItems } = await db.query( ` SELECT ali.*, l.par_level as liquor_par, b.par_level as beer_par, w.par_level as wine_par FROM audit_line_items ali LEFT JOIN liquor_spirits l ON ali.liquor_id = l.id LEFT JOIN beer_catalog b ON ali.beer_id = b.id LEFT JOIN wines w ON ali.wine_id = w.id WHERE ali.audit_id = $1 `, [auditId] ); let flaggedCount = 0; // Check each item for variance for (const item of auditItems) { const variance = item.actual_count - item.expected_count; const variancePercentage = item.expected_count > 0 ? Math.abs(variance / item.expected_count) * 100 : 0; if (variancePercentage > varianceTolerance) { // Flag variance const varianceType = variance > 0 ?"overage" :"shortage"; await db.query( `INSERT INTO breakage_variance ( venue_id, wine_id, liquor_id, beer_id, expected_count, actual_count, variance_qty, variance_percentage, variance_type, status ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'flagged')`, [ venueId, item.wine_id || null, item.liquor_id || null, item.beer_id || null, item.expected_count, item.actual_count, variance, variancePercentage, varianceType, ] ); flaggedCount++; } } // Mark audit as completed await db.query( `UPDATE inventory_audit SET status = 'completed' WHERE id = $1`, [auditId] ); res.json({ status:"completed", flaggedVariances: flaggedCount, variancesTolerance: varianceTolerance, }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Failed to complete audit", }); }
}); /** * GET /api/variance-audit/:venueId * Get all audits for a venue */
router.get("/:venueId", async (req, res) => { try { const { venueId } = req.params; const { status, limit = 50, offset = 0 } = req.query; let query = ` SELECT a.*, u.email as audited_by_email, COUNT(DISTINCT ali.id) as item_count, COUNT(DISTINCT bv.id) as variance_count FROM inventory_audit a LEFT JOIN users u ON a.audited_by_user_id = u.id LEFT JOIN audit_line_items ali ON a.id = ali.audit_id LEFT JOIN breakage_variance bv ON a.id = bv.id WHERE a.venue_id = $1 `; const params: any[] = [venueId]; if (status) { query += ` AND a.status = $${params.length + 1}`; params.push(status); } query += ` GROUP BY a.id ORDER BY a.audit_date DESC LIMIT $${params.length + 1} OFFSET $${params.length + 2}`; params.push(limit, offset); const { rows } = await db.query(query, params); res.json(rows); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Database error", }); }
}); /** * GET /api/variance-audit/flagged/:venueId * Get flagged variances for a venue */
router.get("/flagged/:venueId", async (req, res) => { try { const { venueId } = req.params; const { rows } = await db.query( ` SELECT bv.*, l.name as liquor_name, l.spirit_type, b.name as beer_name, b.beer_style, w.name as wine_name, w.vintage FROM breakage_variance bv LEFT JOIN liquor_spirits l ON bv.liquor_id = l.id LEFT JOIN beer_catalog b ON bv.beer_id = b.id LEFT JOIN wines w ON bv.wine_id = w.id WHERE bv.venue_id = $1 AND bv.status = 'flagged' ORDER BY bv.variance_percentage DESC `, [venueId] ); res.json(rows); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Database error", }); }
}); /** * PATCH /api/variance-audit/investigate/:varianceId * Mark variance as investigated */
router.patch("/investigate/:varianceId", async (req, res) => { try { const { varianceId } = req.params; const { resolution, investigatedByUserId, notes } = req.body; await db.query( `UPDATE breakage_variance SET status = 'investigated', resolution = $1, investigated_by_user_id = $2 WHERE id = $3`, [resolution, investigatedByUserId, varianceId] ); res.json({ status:"investigated" }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Failed to investigate variance", }); }
}); /** * PATCH /api/variance-audit/write-off/:varianceId * Write off a variance (approved loss) */
router.patch("/write-off/:varianceId", async (req, res) => { try { const { varianceId } = req.params; const { writeOffAmount, notes } = req.body; await db.query( `UPDATE breakage_variance SET status = 'written_off', write_off_amount = $1, write_off_date = CURRENT_DATE WHERE id = $2`, [writeOffAmount, varianceId] ); res.json({ status:"written_off" }); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Failed to write off variance", }); }
}); /** * GET /api/variance-audit/report/:venueId * Get variance summary report */
router.get("/report/:venueId", async (req, res) => { try { const { venueId } = req.params; const { startDate, endDate } = req.query; let query = ` SELECT COUNT(*) as total_variances, COUNT(CASE WHEN variance_type = 'shortage' THEN 1 END) as shortage_count, COUNT(CASE WHEN variance_type = 'overage' THEN 1 END) as overage_count, COUNT(CASE WHEN variance_type = 'breakage' THEN 1 END) as breakage_count, SUM(ABS(variance_qty)) as total_units_variance, AVG(variance_percentage) as avg_variance_percentage, COUNT(CASE WHEN status = 'flagged' THEN 1 END) as still_flagged, COUNT(CASE WHEN status = 'written_off' THEN 1 END) as written_off, COALESCE(SUM(write_off_amount), 0) as total_write_off_amount FROM breakage_variance WHERE venue_id = $1 `; const params: any[] = [venueId]; if (startDate) { query += ` AND created_at >= $${params.length + 1}`; params.push(startDate); } if (endDate) { query += ` AND created_at <= $${params.length + 1}`; params.push(endDate); } const { rows } = await db.query(query, params); res.json(rows[0] || {}); } catch (error) { res.status(500).json({ error: error instanceof Error ? error.message :"Database error", }); }
}); export default router;
