#!/usr/bin/env tsx
/**
 * Panel Creation CLI Tool
 * Phase 4: Developer Experience
 * 
 * Usage: npm run panel:create MyPanel
 * Creates a new panel with proper structure
 */

import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

const panelName = process.argv[2];

if (!panelName) {
  console.error("Usage: npm run panel:create <PanelName>");
  process.exit(1);
}

const kebabCase = (str: string) =>
  str
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();

const panelId = kebabCase(panelName);
const panelPath = join(
  process.cwd(),
  "client/modules",
  panelName,
  "index.tsx"
);

if (existsSync(panelPath)) {
  console.error(`Panel ${panelName} already exists at ${panelPath}`);
  process.exit(1);
}

// Create directory
const panelDir = join(process.cwd(), "client/modules", panelName);
mkdirSync(panelDir, { recursive: true });

// Create index.tsx
const panelTemplate = `/**
 * ${panelName} Panel
 * Generated by panel:create CLI
 */

import { Suspense } from "react";
import { PanelFrame } from "@/components/echo/PanelFrame";

export default function ${panelName}Panel(props: any) {
  return (
    <PanelFrame
      title="${panelName}"
      icon="📦"
      onClose={() => console.log("Closed")}
      onMinimize={() => console.log("Minimized")}
      {...props}
    >
      <div className="p-4">
        <h2 className="text-xl font-semibold mb-4">${panelName}</h2>
        <p>Panel content goes here</p>
      </div>
    </PanelFrame>
  );
}
`;

writeFileSync(panelPath, panelTemplate);

console.log(`✅ Created panel: ${panelName}`);
console.log(`   Path: ${panelPath}`);
console.log(`   Panel ID: ${panelId}`);
console.log(`\nNext steps:`);
console.log(`1. Register panel in client/lib/panel-registry.ts`);
console.log(`2. Add metadata in PANEL_METADATA`);
console.log(`3. Implement panel functionality`);
