/***
 * LUCCCA — BUILD 36 (Part 2)
 * ExecExportButton
 *
 * PURPOSE:
 *  - UI button to export Exec snapshot as text/markdown
 *  - For now: simulates fetch and puts text into a textarea for copying
 ***/

import React, { useState } from "react";

export default function ExecExportButton() {
  const [exportText, setExportText] = useState<string | null>(null);

  async function handleExport() {
    const mockText = [
      "# Executive Operational Snapshot — 2025-02-07",
      "",
      "Events Today: 7",
      "Total Headcount: 840",
      "Estimated Revenue: $185,000",
      "Forecast Labor Hours: 420",
      "",
      "Risk Distribution:",
      "- Low: 3",
      "- Medium: 3",
      "- High: 1",
      "",
      "Open Conflicts: 2",
      "",
      "Generated by LUCCCA · Maestro BQT · EchoAi³",
    ].join("\n");

    setExportText(mockText);
  }

  function copyToClipboard() {
    if (!exportText) return;
    navigator.clipboard?.writeText(exportText);
  }

  return (
    <div className="mt-3 border border-slate-200 rounded-lg p-3 bg-white text-xs space-y-2">
      <button
        className="px-3 py-1 bg-slate-900 text-white rounded text-xs hover:bg-slate-800"
        onClick={handleExport}
      >
        Export Executive Snapshot
      </button>

      {exportText && (
        <div className="space-y-1">
          <div className="flex justify-between items-center">
            <span className="text-[10px] text-slate-500">
              Snapshot ready — copy or paste into email/Word/PDF.
            </span>
            <button
              className="text-[10px] px-2 py-1 border border-slate-300 rounded hover:bg-slate-50"
              onClick={copyToClipboard}
            >
              Copy
            </button>
          </div>
          <textarea
            className="w-full h-32 border border-slate-200 rounded p-2 font-mono text-[10px]"
            value={exportText}
            readOnly
          />
        </div>
      )}
    </div>
  );
}
