import type { ApprovalQueueItem } from "@/pages/Invoices";
import type { InvoiceHeader, InvoiceExtractionResult } from "@shared/api"; /** * Builds the state structure that EchoAi³ expects for invoice analysis */
export function buildInvoiceEchoState(item: ApprovalQueueItem, header?: InvoiceHeader) { return { moduleName:"InvoiceImporter", moduleRole:"invoice-processing-hub", invoiceHeader: { invoiceId: item.id, orgId:"", // Will be set from auth context propertyId:"", // Will be set from outlet context vendorId:"", // Will be loaded from vendor lookup vendorName: item.vendor, invoiceNumber: item.invoiceNumber, invoiceDate: item.invoiceDate || new Date().toISOString(), dueDate: item.dueDate, currency:"USD", total: item.total, status: item.status as"uploaded" |"normalized" |"exported" |"paid" |"error", poNumber: item.poNumber, salesPerson: item.vendorContact, customerOutlet: item.orderNumber, payment: { terms: item.terms, methods: [], instructions:"", }, ...header, }, invoiceLines: (item.lineItems || []).map((line) => ({ lineId: `${item.id}-${line.lineNumber}`, invoiceId: item.id, lineNumber: line.lineNumber, description: line.description, quantity: line.quantity, unitCost: line.unitPrice, totalCost: line.totalCost, vendorSku: line.vendorSku ||"", internalSku:"", uom: line.unit ||"", category: line.category ||"", subCategory:"", productName: line.description, region:"", glCode: null, notes:"", })), vendorProfile: { vendorId:"", vendorName: item.vendor, knownRegions: [], knownCategories: [], preferred: false, last12MonthsTotals: item.total, historicalAvgPriceByItem: {}, }, productHierarchy: { Seafood: { Shellfish: { Oyster: { CT: ["Bluepoint","Stonington","Noank", ], MA: ["Island Creek","Wellfleet"], WA: ["Kumamoto","Shigoku"], }, }, }, }, glCodes: [], vectorPayload: { vectorInvoiceDocument: buildInvoiceDocument(item), vectorVendorSegment: `${item.vendor} - Invoice ${item.invoiceNumber}`, vectorLineSegments: (item.lineItems || []).map( (line) => `${line.description} ${line.quantity} ${line.unit} @ $${line.unitPrice}` ), vectorMetadata: { vendor: item.vendor, region:"", category:"", invoiceId: item.id, date: item.invoiceDate || new Date().toISOString(), }, }, };
} function buildInvoiceDocument(item: ApprovalQueueItem): string { const lines = (item.lineItems || []) .map( (line) => `Line ${line.lineNumber}: ${line.description} (${line.quantity} ${line.unit}) $${line.totalCost}` ) .join("\n"); return `
Invoice: ${item.invoiceNumber}
Vendor: ${item.vendor}
Date: ${item.invoiceDate ||"Unknown"}
Due: ${item.dueDate ||"Unknown"}
Total: $${item.total} Items:
${lines} PO: ${item.poNumber ||"None"}
Terms: ${item.terms ||"Unknown"} `.trim();
} /** * Echo action handlers - called from toolbar */
export async function callEchoAction( state: any, actionId: string, prompts: Record<string, string>
) { const prompt = prompts[actionId] ||""; // This would be called via the EchoAi³ framework // For now, we simulate the response structure return { actionId, prompt, moduleName:"InvoiceImporter", context: state, timestamp: new Date().toISOString(), };
} /** * Prepare invoice for vector embedding */
export function prepareVectorPayload(item: ApprovalQueueItem) { return { vectorInvoiceDocument: buildInvoiceDocument(item), vectorVendorSegment: `${item.vendor} Invoice ${item.invoiceNumber} dated ${item.invoiceDate}`, vectorLineSegments: (item.lineItems || []).map((line) => ({ text: `${line.description} - ${line.quantity} ${line.unit} @ $${line.unitPrice}`, lineNumber: line.lineNumber, })), vectorMetadata: { invoiceId: item.id, vendor: item.vendor, date: item.invoiceDate || new Date().toISOString(), total: item.total, }, };
} /** * Echo action prompts from the contract */
export const ECHO_INVOICE_ACTIONS = { explainInvoice: { id:"explainInvoice", label:"Explain this invoice", description:"Echo analyzes the header and lines and returns a human-readable summary", prompt:"Explain this invoice to a manager. Focus on vendor, big cost drivers, and any red flags or anomalies.", }, checkGlCodes: { id:"checkGlCodes", label:"Check GL codes", description:"Echo validates and recommends GL codes for each invoice line", prompt:"Review all invoice lines and verify GL codes based on product hierarchy and category. Suggest corrected GL codes and explain why.", }, detectAnomalies: { id:"detectAnomalies", label:"Detect anomalies", description:"Echo checks for duplicate invoices, price spikes, and unusual vendor patterns", prompt:"Detect pricing anomalies, duplicate risk, and unusual changes for this invoice. Compare to typical vendor pricing patterns.", }, compareHistory: { id:"compareHistory", label:"Compare to history", description:"Echo uses vector search to find similar invoices and compare prices", prompt:"Using vector search, compare this invoice to similar historical invoices for the same vendor and products. Summarize trends and variance.", }, analyzeCategoryBreakdown: { id:"analyzeCategoryBreakdown", label:"Analyze by category", description:"Echo breaks down this invoice by category hierarchy and region", prompt:"Analyze invoice breakdown by product category and region. Summarize spend, volume, and cost trends. Focus on Seafood → Shellfish → Oyster categories.", },
};
