/** * GDPR Compliance Utilities * Data privacy, export, retention policies, and user rights management */ export interface DataExportRequest { id: string; userId: string; userName: string; requestedAt: Date; completedAt?: Date; status:"pending" |"processing" |"completed" |"failed"; dataTypes: ( |"invoices" |"purchases" |"inventory" |"audit_logs" |"personal" )[]; format:"json" |"csv" |"pdf";
} export interface RetentionPolicy { id: string; dataType: string; retentionDays: number; autoDelete: boolean; archiveBeforeDelete: boolean;
} export interface UserConsent { id: string; userId: string; consentType:"marketing" |"analytics" |"essential"; givenAt: Date; expiresAt?: Date; value: boolean;
} export interface DataProcessingRecord { id: string; purpose: string; dataTypes: string[]; legalBasis: string; processors?: string[]; lastUpdated: Date;
} export interface AuditTrailEntry { id: string; userId?: string; action: string; dataType: string; timestamp: Date; details: Record<string, any>;
} /** * Export user data in various formats */
export class DataExportManager { /** * Generate JSON export */ static generateJSONExport(data: Record<string, any>): string { return JSON.stringify(data, null, 2); } /** * Generate CSV export */ static generateCSVExport(data: Array<Record<string, any>>): string { if (data.length === 0) return""; const headers = Object.keys(data[0]); const rows = data.map((row) => headers.map((header) => { const value = row[header]; // Escape quotes and wrap in quotes if contains comma const escaped = String(value).replace(/"/g, '""'); return escaped.includes(",") ? `"${escaped}"` : escaped; }), ); return [headers.join(","), ...rows.map((row) => row.join(","))].join("\n"); } /** * Generate PDF export (placeholder - would use library like jspdf) */ static async generatePDFExport(data: Record<string, any>): Promise<Blob> { // In production, use a library like jspdf const jsonString = this.generateJSONExport(data); return new Blob([jsonString], { type:"application/pdf" }); } /** * Create downloadable export file */ static downloadExport( data: string | Blob, filename: string, mimeType: string, ): void { const blob = data instanceof Blob ? data : new Blob([data], { type: mimeType }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
} /** * Data retention policy management */
export class RetentionPolicyManager { private policies: Map<string, RetentionPolicy> = new Map(); addPolicy(policy: RetentionPolicy): void { this.policies.set(policy.id, policy); } getPolicy(dataType: string): RetentionPolicy | undefined { return Array.from(this.policies.values()).find( (p) => p.dataType === dataType, ); } getAllPolicies(): RetentionPolicy[] { return Array.from(this.policies.values()); } /** * Check if data should be retained */ shouldRetain(dataCreatedAt: Date, dataType: string): boolean { const policy = this.getPolicy(dataType); if (!policy) return true; // Default to retain if no policy const expirationDate = new Date(dataCreatedAt); expirationDate.setDate(expirationDate.getDate() + policy.retentionDays); return expirationDate > new Date(); } /** * Find data eligible for deletion */ getEligibleForDeletion( data: Array<{ createdAt: Date; type: string }>, dataType: string, ): typeof data { const policy = this.getPolicy(dataType); if (!policy || !policy.autoDelete) return []; return data.filter((item) => !this.shouldRetain(item.createdAt, dataType)); } /** * Find data eligible for archiving */ getEligibleForArchiving( data: Array<{ createdAt: Date; type: string }>, dataType: string, ): typeof data { const policy = this.getPolicy(dataType); if (!policy || !policy.archiveBeforeDelete) return []; const archiveDate = new Date(); archiveDate.setDate( archiveDate.getDate() - Math.floor(policy.retentionDays * 0.8), ); return data.filter((item) => item.createdAt < archiveDate); }
} /** * User consent manager */
export class ConsentManager { private consents: Map<string, UserConsent[]> = new Map(); recordConsent(consent: UserConsent): void { if (!this.consents.has(consent.userId)) { this.consents.set(consent.userId, []); } this.consents.get(consent.userId)!.push(consent); } getConsent(userId: string, consentType: string): UserConsent | undefined { const userConsents = this.consents.get(userId) || []; return userConsents.find((c) => c.consentType === consentType); } hasConsent(userId: string, consentType: string): boolean { const consent = this.getConsent(userId, consentType); if (!consent) return false; if (consent.expiresAt && consent.expiresAt < new Date()) { return false; } return consent.value; } revokeConsent(userId: string, consentType: string): void { const userConsents = this.consents.get(userId); if (!userConsents) return; const consent = userConsents.find((c) => c.consentType === consentType); if (consent) { consent.value = false; } } getAllConsents(userId: string): UserConsent[] { return this.consents.get(userId) || []; }
} /** * Data processing record for transparency */
export class DataProcessingRegistry { private records: Map<string, DataProcessingRecord> = new Map(); registerProcessing(record: DataProcessingRecord): void { this.records.set(record.id, record); } getRecord(id: string): DataProcessingRecord | undefined { return this.records.get(id); } getAllRecords(): DataProcessingRecord[] { return Array.from(this.records.values()); } getRecordsByDataType(dataType: string): DataProcessingRecord[] { return Array.from(this.records.values()).filter((r) => r.dataTypes.includes(dataType), ); } updateRecord(id: string, updates: Partial<DataProcessingRecord>): void { const record = this.records.get(id); if (record) { this.records.set(id, { ...record, ...updates, lastUpdated: new Date() }); } }
} /** * Audit trail for GDPR compliance */
export class GDPRAuditTrail { private entries: AuditTrailEntry[] = []; logAccess( userId: string | undefined, dataType: string, details: Record<string, any>, ): void { this.entries.push({ id: `audit-${Date.now()}`, userId, action:"data_access", dataType, timestamp: new Date(), details, }); } logModification( userId: string, dataType: string, details: Record<string, any>, ): void { this.entries.push({ id: `audit-${Date.now()}`, userId, action:"data_modification", dataType, timestamp: new Date(), details, }); } logDeletion( userId: string, dataType: string, details: Record<string, any>, ): void { this.entries.push({ id: `audit-${Date.now()}`, userId, action:"data_deletion", dataType, timestamp: new Date(), details, }); } logExport(userId: string, dataTypes: string[], format: string): void { this.entries.push({ id: `audit-${Date.now()}`, userId, action:"data_export", dataType: dataTypes.join(","), timestamp: new Date(), details: { format }, }); } getEntriesForUser(userId: string): AuditTrailEntry[] { return this.entries.filter((e) => e.userId === userId); } getEntriesByAction(action: string): AuditTrailEntry[] { return this.entries.filter((e) => e.action === action); } getAllEntries(): AuditTrailEntry[] { return [...this.entries]; } exportAuditTrail(format:"json" |"csv" ="json"): string { if (format ==="json") { return JSON.stringify(this.entries, null, 2); } // CSV format const headers = ["ID","User ID","Action","Data Type","Timestamp","Details", ]; const rows = this.entries.map((e) => [ e.id, e.userId ||"", e.action, e.dataType, e.timestamp.toISOString(), JSON.stringify(e.details), ]); return [headers.join(","), ...rows.map((r) => r.join(","))].join("\n"); }
} /** * Right to be forgotten implementation */
export class RightToBeForgettenManager { /** * Anonymize user data instead of hard delete */ static anonymizeUserData(userId: string): Record<string, any> { return { id: `anon-${Date.now()}`, originalUserId: userId, anonymizedAt: new Date(), data: { name:"Anonymized User", email: `anon-${Date.now()}@example.com`, phone:"***-***-****", }, }; } /** * Prepare data for deletion with audit trail */ static prepareForDeletion( userId: string, reason: string, ): { userId: string; reason: string; preparedAt: Date; dataToDelete: string[]; } { return { userId, reason, preparedAt: new Date(), dataToDelete: ["personal_info","email_preferences","login_history","api_keys", ], }; }
} /** * Privacy impact assessment tools */
export class PrivacyImpactAssessment { static assessRisk( dataType: string, numberOfRecords: number, sensitivityLevel:"low" |"medium" |"high", ): { riskLevel:"low" |"medium" |"high"; recommendations: string[]; } { let baseRisk = 0; // Sensitivity scoring const sensitivityScore = { low: 1, medium: 2, high: 3 }[sensitivityLevel]; baseRisk += sensitivityScore * 10; // Data volume scoring if (numberOfRecords > 10000) baseRisk += 30; else if (numberOfRecords > 1000) baseRisk += 20; else if (numberOfRecords > 100) baseRisk += 10; const riskLevel = baseRisk > 50 ?"high" : baseRisk > 25 ?"medium" :"low"; const recommendations: string[] = []; if (riskLevel ==="high") { recommendations.push("Conduct full GDPR impact assessment"); recommendations.push("Implement encryption at rest and in transit"); recommendations.push("Enable audit logging for all access"); recommendations.push("Establish data retention limits"); } else if (riskLevel ==="medium") { recommendations.push("Review access controls"); recommendations.push("Implement data retention policies"); recommendations.push("Enable activity logging"); } recommendations.push("Train staff on data handling"); recommendations.push("Document processing activities"); return { riskLevel, recommendations }; }
}
