/** * Vendor-Specific Pattern Learning * Learns unique signatures for each vendor over time * Improves accuracy with each batch processed */ import { supabase } from "@/lib/supabaseClient";
import type { TemplateFingerprint } from "./invoice-template-fingerprinting"; export interface VendorLearningProfile { vendorName: string; sampleCount: number; colorPattern: { typical: string; // Most common color alternatives: string[]; consistency: number; // 0-1, how consistent are colors }; orientationPattern: { typical:"portrait" |"landscape" |"mixed"; invoiceOrientation:"portrait" |"landscape" |"mixed"; creditOrientation:"portrait" |"landscape" |"mixed"; }; documentTypeDistribution: { invoices: number; creditMemos: number; debits: number; other: number; }; itemCodePattern: { format: string; // e.g.,"4-digit","alphanumeric","mixed" examples: string[]; }; headerKeywords: string[]; lastUpdated: string;
} /** * Build vendor learning profile from historical data */
export async function buildVendorProfile( vendorName: string,
): Promise<VendorLearningProfile | null> { try { // Get all templates for vendor const { data: templates } = await supabase .from("invoice_vendor_templates") .select("*") .eq("vendor_name", vendorName); if (!templates || templates.length === 0) { return null; } // Extract patterns const colorPattern = analyzeColorPattern(templates); const orientationPattern = analyzeOrientationPattern(templates); const docTypeDistribution = analyzeDocumentTypeDistribution(templates); const itemCodePattern = analyzeItemCodePattern(templates); const totalSamples = templates.reduce( (sum: number, t: any) => sum + (t.sample_count || 0), 0, ); return { vendorName, sampleCount: totalSamples, colorPattern, orientationPattern, documentTypeDistribution, itemCodePattern, headerKeywords: templates[0]?.anchor_keywords || [], lastUpdated: new Date().toISOString(), }; } catch (error) { console.error("Failed to build vendor profile:", error); return null; }
} /** * Analyze color patterns across templates */
function analyzeColorPattern(templates: any[]): { typical: string; alternatives: string[]; consistency: number;
} { const colors: string[] = []; const colorScores: number[] = []; for (const template of templates) { if (template.face_fingerprint) { colors.push(template.face_fingerprint); colorScores.push(template.sample_count || 1); } } if (colors.length === 0) { return { typical:"unknown", alternatives: [], consistency: 0, }; } // Find most common color const colorCounts = new Map<string, number>(); for (let i = 0; i < colors.length; i++) { colorCounts.set( colors[i], (colorCounts.get(colors[i]) || 0) + colorScores[i], ); } const sorted = Array.from(colorCounts.entries()).sort((a, b) => b[1] - a[1]); const typical = sorted[0][0]; const alternatives = sorted.slice(1, 4).map(([color]) => color); // Calculate consistency (how much the top color dominates) const totalScore = colorScores.reduce((a, b) => a + b, 0); const typicalScore = colorCounts.get(typical) || 0; const consistency = typicalScore / Math.max(1, totalScore); return { typical, alternatives, consistency, };
} /** * Analyze orientation patterns by document type */
function analyzeOrientationPattern(templates: any[]): { typical:"portrait" |"landscape" |"mixed"; invoiceOrientation:"portrait" |"landscape" |"mixed"; creditOrientation:"portrait" |"landscape" |"mixed";
} { let portraitCount = 0, landscapeCount = 0; let invoicePortrait = 0, invoiceLandscape = 0; let creditPortrait = 0, creditLandscape = 0; for (const template of templates) { const isPortrait = template.orientation ==="portrait"; const isInvoice = template.document_type ==="invoice"; if (isPortrait) portraitCount++; else landscapeCount++; if (isInvoice) { if (isPortrait) invoicePortrait++; else invoiceLandscape++; } else { if (isPortrait) creditPortrait++; else creditLandscape++; } } const overall = portraitCount > landscapeCount ?"portrait" : landscapeCount > portraitCount ?"landscape" :"mixed"; const invoice = invoicePortrait > invoiceLandscape ?"portrait" : invoiceLandscape > invoicePortrait ?"landscape" :"mixed"; const credit = creditPortrait > creditLandscape ?"portrait" : creditLandscape > creditPortrait ?"landscape" :"mixed"; return { typical: overall, invoiceOrientation: invoice, creditOrientation: credit, };
} /** * Analyze document type distribution */
function analyzeDocumentTypeDistribution(templates: any[]): { invoices: number; creditMemos: number; debits: number; other: number;
} { const dist = { invoices: 0, creditMemos: 0, debits: 0, other: 0, }; for (const template of templates) { const type = template.document_type; if (type ==="invoice") dist.invoices++; else if (type ==="credit_memo") dist.creditMemos++; else if (type ==="debit_memo") dist.debits++; else dist.other++; } return dist;
} /** * Analyze item code patterns */
function analyzeItemCodePattern(templates: any[]): { format: string; examples: string[];
} { // This would be extended with actual OCR data // For now, return a template return { format:"unknown", examples: [], };
} /** * Get learning progression for vendor */
export async function getVendorLearningProgress(vendorName: string): Promise<{ sampleGrowth: Array<{ date: string; sampleCount: number }>; accuracyImprovement: Array<{ date: string; accuracy: number }>; templateEvolution: number; // How many template versions estimatedNextImprovement: Date;
}> { try { // Get calibration history const { data: adjustments } = await supabase .from("calibration_events") .select("applied_at, metrics") .eq("vendor_name", vendorName) .order("applied_at", { ascending: true }); const sampleGrowth = adjustments?.map((a: any) => ({ date: a.applied_at, sampleCount: a.metrics?.totalProcessed || 0, })) || []; const accuracyImprovement = adjustments?.map((a: any) => ({ date: a.applied_at, accuracy: a.metrics?.precision || 0, })) || []; // Get template versions const { count: templateVersions } = await supabase .from("invoice_vendor_templates") .select("id", { count:"exact" }) .eq("vendor_name", vendorName); // Estimate next improvement (based on sample rate) const estimatedNextImprovement = new Date(); if (sampleGrowth.length > 1) { const lastGrowth = sampleGrowth[sampleGrowth.length - 1]; const prevGrowth = sampleGrowth[sampleGrowth.length - 2]; const growthRate = (lastGrowth.sampleCount - prevGrowth.sampleCount) / (new Date(lastGrowth.date).getTime() - new Date(prevGrowth.date).getTime()); const samplesNeeded = 100; // Retrain every 100 new samples const msNeeded = samplesNeeded / growthRate; estimatedNextImprovement.setTime( new Date(lastGrowth.date).getTime() + msNeeded, ); } return { sampleGrowth, accuracyImprovement, templateEvolution: templateVersions || 0, estimatedNextImprovement, }; } catch (error) { console.error("Failed to get learning progress:", error); return { sampleGrowth: [], accuracyImprovement: [], templateEvolution: 0, estimatedNextImprovement: new Date(), }; }
} /** * Predict which vendors need retraining */
export async function identifyRetrainingCandidates(): Promise< Array<{ vendorName: string; reason: string; priority:"low" |"medium" |"high"; }>
> { try { const { data: templates } = await supabase .from("invoice_vendor_templates") .select("vendor_name, avg_confidence, sample_count, last_trained_at") .order("last_trained_at", { ascending: true }); if (!templates) { return []; } const candidates = []; const now = new Date(); for (const template of templates) { let reason =""; let priority:"low" |"medium" |"high" ="low"; // Low confidence if (template.avg_confidence < 0.75) { reason = `Low confidence: ${(template.avg_confidence * 100).toFixed(0)}%`; priority ="high"; } // Not trained recently const lastTrained = template.last_trained_at ? new Date(template.last_trained_at) : new Date(0); const daysSinceTrained = (now.getTime() - lastTrained.getTime()) / (1000 * 60 * 60 * 24); if (daysSinceTrained > 30) { reason = `Not trained for ${Math.floor(daysSinceTrained)} days`; priority = priority ==="high" ?"high" :"medium"; } // Low sample count if (template.sample_count < 10) { reason = `Low samples: ${template.sample_count}`; priority ="low"; } if ( reason && !candidates.find((c) => c.vendorName === template.vendor_name) ) { candidates.push({ vendorName: template.vendor_name, reason, priority, }); } } return candidates.sort((a, b) => { const priorityMap = { high: 3, medium: 2, low: 1 }; return priorityMap[b.priority] - priorityMap[a.priority]; }); } catch (error) { console.error("Failed to identify retraining candidates:", error); return []; }
} /** * Update vendor profile with new learning */
export async function updateVendorProfile( vendorName: string, newLearnings: Partial<VendorLearningProfile>,
): Promise<boolean> { try { const profile = await buildVendorProfile(vendorName); if (!profile) return false; // Merge with new learnings const updated = { ...profile, ...newLearnings, lastUpdated: new Date().toISOString(), }; // Save to vendor_learning_profiles table (create if needed) const { error } = await supabase.from("vendor_learning_profiles").upsert( [ { vendor_name: vendorName, profile_data: updated, updated_at: new Date().toISOString(), }, ], { onConflict:"vendor_name" }, ); if (error) throw error; return true; } catch (error) { console.error("Failed to update vendor profile:", error); return false; }
}
