/** * Template Fingerprinting & Matching System * Matches incoming invoices to known vendor templates based on"face" signatures * Enables auto-detection and template auto-loading for training and bulk processing */ import { supabase } from "@/lib/supabaseClient";
import { colorDistance, type InvoiceFaceSignature,
} from "./invoice-face-recognition";
import type { VendorLayoutDetection } from "./invoice-vendor-detection"; export interface TemplateFingerprint { id: string; orgId: string; vendorName: string; documentType: string; orientation: string; fingerprint: string; primaryColorHsv: Record<string, number>; colorPalette: string[]; colorConfidence: number; orientationConfidence: number; fieldSchema: Record<string, unknown>; anchorKeywords: string[]; sampleCount: number; avgConfidence: number; trainingWeight: number; // How many invoices trained on this template lastTrainedAt: string;
} export interface TemplateMatch { template: TemplateFingerprint; matchConfidence: number; colorMatch: number; orientationMatch: boolean; documentTypeMatch: boolean; reasons: string[];
} export interface TemplateMatchResult { matched: boolean; primaryMatch: TemplateMatch | null; alternativeMatches: TemplateMatch[]; noMatchReason?: string;
} /** * Find best matching template for an invoice based on its face signature */
export async function findMatchingTemplate( orgId: string, invoiceFace: InvoiceFaceSignature, vendorName?: string, detectedVendor?: string,
): Promise<TemplateMatchResult> { try { // Build query to fetch templates let query = supabase .from("invoice_vendor_templates") .select("id, vendor_name, document_type, orientation, face_fingerprint, primary_color_hsv, color_palette, color_confidence, orientation_confidence, field_schema, anchor_keywords, sample_count, avg_confidence, training_samples, last_trained_at", ) .eq("org_id", orgId); // If vendor is detected, prefer that vendor's templates if (vendorName || detectedVendor) { const vendor = vendorName || detectedVendor ||""; query = query.eq("vendor_name", vendor); } const { data: templates, error } = await query; if (error) { console.error("Failed to fetch templates:", error); return { matched: false, primaryMatch: null, alternativeMatches: [], noMatchReason:"Failed to load templates", }; } if (!templates || templates.length === 0) { return { matched: false, primaryMatch: null, alternativeMatches: [], noMatchReason:"No templates found for vendor", }; } // Score each template const scores = templates .map((template) => scoreTemplateMatch(template, invoiceFace)) .sort((a, b) => b.matchConfidence - a.matchConfidence); if (scores.length === 0) { return { matched: false, primaryMatch: null, alternativeMatches: [], noMatchReason:"No matching templates", }; } // Primary match if confidence > 70% const primaryMatch = scores[0].matchConfidence > 0.7 ? scores[0] : null; const alternativeMatches = scores .slice(1) .filter((s) => s.matchConfidence > 0.5); return { matched: !!primaryMatch, primaryMatch, alternativeMatches, }; } catch (error) { console.error("Template matching error:", error); return { matched: false, primaryMatch: null, alternativeMatches: [], noMatchReason:"Error during template matching", }; }
} /** * Score template against incoming invoice face */
function scoreTemplateMatch( template: any, invoiceFace: InvoiceFaceSignature,
): TemplateMatch { const reasons: string[] = []; // Document type matching (must match or exact penalty) const docTypeMatch = template.document_type === invoiceFace.documentType; if (!docTypeMatch) { reasons.push(`Document type mismatch (expected ${template.document_type})`); } // Orientation matching const orientationMatch = template.orientation ==="mixed" || invoiceFace.orientation ==="mixed" || template.orientation === invoiceFace.orientation; if (!orientationMatch) { reasons.push(`Orientation mismatch (expected ${template.orientation})`); } // Color matching const templateColor = template.primary_color_hsv ? JSON.parse( typeof template.primary_color_hsv ==="string" ? template.primary_color_hsv : JSON.stringify(template.primary_color_hsv), ) : { h: 0, s: 0, v: 50 }; const colorMatch = colorDistance(templateColor, invoiceFace.primaryColorHsv); // Fingerprint direct matching const fingerprintMatch = template.face_fingerprint === invoiceFace.fingerprint ? 0.95 : colorMatch * 0.7; // Training weight factor (templates trained on more invoices are more reliable) const trainingWeight = Math.min(1, (template.training_samples || 0) / 50); const weightBoost = 0.1 * trainingWeight; // Calculate confidence score let confidence = colorMatch * 0.4; // 40% color confidence += orientationMatch ? 0.25 : 0; // 25% orientation confidence += docTypeMatch ? 0.2 : 0; // 20% document type confidence += (template.avg_confidence || 0) * 0.15; // 15% template confidence // Apply boost from training weight confidence = Math.min(1, confidence + weightBoost); return { template: { id: template.id, orgId: template.org_id, vendorName: template.vendor_name, documentType: template.document_type, orientation: template.orientation, fingerprint: template.face_fingerprint, primaryColorHsv: templateColor, colorPalette: template.color_palette || [], colorConfidence: template.color_confidence || 0, orientationConfidence: template.orientation_confidence || 0, fieldSchema: template.field_schema || {}, anchorKeywords: template.anchor_keywords || [], sampleCount: template.sample_count || 0, avgConfidence: template.avg_confidence || 0, trainingWeight, lastTrainedAt: template.last_trained_at, }, matchConfidence: confidence, colorMatch, orientationMatch, documentTypeMatch: docTypeMatch, reasons, };
} /** * Save new template fingerprint after training */
export async function saveTemplateFingerprint( orgId: string, vendorName: string, invoiceFace: InvoiceFaceSignature, layoutDetection: VendorLayoutDetection, anchorKeywords: string[] = [],
): Promise<TemplateFingerprint | null> { try { // Check if template already exists const { data: existing } = await supabase .from("invoice_vendor_templates") .select("id, training_samples, avg_confidence, sample_count") .eq("org_id", orgId) .eq("vendor_name", vendorName) .eq("document_type", invoiceFace.documentType) .eq("orientation", invoiceFace.orientation) .single(); const now = new Date().toISOString(); const trainingWeight = (existing?.training_samples || 0) + 1; // Merge with existing confidence scores let avgConfidence = invoiceFace.confidence; if (existing?.avg_confidence) { avgConfidence = (existing.avg_confidence * (existing.training_samples || 0) + invoiceFace.confidence) / trainingWeight; } const templateData = { org_id: orgId, vendor_name: vendorName, document_type: invoiceFace.documentType, orientation: invoiceFace.orientation, face_fingerprint: invoiceFace.fingerprint, primary_color_hsv: invoiceFace.primaryColorHsv, color_palette: invoiceFace.colorPalette, color_confidence: invoiceFace.colorConfidence, orientation_confidence: invoiceFace.orientationConfidence, field_schema: layoutDetection, anchor_keywords: anchorKeywords, avg_confidence: avgConfidence, training_samples: trainingWeight, last_trained_at: now, last_face_detected_at: now, }; if (existing) { // Update existing template const { data, error } = await supabase .from("invoice_vendor_templates") .update(templateData) .eq("id", existing.id) .select(); if (error) throw error; return data?.[0] ? formatTemplateResponse(data[0]) : null; } else { // Create new template const { data, error } = await supabase .from("invoice_vendor_templates") .insert([templateData]) .select(); if (error) throw error; return data?.[0] ? formatTemplateResponse(data[0]) : null; } } catch (error) { console.error("Failed to save template fingerprint:", error); return null; }
} /** * Update template usage metrics after successful invoice processing */
export async function updateTemplateMetrics( templateId: string, invoiceProcessingSuccess: boolean, confidence: number,
) { try { const { data } = await supabase .from("invoice_vendor_templates") .select("sample_count, avg_confidence") .eq("id", templateId) .single(); if (!data) return; const newCount = (data.sample_count || 0) + 1; const newConfidence = ((data.avg_confidence || 0) * (data.sample_count || 0) + confidence) / newCount; await supabase .from("invoice_vendor_templates") .update({ sample_count: newCount, avg_confidence: newConfidence, updated_at: new Date().toISOString(), }) .eq("id", templateId); } catch (error) { console.error("Failed to update template metrics:", error); }
} /** * Get all templates for an organization with their fingerprints */
export async function getAllTemplateFingerprints( orgId: string,
): Promise<TemplateFingerprint[]> { try { const { data, error } = await supabase .from("invoice_vendor_templates") .select("*") .eq("org_id", orgId) .order("sample_count", { ascending: false }); if (error) throw error; return (data || []).map(formatTemplateResponse); } catch (error) { console.error("Failed to fetch template fingerprints:", error); return []; }
} /** * Delete template fingerprint */
export async function deleteTemplateFingerprint( templateId: string,
): Promise<boolean> { try { const { error } = await supabase .from("invoice_vendor_templates") .delete() .eq("id", templateId); if (error) throw error; return true; } catch (error) { console.error("Failed to delete template:", error); return false; }
} /** * Format template database response */
function formatTemplateResponse(template: any): TemplateFingerprint { return { id: template.id, orgId: template.org_id, vendorName: template.vendor_name, documentType: template.document_type, orientation: template.orientation, fingerprint: template.face_fingerprint, primaryColorHsv: template.primary_color_hsv ? typeof template.primary_color_hsv ==="string" ? JSON.parse(template.primary_color_hsv) : template.primary_color_hsv : { h: 0, s: 0, v: 50 }, colorPalette: template.color_palette || [], colorConfidence: template.color_confidence || 0, orientationConfidence: template.orientation_confidence || 0, fieldSchema: template.field_schema || {}, anchorKeywords: template.anchor_keywords || [], sampleCount: template.sample_count || 0, avgConfidence: template.avg_confidence || 0, trainingWeight: template.training_samples || 0, lastTrainedAt: template.last_trained_at, };
}
