/** * Bulk Invoice Upload Handler * Processes thousands of invoices during migration * Auto-detects vendor, document type, applies templates * Minimal manual intervention required */ import { supabase } from "@/lib/supabaseClient";
import { extractInvoiceFace } from "./invoice-face-recognition";
import { findMatchingTemplate, saveTemplateFingerprint,
} from "./invoice-template-fingerprinting";
import { detectVendorLayout } from "./invoice-vendor-detection"; export interface BulkUploadConfig { batchName: string; files: File[]; orgId: string; confidenceThreshold: number; // 0-1, default 0.85 autoProcess: boolean; // Auto-process high confidence matches onProgress?: (progress: BulkUploadProgress) => void;
} export interface BulkUploadProgress { batchId: string; totalFiles: number; processedFiles: number; successfulFiles: number; failedFiles: number; currentFile?: string; currentProgress: number; // 0-100 estimatedTimeRemaining?: number; // seconds
} export interface BulkUploadResult { batchId: string; totalProcessed: number; successful: number; failed: number; manualReview: number; autoProcessed: number; duration: number; // milliseconds results: BulkItemResult[];
} export interface BulkItemResult { fileName: string; status:"auto_processed" |"manual_review" |"error"; detectedVendor?: string; detectedDocumentType?: string; matchConfidence?: number; templateUsed?: string; error?: string;
} /** * Main bulk upload handler - orchestrates entire process */
export async function processBulkInvoices( config: BulkUploadConfig,
): Promise<BulkUploadResult> { const startTime = Date.now(); const batchId = await createBulkBatch( config.orgId, config.batchName, config.files.length, config.confidenceThreshold, config.autoProcess, ); const results: BulkItemResult[] = []; const totalFiles = config.files.length; let successful = 0, failed = 0, manualReview = 0, autoProcessed = 0; for (let i = 0; i < config.files.length; i++) { const file = config.files[i]; const progress = ((i / totalFiles) * 100) | 0; config.onProgress?.({ batchId, totalFiles, processedFiles: i, successfulFiles: successful, failedFiles: failed, currentFile: file.name, currentProgress: progress, estimatedTimeRemaining: calculateETA(startTime, i, totalFiles), }); try { const result = await processSingleInvoice( batchId, file, config.orgId, config.confidenceThreshold, config.autoProcess, ); results.push(result); if (result.status ==="auto_processed") { autoProcessed++; successful++; } else if (result.status ==="manual_review") { manualReview++; successful++; } else { failed++; } } catch (error) { results.push({ fileName: file.name, status:"error", error: error instanceof Error ? error.message :"Unknown error", }); failed++; } // Update batch progress in database await updateBulkBatchProgress(batchId, i + 1, successful, failed); } // Complete batch const duration = Date.now() - startTime; await completeBulkBatch(batchId, successful, failed, duration); return { batchId, totalProcessed: results.length, successful, failed, manualReview, autoProcessed, duration, results, };
} /** * Process single invoice in bulk batch */
async function processSingleInvoice( batchId: string, file: File, orgId: string, confidenceThreshold: number, autoProcess: boolean,
): Promise<BulkItemResult> { // Extract face signature from image const faceSignature = await extractInvoiceFace(file); // Find matching template const matchResult = await findMatchingTemplate(orgId, faceSignature); const detectedVendor = matchResult.primaryMatch?.template.vendorName; const detectedDocType = matchResult.primaryMatch?.template.documentType; const matchConfidence = matchResult.primaryMatch?.matchConfidence || 0; const itemResult: BulkItemResult = { fileName: file.name, detectedVendor, detectedDocumentType: detectedDocType, matchConfidence: matchConfidence, templateUsed: matchResult.primaryMatch?.template.id, status:"manual_review", }; try { if ( matchResult.matched && matchConfidence >= confidenceThreshold && autoProcess ) { // Auto-process: upload and attach template itemResult.status ="auto_processed"; } else if (matchResult.matched && matchConfidence > 0.6) { // Manual review: template detected but below threshold itemResult.status ="manual_review"; } else { // Manual review: no template match itemResult.status ="manual_review"; } // Save to bulk_invoice_items table await saveBulkItem(batchId, itemResult, faceSignature); } catch (error) { itemResult.status ="error"; itemResult.error = error instanceof Error ? error.message :"Processing error"; } return itemResult;
} /** * Create bulk batch record */
async function createBulkBatch( orgId: string, batchName: string, totalInvoices: number, confidenceThreshold: number, autoProcess: boolean,
): Promise<string> { const { data, error } = await supabase .from("bulk_invoice_batches") .insert([ { org_id: orgId, batch_name: batchName, total_invoices: totalInvoices, status:"processing", confidence_threshold: confidenceThreshold, auto_process: autoProcess, started_at: new Date().toISOString(), }, ]) .select("id"); if (error) throw error; return data?.[0]?.id ||"";
} /** * Update batch progress */
async function updateBulkBatchProgress( batchId: string, processedCount: number, successfulCount: number, failedCount: number,
): Promise<void> { await supabase .from("bulk_invoice_batches") .update({ processed_invoices: processedCount, successful_invoices: successfulCount, failed_invoices: failedCount, updated_at: new Date().toISOString(), }) .eq("id", batchId);
} /** * Complete bulk batch */
async function completeBulkBatch( batchId: string, successfulCount: number, failedCount: number, durationMs: number,
): Promise<void> { const status = failedCount === 0 ?"completed" : failedCount > successfulCount ?"failed" :"completed"; await supabase .from("bulk_invoice_batches") .update({ status, successful_invoices: successfulCount, failed_invoices: failedCount, completed_at: new Date().toISOString(), updated_at: new Date().toISOString(), metadata: { duration_ms: durationMs, avg_processing_ms: durationMs / (successfulCount + failedCount), }, }) .eq("id", batchId);
} /** * Save individual bulk item */
async function saveBulkItem( batchId: string, itemResult: BulkItemResult, faceSignature: any,
): Promise<void> { await supabase.from("bulk_invoice_items").insert([ { batch_id: batchId, file_name: itemResult.fileName, detected_vendor: itemResult.detectedVendor, detected_document_type: itemResult.detectedDocumentType, detected_orientation: faceSignature.orientation, color_fingerprint: faceSignature.fingerprint, matching_template_id: itemResult.templateUsed, match_confidence: itemResult.matchConfidence, processing_status: itemResult.status, error_message: itemResult.error, processed_at: new Date().toISOString(), }, ]);
} /** * Get bulk batch status and results */
export async function getBulkBatchStatus(batchId: string): Promise<{ batch: any; items: any[];
}> { const { data: batch } = await supabase .from("bulk_invoice_batches") .select("*") .eq("id", batchId) .single(); const { data: items } = await supabase .from("bulk_invoice_items") .select("*") .eq("batch_id", batchId) .order("created_at", { ascending: true }); return { batch, items: items || [] };
} /** * Retry failed items in a batch */
export async function retryBulkBatchItems( batchId: string, orgId: string,
): Promise<number> { const { data: items } = await supabase .from("bulk_invoice_items") .select("*") .eq("batch_id", batchId) .eq("processing_status","error"); if (!items || items.length === 0) return 0; let retryCount = 0; for (const item of items) { try { // Re-attempt template matching with updated templates const matchResult = await findMatchingTemplate( orgId, item.color_fingerprint, item.detected_vendor, ); if (matchResult.matched && matchResult.primaryMatch) { await supabase .from("bulk_invoice_items") .update({ processing_status:"manual_review", matching_template_id: matchResult.primaryMatch.template.id, match_confidence: matchResult.primaryMatch.matchConfidence, error_message: null, }) .eq("id", item.id); retryCount++; } } catch (error) { console.error(`Failed to retry item ${item.file_name}:`, error); } } return retryCount;
} /** * Calculate estimated time remaining */
function calculateETA( startTime: number, currentIndex: number, totalFiles: number,
): number { if (currentIndex === 0) return 0; const elapsedMs = Date.now() - startTime; const avgMsPerFile = elapsedMs / currentIndex; const remainingFiles = totalFiles - currentIndex; return Math.round((avgMsPerFile * remainingFiles) / 1000);
} /** * Export batch results as CSV */
export async function exportBulkBatchResults(batchId: string): Promise<string> { const { batch, items } = await getBulkBatchStatus(batchId); const headers = ["File Name","Status","Detected Vendor","Document Type","Match Confidence","Template ID","Error", ]; const rows = items.map((item: any) => [ item.file_name, item.processing_status, item.detected_vendor ||"", item.detected_document_type ||"", item.match_confidence ? (item.match_confidence * 100).toFixed(1) +"%" :"", item.matching_template_id ||"", item.error_message ||"", ]); const csv = [headers, ...rows] .map((row) => row.map((cell) => `"${cell}"`).join(",")) .join("\n"); return csv;
}
