import { logger } from "./logger"; export type OfflineCaptureSource ="camera" |"upload"; export interface OfflineCaptureRecord { id: string; name: string; type: string; dataUrl: string; createdAt: number; source: OfflineCaptureSource;
} export interface OfflineEnvelope<T = unknown> { id: string; channel: string; payload: T; createdAt: number; retries: number;
} interface OfflineStore { captures: OfflineCaptureRecord[]; envelopes: OfflineEnvelope[];
} const STORAGE_KEY ="echo_offline_store"; const getWindow = () => (typeof window ==="undefined" ? null : window); function readStore(): OfflineStore { const win = getWindow(); if (!win) return { captures: [], envelopes: [] }; try { const raw = win.localStorage.getItem(STORAGE_KEY); if (!raw) { return legacyMigrate(); } const parsed = JSON.parse(raw) as OfflineStore; if ( parsed && Array.isArray(parsed.captures) && Array.isArray(parsed.envelopes) ) { return parsed; } return legacyMigrate(parsed as any); } catch { return { captures: [], envelopes: [] }; }
} function legacyMigrate( previous?: OfflineCaptureRecord[] | OfflineStore,
): OfflineStore { if (!previous) return { captures: [], envelopes: [] }; if (Array.isArray(previous)) { const migrated: OfflineStore = { captures: previous, envelopes: [] }; writeStore(migrated); return migrated; } if (typeof previous ==="object" && previous) { const captures = Array.isArray((previous as any).captures) ? (previous as any).captures : []; const envelopes = Array.isArray((previous as any).envelopes) ? (previous as any).envelopes : []; const result = { captures, envelopes } satisfies OfflineStore; writeStore(result); return result; } return { captures: [], envelopes: [] };
} function writeStore(store: OfflineStore) { const win = getWindow(); if (!win) return; try { win.localStorage.setItem(STORAGE_KEY, JSON.stringify(store)); } catch { // ignore storage overflow or denied access }
} const fileToDataUrl = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("Failed to read file")); reader.onload = () => resolve(String(reader.result ||"")); reader.readAsDataURL(file); }); function dataUrlToFile(dataUrl: string, name: string, type: string): File { const arr = dataUrl.split(","); const base64 = arr[1] ??""; const binary = atob(base64); const len = binary.length; const bytes = new Uint8Array(len); for (let i = 0; i < len; i += 1) { bytes[i] = binary.charCodeAt(i); } return new File([bytes], name, { type: type ||"application/octet-stream" });
} export async function enqueueOfflineCaptures( files: File[], source: OfflineCaptureSource,
): Promise<number> { const store = readStore(); const now = Date.now(); for (const file of files) { try { const dataUrl = await fileToDataUrl(file); const id = typeof crypto !=="undefined" && typeof crypto.randomUUID ==="function" ? crypto.randomUUID() : `${now}-${Math.random().toString(36).slice(2, 8)}`; store.captures.push({ id, name: file.name, type: file.type ||"application/octet-stream", dataUrl, createdAt: now, source, }); } catch { // skip serialization failures } } writeStore(store); return store.captures.length;
} export function listOfflineCaptures(): OfflineCaptureRecord[] { return readStore().captures;
} export async function reconstructOfflineFiles( entries: OfflineCaptureRecord[],
): Promise<File[]> { const files: File[] = []; for (const entry of entries) { try { files.push(dataUrlToFile(entry.dataUrl, entry.name, entry.type)); } catch { // ignore malformed entries } } return files;
} export function removeOfflineCaptures(ids: string[]): void { if (!ids.length) return; const store = readStore(); store.captures = store.captures.filter((record) => !ids.includes(record.id)); writeStore(store);
} export async function enqueueOfflinePayload<T>( channel: string, payload: T,
): Promise<string | null> { const store = readStore(); const id = typeof crypto !=="undefined" && typeof crypto.randomUUID ==="function" ? crypto.randomUUID() : `env-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; store.envelopes.push({ id, channel, payload, createdAt: Date.now(), retries: 0, }); writeStore(store); return id;
} export function listOfflinePayloads<T = unknown>( channel?: string,
): OfflineEnvelope<T>[] { const store = readStore(); const records = store.envelopes as OfflineEnvelope<T>[]; if (!channel) return records; return records.filter((record) => record.channel === channel);
} export function removeOfflinePayloads(ids: string[]): void { if (!ids.length) return; const store = readStore(); store.envelopes = store.envelopes.filter( (record) => !ids.includes(record.id), ); writeStore(store);
} type OfflineHandler<T = unknown> = ( records: OfflineEnvelope<T>[],
) => Promise<void>; const handlers = new Map<string, OfflineHandler>(); async function flushChannel(channel: string) { if (typeof navigator !=="undefined" && navigator.onLine === false) { return; } const pending = listOfflinePayloads(channel); if (!pending.length) return; const handler = handlers.get(channel); if (!handler) return; try { await handler(pending); removeOfflinePayloads(pending.map((record) => record.id)); } catch (error) { logger.warn(`Failed to flush offline channel ${channel}`, error); const store = readStore(); store.envelopes = store.envelopes.map((record) => pending.find((item) => item.id === record.id) ? { ...record, retries: record.retries + 1 } : record, ); writeStore(store); }
} async function flushAllChannels() { const channels = Array.from( new Set(listOfflinePayloads().map((record) => record.channel)), ); await Promise.all(channels.map((channel) => flushChannel(channel)));
} let syncStarted = false; export function registerOfflineHandler<T>( channel: string, handler: OfflineHandler<T>,
) { handlers.set(channel, handler as OfflineHandler); void flushChannel(channel);
} export function startOfflineSync() { if (syncStarted) return () => undefined; syncStarted = true; const onOnline = () => { void flushAllChannels(); }; if (typeof window !=="undefined") { window.addEventListener("online", onOnline); void flushAllChannels(); return () => { window.removeEventListener("online", onOnline); syncStarted = false; }; } return () => undefined;
}
