/** * Watermark and stamp detection for invoice images * Detects and flags overlaid stamps (RECEIVED, PAID, etc.) and watermarks */ export interface WatermarkDetectionResult { hasWatermark: boolean; watermarkType?: string; confidence: number; affectedRegions?: Array<{ x: number; y: number; width: number; height: number; type: string; text?: string; }>; recommendation: string;
} /** * Detect watermarks and stamps in an image * Uses canvas-based image analysis */
export async function detectWatermarks( imageBlob: Blob | File
): Promise<WatermarkDetectionResult> { try { const result = await analyzeImageForWatermarks(imageBlob); return result; } catch (error) { console.error("Watermark detection error:", error); return { hasWatermark: false, confidence: 0, recommendation:"Could not analyze image for watermarks. Proceeding with caution.", }; }
} /** * Analyze image pixels for watermark characteristics * Looks for: translucent overlays, rotated text, diagonal stamps */
async function analyzeImageForWatermarks( imageBlob: Blob | File
): Promise<WatermarkDetectionResult> { const image = await loadImageToCanvas(imageBlob); if (!image) { return { hasWatermark: false, confidence: 0, recommendation:"Could not load image for analysis", }; } const canvas = image.canvas; const ctx = canvas.getContext("2d"); if (!ctx) { return { hasWatermark: false, confidence: 0, recommendation:"Could not access image context", }; } const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height); const data = imageData.data; // Analyze for watermark characteristics const characteristics = { hasHighTransparency: false, hasGrayedOutRegions: false, hasDiagonalPattern: false, hasRotatedText: false, }; // Check for regions with high transparency or faded appearance let transparentPixels = 0; let grayedPixels = 0; let totalPixels = data.length / 4; for (let i = 0; i < data.length; i += 4) { const r = data[i]; const g = data[i + 1]; const b = data[i + 2]; const a = data[i + 3]; // Detect faded/grayed regions (similar R, G, B values, lower saturation) const isFaded = Math.abs(r - g) < 30 && Math.abs(g - b) < 30 && r < 180 && a < 250; if (isFaded) { grayedPixels++; } // Detect transparency anomalies if (a < 200 && a > 0) { transparentPixels++; } } characteristics.hasHighTransparency = transparentPixels / totalPixels > 0.02; characteristics.hasGrayedOutRegions = grayedPixels / totalPixels > 0.1; // Check for diagonal patterns (stamps are often rotated) characteristics.hasDiagonalPattern = checkForDiagonalPattern(data, canvas.width, canvas.height); // Detect common stamp patterns const stampPatterns = detectCommonStamps(canvas, ctx); const affectedRegions = stampPatterns.map((p) => ({ x: p.x, y: p.y, width: p.width, height: p.height, type: p.type, text: p.text, })); const hasWatermark = stampPatterns.length > 0 || characteristics.hasHighTransparency || characteristics.hasGrayedOutRegions; let confidence = 0; if (stampPatterns.length > 0) confidence += 0.8; if (characteristics.hasDiagonalPattern) confidence += 0.3; if (characteristics.hasHighTransparency) confidence += 0.2; confidence = Math.min(confidence, 1); return { hasWatermark, watermarkType: stampPatterns.length > 0 ? stampPatterns[0].type : undefined, confidence, affectedRegions: affectedRegions.length > 0 ? affectedRegions : undefined, recommendation: getWatermarkRecommendation(hasWatermark, confidence, stampPatterns), };
} /** * Detect common stamp patterns (RECEIVED, PAID, COPY, etc.) */
function detectCommonStamps( canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D
): Array<{ x: number; y: number; width: number; height: number; type: string; text?: string }> { const stamps: Array<{ x: number; y: number; width: number; height: number; type: string; text?: string }> = []; // Common stamp text patterns const stampPatterns = [ { text:"RECEIVED", type:"received" }, { text:"PAID", type:"paid" }, { text:"COPY", type:"copy" }, { text:"DRAFT", type:"draft" }, { text:"CONFIDENTIAL", type:"confidential" }, { text:"APPROVED", type:"approved" }, { text:"DUPLICATE", type:"duplicate" }, ]; // Try to detect stamp regions by looking for high-contrast text areas // This is a simplified heuristic - a full implementation would use OCR const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height); const data = imageData.data; // Look for rectangular regions with text-like characteristics const regions = findHighContrastRegions(data, canvas.width, canvas.height); for (const region of regions) { // Check if region appears to be a rotated stamp if (region.width > 50 && region.height > 20 && region.isRotated) { stamps.push({ x: region.x, y: region.y, width: region.width, height: region.height, type:"diagonal_stamp", text:"Stamp/Watermark (diagonal)", }); } } return stamps;
} /** * Find high-contrast regions that might be stamps or watermarks */
function findHighContrastRegions( data: Uint8ClampedArray, width: number, height: number
): Array<{ x: number; y: number; width: number; height: number; isRotated: boolean;
}> { const regions: Array<{ x: number; y: number; width: number; height: number; isRotated: boolean; }> = []; // Simplified: scan for areas with high edge density (text/stamp characteristic) const blockSize = 50; for (let blockY = 0; blockY < height; blockY += blockSize) { for (let blockX = 0; blockX < width; blockX += blockSize) { let edges = 0; const blockHeight = Math.min(blockSize, height - blockY); const blockWidth = Math.min(blockSize, width - blockX); // Count edges in block for (let y = blockY; y < blockY + blockHeight - 1; y++) { for (let x = blockX; x < blockX + blockWidth - 1; x++) { const idx1 = (y * width + x) * 4; const idx2 = ((y + 1) * width + x) * 4; const brightness1 = (data[idx1] + data[idx1 + 1] + data[idx1 + 2]) / 3; const brightness2 = (data[idx2] + data[idx2 + 1] + data[idx2 + 2]) / 3; if (Math.abs(brightness1 - brightness2) > 100) { edges++; } } } // If high edge density, mark as potential stamp region const edgeDensity = edges / (blockWidth * blockHeight); if (edgeDensity > 0.1) { regions.push({ x: blockX, y: blockY, width: blockWidth, height: blockHeight, isRotated: false, }); } } } return regions.slice(0, 3); // Return top 3 regions
} /** * Check for diagonal patterns (stamps are often rotated 45 degrees) */
function checkForDiagonalPattern( data: Uint8ClampedArray, width: number, height: number
): boolean { let diagonalEdges = 0; let horizontalEdges = 0; for (let y = 1; y < height - 1; y++) { for (let x = 1; x < width - 1; x++) { const idx = (y * width + x) * 4; // Check diagonal neighbors const topLeftIdx = ((y - 1) * width + (x - 1)) * 4; const bottomRightIdx = ((y + 1) * width + (x + 1)) * 4; const topLeftBright = (data[topLeftIdx] + data[topLeftIdx + 1] + data[topLeftIdx + 2]) / 3; const bottomRightBright = (data[bottomRightIdx] + data[bottomRightIdx + 1] + data[bottomRightIdx + 2]) / 3; const centerBright = (data[idx] + data[idx + 1] + data[idx + 2]) / 3; if (Math.abs(topLeftBright - bottomRightBright) > 100) { diagonalEdges++; } // Check horizontal neighbors const leftIdx = (y * width + (x - 1)) * 4; const rightIdx = (y * width + (x + 1)) * 4; const leftBright = (data[leftIdx] + data[leftIdx + 1] + data[leftIdx + 2]) / 3; const rightBright = (data[rightIdx] + data[rightIdx + 1] + data[rightIdx + 2]) / 3; if (Math.abs(leftBright - rightBright) > 100) { horizontalEdges++; } } } // If diagonal edges > horizontal edges, likely rotated pattern return diagonalEdges > horizontalEdges * 1.5;
} /** * Load image blob into canvas */
async function loadImageToCanvas( imageBlob: Blob | File
): Promise<{ canvas: HTMLCanvasElement; image: HTMLImageElement } | null> { return new Promise((resolve) => { const reader = new FileReader(); reader.onload = (event) => { const img = new Image(); img.onload = () => { const canvas = document.createElement("canvas"); canvas.width = img.width; canvas.height = img.height; const ctx = canvas.getContext("2d"); if (!ctx) { resolve(null); return; } ctx.drawImage(img, 0, 0); resolve({ canvas, image: img }); }; img.onerror = () => { resolve(null); }; img.src = event.target?.result as string; }; reader.onerror = () => { resolve(null); }; reader.readAsDataURL(imageBlob); });
} /** * Get recommendation based on watermark detection */
function getWatermarkRecommendation( hasWatermark: boolean, confidence: number, stamps: Array<{ type: string }>
): string { if (!hasWatermark) { return"No watermarks detected. OCR should be reliable."; } if (confidence < 0.3) { return"Possible watermark detected. Monitor OCR accuracy."; } if (confidence < 0.7) { return"Watermark/stamp likely present. Consider manual review of extraction near stamp area."; } const stampType = stamps[0]?.type ||"unknown"; return `Watermark/stamp detected (${stampType}). OCR in stamp area may be inaccurate. Recommend manual verification.`;
}
