/** * IoT Device Management API * Handles device registration, configuration, health monitoring */ import { IoTDevice, DeviceLocation, DeviceConfiguration, DeviceHealthLog, DeviceStatusView, DevicePairingToken } from '@shared/types/iot'; const API_URL = '/api'; // ============================================================================
// DEVICE MANAGEMENT
// ============================================================================ export async function getDevices(organizationId: string, filters?: { outletId?: string; status?: string; deviceType?: string;
}): Promise<IoTDevice[]> { const params = new URLSearchParams({ organization_id: organizationId, ...filters || {}, }); const response = await fetch(`${API_URL}/iot-devices?${params}`); if (!response.ok) throw new Error(`Failed to fetch devices: ${response.statusText}`); return response.json();
} export async function getDevice(deviceId: string): Promise<IoTDevice> { const response = await fetch(`${API_URL}/iot-devices/${deviceId}`); if (!response.ok) throw new Error(`Failed to fetch device: ${response.statusText}`); return response.json();
} export async function createDevice(device: Omit<IoTDevice, 'id' | 'created_at' | 'updated_at'>): Promise<IoTDevice> { const response = await fetch(`${API_URL}/iot-devices`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(device), }); if (!response.ok) throw new Error(`Failed to create device: ${response.statusText}`); return response.json();
} export async function updateDevice(deviceId: string, updates: Partial<IoTDevice>): Promise<IoTDevice> { const response = await fetch(`${API_URL}/iot-devices/${deviceId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(updates), }); if (!response.ok) throw new Error(`Failed to update device: ${response.statusText}`); return response.json();
} export async function deleteDevice(deviceId: string): Promise<void> { const response = await fetch(`${API_URL}/iot-devices/${deviceId}`, { method: 'DELETE', }); if (!response.ok) throw new Error(`Failed to delete device: ${response.statusText}`);
} export async function updateDeviceStatus(deviceId: string, status: 'active' | 'inactive' | 'maintenance' | 'offline'): Promise<IoTDevice> { return updateDevice(deviceId, { status });
} export async function updateDeviceBatteryLevel(deviceId: string, batteryLevel: number): Promise<IoTDevice> { return updateDevice(deviceId, { battery_level: batteryLevel });
} // ============================================================================
// DEVICE LOCATIONS
// ============================================================================ export async function getDeviceLocations(deviceId: string): Promise<DeviceLocation[]> { const response = await fetch(`${API_URL}/iot-devices/${deviceId}/locations`); if (!response.ok) throw new Error(`Failed to fetch device locations: ${response.statusText}`); return response.json();
} export async function assignDeviceLocation( deviceId: string, location: Omit<DeviceLocation, 'id' | 'assigned_at'>
): Promise<DeviceLocation> { const response = await fetch(`${API_URL}/iot-devices/${deviceId}/locations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(location), }); if (!response.ok) throw new Error(`Failed to assign device location: ${response.statusText}`); return response.json();
} export async function deassignDeviceLocation(locationId: string): Promise<void> { const response = await fetch(`${API_URL}/device-locations/${locationId}/deassign`, { method: 'POST', }); if (!response.ok) throw new Error(`Failed to deassign device location: ${response.statusText}`);
} // ============================================================================
// DEVICE CONFIGURATION
// ============================================================================ export async function getDeviceConfiguration(deviceId: string): Promise<DeviceConfiguration> { const response = await fetch(`${API_URL}/iot-devices/${deviceId}/configuration`); if (!response.ok) throw new Error(`Failed to fetch device configuration: ${response.statusText}`); return response.json();
} export async function updateDeviceConfiguration( deviceId: string, config: Partial<DeviceConfiguration>
): Promise<DeviceConfiguration> { const response = await fetch(`${API_URL}/iot-devices/${deviceId}/configuration`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(config), }); if (!response.ok) throw new Error(`Failed to update device configuration: ${response.statusText}`); return response.json();
} // ============================================================================
// DEVICE HEALTH & DIAGNOSTICS
// ============================================================================ export async function getDeviceHealthLogs( deviceId: string, options?: { limit?: number; offset?: number; eventType?: string }
): Promise<DeviceHealthLog[]> { const params = new URLSearchParams({ limit: (options?.limit ?? 50).toString(), offset: (options?.offset ?? 0).toString(), ...options?.eventType ? { event_type: options.eventType } : {}, }); const response = await fetch(`${API_URL}/iot-devices/${deviceId}/health-logs?${params}`); if (!response.ok) throw new Error(`Failed to fetch device health logs: ${response.statusText}`); return response.json();
} export async function getDeviceStatus(deviceId: string): Promise<DeviceStatusView> { const response = await fetch(`${API_URL}/iot-devices/${deviceId}/status`); if (!response.ok) throw new Error(`Failed to fetch device status: ${response.statusText}`); return response.json();
} export async function getOrganizationDeviceStatus(organizationId: string): Promise<DeviceStatusView[]> { const response = await fetch(`${API_URL}/organizations/${organizationId}/device-status`); if (!response.ok) throw new Error(`Failed to fetch organization device status: ${response.statusText}`); return response.json();
} export async function logDeviceHealthEvent( deviceId: string, event: Omit<DeviceHealthLog, 'id' | 'created_at'>
): Promise<DeviceHealthLog> { const response = await fetch(`${API_URL}/iot-devices/${deviceId}/health-events`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(event), }); if (!response.ok) throw new Error(`Failed to log device health event: ${response.statusText}`); return response.json();
} export async function resolveDeviceHealthEvent(eventId: string): Promise<void> { const response = await fetch(`${API_URL}/device-health-logs/${eventId}/resolve`, { method: 'POST', }); if (!response.ok) throw new Error(`Failed to resolve device health event: ${response.statusText}`);
} // ============================================================================
// DEVICE PAIRING
// ============================================================================ export async function generatePairingToken( organizationId: string, options?: { deviceTypeId?: string; outletId?: string; createdBy?: string; }
): Promise<DevicePairingToken> { const response = await fetch(`${API_URL}/organizations/${organizationId}/pairing-tokens`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(options || {}), }); if (!response.ok) throw new Error(`Failed to generate pairing token: ${response.statusText}`); return response.json();
} export async function getPairingTokens(organizationId: string): Promise<DevicePairingToken[]> { const response = await fetch(`${API_URL}/organizations/${organizationId}/pairing-tokens`); if (!response.ok) throw new Error(`Failed to fetch pairing tokens: ${response.statusText}`); return response.json();
} export async function claimDeviceWithToken(token: string, deviceId: string): Promise<IoTDevice> { const response = await fetch(`${API_URL}/pairing-tokens/${token}/claim`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ device_id: deviceId }), }); if (!response.ok) throw new Error(`Failed to claim device: ${response.statusText}`); return response.json();
} export async function revokePairingToken(tokenId: string): Promise<void> { const response = await fetch(`${API_URL}/pairing-tokens/${tokenId}`, { method: 'DELETE', }); if (!response.ok) throw new Error(`Failed to revoke pairing token: ${response.statusText}`);
} // ============================================================================
// DEVICE BULK OPERATIONS
// ============================================================================ export async function bulkUpdateDeviceStatus( organizationId: string, deviceIds: string[], status: string
): Promise<{ updated: number; failed: number }> { const response = await fetch(`${API_URL}/organizations/${organizationId}/devices/bulk-update`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ device_ids: deviceIds, status }), }); if (!response.ok) throw new Error(`Failed to bulk update devices: ${response.statusText}`); return response.json();
} export async function bulkAssignDevices( organizationId: string, deviceIds: string[], outletId: string
): Promise<{ assigned: number; failed: number }> { const response = await fetch(`${API_URL}/organizations/${organizationId}/devices/bulk-assign`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ device_ids: deviceIds, outlet_id: outletId }), }); if (!response.ok) throw new Error(`Failed to bulk assign devices: ${response.statusText}`); return response.json();
}
