/** * Supplier Marketplace & RFQ API * Enables group buying aggregation, RFQ distribution, multi-supplier bidding */ import { supabase, executeQuery, getUserOrganization } from '@/lib/supabaseClient'; /** * Create RFQ (Request for Quote) */
export async function createRFQ(rfq: { rfq_title: string; description?: string; rfq_type: 'goods' | 'service' | 'combined'; outlet_group_id?: string; estimated_annual_spend?: number; response_deadline: string; line_items: Array<{ product_id?: string; product_description: string; quantity_needed: number; uom: string; annual_volume_estimate?: number; }>;
}) { const orgId = await getUserOrganization(); const user = await getAuthenticatedUser(); // Create RFQ header const rfqNumber = await generateRFQNumber(orgId); const { data: rfqHeader, error: headerError } = await supabase .from('rfq_headers') .insert({ organization_id: orgId, outlet_group_id: rfq.outlet_group_id, rfq_number: rfqNumber, rfq_type: rfq.rfq_type, rfq_title: rfq.rfq_title, description: rfq.description, estimated_annual_spend: rfq.estimated_annual_spend, status: 'draft', response_deadline: rfq.response_deadline, created_by: user.id, }) .select() .single(); if (headerError) { throw new Error(`Failed to create RFQ: ${headerError.message}`); } // Add line items const lineItems = rfq.line_items.map((item, idx) => ({ rfq_id: rfqHeader.id, product_id: item.product_id, product_description: item.product_description, category_tier1_id: null, // Would be extracted from product quantity_needed: item.quantity_needed, uom: item.uom, annual_volume_estimate: item.annual_volume_estimate, line_number: idx + 1, })); const { error: linesError } = await supabase.from('rfq_line_items').insert(lineItems); if (linesError) { throw new Error(`Failed to add RFQ lines: ${linesError.message}`); } return getRFQ(rfqHeader.id);
} /** * Get RFQ details */
export async function getRFQ(rfqId: string) { const orgId = await getUserOrganization(); return executeQuery( supabase .from('rfq_headers') .select(` *, rfq_line_items (*), rfq_evaluation_criteria (*), rfq_responses ( *, vendors (name, supplier_type), rfq_response_line_items (*) ) `) .eq('organization_id', orgId) .eq('id', rfqId) .single() );
} /** * Publish RFQ (send invitations to suppliers) */
export async function publishRFQ(rfqId: string, supplierIds: string[]) { const orgId = await getUserOrganization(); // Update RFQ status const { error: updateError } = await supabase .from('rfq_headers') .update({ status: 'published', published_date: new Date().toISOString(), }) .eq('id', rfqId) .eq('organization_id', orgId); if (updateError) { throw new Error(`Failed to publish RFQ: ${updateError.message}`); } // Create supplier invitations const invitations = supplierIds.map((supplierId) => ({ rfq_id: rfqId, supplier_id: supplierId, invitation_sent_date: new Date().toISOString(), })); const { error: inviteError } = await supabase .from('rfq_supplier_invitations') .insert(invitations); if (inviteError) { throw new Error(`Failed to send invitations: ${inviteError.message}`); } // Send email notifications to suppliers await notifySuppliers(rfqId, supplierIds); return getRFQ(rfqId);
} /** * Submit RFQ response (supplier bid) */
export async function submitRFQResponse(rfqResponse: { rfq_id: string; supplier_id: string; response_number: string; total_bid_amount: number; payment_terms?: string; delivery_timeline_days?: number; contact_person?: string; contact_email?: string; line_items: Array<{ rfq_line_id: string; unit_price: number; delivery_date?: string; notes?: string; }>;
}) { // Create response header const { data: response, error: responseError } = await supabase .from('rfq_responses') .insert({ rfq_id: rfqResponse.rfq_id, supplier_id: rfqResponse.supplier_id, response_number: rfqResponse.response_number, response_date: new Date().toISOString(), total_bid_amount: rfqResponse.total_bid_amount, payment_terms: rfqResponse.payment_terms, delivery_timeline_days: rfqResponse.delivery_timeline_days, contact_person: rfqResponse.contact_person, contact_email: rfqResponse.contact_email, status: 'received', }) .select() .single(); if (responseError) { throw new Error(`Failed to submit response: ${responseError.message}`); } // Add line items const lineItems = rfqResponse.line_items.map((item) => ({ rfq_response_id: response.id, rfq_line_id: item.rfq_line_id, unit_price: item.unit_price, delivery_date: item.delivery_date, notes: item.notes, })); const { error: linesError } = await supabase.from('rfq_response_line_items').insert(lineItems); if (linesError) { throw new Error(`Failed to add response lines: ${linesError.message}`); } return response;
} /** * Get all RFQ responses for evaluation */
export async function getRFQResponses(rfqId: string) { return executeQuery( supabase .from('rfq_responses') .select(` *, vendors (name, supplier_type, primary_region), rfq_response_line_items (*) `) .eq('rfq_id', rfqId) .order('response_date', { ascending: true }) );
} /** * Score RFQ response against evaluation criteria */
export async function scoreRFQResponse( rfqResponseId: string, scores: Array<{ criteria_id: string; score: number; comments?: string }>
) { const user = await getAuthenticatedUser(); // Insert scores const scoreRecords = scores.map((s) => ({ rfq_response_id: rfqResponseId, criteria_id: s.criteria_id, score: s.score, comments: s.comments, scored_by: user.id, scored_at: new Date().toISOString(), })); const { error } = await supabase.from('rfq_evaluation_scores').insert(scoreRecords); if (error) { throw new Error(`Failed to record scores: ${error.message}`); } // Update response with calculated score const { data: evaluationData } = await supabase .from('rfq_evaluation_scores') .select('score') .eq('rfq_response_id', rfqResponseId); const avgScore = evaluationData && evaluationData.length > 0 ? evaluationData.reduce((a: any, b: any) => a + b.score, 0) / evaluationData.length : 0; const { error: updateError } = await supabase .from('rfq_responses') .update({ evaluation_score: avgScore, status: 'passed_initial_review', evaluation_by: user.id, evaluation_at: new Date().toISOString(), }) .eq('id', rfqResponseId); if (updateError) { throw new Error(`Failed to update response: ${updateError.message}`); }
} /** * Award RFQ to selected supplier */
export async function awardRFQ( rfqId: string, rfqResponseId: string, contractStartDate: string, contractEndDate: string
) { const orgId = await getUserOrganization(); const user = await getAuthenticatedUser(); // Get response details const { data: response } = await supabase .from('rfq_responses') .select('supplier_id, total_bid_amount') .eq('id', rfqResponseId) .single(); if (!response) { throw new Error('Response not found'); } // Call Postgres function to create contract const { data: contractId, error: contractError } = await supabase.rpc( 'award_rfq_and_create_contract', { p_rfq_id: rfqId, p_selected_response_id: rfqResponseId, p_contract_start_date: contractStartDate, p_contract_end_date: contractEndDate, } ); if (contractError) { throw new Error(`Failed to award RFQ: ${contractError.message}`); } return { success: true, contract_id: contractId, message: `RFQ awarded. Contract created with ID: ${contractId}`, };
} /** * Get marketplace listings (public supplier offerings) */
export async function getMarketplaceListings(filters?: { category_tier1_id?: string; supplier_id?: string; min_price?: number; max_price?: number; limit?: number; offset?: number;
}) { let query = supabase .from('marketplace_listings') .select(` *, vendors (name, supplier_type, primary_region), products (id, name, code) `) .eq('status', 'active') .order('created_at', { ascending: false }); if (filters?.category_tier1_id) { query = query.eq('category_tier1_id', filters.category_tier1_id); } if (filters?.supplier_id) { query = query.eq('supplier_id', filters.supplier_id); } if (filters?.min_price) { query = query.gte('price', filters.min_price); } if (filters?.max_price) { query = query.lte('price', filters.max_price); } if (filters?.limit) { query = query.limit(filters.limit); } if (filters?.offset) { query = query.range(filters.offset, filters.offset + (filters.limit || 20) - 1); } return executeQuery(query);
} // ============================================================================
// HELPERS
// ============================================================================ async function generateRFQNumber(organizationId: string): Promise<string> { const today = new Date(); const dateStr = `${today.getFullYear()}${String(today.getMonth() + 1).padStart(2, '0')}`; const { data: lastRFQ } = await supabase .from('rfq_headers') .select('rfq_number') .eq('organization_id', organizationId) .like('rfq_number', `RFQ-${dateStr}-%`) .order('created_at', { ascending: false }) .limit(1) .single(); const sequence = lastRFQ ? parseInt(lastRFQ.rfq_number.split('-')[2]) + 1 : 1; return `RFQ-${dateStr}-${String(sequence).padStart(4, '0')}`;
} async function getAuthenticatedUser() { const { data: { user }, error, } = await supabase.auth.getUser(); if (error || !user) { throw new Error('User not authenticated'); } return user;
} async function notifySuppliers(rfqId: string, supplierIds: string[]) { // Get RFQ and supplier emails const { data: rfq } = await supabase.from('rfq_headers').select('*').eq('id', rfqId).single(); const { data: suppliers } = await supabase .from('vendors') .select('id, email, name') .in('id', supplierIds); // Send emails (simplified - would use proper email service) console.log(`Sending RFQ ${rfq.rfq_number} to ${suppliers?.length || 0} suppliers`);
} export default { createRFQ, getRFQ, publishRFQ, submitRFQResponse, getRFQResponses, scoreRFQResponse, awardRFQ, getMarketplaceListings,
};
