/***
 * LUCCCA — BUILD 36 (Part 1)
 * Exec Snapshot & Briefing Export Formatter
 *
 * PURPOSE:
 *  - Convert exec summary + briefings to plain text / markdown
 *  - For copy/paste, email, or PDF export downstream
 ***/

export type ExecSummary = {
  date: string;
  totalEvents: number;
  totalHeadcount: number;
  estRevenue: number;
  totalLaborHours: number;
  riskCounts: { low: number; medium: number; high: number };
  conflictsOpen: number;
};

export function formatExecSnapshot(summary: ExecSummary): string {
  return [
    `# Executive Operational Snapshot — ${summary.date}`,
    ``,
    `Events Today: ${summary.totalEvents}`,
    `Total Headcount: ${summary.totalHeadcount}`,
    `Estimated Revenue: $${summary.estRevenue.toLocaleString()}`,
    `Forecast Labor Hours: ${summary.totalLaborHours}`,
    ``,
    `Risk Distribution:`,
    `- Low: ${summary.riskCounts.low}`,
    `- Medium: ${summary.riskCounts.medium}`,
    `- High: ${summary.riskCounts.high}`,
    ``,
    `Open Conflicts: ${summary.conflictsOpen}`,
    ``,
    `Generated by LUCCCA · Maestro BQT · EchoAi³`,
  ].join("\n");
}

export function formatEventBriefingMarkdown(briefing: any): string {
  const lines: string[] = [];

  lines.push(`# Pre-Service Briefing — ${briefing.header.name}`);
  lines.push("");
  lines.push(`Date/Time: ${briefing.header.date || "TBD"}`);
  lines.push(`Space: ${briefing.header.space}`);
  lines.push(`Headcount: ${briefing.header.headcount}`);
  lines.push(`Risk: ${briefing.header.riskScore} (${briefing.header.riskBand})`);
  lines.push("");

  lines.push("## Timeline");
  (briefing.timeline || []).forEach((t: any) => {
    lines.push(`- ${t.label}: ${t.time}`);
  });
  lines.push("");

  lines.push("## Staffing");
  (briefing.staffing || []).forEach((s: any) => {
    lines.push(`- ${s.role}: ${s.count} (${s.totalHours} hours)`);
  });
  lines.push("");

  lines.push("## Procurement Highlights");
  (briefing.procurement || [])
    .slice(0, 10)
    .forEach((p: any) => {
      lines.push(`- ${p.ingredient}: ${p.total}`);
    });
  if ((briefing.procurement || []).length > 10) {
    lines.push(`- ... and more items in LUCCCA.`);
  }
  lines.push("");

  lines.push("## Risks & Focus Points");
  (briefing.risks || []).forEach((r: any) => {
    lines.push(`- ${r.label} (+${r.impact} risk)`);
  });
  lines.push("");

  lines.push("## Notes");
  (briefing.notes || []).forEach((n: string) => {
    lines.push(`- ${n}`);
  });
  lines.push("");
  lines.push(`Generated by LUCCCA · Maestro BQT · EchoAi³`);
  return lines.join("\n");
}
