INSERT INTO wines (sku, name, producer, region, sub_region, country, vintage, varietals, style, abv, body, tannin, acidity, sweetness, oak, aromas, retail_price, cost_price) VALUES
('BDX-001', 'Château Margaux', 'Château Margaux', 'Bordeaux', 'Médoc', 'France', 2015, ARRAY['Cabernet Sauvignon', 'Merlot', 'Cabernet Franc', 'Petit Verdot'], 'Red', 12.8, 'full', 'high', 'medium', 'dry', true, ARRAY['blackcurrant', 'cedar', 'graphite', 'violet'], 350.00, 120.00),
('BUR-001', 'Chablis William Fèvre', 'William Fèvre', 'Burgundy', 'Chablis', 'France', 2022, ARRAY['Chardonnay'], 'White', 12.5, 'light', 'low', 'high', 'dry', false, ARRAY['green apple', 'lemon', 'flint', 'oyster shell'], 28.00, 8.50),
('PIE-001', 'Barolo Luciano Sandrone', 'Luciano Sandrone', 'Piedmont', 'Langhe', 'Italy', 2018, ARRAY['Nebbiolo'], 'Red', 14.0, 'full', 'high', 'medium', 'dry', true, ARRAY['cherry', 'rose', 'tar', 'licorice'], 95.00, 32.00),
('TOS-001', 'Chianti Classico Riserva', 'Antinori', 'Tuscany', 'Chianti Classico', 'Italy', 2019, ARRAY['Sangiovese', 'Canaiolo', 'Colorino'], 'Red', 13.5, 'medium', 'medium', 'high', 'dry', true, ARRAY['red cherry', 'leather', 'earth', 'tobacco'], 45.00, 15.00),
('RIO-001', 'Riesling Mosel', 'Dr. H. Thanisch', 'Mosel', 'Bernkastel', 'Germany', 2021, ARRAY['Riesling'], 'White', 10.5, 'light', 'low', 'high', 'off-dry', false, ARRAY['peach', 'apricot', 'lime', 'honey'], 22.00, 6.80),
('NAP-001', 'Cabernet Sauvignon Napa', 'Ridge Vineyards', 'Napa Valley', 'Monte Bello', 'USA', 2017, ARRAY['Cabernet Sauvignon', 'Merlot', 'Petit Verdot'], 'Red', 13.8, 'full', 'high', 'medium', 'dry', true, ARRAY['dark plum', 'cassis', 'mint', 'oak spice'], 85.00, 28.00),
('SOM-001', 'Chablis Premier Cru', 'La Chablisienne', 'Burgundy', 'Chablis', 'France', 2020, ARRAY['Chardonnay'], 'White', 12.0, 'light', 'low', 'high', 'dry', false, ARRAY['apple', 'almonds', 'minerality'], 38.00, 12.50),
('LIR-001', 'Lirac Côtes du Rhône', 'Château d''Aquéria', 'Rhône', 'Lirac', 'France', 2020, ARRAY['Grenache', 'Syrah', 'Mourvèdre'], 'Red', 14.5, 'medium', 'medium', 'low', 'dry', true, ARRAY['strawberry', 'pepper', 'herbs'], 32.00, 10.00);
