import React, { useState } from "react";
const { useState } = React;

import { View, ScrollView, StyleSheet, KeyboardAvoidingView, Platform, ActivityIndicator,
} from"react-native";
import { Button, TextInput, Text, useTheme } from"react-native-paper";
import { useAuth } from"../../client/context/AuthContext"; export default function LoginScreen({ navigation }: any) { const { signIn, loading, error } = useAuth(); const theme = useTheme(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const handleLogin = async () => { const success = await signIn(email, password); if (success) { // Navigation handled by auth context } }; return ( <KeyboardAvoidingView behavior={Platform.OS ==="ios" ?"padding" :"height"} style={styles.container} > <ScrollView contentContainerStyle={styles.scrollContent}> <View style={styles.header}> <Text variant="displaySmall" style={styles.title}> Echo Recipe Pro </Text> <Text variant="bodyMedium" style={styles.subtitle}> Restaurant Management Suite </Text> </View> <View style={styles.form}> <TextInput label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" editable={!loading} mode="outlined" style={styles.input} /> <TextInput label="Password" value={password} onChangeText={setPassword} secureTextEntry={!showPassword} editable={!loading} mode="outlined" style={styles.input} right={ <TextInput.Icon icon={showPassword ?"eye-off" :"eye"} onPress={() => setShowPassword(!showPassword)} /> } /> {error && ( <Text style={{ color: theme.colors.error, marginBottom: 12 }}> {error} </Text> )} <Button mode="contained" onPress={handleLogin} disabled={loading || !email || !password} style={styles.button} > {loading ? ( <ActivityIndicator color="#fff" /> ) : ("Sign In" )} </Button> <View style={styles.footer}> <Text variant="bodySmall">Don't have an account? </Text> <Button mode="text" onPress={() => navigation.navigate("SignUp")} disabled={loading} labelStyle={styles.linkLabel} > Sign Up </Button> </View> </View> </ScrollView> </KeyboardAvoidingView> );
} const styles = StyleSheet.create({ container: { flex: 1, backgroundColor:"#fff", }, scrollContent: { flexGrow: 1, justifyContent:"center", padding: 20, }, header: { marginBottom: 40, alignItems:"center", }, title: { fontWeight:"bold", marginBottom: 8, }, subtitle: { color:"#64748b", }, form: { gap: 16, }, input: { marginBottom: 8, }, button: { marginTop: 16, paddingVertical: 8, }, footer: { flexDirection:"row", justifyContent:"center", marginTop: 20, alignItems:"center", }, linkLabel: { fontSize: 14, },
});
