import React, { useState } from"react"
import { ChevronDown, Settings, LayoutGrid, FileText, BarChart3, Layers } from"lucide-react"
import { cn } from"@/lib/utils" interface SidebarSection { id: string title: string icon: React.ReactNode items: Array<{ id: string label: string icon?: React.ReactNode }>
} interface GlassSidebarProps { sections: SidebarSection[] onItemClick?: (sectionId: string, itemId: string) => void onSettingsClick?: () => void showSettings?: boolean
} export function GlassSidebar({ sections, onItemClick, onSettingsClick, showSettings = true,
}: GlassSidebarProps) { const [expanded, setExpanded] = useState<Record<string, boolean>>( sections.reduce((acc, s) => ({ ...acc, [s.id]: true }), {}) ) const toggleSection = (id: string) => { setExpanded((prev) => ({ ...prev, [id]: !prev[id] })) } return ( <div className="w-64 h-full flex flex-col bg-gradient-to-b from-white/40 to-white/20 dark:from-gray-900/40 dark:to-black/20 backdrop-blur-xl border-r border-white/50 dark:border-cyan-400/10"> {/* Header */} <div className="p-4 border-b border-white/30 dark:border-cyan-400/10"> <h2 className="text-sm font-bold text-gray-900 dark:text-cyan-300 flex items-center gap-2"> <Layers className="w-4 h-4" /> Workspace </h2> </div> {/* Sections */} <div className="flex-1 overflow-y-auto scrollbar-hide space-y-2 p-3"> {sections.map((section) => ( <div key={section.id} className="space-y-1"> {/* Section Header */} <button onClick={() => toggleSection(section.id)} className={cn("w-full flex items-center justify-between px-3 py-2 rounded-lg transition-all","hover:bg-background dark:hover:bg-cyan-400/10", expanded[section.id] &&"bg-background dark:bg-cyan-400/5" )} > <div className="flex items-center gap-2 text-sm font-medium"> <span className="text-foreground dark:text-cyan-400">{section.icon}</span> <span className="text-gray-900 dark:text-cyan-50">{section.title}</span> </div> <ChevronDown className={cn("w-4 h-4 text-muted-foreground dark:text-gray-400 transition-transform", expanded[section.id] &&"rotate-180" )} /> </button> {/* Section Items */} {expanded[section.id] && ( <div className="pl-2 space-y-1 animate-fade-in"> {section.items.map((item) => ( <button key={item.id} onClick={() => onItemClick?.(section.id, item.id)} className={cn("w-full flex items-center gap-2 px-3 py-1.5 rounded-md text-sm transition-all","text-foreground dark:text-gray-300 hover:text-gray-900 dark:hover:text-cyan-200","hover:bg-background dark:hover:bg-cyan-400/10" )} > {item.icon && <span className="w-4 h-4">{item.icon}</span>} <span>{item.label}</span> </button> ))} </div> )} </div> ))} </div> {/* Settings Button */} {showSettings && ( <div className="p-3 border-t border-white/30 dark:border-cyan-400/10"> <button onClick={onSettingsClick} className={cn("w-full flex items-center justify-center gap-2 px-3 py-2 rounded-lg","bg-gradient-to-r from-blue-500/20 to-cyan-500/20 dark:from-cyan-500/20 dark:to-purple-500/20","border border-primary/30 dark:border-cyan-400/30","text-gray-900 dark:text-cyan-300 hover:text-gray-950 dark:hover:text-cyan-200","hover:bg-gradient-to-r hover:from-blue-500/30 hover:to-cyan-500/30 dark:hover:from-cyan-500/30 dark:hover:to-purple-500/30","transition-all text-sm font-medium" )} > <Settings className="w-4 h-4" /> Settings </button> </div> )} </div> )
} // Default sections for event studio
export const defaultSections: SidebarSection[] = [ { id:"workspace", title:"Workspace", icon: <LayoutGrid className="w-4 h-4" />, items: [ { id:"projects", label:"Projects", icon: <FileText className="w-3 h-3" /> }, { id:"assets", label:"Assets", icon: <Layers className="w-3 h-3" /> }, { id:"variants", label:"Variants", icon: <BarChart3 className="w-3 h-3" /> }, ], }, { id:"tools", title:"Tools", icon: <LayoutGrid className="w-4 h-4" />, items: [ { id:"outliner", label:"Outliner" }, { id:"inspector", label:"Inspector" }, { id:"annotations", label:"Annotations" }, ], },
]
